### ISSUE TITLE
[Bug] Non-respect of an Open (Libre) and Free Monetary System

### ISSUE THREAD

**Issue by ManUtopiK** [libra/libra#101]
# 🐛 Bug

After the first read-through of the white-paper, I noticed in the section "[the-libra-currency-and-reserve](https://libra.org/en-US/white-paper/#the-libra-currency-and-reserve)" and others parts of the [_white paper_](https://libra.org/en-US/white-paper/) that Libra doesn't respect some of the basics of an **Open (Libre) and Free Monetary System**.

## Concise bug description

References:
- [Relative Theory of Money v2.718](http://en.trm.creationmonetaire.info/)
- [https://wiki.p2pfoundation.net/Relative_Theory_of_Money]()

**Unrespect of the _Principle of Relativity_ rule**
> Money creation is not equal in space and time for individual within his monetary zone. Like bitcoin, early adopters benefits are unfair. Futur adopters may struggle to find Libra money. Non Facebook user or unconnected people will be excluded from monetary zone.

**Unrespect of the _Freedom of democratic modification_ rule**
> No citizen opinion could be found in the foundation and except Libra foundation members, nobody can change Libra money rules. Libra is imposed to world citizen without their consents. It is pure global authoritarianism and global financial surveillance of billions of people.

**Unrespect of the _Freedom to access resources_ rule**
> Because we all should have access to economic & monetary resources. Facebook is a capitalist company which will logically maintain its system into its currency, yet capitalism implies rarity, which leads to increasing inequality in accessing resources.

**Unrespect of the _Freedom of production_ rule**
> Money is not co-produced by all the community members. You will expect catastrophic behavior despite of Libra is backed by a collection of low-volatility assets, such as bank deposits and short-term government securities in currencies.

**Unrespect of the _Freedom to exchange “in the money”_ rule**
> It'll become a gravity well the masses can't and won't escape. If the masses don't move away from Facebook today, why do you think people will move away from Libra in the future? Libra will be a totalitarism nightmare.

## Summary

You're currently building the **first world based blockchain coupon!** Libra is just an improvement on the existing fiat backed tokens, which peg to a specific national money.

![](https://pbs.twimg.com/media/D9XM5dqWkAAJs3T?format=jpg&name=small)

# To reproduce

**Code snippet to reproduce**
```sh
git clone https://github.com/bitcoin/bitcoin
git merge some-private-monetary-functions
git add gafa-founding-members & private-partnerships
docker build some-facebook-magic-UX-design
cargo new world-business-opportunities
cargo build --exclude citizen-opinion & human-rights
```
> Expected world coup doesn't happen.

**Stack trace/error message**
```
Proto-state fail: Borders (algorithm) and communism-like-government (board) are set,  
but missing monetary commons-based peer production.
```

# Expected Behavior

1. Close centralized private corporation ownership.
2. A global partnership for a thriving fair global commons economy.
3. Build a real open, free and decentralized monetary system with true digital currency.
4. Escape states and banks money creation monopoly.
5. More freedom, more transparency, more justice, more equity, more autonomy, less surveillance Society...

# System information

- Earth 1.0 
- Chaotic non-fair economy ^2008
- Dangerous climate change COP24
- World society disorder fakenews ~2016

Currently running process:
- Global _every aspect of life_ digital disruption
- Political collapse due by irrelevant agents
- World rise private corporations
- Huge monetary mass inequality

# Possible solution

Implement the cryptocurrency dapp called [Duniter](https://duniter.org/en/introduction/) (also written in Rust). More info in the [wiki](https://duniter.org/en/wiki/).

**Comment by karozagorus** [comment]
An unsound money used together with another form of unsound money will accelerate the collapse of the global financial system.

**Comment by gwestcot** [comment]
Ya I am somewhat ok with all of this because the Libra and all other corresponding stablecoins are doomed to inevitable failure. I suppose the pivot would be backing the Libra in gold, silver, and crypto but even then the need to trust them will probably mean this project fails miserably. Anyone with half a brain knows that Facebook has repeatedly abused its users privacy and there is no reason to believe that will change in the future.
