### ISSUE TITLE
Waypoints for trusted starting point

### ISSUE THREAD

**Issue by kphfb** [libra/libra#1013]
# Waypoints

### Terminology:

**Node**: In the context of this document, a node refers to any of validator node, full node, or wallet/client node which wants to synchronize to the Libra chain.
* * *

## Motivation

* * *
When a node comes online for the first time or after being offline for an extended period of time, in the face of old validator keys potentially being compromised, there is no way for that node to be certain that updates it receives are relative to the current state of the Libra blockchain.  In addition, it may take a longer period of time to fully synchronize to the blockchain and/or old data may have already been pruned by the seeding nodes, and it is thus needed to have a trusted starting place for nodes.

Waypoints are the way to provide nodes with an external source of information about the history of the blockchain. A Waypoint at version n commits to a specific history of transactions T_0...T_n as well as the resulting states S_0...S_n.

Waypoints help nodes in multiple ways. First, waypoints provide an extra layer of validation on top of the history of validator signatures. If a node is configured with a waypoint from a trustworthy source, it will not be misled if the majority of a historical validator set is compromised (see [Weak Subjectivity and Long Range Forks](https://blog.ethereum.org/2014/11/25/proof-stake-learned-love-weak-subjectivity/)). Second, waypoints can be used to configure the genesis of the system — attesting to the first transaction.  In addition, waypoints can be used to move past a hard fork in the chain.

Waypoints will be embedded within node code as a trusted “starting place”.  A node may also have a trusted source from which it can query for waypoints - perhaps this is a value checked into GitHub for example.  By knowing this information, a node can have an increased level of assurance that the data it is receiving from queries is indeed valid.
* * *

## Waypoint Specification

* * *
Waypoints are defined as the following:

`version:transaction_accumulator_root_hash:previous_reconfiguration_event_seq_number`

|Field	|_Definition_	|Use	|
|---	|---	|---	|
|version	|The version Vw specified by this waypoint	|Becomes the "known_version" when performing a subsequent update against a peer node	|
|transaction_accumulator_root_hash	|The accumulator root hash at version Vw	|Used in verification of returned data in any queries.  The data returned from a query would be relative to this known root hash, so any proof would require this root hash as verification	|
|previous_reconfiguration_event_seq_number	|Reconfigurations of the validator set emit events upon reconfiguration which contain the new validator set.  The previous reconfiguration event sequence number field is the event sequence number of the event prior to Vw of the last reconfiguration event emission	|This event sequence number is used to look up the validator set at the version of this waypoint.  This is the event sequence number of the reconfiguration event immediately prior to the version represented by this waypoint.  The validator set is then used in proof verification to ensure that any ledger info returned by a query is signed by this validator set (or subsequent validator sets which are proven by the resultant data)	|

This creates a single value that can be easily copied from a trusted online resource and plugged into a node on startup.  The generation of the waypoint is performed by the following:

```
version = get_latest_version();
accumulator_root_hash = get_root_hash_at_version(version);
previous_event_reconfig_number = get_latest_reconfiguration_event_seq_number();
waypoint = 
    version + ":" + accumulator_root_hash + ":" + previous_event_reconfig_number;
```

* * *

## Waypoint Utilization

* * *
Waypoints are used by all types of nodes — validators, full nodes and wallets - and the node would be configured with a specific waypoint.  This can be done via the waypoint being embedded in code, being pulled from a known resource or config file, or manually entered by the user.  For all node types, initial syncing is based off of this waypoint once the waypoint is loaded as the trusted version.  

When a node comes online, it must perform an update to the latest ledger info and request the event at the event sequence number specified by the waypoint.  The data that is fetched by this query is used to determine the current validator set.  The proof returned by updating to the latest ledger info will contain signed ledger infos at each validator transition and these ledger infos will contain the new validator set.  This can be used to prove the current validator set.  Once the event proof is verified, the node can begin normal operation.

Waypoint utilization is shown in the following pseudocode:

```
// Pull the values out of the waypoint
(version, accumulator_root_hash, event_number) = 
    parse_waypoint(waypoint);

// To learn of the validator set at "version", perform an update_to_latest_ledger
// to update to the latest ledger info and fetch the event at "event_number".
// The response will contain the validator set at "version" as well as a proof
// from our known version through the latest version known by the node
// from which we are querying.
// Note that the access_path is TBD but will be a consistent account
GetEventsByEventAccessPathRequest get_event_req =
    {
        access_path: "/{association_account}/recon_events",
        start_event_seq_num: event_number,
    };

(latest_li, event_with_proof) = 
    other_node.update_to_latest_ledger_info(get_event_req);

validator_set = events_with_proof.get_validator_set();

// Verify the proof.  See "Proof explanation" section below.
// Note that the validator set is included on the signed LIs which
// are also returned by this query for each epoch.  The proof verification
// will verify these signed LIs
events_with_proof.verify_proof(
    version /*known_version*/,
    accumulator_root_hash /*known_root_hash*/,
    validator_set /*known_validator_set*/,
);

```

* * *

## Proof explanation

* * *

### Definitions

Waypoint contains the following values which we trust because we trust the waypoint source:
`Vw = Version of waypoint`
`Hw = Accumulator root hash at Vw`
`Ew = Event sequence number specified by waypoint`

At the latest ledger version on chain:
`Vc = Version at current latest on-chain version`
`Hc = Accumulator root hash at current latest on-chain version Vc`

### What must be verified

There are several items which must be verified:

1. Hw must be under Hc
    1. **What does this prove:** This proves that Hc is a parent to Hw and thus a continuation of the same chain
    2. **How do we verify this**: updateToLatestLedger() provides the hash proof from Hw to Hc
2. The path from Hw to Hc must include signed ledger info proofs for all epoch changes between times w and c
    1. **What does this prove:** This proves that if we trust the validator set VSw, then we can trust the current validator set VSc
    2. **How do we verify this**: updateToLatestLedger() provides the signed ledger info proofs from Hw to Hc
3. Ew must be under Hw.
    1. **What does this prove:** Proves that we can trust the validator set VSw represented by Ew
    2. **How do we verify this:** updateToLatestLedger() returns a proof from Ew to Hc.  Since in (2)/(3) we proved that Hw is under Hc, and since we trust the waypoint to be valid - meaning that Ew is the last reconfiguration event prior to Vw, we can infer that Ew is under Hw.  We could also verify this if desired, but it is unnecessary due to the logical inference.

### Procedure for proving results

This means that to perform verification, we do a single query via updateToLatestLedger().  The request item is for the event Ew with a known version of Vw.  

The proof returned by this query includes multiple elements used to verify the entire proof:

    1. Verify **(1)** by verifying the hash proof from Hw to Hc (this is how we always verify any response from updateToLatestLedger(), so nothing is different here).  This is verified by checking the hashes going up the accumulator from Hw to the latest signed ledger info’s accumulator root Hc.
    2. The signed ledger infos at every epoch.  These will contain the new validator set for that epoch.  There will also be a proof returned for the accumulator root hash of each of these up to the latest accumulator root hash at Vc.  Proof verification must first verify the accumulator proof for each of these.  It must then verify the signatures on each signed ledger info.  The result of this entire process will allow the client to know the latest validator set.  This will also verify **(2)** since any updateToLatestLedgerInfo will also verify the signed ledger infos at epochs.
    3. The latest signed ledger info at Vc.  The client must use the latest validator set derived from (b) to verify the signatures on this ledger info.

By verifying the above, we can now infer that **(3) **is also true.  So we can now trust the latest version Vc.
* * *

## Appendix: Alternatives Considered

* * *
One option instead of storing in events is to store in state.  But this requires a validator remembering the state and exposing queries against non-current states (something that doesn’t currently exist).

Since the Ledger Info (LI) struct contains both the version and the transaction accumulator root hash, one could wonder why the entire LI struct isn’t used as the waypoint.  The LI struct contains additional information that isn’t relevant to proving validity, and in addition would be too large to be an easily copyable value in the case where a user wishes to set a waypoint within their node via copying from an online source.

Another alternative could be to use the hash of the LI.  In this proposal, a node would query a validator for the LI at that hash value and then use the resultant version/accumulator root hash in future API calls to get_with_proof (or perhaps modify that API and simply use the LI hash in those API calls).  Unfortunately, this also isn’t an option since LI hashes are not stored by validators with the exception of the most recent LI root hash and the LI root hash at validator rotation boundaries.  This would imply that waypoints could only exist at validator rotation boundaries.

**Comment by dmitri-perelman** [comment]
After several rounds of discussions it seems that we're going to use a slightly different design for the waypoints described in #1384
