### ISSUE TITLE
[bors] if bors times out it doesn't notify the PR that no progress has been made

### ISSUE THREAD

**Issue by bmwill** [libra/libra#1017]
We ran into some issues with CircleCI today where we ran out of "seats" and builds weren't being run. When this happens I'm assuming that bors has some sort of timeout but it never notified the PR that it had hung. Example here: https://github.com/libra/libra/pull/1007.

I had to manually re-approve it in order to get bors to re-kickoff a build.

**Comment by davidiw** [comment]
hmm... still an issue?
