### ISSUE TITLE
[Bug] My Libra Coins Just Got Confiscated By a Third Party

### ISSUE THREAD

**Issue by pigd0g** [libra/libra#102]
# 🐛 Bug

Funds have been seized by a third party due to violation of terms of service. I just posted something the validators don't agree with on social media.

## To reproduce

Trust facebook with your money.

## Expected Behavior

Be able to do what I want with my money.

**Comment by xmrdsc** [comment]
It's a feature not a bug.

**Comment by ZettaScript** [comment]
> It's a feature not a bug.

Effectively, so we can say this feature is a bug.

**Comment by lpfloyd** [comment]
You win!

**Comment by lucasverra** [comment]
keeping this for posterity. M$ do not delete this :)

**Comment by ericnakagawa** [comment]
Hi @pigd0g, I'm closing this issue as it appears off-topic.

**Comment by fedekunze** [comment]
"permissionless" "blockchain"

**Comment by krrisis** [comment]
so on-topic!

**Comment by krrisis** [comment]
> Hi @pigd0g, I'm closing this issue as it appears off-topic.

so on-topic actually!
