### ISSUE TITLE
when run  ./scripts/cli/start_cli_testnet.sh error

### ISSUE THREAD

**Issue by fisho2017** [libra/libra#103]
error: failed to run custom build command for `grpcio-sys v0.4.4`

Caused by:
  process didn't exit successfully: `/usr/libra/target/debug/build/grpcio-sys-18712f499919ddc1/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=grpc_wrap.cc
cargo:rerun-if-changed=grpc
cargo:rerun-if-env-changed=GRPCIO_SYS_USE_PKG_CONFIG
cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
running: "cmake" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.4.4/grpc" "-DgRPC_INSTALL=false" "-DgRPC_BUILD_CSHARP_EXT=false" "-DgRPC_BUILD_CODEGEN=false" "-DgRPC_BENCHMARK_PROVIDER=none" "-DCMAKE_INSTALL_PREFIX=/usr/libra/target/debug/build/grpcio-sys-c998cb3e25589d95/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/libra/target/debug/build/grpcio-sys-c998cb3e25589d95/out/build

software version
go version go1.10.8 linux/amd64
libprotoc 3.8.0

**Comment by trustfarm-dev** [comment]
check your rustup toolchain versions please.

https://github.com/libra/libra/issues/99

**Comment by horca17** [comment]
I have to upgrade go to the latest version, I was using go 1.9.2 and having the same error.

**Comment by trustfarm-dev** [comment]
@horca17 latest nightly version fails to build.
You can do exact rust toolchain version like this way.

```
cargo clean --package libra_swarm
rustup toolchain install nightly-2019-05-22-x86_64-unknown-linux-gnu
rustup override set nightly-2019-05-22
cargo run -p libra_swarm -- -s

```

**Comment by fisho2017** [comment]
libprotoc 3.8.0
go1.12.5
rustup 1.18.3
rustc 1.36.0-nightly
ok~

**Comment by sinhang** [comment]
> libprotoc 3.8.0
> go1.12.5
> rustup 1.18.3
> rustc 1.36.0-nightly
> ok~

cmake >= 3.3
