### ISSUE TITLE
[state_synchronizer] `test_peer_manager` is flaky

### ISSUE THREAD

**Issue by bmwill** [libra/libra#1034]
The state_synchronizer unit test `test_peer_manager` is flaky and need to be either disabled or fixed to be deterministic and no longer flaky.

Some instances of this flakiness:
https://github.com/libra/libra/pull/1007#issuecomment-533659479
https://circleci.com/gh/libra/libra/7309#tests/containers/2

**Comment by sunmilee** [comment]
Thanks for reporting, will get it fixed

**Comment by sunmilee** [comment]
Resolved
