### ISSUE TITLE
 [state_synchronizer] `smoke_test::test_basic_state_synchronization` is flaky

### ISSUE THREAD

**Issue by bmwill** [libra/libra#1039]
The state_synchronizer smoke test test_basic_state_synchronization is flaky and need to be either disabled or fixed to be deterministic and no longer flaky.

An instances of this flakiness:
https://circleci.com/gh/libra/libra/7413#tests/containers/3

**Comment by zekun000** [comment]
it may be related to https://github.com/libra/libra/issues/1054 if it only becomes flaky after 6cc5365 

is there a way to see test failure frequency to confirm? (I guess probably not)

**Comment by zekun000** [comment]
I saw this is still happening -  more logs available this time
https://circleci.com/gh/libra/libra/7923#tests/containers/3

**Comment by bmwill** [comment]
Closed by #1092
