### ISSUE TITLE
libra_node usage information request

### ISSUE THREAD

**Issue by trustfarm-dev** [libra/libra#106]
### Please note that this issue tracker is not a help form and this issue will be closed.

there's libra_node packages in it.

```
cargo build -p libra_node 
./target/debug/libra_node -h

Libra single node 0.1.0
Libra Association <opensource@libra.org>
Libra single node Service

USAGE:
    libra_node [FLAGS] [OPTIONS]

FLAGS:
    -d, --no_logging    Controls logging
    -h, --help          Prints help information
    -V, --version       Prints version information

OPTIONS:
    -f, --config_path <--config_path>    Specify the path to the config file
    -p, --peer_id <--peer_id>            Specify peer id for this node
```
can't found usages examples.

please inform .

**Comment by kphfb** [comment]
Hi @trustfarm-dev, libra_node is used to run a single node.  For more usage information, please look at libra_swarm and how it uses libra_node.  The preferred method to spawning a libra node is to run libra_swarm.
