### ISSUE TITLE
[Bug]./scripts/cli/start_cli_testnet.sh error on CentOS7 release 3.10.0-957.12.2.el7.x86_64

### ISSUE THREAD

**Issue by MattWangming** [libra/libra#107]
# 🐛 Bug
There is error on `./scripts/cli/start_cli_testnet.sh` with output of:
```
Compiling grpcio-sys v0.4.4
error: failed to run custom build command for `grpcio-sys v0.4.4`
```

## To reproduce
Just follow the instruction 
1. `git clone https://github.com/libra/libra.git`
2. `./scripts/dev_setup.sh`
3. `./scripts/cli/start_cli_testnet.sh`
The error occurred on step3.

** Stack trace/error message **
```
 Compiling grpcio-sys v0.4.4
error: failed to run custom build command for `grpcio-sys v0.4.4`

Caused by:
  process didn't exit successfully: `/root/libra/libra/target/debug/build/grpcio-sys-18712f499919ddc1/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=grpc_wrap.cc
cargo:rerun-if-changed=grpc
cargo:rerun-if-env-changed=GRPCIO_SYS_USE_PKG_CONFIG
cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
```
For details, please refer to below link: 
[error_in_testnet_script.txt](https://github.com/libra/libra/files/3305846/error_in_testnet_script.txt)
## System information

**Please complete the following information:**
- 

- 
- CentOS7 3.10.0-957.12.2.el7.x86_64

**Comment by csunny** [comment]
@MattWangming    [#76](https://github.com/libra/libra/issues/76)   There is the same problem.  Maybe you need to install cmake3.

**Comment by MattWangming** [comment]
One more thing to emphasize is that the h/w resources consumption is really high during the compiling state, even my laptop with latest core i5 could not make it easy.
So what I suggest is to make full use of h/w with high level configuration, and other s/w configuration could be ignored compared to this.

**Comment by csunny** [comment]
@MattWangming   Yes, I used my mac with 4core 8G mem, It's very slow.   So I build this with 8core 16G Centos7.6
