### ISSUE TITLE
[Bug]Will this coin perform better than Bitcoin ?

### ISSUE THREAD

**Issue by Solexplorer** [libra/libra#108]

**Comment by slash7** [comment]
@Solexplorer 😂

**Comment by bugthug** [comment]
In order to invest you need to:
1. Have 10 million dollars

**Comment by Solexplorer** [comment]
@bugthug Is there a way to invest with 10$ ?

**Comment by slash7** [comment]
Libra is a stable coin. It has the same function as Tether: it’s stable! In other words is pegged to USD and will always have the same value. Assuming 1 Libra equals 1 USD, the value will never change, so it’s useless to “invest” in the hopes that the value of your Libra coins will go up.

**Comment by Solexplorer** [comment]
@slash7 Huh ?
I thought I could dump my stocks to fill my Libra positions . So I don't get more Bitcorns ?

How rude Facebook to not let us speculate

**Comment by Guillerbr** [comment]
is an application for code development this subject must be dealt with in another medium.

**Comment by Guillerbr** [comment]
is an application for code development this subject must be dealt with in another medium.
