### ISSUE TITLE
Client fails to connect to Docker based validator node: Deadline exceeded

### ISSUE THREAD

**Issue by RobertoDonPedro** [libra/libra#1081]
I did exactly the 6 steps as described in the [Libra Docker Readme](https://github.com/libra/libra/blob/master/docker/README.md).

After doing the steps 1-5 the validator nodes and the faucet server are running successfully:
`docker ps`
> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                          NAMES
fd84c8aa87a6        libra_mint:latest   "/bin/sh -c 'cd /opt…"   13 minutes ago      Up 13 minutes       0.0.0.0:8080->8000/tcp         awesome_pike
22e5b50811dc        libra_e2e:latest    "/bin/sh -c 'cd /opt…"   14 minutes ago      Up 14 minutes       6180/tcp, 8000/tcp, 9101/tcp   pedantic_wescoff
31273f30a6f9        libra_e2e:latest    "/bin/sh -c 'cd /opt…"   14 minutes ago      Up 14 minutes       6180/tcp, 8000/tcp, 9101/tcp   friendly_gauss
4a7f99d15f80        libra_e2e:latest    "/bin/sh -c 'cd /opt…"   14 minutes ago      Up 14 minutes       6180/tcp, 8000/tcp, 9101/tcp   sweet_mendel
324cb273f4fa        libra_e2e:latest    "/bin/sh -c 'cd /opt…"   14 minutes ago      Up 14 minutes       6180/tcp, 8000/tcp, 9101/tcp   pensive_kepler

 
But the last command  fails and I get the error message below:
`cargo run -p client --bin client -- -a localhost -p 8000 -f localhost:8080 -s terraform/validator-sets/dev/consensus_peers.config.toml`

> Not able to connect to validator at localhost:8000, error RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") })

**Comment by surushtaherian** [comment]
god is sooo goood make a pray

**Comment by davidiw** [comment]
please re-open if issues persist.
