### ISSUE TITLE
vscode debug, args parsing failure 

### ISSUE THREAD

**Issue by gzuhlwang** [libra/libra#110]
### 
when I debug client program with vscode on Mac, the args part of launch.json file is as follows: 
```
"args": [
                "--host ac.testnet.libra.org",
                "--port 8000",
                "-s $SCRIPT_PATH/trusted_peers.config.toml"
            ],

```
it does't work.
But when I replace it with the following :
```
"args": [
                "-a ac.testnet.libra.org",
                "-p 8000",
                "-s $SCRIPT_PATH/trusted_peers.config.toml"
            ],
```
Parsing command line is successful.
please check. thanks.

**Comment by jianglinchun** [comment]
for you reference:
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "[Debug] Libra Test Net",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/target/debug/client",
            "args": [
                "--host",
                "ac.testnet.libra.org",
                "--port",
                "8000",
                "-s",
                "${workspaceFolder}/scripts/cli/trusted_peers.config.toml"
            ],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "linux": {
                "MIMode": "gdb",
                // "miDebuggerPath": "/usr/local/cargo/bin/rust-gdb",
            },
            "logging": {
                "trace":true
            }
        }
    ]
}`

**Comment by bmwill** [comment]
This seems to be more of an editor issue than a libra one, if i've misunderstood please reopen the issue.
