### ISSUE TITLE
Why the validator node is 100?

### ISSUE THREAD

**Issue by csunny** [libra/libra#111]
## ❓ Questions and Help

The validator node is 100, I wonder to know, why?  why not 21 or another number?

Someone can answer me?

**Comment by fxsjy** [comment]
100 is perfect score.

**Comment by gzuhlwang** [comment]
@fxsjy  so naughty 😄

**Comment by gianlucamazza** [comment]
it's easier to calculate 51% attacks

**Comment by bmaurer** [comment]
The system doesn't depend on having exactly 100 -- it's simply an estimate of how many validators might participate in the system initially.
