### ISSUE TITLE
Baidu, China's Version of Google, released its blockchain architecture xuperunion.

### ISSUE THREAD

**Issue by qizheng09** [libra/libra#112]
# 🚀 Feature Request

https://github.com/xuperchain/xuperunion

## Motivation

**XuperUnion, the first open source project of XuperChain, introduces a highly flexible blockchain architecture with great transaction performance.**

## Additional context

XuperUnion is the underlying solution for union networks with following highlight features:

* **High Performance**

    * Creative XuperModel technology makes contract execution and verification run parallelly.
    * TDPoS ensures quick consensus in a large scale network.
    * WASM VM using AOT technology.

* **Solid Security**

    * Contract account protected by multiple private keys ensures assets safety.
    * Flexible authorization system supports weight threshold, AK sets and could be easily extended.

* **High Scalability**

    * Robust P2P network supports a large scale network with thousands of nodes.
    * Branch management on ledger makes automatic convergence consistency and supports global deployment.

* **Multi-Language Support**: Support pluggable multi-language contract VM using XuperBridge technology.

* **Flexibility**:  Modular and pluggable design provides high flexibility for users to build their blockchain solutions for various business scenarios.

**Comment by fxsjy** [comment]
Spam, close it.

**Comment by duanbing** [comment]
Good repo, worth reading.
