### ISSUE TITLE
[Roadmap][Move] Core Modules

### ISSUE THREAD

**Issue by ericnakagawa** [libra/libra#1137]
This issue tracks development of the core modules planned for the initial launch. We are continuing to revise the content of these modules with modifications and enhancements, but most of them are functionally complete.

The remaining work consists of two core modules:

* Time
* Cold wallet support

The Time module will provide access to the latest time recorded in the blockchain metadata. This will be straightforward and we expect to implement that soon.

The cold wallet support module will define a set of rules for extra security policies. Security policies are intended to restrict the power of an approval group by restricting the parameters of the transactions it is allowed to authorize, or limiting the rate at which transactions are authorized or delays before they are executed.

1. Threshold Approval Policy: This policy distributes the authorization power among a number of trusted approvers, and ensures that no single entity has the power to perform actions unilaterally. The threshold defines how many approvers need to approve a transaction in order for it to be authorized.

2. Allowed Recipient Policy: This policy helps to limit the allowed recipient addresses of an outgoing transaction. This is a useful guardrail to have in situations where it is known in advance all the possible recipients of this account. For example, transfer from cold wallet to hot wallets, or from hot wallets to one of the exchanges. This policy limits the damage even when the private keys of the authorized group members are compromised. 

3. Rate Limiting Policy: The rate limiting policy helps to provide another layer of protection even when a quorum number of signatures on a fraudulent transaction is obtained by an adversary. In that
 situation, the amount of damage is limited to what the rate limiting policy allows for the
 Wallet, e.g., 10M/24hour, provided that the enforcement of this policy still maintains its
 integrity. 

4. Delayed Execution Policy: The transaction is first published on-chain and then wait for a delay period before being executed. This allows people to react and cancel a pending transaction in case a mistake happened.

5. Cancelation Policy: A pending transaction can be canceled before it is executed (this is linked to the delayed execution policy).

**Comment by bob-wilson** [comment]
The Time module (now named LibraTime) was added in https://github.com/libra/libra/pull/2275

**Comment by bob-wilson** [comment]
We are also planning to add support for multisig accounts. The initial work for this is in #2723

**Comment by bob-wilson** [comment]
Multisig support is done in #2939

**Comment by bob-wilson** [comment]
Our current expectation is that multisig accounts are the only real must-have feature for cold wallets. We can continue to explore adding the other cold wallet features as future enhancements, but for now, let's consider these Core Modules features to be done.
