### ISSUE TITLE
[Roadmap][Move] Generics/Collections

### ISSUE THREAD

**Issue by ericnakagawa** [libra/libra#1138]
The development of generic types in Move is tracked in https://github.com/libra/libra/issues/1000.
This issue tracks providing generic collections. For v1, we specifically need a generic Vector type. Other collection types may be considered in the future, but for now we are only committing to implement Vector.

**Comment by bob-wilson** [comment]
Generic Vectors have been implemented now (https://github.com/libra/libra/pull/694). We have made some subsequent changes to add more APIs to the Vector type (e.g., https://github.com/libra/libra/pull/972, https://github.com/libra/libra/pull/1110, https://github.com/libra/libra/pull/1089, etc.). There may be some further polishing of the interface, but we can consider this complete now.
