### ISSUE TITLE
[Roadmap][Consensus] Reconfiguration

### ISSUE THREAD

**Issue by ericnakagawa** [libra/libra#1139]
This issue tracks reconfiguration of LibraBFT - an extension to LBFT to support reconfigure itself
 by embedding configuration-change commands in the sequence.
LBFT addresses the fundamental consensus problem of the libra blockchain with fixed configuration setup, think of validator set, consensus keys, VM features, software version etc.
Those are all like configuration of one LBFT protocol instance. we want to support those configuration changes without human intervention which could be excessive work and error prone. Instead we present a protocol to handle reconfiguration just like a normal transaction.

- [x] Consensus Support #895 #897 #899  
- [x] Networking Support #1380 
- [x] Language Support #1382 
- [x] Execution Support #1383 
- [x] Storage Support #849

**Comment by pdhamdhere** [comment]
Blog post: https://developers.libra.org/blog/2020/01/14/reconfiguration-is-live-on-testnet
