### ISSUE TITLE
[Question] Question about your virtual machine

### ISSUE THREAD

**Issue by blockchainmanZ** [libra/libra#114]
The design of Libra's virtual machine is ingenious, And we want to transplant your VM into our blockchain system which is called XuperChain. But we have one consideration:1) If your virtual machine is strongly related to the language of rust because our programming language is go. For more details about XuperChain, Please visit the repo of https://github.com/xuperchain/xuperunion.

**Comment by fxsjy** [comment]
I don't think so.   Move is based on Rust which has many good features to design a  strong VM. May be you can try to migrate it from Rust to Go. But, I thinks it is not easy.

**Comment by sblackshear** [comment]
Thanks for the kind words!

Rust is a good language for implementing a virtual machine, but there is nothing Rust-specific about the Move VM. However, it is probably too early to implement the virtual machine in a different language. We are still in the process of writing a VM specification (along with specs for other key parts of the protocol), and we expect that things will change a bit.

**Comment by ericnakagawa** [comment]
@blockchainmanZ How about moving this discussions to [Discourse](https://community.libra.org)?
