### ISSUE TITLE
[Roadmap] VM Versioning

### ISSUE THREAD

**Issue by ericnakagawa** [libra/libra#1144]
There are multiple things that might need to be versioned:

- Move source language: We anticipate using semantic versioning for the Move source language, but at this point, there isn't much to do in that regard. Developers may need to be aware of what version of the language they are using, since new features may be added over time.

- Modules: What happens if a Move module is published on chain and then needs to be modified? We do not yet have a plan for this. In the initial rollout, we expect to only support modules published by the Libra Association, and we will have a mechanism to update those core modules.

- Resources: Versioning resources that are published on chain is complicated. We will explore this for the future but do not plan to support it for now.

 - Move VM: As the VM evolves, we need to make sure that it can still process old transactions if someone wants to reconstruct the blockchain. Any change that causes the VM to produce different results needs to be versioned. Similarly any new feature that is added should be associated with a way to check if that feature is supported by a particular version of the VM. We intend to use "feature flags" stored on-chain to implement this versioning of the VM.

This issue tracks only the work for that last item: feature flags stored on-chain to mark changes in 
VM functionality.

**Comment by bob-wilson** [comment]
We are currently in the process of planning the implementation of the VM feature flags.

**Comment by bob-wilson** [comment]
Support for on-chain configuration is in #2932. I think there may be a small amount of work on top of that before this is done.

**Comment by bob-wilson** [comment]
@runtian-zhou Is this done now with #3143?

**Comment by runtian-zhou** [comment]
That is done with #3143. We will need more testing on this to demonstrate a migration path in the future.
