### ISSUE TITLE
[network] Convert verified Discovery messages to a verified type without unwrap accessors

### ISSUE THREAD

**Issue by bothra90** [libra/libra#1150]
At present, Discovery message fields are accessed using `.unwrap()` once they've been verified to be present and valid. This makes the code look uglier and riskier than it really is or needs to be. A better solution would be to convert verified messages into an alternate type which provides accessors that don't unwrap, along the following lines:

`fn verify_message(raw_discovery_msg: bytes) -> Result<VerifiedDiscoveryMsg>`

**Comment by ackintosh** [comment]
I'll work on this issue. 😃

**Comment by bothra90** [comment]
fixed by #1332
