### ISSUE TITLE
Runtime reconfiguration of log level

### ISSUE THREAD

**Issue by mgorven** [libra/libra#1151]
# 🚀 Feature Request

At the moment we set the logging level in the `RUST_LOG` environment variable at startup, and changing the log level requires restarting the process. It would be useful to be able to change the log level at runtime to avoid throwing away the process state. The feature request is to build an API which allows the administrator to provide new logging configuration. For example, this could be an HTTP endpoint which takes a new `RUST_LOG` value and reconfigures the logging:

    curl -d level=debug http://localhost:6190/config/logging

**Comment by davidiw** [comment]
@bmwill, seem you might make @mgorven happy soon. hahaha

**Comment by bmwill** [comment]
I'm currently adding back in Filtering from Env Vars as we speak (it had to be ripped out for text logs when we unified our two systems) And once thats done I'll be able to do this! :D
