### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by Sm1le291** [libra/libra#116]
Please create RestAPI to access to the validator

**Comment by ericnakagawa** [comment]
Hi @Sm1le291, you should be able to access the network using a gRPC package. However, a wrapper could be a great idea. Someone in the community could kick this off!

**Comment by PhearZero** [comment]
:sparkles: Sorry for necroposting this, should have another issue stub/PR for the general RFC sometime this next week or so. If you know of anyone with progress towards exposing the RPC let me know and I'll team up over there. For now I'll backlink to this thread
