### ISSUE TITLE
[Feature Request][Metrics] Update Metric Key Names

### ISSUE THREAD

**Issue by koensayr** [libra/libra#1185]
# 🚀 Feature Request

Metric names should follow some set of best practices.

## Motivation

Currently metric names emitted by the software have the potential to conflict with metrics already collected. Instead they should follow at least the best practices for naming conventions. This will help more easily integrate Libra in with current tooling already in place and decrease the risk of named key-pair collisions.

## Pitch

This is discussed further here:

https://prometheus.io/docs/practices/naming/

At the very least:

* The libra prefix should be added

* The prefix should consist of “libra” and a component, e.g. libra_consensus, libra_network The unit should be specified, and should be a base unit (seconds not milliseconds), e.g. libra_network_sent_bytes, libra_consensus_block_latency_seconds

* Labels within a metric name should represent the same logical thing, e.g. libra_network_requests_total{method=”UpdateToLatestLedger”} and libra_network_peers{state=”connected”}.

* “As a rule of thumb, either the sum() or the avg() over all dimensions of a given metric should be meaningful (though not necessarily useful). If it is not meaningful, split the data up into multiple metrics.”

* Metric names and labels should not contain values with high cardinality (e.g. a label with the gRPC method name is fine, a label with the client’s IP is not).

**Comment by bob-wilson** [comment]
I updated the VM metrics in #3600

**Comment by davidiw** [comment]
good call! I think we should be in a better state and would be better off creating distinct issues at this point in time.
