### ISSUE TITLE
[Bug] ArgType.UNRECOGNIZED gets -1 value in Java while Enum encoded as UInt32 in proto file

### ISSUE THREAD

**Issue by chaingrok** [libra/libra#1192]
# 🐛 Bug

When we generate the libra proto files in Java, for transactio.proto, we get 

public enum ArgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>U64 = 0;</code>
       */
      U64(0),
      /**
       * <code>ADDRESS = 1;</code>
       */
      ADDRESS(1),
      /**
       * <code>STRING = 2;</code>
       */
      STRING(2),
      /**
       * <code>BYTEARRAY = 3;</code>
       */
      BYTEARRAY(3),
      UNRECOGNIZED(-1),
      ;

etc.

full code at https://github.com/chaingrok/libra4j/blob/master/src/grpc/java/org/libra/grpc/types/Transaction.java  (see line 116)

The UNRECOGNIZED(1-) is a problem because, as per https://github.com/libra/libra/tree/master/common/canonical_serialization, enum values are represented as UInt32 which cannot by definition contain a negative value.

We understand that this -1 is generated automatically by the Java proto compiler. But, it would make testing clean if this -1 got replaced by a positive value like Integer.MAX_VALUE.

**Comment by davidiw** [comment]
we no longer use protobuf
