### ISSUE TITLE
[cluster_test] Network delay simulation

### ISSUE THREAD

**Issue by andll** [libra/libra#1198]
We want to be able to simulate network latencies between validators from cluster_test

So far it seems that [netem](https://wiki.linuxfoundation.org/networking/netem) is a good tool to control traffic on kernel level. We already have it installed on validators, cluster test can use ssh to run it.

For example of ssh usage see `Reboot effect`(testsuite/cluster-test/src/effects/reboot.rs)

With network delay we are interested in two different kinds of experiments
1) Simulating that some nodes have network problems - large delay, packet loss, etc. We want to verify during this experiment that other nodes are doing fine during those experiments and make progress.
2) Simulating multi-region environment. We want to be able to define clusters('regions') of nodes, that would have low latency between each other, but high latencies between nodes in different regions. We want to evaluate how this will affect libra performance.

Current test libra cluster is 100 nodes, and we can scale it up to 1000, we need to take this into account when designing solution, so it can apply network settings to all nodes in a reasonable time.

**Comment by ankushagarwal** [comment]
> We already have it installed on validators, cluster test can use ssh to run it

I don't think this is true. Created #1472 to add the `tc` package which adds `netem` to validators
