### ISSUE TITLE
[Feature Request] nextgen_crypto without stdlib

### ISSUE THREAD

**Issue by prestonvanloon** [libra/libra#121]
# 🚀 Feature Request

[nextgen_crypto](https://github.com/libra/libra/tree/master/crypto/nextgen_crypto) libraries without the use of stdlib. 

## Motivation

I want to (potentially) statically link nextgen_crypto libraries with FFI, but I don't want to bring the rust standard library with me. 

## Pitch

**Describe the solution you'd like**
nextgen_crypto with `#![no_std]`

https://doc.rust-lang.org/1.8.0/book/using-rust-without-the-standard-library.html

**Describe alternatives you've considered**
Not using this / roll-your-own-crypto / forking without stdlib.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Probably not. I don't know enough about this to fulfill the requirements effectively. 

## Additional context

Thanks

**Comment by rauljordan** [comment]
+1 on this!

**Comment by terencechain** [comment]
This will be awesome!

**Comment by c-o-l-o-r** [comment]
This would a great contribution to rust!

**Comment by ladiJ2N** [comment]
Hi there,

I'm on the Libra Cryptography team and this is deffinitely something we can start working on.

That said, here's an idea: Why don't we do it together!

You seem interested in the topic and claimed that you don't know enough about the topic to fulfill the requirements effectively. If you'd like, I can provide support.

If you would prefer not to be involved, it will need to be prioritized in the list of things we currently have on our cryptography roadmap which primarily revolves around providing high-assurance cryptography for the Libra blockchain.

Let me know if you're interested. I'm always game for collaboration.

**Comment by prestonvanloon** [comment]
Hey @ladiJ2N, definitely interested in collaboration and willing to learn. 
I have limited exposure to Rust, but it doesn't seem that intimidating. 

With your support, it sounds like we can resolve this. Kindly let me know where to start. 

I have a specific ask that we avoid using dynamically allocated data structures; I had some pain trying to specify a global allocator without stdlib and prevent duplicate symbols in the linker (could be something I was doing wrong with linking it). It seems like we can avoid things like `alloc::vec::Vec` and still have a working crypto. What do you think? 

Thanks!

**Comment by ladiJ2N** [comment]
I believe the issue lies in the threshold_crypto crate.

You can try to remove BLS from the nextgen_crypto crate first and see if you are able to get it to work that way.

**Comment by prestonvanloon** [comment]
As expected, adding `#![no_std]` to crypto/nextgen_crypto/lib.rs fails: [build.log](https://github.com/libra/libra/files/3315940/build.log)

What is the pattern of best practice here? Is there way to support std and no_std builds?
Do we need std for some things? Seems like there are debug log statements, use of several `std::` components. Not sure what the non, std library options are for `std::hash:Hash` or `std::result::Result`. 

To clarify requirements, we're trying to use no_std without heap or collections, if possible.

![Screenshot from 2019-06-21 16-36-15](https://user-images.githubusercontent.com/7246818/59950026-d7c0cd00-9442-11e9-8c92-2ec05ad3d95b.png)

[img src](https://rust-embedded.github.io/book/intro/no-std.html)

**Comment by davidiw** [comment]
Closing this out as our crypto crate is a wrapper around underlying libraries.
