### ISSUE TITLE
error: failed to run custom build command for `proto_conv v0.1.0

### ISSUE THREAD

**Issue by barray888** [libra/libra#1214]
Caused by:
  process didn't exit successfully: `/Users/barray/Documents/learn-libra/libra/target/debug/build/proto_conv-92f45ffe9bbc0fa2/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=tests/proto/test.proto

--- stderr
thread 'main' panicked at 'Failed to compile protobuf input: "tests/proto/test.proto"', common/build_helpers/src/build_helpers.rs:62:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by bmwill** [comment]
We recently removed the proto_conv crate so you might want to try fetching the latest master and trying again.
