### ISSUE TITLE
[Feature Request] Allow to run cluster test locally with libra swarm

### ISSUE THREAD

**Issue by andll** [libra/libra#1219]
Running
`cargo run -p libra-swarm -- -n 4`
Will start local libra cluster of 4 nodes.
It would be good for dev purposes if we could also run cluster_test(at least in some capacity) on those nodes.
It would not be possible to integrate with experiments that require, for example, rebooting machines, but it can integrate with transaction generator(`--emit-tx` flag).

When libra swarm starts, it output two essential lines
```
Faucet account created in (loaded from) file <path to mint key file>
...
To run the Libra CLI client in a separate process and connect to the validator nodes you just spawned, use this command:
	cargo run --bin client -- -a localhost -p <Port>
```

Ideally we want libra swarm to additionally print something like

```
To run transaction generator run
cargo run --bin cluster-test -- --mint-file <path to mint key file> --peers <localhost:Port> --emit-tx 
```

This essentially requires modification in two places
(1) In libra swarm - to output this hint message with port and path to mint file taken from generated libra swarm config
(2) In cluster_test - support running it locally with libra swarm
   (a) Add `--mint-file` arg and read file name from it, instead of `"mint.key"` in `tx_emitter.rs`
   (b) Add `ac_port` field to `Instance` class to allow custom ac ports instead of default 8000 (see TxEmitter::make_client)
   (c) In `Cluster::discovery` detect if `--peers` arg has host:port pairs in it, use those host:port instead of aws discovery.

**Comment by ankushagarwal** [comment]
@andll In the case of using local libra-swarm as the Cluster, what should we set `prometheus_ip` to in `struct Cluster` from `cluster.rs`?

**Comment by andll** [comment]
Yeah, prometheus is a problem - there is no prometheus in libra swarm.
I think simplest solution is to put something like `127.0.0.1:99999` there. This will make calls to prometheus to fail, which means `print_stat` won't print stats, which is ok.
We still will only be able to run `--health-check` and `--emit-tx`, just without printing stats.

**Comment by andll** [comment]
Other alternative is to have prometheus ip as an Option :)

**Comment by ankushagarwal** [comment]
> Other alternative is to have prometheus ip as an Option :)

This is what I was thinking.

**Comment by andll** [comment]
Yeah, I just was not supporting pretty narrow use case for local start worth code complication..
