### ISSUE TITLE
[Feature Request] Add Support for FreeBSD 

### ISSUE THREAD

**Issue by EvertonMelo** [libra/libra#122]
# 🚀 Feature Request

Add support FreeBSD 12.x >

## Motivation

Freebsd has one of the market's TCP / IP stack miles, it can be useful for a benchmark

## Pitch
map installation requirements, find equivalents in x[BSD PORTS](https://github.com/freebsd/freebsd-ports);
or we can look for a solution by [binary compatibility](https://www.freebsd.org/doc/handbook/linuxemu.html) with LINUX.

**Comment by bmwill** [comment]
The external dependencies needed to build Libra have been simplified and should only require Rust now so this shouldn't be an issue anymore on master. If it is, please let us know.

**Comment by EvertonMelo** [comment]
@bmwill 

yes it is a problem in the master, but who cares? you have not read the issue about and you will not read this comment. 

the issue has libra-core/master screens.
