### ISSUE TITLE
[cluster-test] Download genesis blob on deploy

### ISSUE THREAD

**Issue by andll** [libra/libra#1224]
Currently when cluster test wants to deploy new version it stop nodes, delete db, updates task definitions to use new version and start nodes. See `cluster-test/main.rs:redeploy`

It does not however, update genesis.blob automatically.

This means that if genesis.blob was updated, and new code requires updated genesis.blob, then cluster test will fail

In order to avoid it we also need to deploy latest genesis.blob. It is not part of docker image, because it specific to setup, so we need a way to fetch it separately.

As discussed in meeting with @bschwab and @mgorven, current thought is that we going to put genesis.blob into S3 bucket and then cluster test can fetch it to validators during deploy. @sausagee is working on build part (putting into S3 bucket) but we also need support on cluster test side to download it during deploy

**Comment by andll** [comment]
cc @bschwab @mgorven @sausagee

**Comment by sausagee** [comment]
@andll nightly has been updated.  It will upload the blob to `s3://toro-validator-sets/upstream_{hash}/100/genesis.blob`.
