### ISSUE TITLE
[Bug] 'chained_bft::chained_bft_smr_test::basic_commit_and_restart' panicked

### ISSUE THREAD

**Issue by aching** [libra/libra#1255]
# 🐛 Bug

---- chained_bft::chained_bft_smr_test::basic_commit_and_restart stdout ----
thread 'chained_bft::chained_bft_smr_test::basic_commit_and_restart' panicked at 'round of node 1 is 17', consensus/src/chained_bft/chained_bft_smr_test.rs:403:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at /rustc/fa5c2f3e5724bce07bf1b70020e5745e7b693a57/src/libstd/io/mod.rs:1412
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:141
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:207
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  12: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:335
  14: consensus::chained_bft::chained_bft_smr_test::basic_commit_and_restart::{{closure}}
             at consensus/src/chained_bft/chained_bft_smr_test.rs:403
  15: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/fa5c2f3e5724bce07bf1b70020e5745e7b693a57/src/libstd/future.rs:42
  16: std::future::set_task_context
             at /rustc/fa5c2f3e5724bce07bf1b70020e5745e7b693a57/src/libstd/future.rs:78
  17: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fa5c2f3e5724bce07bf1b70020e5745e7b693a57/src/libstd/future.rs:42
  18: futures_executor::local_pool::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.19/src/local_pool.rs:295
  19: futures_executor::local_pool::run_executor::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.19/src/local_pool.rs:68
  20: std::thread::local::LocalKey<T>::try_with
             at /rustc/fa5c2f3e5724bce07bf1b70020e5745e7b693a57/src/libstd/thread/local.rs:262
  21: std::thread::local::LocalKey<T>::with
             at /rustc/fa5c2f3e5724bce07bf1b70020e5745e7b693a57/src/libstd/thread/local.rs:239
  22: futures_executor::local_pool::run_executor
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.19/src/local_pool.rs:64
  23: futures_executor::local_pool::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.19/src/local_pool.rs:295
  24: consensus::chained_bft::chained_bft_smr_test::basic_commit_and_restart
             at consensus/src/chained_bft/chained_bft_smr_test.rs:376
  25: consensus::chained_bft::chained_bft_smr_test::basic_commit_and_restart::{{closure}}
             at consensus/src/chained_bft/chained_bft_smr_test.rs:313
  26: core::ops::function::FnOnce::call_once
             at /rustc/fa5c2f3e5724bce07bf1b70020e5745e7b693a57/src/libcore/ops/function.rs:227
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/fa5c2f3e5724bce07bf1b70020e5745e7b693a57/src/liballoc/boxed.rs:922
  28: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  29: std::panicking::try
             at /rustc/fa5c2f3e5724bce07bf1b70020e5745e7b693a57/src/libstd/panicking.rs:271
  30: std::panic::catch_unwind
             at /rustc/fa5c2f3e5724bce07bf1b70020e5745e7b693a57/src/libstd/panic.rs:394
  31: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1413
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    chained_bft::chained_bft_smr_test::basic_commit_and_restart

test result: FAILED. 80 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p consensus --lib'
Exited with code 101

## Suspected related PR

#1245

**Comment by huitseeker** [comment]
Fixed in #1256 (thanks @dmitri-perelman )

**Comment by aching** [comment]
Thanks @dmitri-perelman !
