### ISSUE TITLE
Tag faucet and client images in cluster_test

### ISSUE THREAD

**Issue by andll** [libra/libra#1277]
We have 3 nightly images currently - client, validator(libra_e2e) and faucet

Cluster test only tests validator and tags it with nightly_tested.

However in order to use it for prod deploy, we need to tag all 3 with nightly_tested when test passes
We can find those other images by matching `upstream_xxx` tag on them

**Comment by bschwab** [comment]
Thank you! This will make the tags/rev on the pushes uniform
