### ISSUE TITLE
ZkSNARK implementation

### ISSUE THREAD

**Issue by dhruvmalik007** [libra/libra#128]
# 🚀 Feature Request

## Motivation
i have been doing research in this field and  has seen the promising research done by the many startups to create solutions for the DeX and other wrapper solutions on top of libra ( for  scalable solutions) . also the underlying protocol's  property of being robust does not avoid it to be tracked by the nation states and other hackers.

**Is your feature request related to a problem? Please describe.**
Privacy and also scalablity concerns :- the  transactions between the validators and the nodes and transaction manager can be modified or stolen  even if  we have modern day Elliptical signatures or other post quantum crypto.  also the merkle tree for maintaining the states of transaction for ledger history is  not a scalable proposition without using the ZkProofs ( coda is the great example). its quite odd that there is no significant mention on this subject even though majority of the security  researchers in the cryptocurrency  community had given significant intrest in this topic.     
## Pitch

**Describe the solution you'd like**
have a  sincere discussion on how to apply the zero knowledge proof  and their implementation by using the standards as mentioned by the Zkproof.org.

**Describe alternatives you've considered**
think of implementing ZkSNARK  libraries or solutions  (like Libsnark / Zokrates) / coda   and other  concepts  for the  libra transactions. 

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

## Additional context

an exhaustive resource  for this research :-  www.zkp.science

**Comment by bitzec** [comment]
Do you mean like in zcash  or  the binary digit zero knowledge electronic currency bzc http://bitzec.org

**Comment by dhruvmalik007** [comment]
yes like in Zcash  ans other startups like Qedit / STARKDEX have being promoting on-chain / offchain solution for allowing the parties to authenticate the identity / assertion without sharing the actual credentials ( even encrypted) . for basic intro :- https://en.wikipedia.org/wiki/Non-interactive_zero-knowledge_proof .

**Comment by ericnakagawa** [comment]
Hi @dhruvmalik007, let's move this discussion to [Discourse](https://community.libra.org).
