### ISSUE TITLE
[VM] New API for VM

### ISSUE THREAD

**Issue by runtian-zhou** [libra/libra#1281]
## Motivation

As we extend the definition of a transaction in #1173, we probably need to update the API for VM to be able to process the system transaction to come.

## Problem statement
Currently the VM api looks like this:
``` rust
pub trait VMExecutor {
    fn execute_block(
        transactions: Vec<SignedTransaction>,
        config: &VMConfig,
        state_view: &dyn StateView,
    ) -> Vec<TransactionOutput>;
}
```
With the new `Transaction` type, it seems pretty natural to change the api to be 
``` rust
pub trait VMExecutor {
    fn execute_block(
        transactions: Vec<Transaction>,
        config: &VMConfig,
        state_view: &dyn StateView,
    ) -> Vec<TransactionOutput>;
}
```
However, there's still a bunch of remaining open question.

## Open Questions
- Should the API follows the block boundary, and if so, what should the VM return when the vector doesn't follow the spec?

Ideally a block of transaction should look like following: Each block should start with a block prologue transaction that updates the metadata and potentially changes the validator set. Followed by the block prologue transaction there should either be a vector of user transactions or one single writeset transaction. The reason why we would like to keep writeset on itself (or at least at the end of a vector) is that it might potentially modify the code which is gonna invalidates both VM's code cache and data cache. However, the naive API of `Vec<Transaction>` doesn't demonstrate such restriction in the API. 

One potential solution here is to replace `Vec<Transaction>` with a new struct defined as following:
``` rust
pub struct TransactionBlock {
      BlockMetadata block_header;
      TransactionBlockPayload payload;
}

pub enum TransactionBlockPayload {
    User(Vec<UserTransaction>),
    WriteSet(WriteSet),
}
```
By doing that, we are enforcing the structural property of a block of transactions in the rust type system. The downside of this approach is it will make the life for state synchronizer a lot harder as it will need to convert a vector of `Transaction` obtained from the storage into that special `TransactionBlock` structure.

Another possibility here is we can keep the api of `Vec<Transaction>` and verify the property at runtime. This would make the API clean but we still need to implement the manual chunking as we did in the first approach to chunk a `Vec<Transaction>` into several different vectors, each of them should follow the specification of a block. This approach will have the cleanest api for the VM as each call to the VM means that one block is being processed.

The third possibility here is the VM would have no checks at all. Instead, the VM will flush the cache when there's a WriteSet transaction. This will guarantee that the semantics of the transaction execution is still correct. This should be the API that state synchronizer would want but also got the most flexibility. The VM can start its execution at any transaction and terminate execution at any transaction, which might be a bit more error prone and may have issue with reconfiguration in the future.

-  Should the VM return a change of validator set when there's such change?
When I was reading #1027, it occured to me that the VM might want to include an optional value in the return values to represent if there's an executor change event happened in this block. By doing this, we don't need to do the logic in the executor, which would made the code a lot cleaner.

**Comment by zekun000** [comment]
The principle of the special transaction approach is to try to make VM unaware of the `Block` concept. That suggests:
- Anything VM needs to know about a Block is written to state by the prologue transaction e.g. timestamp.
- Any invariants needs to be checked as a Block should be delegated to upper layer e.g. BlockTxn + Vec\<UserTxn\>

**Comment by runtian-zhou** [comment]
Had a discussion with both @zekun000 and @bmaurer on this issue. It seems to me that the third option is desirable, due to the following reasons:
1. The VM shouldn't be aware of the concept of a block. All the things VM needs to know should come from the transactions and the initial state store.
2. The caller of VM shouldn't worry about the cache invalidation of a VM.

**Comment by dariorussi** [comment]
somewhat of a side issue: I think it would be great to have the block id being passed by the Executor to `VMExecutor::execute_block(...)` so that we could correlate errors to specific block id. I believe the block id is going to be a good identifier in logging to monitor and debug problems in the system.
I mention that because I think it may be good to have a different API for "normal" execution and state synchronization. Of course that assumes that the 2 code paths are in fact different (and don't know if they are).
That should not change a bunch of the assumptions or considerations in this issue but just something to keep in mind because of logging and monitoring.
I think having the VM completely unaware of block boundaries may be a good thing or at least something we should try. I am still not too clear about the break up of responsibilities between transaction processor and VM but it is worth to go down the suggested path and see how things shape up.
