### ISSUE TITLE
[Bug] New dev script missed unzip

### ISSUE THREAD

**Issue by antonio-fr** [libra/libra#129]
On Linux, the dev_setup scripts now downloads a zip package with binaries to ease out the protobuf installation, instead of *apt-get install protobuf*. Unfortunately, it needs "unzip" which is not installed. I would add *sudo apt-get install unzip* on line 123 in this new script version.

https://github.com/libra/libra/commit/653ebdfe8b75e0679d7667f981a075179d12dac9#diff-6a73bb21fe28ae8b5e645016a6a490f1R117

**Comment by antonio-fr** [comment]
I created a pull request to fix that. The change is even more platforms wide compatible than previously stated, not only "apt-get" but others packages managers.
https://github.com/libra/libra/pull/130

**Comment by bmwill** [comment]
The external dependencies needed to build Libra have been simplified and should only require Rust now so this shouldn't be an issue anymore on master. If it is, please let us know.
