### ISSUE TITLE
Properly adhere to LCS spec

### ISSUE THREAD

**Issue by bmwill** [libra/libra#1307]
During the process of implementing a proper Serde `Serializer` and `Deserializer` for the LCS format (#1301), and then converting the entire codebase to use the new implementation, I discovered that there were a number of types which we had incorrectly implemented LCS for and need to be fixed:

- [ ]  NativeStructValue
- [ ] ValueImpl
- [ ] RawTransaction (specifically serializing Duration type)
- [x] Transaction
- [ ] StatusCode (not exactly violating, but we need to concretely decide which integer type to use for this C-style enum) 

There are also a number of types which we cannot utilize the Serde derive Serialize/Deserialize macros for because we treat many fixed sized arrays as variable length sequences which requires an additional 4 bytes for the unneeded length in the serialized form:

- [ ] HashValue
- [x] AccountAddress
- [ ] EventKey
- [ ] Public/Private Key types
- [ ] Signature types

cc @gedigi @weilei0107 @davidiw

**Comment by huitseeker** [comment]
For the crypto types, the variable length sequences may serve to provide LCS at the trait level, where various key types (BLS / EdDSA) provide distinct lengths. /cc @kchalkias

**Comment by dariorussi** [comment]
let's talk about the Value serialization in the Vm because we don't have Rust native structs to map to and the serialization was tailored to our needs. So I am not sure about incorrectly implementing LCS as much as we are serializing value for the VM using LCS but not being entirely LCS entities... if that makes any sense...

**Comment by davidiw** [comment]
This is as done as it ever will be :D
