### ISSUE TITLE
[Consensus] Reduce StateSync rate

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#1321]
When running the system with 100 validators and empty blocks we can observe an average rate of ~1 state sync every 5 seconds per validators (this rate varies across the validators, larger for some and lower for the others).
This is not a rate we can be happy with. State Synchronization is a relatively expensive operation (bring the 3-chain, invoke state synchronizer, bring chunks, rebuild the tree from scratch), and my current intuition is that we're misusing it by invoking it every time we're lagging by may be one committed block.
We should add a histogram counter that measures the gap between the last committed block and the remote LI block round in order to know what gaps we're actually closing with the state sync.
We should then introduce some higher threshold for starting state synchronization (today this threshold is implicitly 1).

**Comment by zekun000** [comment]
state sync should be strictly cheaper than block retrieval even it's one block behind(without considering the cost talking to synchronizer).

Imagine we have B0 <- B1 <- B2, and we receive a LedgerInfo commits B3(B2<-B3).

Without state sync, we need to fetch B5, B4, B3 separately and execute B3, B4, B5. and commit B3.

With state sync, we fetch B3, B4, B5 in one request and execute and commit B3, execute B4, B5 to re-build the tree.

**Comment by dmitri-perelman** [comment]
Huh, yea, you're probably right. Let's just improve the monitoring of state sync (histogram for the gap in the rounds and a counter for the success rate), and think about why it's happening so frequently. I was surprised to see the state sync happening with such a frequency.

**Comment by dmitri-perelman** [comment]
Thinking more about the counters here: I'd like to see the following histograms:
- the gap in the rounds
- the timeout that we calculate for the state sync operation
- success rate
