### ISSUE TITLE
[language][vm] increment/don't increment sequence number under certain cirumstances

### ISSUE THREAD

**Issue by vgao1996** [libra/libra#1322]
Comments found in an old test:
```
// TODO don't increment sequence number after:
// bad signature
// bad auth key
// can't pay gas deposit

// TODO: do increment sequence number after:
// parse error
// module publish error
// bytecode verification error
// non-assert runtime error
```
@dariorussi @runtian-zhou @sblackshear @tnowacki @tzakian @sunshowers @shazqadeer 
We should review the list and decide what to do with each item. (Comply or remove.)

**Comment by dariorussi** [comment]
I am not sure I remember all the issues here but as an initial thought would it make sense that we increment the sequence number on all errors except invariant violations?
That is, assuming transaction went through AC we just penalize bad transactions in any form by having them pay gas.
Not sure that has got problems though, thoughts?

**Comment by runtian-zhou** [comment]
IMHO the rule of thumb here is that we shouldn't sequence number ONLY if the transaction can't possibly charge. All of the case you mentioned above are examples where the transaction can't prove its ownership of the on chain account that it's trying to spend. We should charge gas for all the other cases as they would cost gas to verify.

**Comment by bob-wilson** [comment]
Runtian, do you know if this has been implemented yet? If not, can you follow up and either do it or figure out who else should take it?
