### ISSUE TITLE
Smarter incoming channels for networking and consensus

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#1323]
Today's flow of incoming messages can be described in the following way:
1. Some networking task is running in a loop, retrieving the messages from a shared network queue and demuxes the messages based on their message type to the corresponding module (e.g., mempool, consensus, state synchronizer). Let's call the channel between network and consensus `Net2Con`.
2. The network thread responsible for serving consensus messages is reading the messages from `Net2Con`, determines their type (e.g., `Proposal`, `Vote`, `SyncInfo`), verifies the message and passes it to a channel, which is specific to that message type. Let's call these channels `ConsensusReceivers`.
3. Finally, a main consensus thread is running an event base loop doing `select` from the `ConsensusReceivers` and invoking the corresponding processing functions of event processor.

Both `Net2Con` and `ConsensusReceivers` today are implemented via rust async bounded channels. These are FIFO mpsc queues.
There are two big disadvantages to this setup:
1. **Validator Fairness.** A single noisy validator can fill up all the slots in the channel, thus preventing progress.
2. **Old messages first.** Whenever a system gets slightly slower than usual the messages in the incoming queues pile up very quickly. As a result consensus event base is processing some old irrelevant messages only to get to the older one later, which only deepens the lag.

We'd like to come up with `LibraChannel`, which would be a better implementation for the Libra channels that we could use both for channels between network and individual models (consensus, mempool, state synchronizer) and the channels accumulating specific consensus messages.
While the details are unclear, the basic criteria for `LibraChannel` are as follows:
* Internal separation of queues belonging to different peers, so that a noisy actor could not force dropping messages of other peers.
* Some fairness across peers when retrieving messages, e.g., round robin. This way a noisy actor would not be able to starve other peers.
* Config parameter for the per-validator queue size with an ability to 1) drop old messages when a new message is added, 2) use LIFO / FIFO when retrieving the message.

For example, a per validator queue of TimeoutMsgs could be of size 1. We are interested in the latest timeout message per validator only. A per validator queue of proposals and votes should be of size 1 as well. Because we want `LibraChannel` to be used for communication between network and other modules as well, we want to keep these as a configuration parameters.

**Comment by dmitri-perelman** [comment]
A couple of thoughts clarifying one possible implementation of such a `LibraChannel`. At high level we could take two approaches:
1) Implement it with internal Futures API (`poll()` function, notify the task when something is ready, etc.)
2) Implement it without entering the details of Futures, via using the existing channels. This approach is simpler to implement & maintain, but it incurs an additional overhead of having a separate task running inside `LibraChannel` and moving things around.

Below are my thoughts about approach 2 implementation.
Consider an internal synchronous data structure `FairMsgPool`, which is keeping messages in a circular buffer per validator and applying some sort of round robin policy across validators. The API would like that:
```
impl FairMsgPool {
  pub fn new(num_msgs_per_validator: u64);
  pub fn gc(); // cleanup old entries of validators with empty circular buffers once in a while
  /// Returns a previous message if replaced by this addition.
  pub fn add_msg(validator: Validator, msg: Message) -> Option<Message>;
  /// Returns the next message following the fairness criteria for validators (e.g., round robin across validators and FIFO across the messages of the same validator)
  pub fn next_msg() -> Option<Message>;
}
```
The idea behind `LibraChannel` would then be as follows:
* Keep an internal unbounded channel `pool_ready` with empty events, where each event corresponds to **some** message in the `FairMsgPool` ready to be consumed (each such even is a predicate for some message being present in the pool). Whenever a new message is added to the `FairMsgPool`, if this message is not overriding the old one, `()` is added to `pool_ready`.
* Keep an internal bounded channel `outgoing_msgs` of size 1. We alternate the messages added to this channel: right after adding a real message we set up two futures adding two dummy empty messages to `outgoing_msgs`: when the second dummy empty message is successfully added to `outgoing_msgs`, it indicates that the client is done with consuming the real one (see below).
* Keep an internal bounded channel `consumer_ready` of size 1 with empty events. The `()` event is added to `consumer_ready` when the second dummy outgoing message is successfully added to the `outgoing_msgs`.

The main task of `LibraChannel` runs the following loop (pseudocode below, don't try to compile :)):
```
let mut outgoing_msg_processed = never();
consumer_ready.send(()).await();
loop {
  select! {
    msg = incoming_msgs.select_next_some() => {
      if fair_msg_pool.add_msg(msg).is_none() {
        // the new message didn't override anything, add a new event to `pool_ready`
        pool_ready.send(());
      }
    }
    ready = pool_ready.zip(consumer_ready).select_next_some() => {
      outgoing_msg_processed = outgoing_msgs.send(fair_msg_pool.next_msg())
            .and_then(outgoing_msgs.send(dummy)) // msg delivered
            .and_then(outgoing_msgs.send(dummy)) // dummy msg delivered (real one processed)
    }
    outgoing_msg_processed => {
      consumer_ready.send(());
      outgoing_msg_processed = never();
    }
    complete => { break; }
  }
}
```
Now the proposal above is using the dummy messages: we need them as an indicator that the outgoing message has been processed, s.t. we could deliver the "best possible" message to the client from the msg pool following the fairness criteria.
We could relax this requirement and say that it's ok to pick up the next message from the message pool when the previous one has been delivered (not processed), in which case we'd not need dummy entries. If we do use dummy messages we should wrap the `InnerLibraChannel` with `LibraChannel` that would filter out the dummy messages.

**Comment by ankushagarwal** [comment]
@dmitri-perelman 

I have created a draft pull request #1462 which has a sample implementation of the `LibraChannel` data structure that we discussed. This does not use the multiple channels approach as you had explained, but it implements the Future API.

I have added detailed comments to the PR and the code. Lets use that PR for further discussion about this feature.
