### ISSUE TITLE
[consensus] byzantine attack on state sync

### ISSUE THREAD

**Issue by zekun000** [libra/libra#1324]
Attack scenario: 
1. f byzantine nodes collect a QuorumCert committed B_n, none of 2f+1 honest nodes are aware of this QC.
2. 1 honest node is lag behind and start to sync to this QC from byzantine node
3. f byzantine nodes go offline
4. the system will stuck because of honest node can not finish the state sync(none of the 2f honest commit B_N) and crash looping, other 2f nodes can not move forward without this node.

Solution:
We used to solve this by processing the sync_to QC from synchronizer so that at least f+1 honest nodes who voted for are able to commit B_n and sync back to the lag behind node.

After we separate state synchronizer out of consensus, we lose this mechanism.

**Comment by bmaurer** [comment]
Right now, we require syncing to the 3-chain that commits B_n. Does this open up additional byzantine scenarios of any sort (are there situations that might discard that data)

**Comment by dmitri-perelman** [comment]
Just to add that the solution to this problem is not obvious: state synchronizer is currently not aware of consensus so we can't easily force the state synchronizer to "commit" a ledger info (something that we could do when we were running it in the same event loop)

**Comment by zekun000** [comment]
@bmaurer the receiver should verify the 3-chain is valid to continue the sync process, otherwise it'll just ignore the whole message.

**Comment by zekun000** [comment]
closed via https://github.com/libra/libra/issues/1590
