### ISSUE TITLE
[types, lcs] better document lcs format of types needed for clients

### ISSUE THREAD

**Issue by bmwill** [libra/libra#1334]
In the process of making it easier to use LCS in #1301 we discovered that the documentation for the layout and format of a number of types wasn't 100% accurate and in some cases the documentation was far away from the actual definition of the type.

One potential proposal to address this would be to include detailed examples of the layout of each time as a rustdoc comment next to each type (with links to these examples from the readme). One benefit of including these as a rustdoc example is that the examples would be built and tested at CI time to verify that the examples never fall out of date with their implementation.

cc @weilei0107, @davidiw

**Comment by davidiw** [comment]
@matbd has done great things here....
