### ISSUE TITLE
[Bug] Libra latest rev in testnet fail building on Mac 

### ISSUE THREAD

**Issue by gbenattar** [libra/libra#1367]
This issue was introduced after rev 8b7b9ae as a fix to https://github.com/libra/libra/issues/1341.
It seems related to a new version of gprcio: `grpcio-sys v0.5.0-alpha.2`.
./dev_setup.sh was run successfully and required dependencies are on latest.

This is preventing from using Libra client.

```
Darwin 18.7.0 Darwin Kernel Version 18.7.0
cmake 3.15.4 already installed
protobuf 3.10.0 already installed
rustc 1.39.0-beta.6 (224f0bc90 2019-10-15)
```

# 🐛 Bug

```
--- stderr
CMake Warning at cmake/protobuf.cmake:48 (message):
  gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:140 (include)


CMake Warning at cmake/gflags.cmake:26 (message):
  gRPC_GFLAGS_PROVIDER is "module" but GFLAGS_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:142 (include)


CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   zlib

This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by runtian-zhou** [comment]
I encountered with similar issue before on my Mac. What was the version of clang on your machine? I had a compilation failure when using clang 9.0 and it went away once I upgrade the xcode toolchain.

**Comment by bmwill** [comment]
The external dependencies needed to build Libra have been simplified and should only require Rust now so this shouldn't be an issue anymore on master. If it is, please let us know.
