### ISSUE TITLE
[Bug] Build Error on EC2 machine

### ISSUE THREAD

**Issue by rxu18** [libra/libra#137]
# 🐛 Bug

When build is run on Red Hat EC2 machine, it fails with unintuitive error message.

## To reproduce

Spin up a Red Hat EC2 instance
`sudo yum install gcc gcc-c++` to run CMake
follow contribute.md instructions until `cargo build`

** Stack trace/error message **
```
stderr
CMake Warning at cmake/protobuf.cmake:48 (message):
  gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:140 (include)


CMake Warning at cmake/gflags.cmake:26 (message):
  gRPC_GFLAGS_PROVIDER is "module" but GFLAGS_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:142 (include)


CMake Error at CMakeLists.txt:738 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

CMake Error at CMakeLists.txt:2694 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression


CMake Error at CMakeLists.txt:2694 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression


CMake Error at CMakeLists.txt:8114 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.40/src/lib.rs:832:5
......

```

## System information

**Please complete the following information:**
- Libra build from source, commit 5ec3f69bae1a15
- Rust version 1.36.0-nightly
- Redhat 7 Enterprise

## Additional context

Machine also used to run Vertica database cluster.

**Comment by ericnakagawa** [comment]
@rxu18 I've tagged the build team to take a look at this.

**Comment by wqfish** [comment]
What is your output of `cmake --version`? I managed to reproduce this with a very old version of `cmake`. Can you try upgrading to latest version?

**Comment by jonrau1** [comment]
@rxu18 I am encountering the same thing as you did - running RHEL 8 (ami-098bb5d92c8886ca1) on a t3.medium EC2 Instance
Installed the latest version of Cargo and CMake manually, ran the build script and when I got to `source /home/ec2-user/.cargo/env
cargo build` I got the same fail as well

**Comment by khetanvallurupalli** [comment]
You need to remove the older version of Cmake and Reinstall newer Version. http://jotmynotes.blogspot.com/2016/10/updating-cmake-from-2811-to-362-or.html
This document may help you.  Also, make sure you are not using Sudo without proper understanding.

**Comment by ericnakagawa** [comment]
@rxu18 Hoping you're able to build with the suggested changes from @wqfish and @khetanvallurupalli.

**Comment by tiendq** [comment]
I had a build error with CMake several days ago too, just re-install latest CMake 3.14.5 fixed it.

**Comment by rxu18** [comment]
@wqfish @khetanvallurupalli @ericnakagawa thanks for the suggestions! Will try them out tonight and see how it goes.

**Comment by rxu18** [comment]
Issue fixed. Thanks for the help.
