### ISSUE TITLE
CRITICAL security fix

### ISSUE THREAD

**Issue by 0xSnipe** [libra/libra#138]
Reopening #83 
You will not censor github

**Comment by 0xSnipe** [comment]
#135

**Comment by 0xSnipe** [comment]
#135 Relevant

**Comment by karozagorus** [comment]
ACK

**Comment by rockstardev** [comment]
https://www.youtube.com/watch?v=l1RM8ECQe5g&list=RDl1RM8ECQe5g&start_radio=1

**Comment by bmaurer** [comment]
Let's move the conversation over to #135 where we're discussing the best moderation policy.
