### ISSUE TITLE
Waypoints for trusted starting point

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#1384]
## Motivation for using Waypoints
A node that comes online after being disconnected for a long period of time faces a problem of the initial syncup because it might no longer trust the old public keys of the historical validators it is aware of, which could have been compromised since then (the so called “long range attack”).

We’d like to use Waypoints as an off-chain mechanism for providing the initial trusted set of validators and a point in the accumulator history. Waypoints are going to be published by the association on a regular basis (e.g., on GitHub once in two weeks), and should be embedded within the nodes (clients / full nodes / validators) as a trusted “starting place”. 

The Waypoints as “initial trusted starting point” can then be used in the following situations:
Quick trusted recovery starting from a recent point in time after a long offline period.
Configuring genesis: a genesis waypoint certifies the genesis with its initial validator set.
Hard forks: in case of a fork the chosen branch is stamped with the waypoint.

Obviously, being an off-chain mechanism there is no way to “prove” a waypoint, the nodes trust waypoints in order to jumpstart.

## Waypoint properties and debate
We considered several alternatives for implementing the waypoints, and after several iterations of discussions we partitioned the differences along the following lines:

1. **Simplicity of verification using waypoints.**
What is the protocol for verification of the latest ledger info given a waypoint?
We’d like the verification to be intuitive and straightforward. If the waypoint verification is not obvious, clients might choose not to use it, and we'll have a hard time putting it in TCB.

2. **Waypoints in the middle of epochs.**
Do we want to be able to generate waypoints for arbitrary versions in history, or we can limit ourselves to epoch boundaries only?
We are generally planning to have smart contracts for generating epochs on a regular basis (e.g., once a day). Epoch increments can happen even without external requests, and they are cheap (two empty blocks).
In case of a hard fork we should start a new epoch for the newly started branch as well.
There seems to be no value in adding a waypoint in the middle of a previous epoch because they change frequently enough. There is also no value in adding a waypoint in the middle of the current epoch, because if we suspect that there might be a fork in the current epoch it means we don't trust the current validator set and we should absolutely move to the next epoch anyway.

3. **Waypoints that cannot generate partially correct synchronization.**
Is it possible to construct a malicious waypoint, which, together with a malicious remote storage, could trick a client to synchronizing to the latest ledger info with a correct root hash but a wrong validator set?
Obviously that would be very bad for the node (that said, it can happen only if a waypoint is intentionally malicious, which contradicts the whole idea of trusted off-chain info).

## Previous waypoint proposal
Our previous proposal for implementing waypoints is thoroughly described in https://github.com/libra/libra/issues/1013. It is working fine and achieves properties 2 and 3, however, we had some concerns regarding the simplicity of verification. Hence, we tried to come up with a simpler solution via sacrificing property number 2 and temporarily relaxing property 3.

## The simplified waypoint design
The basic idea is to issue waypoints that can certify epoch transitions only. By giving up on the ability to put waypoints on the arbitrary versions in the middle of the epochs (property 2) we can leverage the fact that storage keeps the latest LedgerInfos per epochs and these LedgerInfos include both the accumulator hashes and the validator sets:

```
pub struct LedgerInfo {
   /// The version of the latest transaction in the ledger.
   version: Version,
   /// The root hash of transaction accumulator that includes the latest transaction.
   transaction_accumulator_hash: HashValue,
...
   /// An optional field keeping the set of new validators to start the next epoch.
   /// The very last ledger info of an epoch contains the validator set for the next one,
   /// other ledger info instances are None.
   next_validator_set: Option<ValidatorSet>,
}
```
The regular verification across epochs includes a series of ledger infos that can be verified starting with a trusted validator set corresponding to the epoch given by the client.
```
pub struct UpdateToLatestLedgerResponse<Sig> {
   ...
   /// The validator change events is a vector of transitions that help a client
   /// to verify the latest validator set given the initial trusted validator set.
   pub validator_change_events: Vec<ValidatorChangeEventWithProof<Sig>>,
   ...
}

pub struct ValidatorChangeEventWithProof<Sig> {
   /// The latest ledger info of an epoch keeps the validator set of the next epoch.
   ledger_info_with_sigs: LedgerInfoWithSignatures<Sig>,
   ...
}
```
The goal of waypoints is to provide a client node with the initial trusted root hash and validators; in other words, it is enough for the waypoint to include the information about a LedgerInfo on the epoch boundary. We don’t want Waypoint representation to be a large string (LedgerInfo is relatively large because it includes info about the validators of the next epoch), hence the waypoints will keep the hash of LedgerInfos:
```
pub struct Waypoint {
   /// Version of the last txn in the chosen epoch
   version: Version,
   /// Hash of the latest LedgerInfo of that epoch
   ledger_info_hash: Hash,
}
```
Waypoints are published via strings `version:ledger_info_hash`.

What should a client do with the waypoint upon restart?
* Well, almost the same regular thing that it does for any other validation!
* It’s sending the `UpdateToLatestLedgerInfoRequest` to the remote storage with the version of the waypoint.
* The only difference is that the very first LedgerInfo in the returned vector of validator_change_events is verified differently. Instead of a typical verification that is using the signatures of the current trusted validator set, we’re verifying the first LedgerInfo by comparing its hash with the hash of the waypoint.

## The simplified waypoint design ++
The simplified design depicted above does not satisfy property 3, because a malicious waypoint might contain a hash of a ledger info with the proper accumulator root hash but a bogus validator set. 
If we want to make sure that the validator set matches the accumulator root hash, we must provide a proof from the corresponding reconfiguration event to the accumulator root hash.
Note that this additional verification (proof from reconfiguration event to the root hash) is not specific to the waypoints. It’s a property of any verification that goes through epochs.
It’s important to emphasize that this additional level of verification is not necessary if we trust the waypoints. 
In order to obtain the additional level of protection we should extend the `ValidatorChangeEventWithProof` struct to include the proof of event:
```
pub struct ValidatorChangeEventWithProof<Sig> {
   /// The latest ledger info of an epoch keeps the validator set of the next epoch.
   ledger_info_with_sigs: LedgerInfoWithSignatures<Sig>,
   /// The proof connecting the reconfiguration event with the accumulator root hash of LI.
   event_with_proof: EventWithProof,
}
```
Our plan is to first implement the basic simplified waypoint design, and implement the additional level of verification as a second step.

**Comment by mimoo** [comment]
A LedgerInfo now looks a bit different, with the important parts highlighted:

![Screen Shot 2019-12-09 at 12 21 01 PM](https://user-images.githubusercontent.com/1316043/70469701-67544980-1a7e-11ea-93db-153cc11acdb4.png)

If I understand correctly, the additional level of security mitigates an attack where I give you a fake **waypoint** which makes you sync to **the correct state of the chain but with the wrong validator set**.

But an attacker can do even worse right? He can give you an incorrect state as well. In which case the additional security checks wouldn't be able to do much.

Knowing that, is there really any benefits in these additional checks?

**Comment by pdhamdhere** [comment]
- [ ] Waypoint distribution and consumption #2425

**Comment by the729** [comment]
Waypoint property 2:

>  …if we suspect that there might be a fork in the current epoch it means we don’t trust the current validator set and we should absolutely move to the next epoch anyway.

Could someone please elaborate this statement a little bit? How would you expect a client to detect fork within an epoch? Is it expected to use `LedgerConsistancyProof`?

**Comment by the729** [comment]
Current waypoint implementation does not provide frozen subtrees in order to use consistency proof.

For example, a client is inited with a waypoint 1234:xxxxx, by querying the ledger with KnownVersion=1234, it can verify the waypoint, but cannot gain the frozen subtrees from 0 through 1234. Without those subtrees, it can not detect forks in subsequent queries.

I'd suggest to include frozen subtrees (e.g. for version 0 through 1234) into LedgerInfos at epoch boundaries (e.g. version 1234), so that these information also gets hashed into the Waypoint and returned with ValidatorChangeProof, just like the next validator set. Thus, by querying and verifying a LedgerInfo at the version specified in a Waypoint, a client can also learn the frozen subtrees, with which it can make use of LedgerConsistancyProof and detect forks later.

**Comment by dmitri-perelman** [comment]
@the729 thanks for the question. Note that the waypoint is covering the hash of the fields of LedgerInfo, which include the root hash of the accumulator. Given a trusted root hash / version, a client can verify any other `AccumulatorConsistentyProof` with respect to that hash and version, hence there is no need to keep any of the frozen subtrees explicitly in order to verify information.

**Comment by the729** [comment]
@dmitri-perelman thanks for the reply. But I believe that knowing the root hash without frozen subtrees is not sufficient to verify `AccumulatorConsistencyProof`. I'm referring to the comment [here](https://github.com/libra/libra/blob/1e959cd75861145cbb4c0badd3904fc758e23f5a/types/src/proof/definition.rs#L375) which refers to [`Accumulator::append_subtrees`](https://github.com/libra/libra/blob/1e959cd75861145cbb4c0badd3904fc758e23f5a/types/src/proof/accumulator/mod.rs#L133). 

That's why I think maybe the waypoint should also cover frozen subtrees.

**Comment by dmitri-perelman** [comment]
@the729 interesting, I guess there is some miscommunication here. I don't understand the circumstances in which the client needs to use `AccumulatorConsistencyProof`. Here's my understanding of it:
* Client typically needs to know the root hash of the ledger because all the proofs about transactions / account state / events are built relative to this root hash.
* A root hash of the ledger is delivered to the client in the `LedgerInfoWithSignatures` struct. The struct is verified using the trusted signatures of a validator set.
* In a world with reconfigurations, the trusted signatures are updated upon epoch change. The last `LedgerInfo` of epoch `n` carries a validator set for the next epoch `n+1` (signed by the validators of epoch `n`).
* If we don't fully trust some old keys anymore (long range attacks) a client needs to have another mechanism of validating the `LedgerInfo` carrying the new validator set: it verifies this `LedgerInfo` using a waypoint.

**Comment by the729** [comment]
@dmitri-perelman I noticed the reference CLI client does not verify `AccumulatorConsistencyProof`. I thought it is work-in-progress, since the proof is returned in the gRPC response message. But are you suggesting that a client don't need to verify it at all?

Regarding the 4th point you mentioned, before a client can reset from a new waypoint, it has to detect a hard fork or an attack in the first place. Without consistency checks, how can the client know if it needs to reset from a waypoint?

For example, a client is at v103, but some validators are compromised since v102. Forturnately the attack is detected by the Association, and a hardfork is issued from v101, generating a new branch v102' through v104'. Now, when the client queries the ledger again, it might think 104' is directly following 103. 

If the client only cares about the latest states, it sees 104' and there is no problem. But if it also cares about the evolution of the states (for example a blockchain explorer), there is a problem. 

```
Truth:
100 --- 101 --- 102 --- 103
          \
            --- 102' --- 103' --- 104'

Client thinks:
100 --- 101 --- 102 --- 103 --- 104'
```

p.s. This discussion seems have diverted from waypoint to consistency check. :-)

**Comment by dmitri-perelman** [comment]
@the729 yup, the discussion is getting more interesting and high level :)
1. The "typical" usage of waypoints is to add additional level of security for starting the client nodes / Full Nodes. Consider a client that has been offline since epoch `20` for one year: if the latest epoch of a ledger is `2000` then this client needs to retrieve the `ValidatorChangeProof` starting from `20` to `2000`. Each epoch transition in this proof is signed by the old keys that are not in use. In order to make sure this client does not diverge in case some of these old keys are compromised, a client can use a `Waypoint` issued by the association for some relatively recent epoch `1985`. The client verifies the `LedgerInfo` with the validator set for `1985` using the waypoint, and will verify the rest of the epoch changes using relatively recent keys.
2. The "non-typical" usage of waypoints is to stamp reconfiguration transactions that do not go through regular consensus protocol (note that this is a last-resort measure for emergency situations, which should hopefully never happen). A good example would be a disaster with all the private keys of the validators being lost and the system being stuck. In this case there are two options:
   2.1. Client's last version is less than the version of the "emergency reconfiguration". In this case when a client restarts it downloads the fresh waypoint and successfully verifies the validator set established by the association.
   2.2. Client's last version is higher than the "emergency reconfiguration" (this is the case depicted in your figure above). This would be an extremely visible situation (reverting transactions!!). In this case, as you correctly pointed out a client will fail to verify the `LedgerInfo` sent by the ledger because it'll be signed by the keys that are not recognized by the client. A client would need to forcefully reset some of its state in order to "forget" transactions `102` and `103` in your example. 

By the way, we tried to describe some thoughts about the verification with respect to the waypoints and reconfigurations in the following tech-paper that you might find interesting: https://github.com/libra/libra/blob/master/tech-papers/lbft-verification/lbft-verification.pdf

**Comment by davidiw** [comment]
amazing work!
