### ISSUE TITLE
[Bug]can't connect to validator at ac.testnet.libra.org:8000, need to revise the port from 8000 to 80

### ISSUE THREAD

**Issue by friendmine** [libra/libra#139]
[Bug]can't connect to validator at ac.testnet.libra.org:8000, need to revise the port from 8000 to 80

**Comment by bothra90** [comment]
@friendmine: `8000` still works for me. Could you try again, please?

**Comment by ericnakagawa** [comment]
@friendmine I'm going to close this as we can't reproduce. If you still experience this issue, please submit a new issue that includes your system configuration and exact steps to reproduce.

**Comment by zavodil** [comment]
Have same issue.
May I register CA file somewhere?

**Comment by php7webmob** [comment]
I am facing the same issue:
Running `target/debug/client --host ac.testnet.libra.org --port 8000 -s ./scripts/cli/trusted_peers.config.toml`
Not able to connect to validator at ac.testnet.libra.org:8000, error RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") })

**Comment by Johnny-lou** [comment]
resolved? @php7webmob

**Comment by php7webmob** [comment]
> resolved? @php7webmob

yes.

**Comment by DongfightingABC** [comment]
i try to connect the testnet、but the result is error Author is unknown， please help me

**Comment by korrio** [comment]
Not able to connect to validator at ac.testnet.libra.org:8000
