### ISSUE TITLE
[Consensus] Convert the async non-leaf functions to synchronous functions

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#1399]
We used to run Consensus event processing in multiple tasks, however, today the event processing is done by a single task in a single event loop.

We're still left with a number of asynchronous functions that that main event loop is just awaiting for. This is not convenient for debugging, because the stacktraces are not depicted properly. What we want to do instead is to have "real async" functions (the leaves) be asynchronous, while the rest of the functions to just `block_on` on the result.

**Comment by rofrol** [comment]
Maybe it is not needed now? https://www.reddit.com/r/rust/comments/edf6ga/async_debug_improved_a_lot_in_nightly/

**Comment by zekun000** [comment]
not planned any more
