### ISSUE TITLE
How to deploy a new module?

### ISSUE THREAD

**Issue by vjoke** [libra/libra#142]
I am wondering how to deploy a new module?

**Comment by c-o-l-o-r** [comment]
The ability to deploy modules is managed by the genesis configuration file on this line:
https://github.com/libra/libra/blob/5ec3f69bae1a15f4ccc67fcdce8d0441b47e2539/language/vm/vm_genesis/genesis/vm_config.toml#L2

You'll need to set type to `"Open"` before custom modules will be accepted. However, the the CLI tools don't currently have a way craft a module deployment transaction, so unless you hack together something yourself -- we'll have to wait!

In the mean time, I think the easiest way to get started playing around with Move is to create some new `*.mvir` files here: 

https://github.com/libra/libra/tree/master/language/functional_tests/tests/testsuite

**Comment by gc3** [comment]
> The ability to deploy modules is managed by the genesis configuration file on this line:
> 
> https://github.com/libra/libra/blob/5ec3f69bae1a15f4ccc67fcdce8d0441b47e2539/language/vm/vm_genesis/genesis/vm_config.toml#L2
> 
> You'll need to set type to `"Open"` before custom modules will be accepted. However, the the CLI tools don't currently have a way craft a module deployment transaction, so unless you hack together something yourself -- we'll have to wait!
> 
> In the mean time, I think the easiest way to get started playing around with Move is to create some new `*.mvir` files here:
> 
> https://github.com/libra/libra/tree/master/language/functional_tests/tests/testsuite

This is accurate. Looking forward to making this easier for you soon!

**Comment by vjoke** [comment]
thanks~

**Comment by ctzurcanu** [comment]
How is this *not* the most important issue to fix in Libra? Why then is it *closed*?

**Comment by jolestar** [comment]
@vjok I write a command to publish module and script for libra https://github.com/jolestar/libra/tree/hack/client

**Comment by podgostar** [comment]
Any progress on this?

> > The ability to deploy modules is managed by the genesis configuration file on this line:
> > https://github.com/libra/libra/blob/5ec3f69bae1a15f4ccc67fcdce8d0441b47e2539/language/vm/vm_genesis/genesis/vm_config.toml#L2
> > 
> > You'll need to set type to `"Open"` before custom modules will be accepted. However, the the CLI tools don't currently have a way craft a module deployment transaction, so unless you hack together something yourself -- we'll have to wait!
> > In the mean time, I think the easiest way to get started playing around with Move is to create some new `*.mvir` files here:
> > https://github.com/libra/libra/tree/master/language/functional_tests/tests/testsuite
> 
> This is accurate. Looking forward to making this easier for you soon!

Any progress on this?
