### ISSUE TITLE
[Roadmap][Network] QoS

### ISSUE THREAD

**Issue by gc3** [libra/libra#1430]
*Goals:*

* Easy creation of LibraNet clients outside p2p use-case (e.g. client → full node, validator → CTCB)
* Separate network queues per peer for isolating back-pressure
* Remove leakage of application layer notions into LibraNet (e.g. add_consensus like functions)

Related Issues:
#1670 Refactor LibraNet for end-to-end QoS fairness and backpressure isolation

**Comment by phlip9** [comment]
Closed by #2130
