### ISSUE TITLE
[Roadmap][Move] Tooling

### ISSUE THREAD

**Issue by gc3** [libra/libra#1433]
- [x] Bytecode source map
- [x] Basic debugging support

**Comment by bob-wilson** [comment]
We have a bytecode source map now! https://github.com/libra/libra/pull/1179

**Comment by bob-wilson** [comment]
For basic debugging support, we intended to support (1) stack traces, and (2) some mechanism for printing values when debugging.

**Comment by bob-wilson** [comment]
Stack traces are done in #3382 
Debug support for printing values was added earlier in #2912
