### ISSUE TITLE
[Bug] cargo build failed

### ISSUE THREAD

**Issue by download8866** [libra/libra#147]
Compiling snappy-sys v0.1.0 (https://github.com/busyjay/rust-snappy.git?branch=static-link#8c12738b)
   Compiling libtitan_sys v0.0.1 (https://github.com/pingcap/rust-rocksdb.git?rev=8d6cda70f22da2cd15ed7351fcffa9add3444595#8d6cda70)
error: failed to run custom build command for `libtitan_sys v0.0.1 (https://github.com/pingcap/rust-rocksdb.git?rev=8d6cda70f22da2cd15ed7351fcffa9add3444595#8d6cda70)`

Caused by:
  process didn't exit successfully: `/root/libra/target/debug/build/libtitan_sys-b1a12143eee7c4ae/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/root/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan" "-DROCKSDB_DIR=/root/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb" "-DWITH_TITAN_TESTS=OFF" "-DWITH_TITAN_TOOLS=OFF" "-DWITH_ZLIB=ON" "-DWITH_BZ2=ON" "-DWITH_LZ4=ON" "-DWITH_ZSTD=ON" "-DWITH_SNAPPY=ON" "-DCMAKE_INSTALL_PREFIX=/root/libra/target/debug/build/libtitan_sys-df017291157e4504/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- Configuring incomplete, errors occurred!
See also "/root/libra/target/debug/build/libtitan_sys-df017291157e4504/out/build/CMakeFiles/CMakeOutput.log".

--- stderr
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find zlib (missing: ZLIB_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /root/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/rocksdb/cmake/modules/Findzlib.cmake:17 (find_package_handle_standard_args)
  cmake/rocksdb_flags.cmake:35 (find_package)
  CMakeLists.txt:11 (include)

thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.40/src/lib.rs:832:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by riemass** [comment]
LibrocksDB is being pulled and build via CMake, as it is a c++ project. It has a dependency on zlib which enables compression in it's data storage. zlib is in fact a system dependency, and you need to install it from your package vendor (apt-get, pacman, etc.). 
Zlib is an optional dependency for librocksdb, but it seems that it is enabled by the developers. I presume that it is used.

**Comment by wqfish** [comment]
Yeah, @download8866 please try installing zlib. For example on Ubuntu it is `apt-get install zlib1g-dev`.

**Comment by download8866** [comment]
@wqfish @riemass thanks for help. I am trying again. :)

**Comment by okcrinum** [comment]
I have the same problem, how to solve this correctly? 
Thank you.
