### ISSUE TITLE
[Consensus] Pull out the proposal generation from the block store

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#1482]
We used to have the proposal generation in the block store mostly for historic reasons (and the fact that the block store was keeping the signer). However, after https://github.com/libra/libra/pull/1478 we don't need block store to be responsible for proposal generation: given the highest QC a caller can generate it by itself

**Comment by davidiw** [comment]
Ahh, that makes sense! And it would be a pretty nice separation of responsibilities! It is still a shame that proposal generator needs to know about the block store. Should we consider removing that requirement as well? As far as I can see, the dependency only (really) exists so we can see if we are a round at reconfiguration, perhaps we should pass that in a as a boolean along with the highest qc?
