### ISSUE TITLE
[Bug] found a virtual manifest at `*/libra/Cargo.toml` instead of a package manifest

### ISSUE THREAD

**Issue by chasel** [libra/libra#149]
# 🐛 Bug

## To reproduce

** Code snippet to reproduce **
```rust
cargo install
```

** Stack trace/error message **
```
error: found a virtual manifest at `*/libra/Cargo.toml` instead of a package manifest
```

## System information

**Please complete the following information:**
- 
Libra Version: Master
- 
Rust Version: rustc 1.36.0-nightly (50a0defd5 2019-05-21)
- 
Computer OS: mac OS 10.13

## Additional context

cargo build && test is work

**Comment by wqfish** [comment]
This is expected. See https://users.rust-lang.org/t/cargo-install-workspace/29145.

What is your high-level goal with `cargo install`? If you want to install the node binary you can do `cargo install --path libra_node`.

**Comment by icarter09** [comment]
@chasel I believe i was running into this same problem the other day.

@wqfish I'll give your suggestion a shot and let you know if that fixes the issue for me. Thanks.

**Comment by bmwill** [comment]
This looks to be like an issue with `cargo install` in that you need to provide which binary you want to install to cargo.
