### ISSUE TITLE
when can i buy libra with alipay？

### ISSUE THREAD

**Issue by acodercc** [libra/libra#15]
when can i by libra with alipay？

does the coinbase or binance support libra/btc?

**Comment by leomeloxp** [comment]
Libra is not available for purchase yet on any platform. Please check their [FAQ](https://libra.org/en-US/learn-faqs/#questions) and look for updates on their official channels. This is a code repository and information about the platform and its availability are unlikely to be announced/discussed in detail here.

**Comment by charj** [comment]
This is not really the place to discuss such things :-1:

**Comment by ericnakagawa** [comment]
The Libra testnet is an example. To use you can follow this guide: https://developers.libra.org/docs/my-first-transaction
