### ISSUE TITLE
[network] Discovery, Health Checker, and Connectivity modules should be application modules

### ISSUE THREAD

**Issue by bothra90** [libra/libra#1516]
# 🚀 Feature Request

## Motivation
Today, the [Discovery module](https://github.com/libra/libra/blob/master/network/src/protocols/discovery/mod.rs) utilizes raw substreams to execute the gossip protocol for p2p discovery. This is unnecessary, since we can utilize the DirectSend protocol for p2p gossip - this should remove some code duplication and move Discovery to right layer of abstraction.

We can take this idea further by making discovery a pluggable application module similar to consensus and mempool. This has 2 benefits:
- ease the creation of a network library that is independent of the p2p nature of validators
- allow different discovery module implementations for different parts of the libra ecosystem such as full nodes.

cc: @phlip9

**Comment by phlip9** [comment]
Yeah, this definitely makes sense to me. The forthcoming on-chain discovery protocol feels like it has enough outside dependencies so as to not live inside network module.

I guess we would probably also include some new commands for application modules to connect/disconnect peers?

```rust
// network/src/interface/mod.rs

/// Requests [`NetworkProvider`] receives from the network interface.
#[derive(Debug)]
pub enum NetworkRequest {
    /// Send an RPC request to a remote peer.
    SendRpc(PeerId, OutboundRpcRequest),
    /// Fire-and-forget style message send to a remote peer.
    SendMessage(PeerId, Message),
    /// Update set of nodes eligible to join the network.
    UpdateEligibleNodes(HashMap<PeerId, NetworkPublicKeys>),
    /// +++ ADD +++
    DialPeer(PeerId, Multiaddr, oneshot::Sender<Result<(), PeerManagerError>>),
    /// +++ ADD +++
    DisconnectPeer(PeerId, oneshot::Sender<Result<(), PeerManagerError>>),

}
```

**Comment by phlip9** [comment]
After further discussion offline, I believe we can rearchitect network a bit so that `health_checker`, `connectivity_manager`, and `discovery` are now pluggable application modules as opposed to built-in protocols. They can then use the provided `direct_send` and `rpc` interfaces that `consensus`, `mempool`, and `state_sync` use today.
