### ISSUE TITLE
[libra-types] cut dependencies with libra-logger

### ISSUE THREAD

**Issue by thefallentree** [libra/libra#1518]
This makes libra-types pullin a ton of mostly irrelevant dependencies. 

The only place in  libra-types that uses libra-logger is here

https://github.com/libra/libra/blob/d3dc5a57550b82b0ab84c02c8db164106da3e344/types/src/validator_verifier.rs#L188

I can submit an PR if someone knowledgeable can point me to how to move the warnings to somewhere else.

**Comment by phlip9** [comment]
cc @kchalkias @huitseeker

**Comment by bmwill** [comment]
Honestly this is a problem across our whole codebase. Most libraries only need to include the `log` crate which provides the logging macros and then binaries which want to instantiate and collect logs would need to include something like `libra-logger`

**Comment by thefallentree** [comment]
Fixed in #1614
