### ISSUE TITLE
[Bug]Build client Error

### ISSUE THREAD

**Issue by jmzhuzhonghua** [libra/libra#153]
jm@jm:~/project/facebook/libra$ ./scripts/cli/start_cli_testnet.sh
Building and running client in debug mode.
   Compiling grpcio v0.4.4
   Compiling compiler v0.1.0 (/home/jm/project/facebook/libra/language/compiler)
   Compiling mempool v0.1.0 (/home/jm/project/facebook/libra/mempool)
   Compiling admission_control_proto v0.1.0 (/home/jm/project/facebook/libra/admission_control/admission_control_proto)
   Compiling crypto v0.1.0 (/home/jm/project/facebook/libra/crypto/legacy_crypto)
error: failed to run custom build command for `admission_control_proto v0.1.0 (/home/jm/project/facebook/libra/admission_control/admission_control_proto)`

Caused by:
  process didn't exit successfully: `/home/jm/project/facebook/libra/target/debug/build/admission_control_proto-d741184a6093a7c5/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=../../types/src/proto/transaction.proto
cargo:rerun-if-changed=../../types/src/proto/proof.proto
cargo:rerun-if-changed=../../types/src/proto/transaction_info.proto
cargo:rerun-if-changed=../../types/src/proto/vm_errors.proto
cargo:rerun-if-changed=../../types/src/proto/account_state_blob.proto
cargo:rerun-if-changed=../../types/src/proto/validator_change.proto
cargo:rerun-if-changed=../../types/src/proto/access_path.proto
cargo:rerun-if-changed=../../types/src/proto/ledger_info.proto
cargo:rerun-if-changed=../../types/src/proto/get_with_proof.proto
cargo:rerun-if-changed=../../types/src/proto/validator_public_keys.proto
cargo:rerun-if-changed=../../types/src/proto/events.proto
cargo:rerun-if-changed=../../types/src/proto/validator_set.proto
cargo:rerun-if-changed=../../mempool/src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=src/proto/admission_control.proto

--- stderr
admission_control.proto: warning: Import ledger_info.proto but not used.
admission_control.proto: warning: Import proof.proto but not used.
admission_control.proto: No such file or directory
thread 'main' panicked at 'failed to write descriptor set: Custom { kind: Other, error: StringError("protoc (\"protoc\" \"-I../../types/src/proto\" \"-I../../mempool/src/proto/shared\" \"-Isrc/proto\" \"--descriptor_set_out=/tmp/8a6e8e957f644bffad147eaa72747cd8\" \"--include_imports\" \"admission_control.proto\") exited with non-zero exit code") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `mempool v0.1.0 (/home/jm/project/facebook/libra/mempool)`

Caused by:
  process didn't exit successfully: `/home/jm/project/facebook/libra/target/debug/build/mempool-e30338c93f591351/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=../types/src/proto/transaction.proto
cargo:rerun-if-changed=../types/src/proto/proof.proto
cargo:rerun-if-changed=../types/src/proto/transaction_info.proto
cargo:rerun-if-changed=../types/src/proto/vm_errors.proto
cargo:rerun-if-changed=../types/src/proto/account_state_blob.proto
cargo:rerun-if-changed=../types/src/proto/validator_change.proto
cargo:rerun-if-changed=../types/src/proto/access_path.proto
cargo:rerun-if-changed=../types/src/proto/ledger_info.proto
cargo:rerun-if-changed=../types/src/proto/get_with_proof.proto
cargo:rerun-if-changed=../types/src/proto/validator_public_keys.proto
cargo:rerun-if-changed=../types/src/proto/events.proto
cargo:rerun-if-changed=../types/src/proto/validator_set.proto
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=src/proto/mempool.proto

--- stderr
mempool.proto: No such file or directory
thread 'main' panicked at 'failed to write descriptor set: Custom { kind: Other, error: StringError("protoc (\"protoc\" \"-I../types/src/proto\" \"-Isrc/proto/shared\" \"-Isrc/proto\" \"--descriptor_set_out=/tmp/4c3b7f8f242749b28890302b89a0f581\" \"--include_imports\" \"mempool.proto\") exited with non-zero exit code") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by yanncarlier** [comment]
I have the same issue
+++++++++++++++++++++++++++++++++++++++++++++++++++++
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
+++++++++++++++++++++++++++++++++++++++++++++++++++++
cargo:rerun-if-changed=src/proto/mempool.proto

--- stderr
mempool.proto: No such file or directory
thread 'main' panicked at 'failed to write descriptor set: Custom { kind: Other, error: StringError("protoc (\"protoc\" \"-I../types/src/proto\" \"-Isrc/proto/shared\" \"-Isrc/proto\" \"--descriptor_set_out=/tmp/9d03d14afa7246fdb48b9c8935c9544b\" \"--include_imports\" \"mempool.proto\") exited with non-zero exit code") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
+++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by katopz** [comment]
Working for me https://medium.com/coinmonks/libra-digitalocean-8083326bb266
Maybe memory is too low?

**Comment by yanncarlier** [comment]
I'm running on my laptop, 8G ram

**Comment by yanncarlier** [comment]
> Working for me https://medium.com/coinmonks/libra-digitalocean-8083326bb266
> Maybe memory is too low?

nice article... but I'm stuck in "Feed your cat" I dont have one

**Comment by katopz** [comment]
@yanncarlier lol, let's try docker way here https://medium.com/@katopz/libra-docker-844629b5d6ae

**Comment by yanncarlier** [comment]
Instaled in a new machine, same OS version fresh installation, all worked fine

**Comment by icarter09** [comment]
@jmzhuzhonghua are you still experiencing this issue?

**Comment by bmwill** [comment]
The external dependencies needed to build Libra have been simplified and should only require Rust now so this shouldn't be an issue anymore on master. If it is, please let us know.
