### ISSUE TITLE
[Feature Request] expose revision hash to public metrics port

### ISSUE THREAD

**Issue by sherry-x** [libra/libra#1530]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**
We're building a public monitoring dashboard for partners to monitoring each validators' health.
One thing to add in the dashboard is what's the current revision number each node is running on, so that we can track each other's release progress.

## Pitch

**Describe the solution you'd like**
Currently we only expose Prometheus counters for monitoring purpose, which does not support numeric metrics. We should add a non-numeric metric folder for other format of metrics. 

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes

**Comment by gregnazario** [comment]
@sherry-x I believe we do monitor the code revision now for logs and metrics?

**Comment by sherry-x** [comment]
yes
