### ISSUE TITLE
[Bug] cargo-audit doesn't break the build on warnings

### ISSUE THREAD

**Issue by gedigi** [libra/libra#1535]
# 🐛 Bug

`cargo-audig` should break the build also when it generate warnings, so developers can be alerted if something not-vulnerable-but-fishy is happening.

## To reproduce

For example, [this CircleCI run](https://app.circleci.com/jobs/github/libra/libra/13047) shows `cargo-audit` warnings but completes successfully.

## Expected Behavior

There's no such thing as enough paranoia, so `cargo-audit` warnings should break the build.

## System information

n/a

## Additional context

n/a

**Comment by sausagee** [comment]
I will fix up the CI to fail the build at warning level.  

For the time being, is anyone looking to the crate in question? 
```
Crate:    term
Title:    term is looking for a new maintainer
Date:     2018-11-19
URL:      https://rustsec.org/advisories/RUSTSEC-2018-0015
Dependency tree:
{Too long to post here. It's used all over the place.}
```
