### ISSUE TITLE
[network][discovery] Add on-chain discovery module

### ISSUE THREAD

**Issue by phlip9** [libra/libra#1547]
# 🚀 Feature Request

See #1143 #1516 

We should rename the current discovery module to "gossip discovery" and add a new "on-chain discovery". The on-chain discovery module then follows `LedgerInfo` updates and periodically issues `UpdateToLatestLedgerInfo` requests to learn the latest validator set and discovery set. It then needs to pass down discovery info to the connectivity manager (how to dial peers) and peer manager (which peers to accept connections from).

**Comment by bmwill** [comment]
As long as this new "on-chain" discovery is used in addition to and not in place of the gossip discovery we already have then I think this would be ok.

**Comment by phlip9** [comment]
closed by #3354
