### ISSUE TITLE
Bad Naming

### ISSUE THREAD

**Issue by karlosagudo** [libra/libra#156]
For 400 millions spanish speakers libra is already a real currency, the english pound.
The translation of pound is "libra" in spanish, so.. its impossible if you are talking about buying "libras", if you are talking about pounds or this new coin.

**Comment by karlosagudo** [comment]
To give more context, imagine I create a new e-coin and I call it Renminbi, or Dollar

**Comment by desarrolla2** [comment]
I totally agree with @karlosagudo , call a new currency with the name of a currency that already exists, can cause confusion, and maybe chaos at global level.

**Comment by mtaipe** [comment]
There was such problem with Bitcoin, Bitcoin Cash, Gold, Private and SV and unless someone wants to scam others the complete name is used. Libra is not the same as Libra Esterlina, hence there is no misunderstanding IMHO. The same is for Canadian Dollars, Australian Dollars and many others that you can find here: https://en.wikipedia.org/wiki/ISO_4217

**Comment by karlosagudo** [comment]
" Libra is not the same as Libra Esterlina" - Before this,  it was, and for a long time it is, and will be for a spanish speaker.
BEFORE Facebook:, pound  is libra, and libra is libra esterlina.
AFter: libra, that was before libra esterlina or libra now is libra by facebook...and libra now its the complete name you never used before of libra esterlina all clear no?? 
Do you realise the mess?

well.. no :D , how many coin names there are with the traslations in all languages... **why you choose one of the most famous coins (top 5 by familiarity for sure, after euro and american dollar probably the next one) in the 2-3 more used language in the world?** 
Its common sense, not ISO related.

**Comment by ZettaScript** [comment]
I opened #93 for a similar reason, but it was closed.

Generally, for big international projects, expert linguists or translators verify if names sound good in several languages... This issue shows that either Facebook started this project without thinking, or they don't care about Spanish speakers. Maybe both.

**Comment by bmaurer** [comment]
The name Libra was inspired by historical names for money in the Roman Empire (the source of the symbol for the British Pound). We were aware of the fact that this has resulted in Spanish still using the word Libra to refer to the British Pound. We discussed the impact and decided to go forward with the name.

**Comment by karlosagudo** [comment]
Why not aureus, denarius or other variation...no.. let's choose one that goes against 400 million people... Sorry to say this but in Spanish eyes this is not wise, not polite and very egocentric.  Imagine if telefónica creates a new crypto currency and name it dollar, will you consider this naming a bit offensive? Or at least as no sense at all? Imagine if their answer is...yeah why know it's a coin for some speakers but we didn't care... Anyway.. bad bad decision.

**Comment by jeremyckahn** [comment]
As an alternative, I suggest “ZuckBucks” or “FaceDollars,” as those names are descriptive and do not conflict with the names of any existing currencies that I am aware of.

**Comment by ashanan** [comment]
> We were aware of the fact that this has resulted in Spanish still using the word Libra to refer to the British Pound. We discussed the impact and decided to go forward with the name.

This sentence makes it clear that ZuckBucks is the proper name for such a careless and arrogant process.

**Comment by thatsanicehat** [comment]
Why has the obvious choice "FaceBucks" not instead been adopted? Same number of syllables, and makes very clear the origin of yet another CC in a sea of hundreds.
