### ISSUE TITLE
[Bug]compiler subcommand unmatching the description in libra/language/compiler/README

### ISSUE THREAD

**Issue by 3for** [libra/libra#162]
![image](https://user-images.githubusercontent.com/30716372/59895245-60754400-9416-11e9-8f0e-9f80b2e878fa.png)
```
./target/debug/compiler -s ./language/stdlib/transaction_scripts/create_account.mvir

error: Found argument '-s' which wasn't expected, or isn't valid in this context
```

**Comment by perfectmak** [comment]
I also noticed this while working with the compiler and submitted a PR to update the documentation here #213

**Comment by bmwill** [comment]
Looks like the `-s` option has been replaced with the `-m` option. If you're still running into problems please let us know.
