### ISSUE TITLE
[Feature Request] Simple docker dev environment to avoid wasting time. 

### ISSUE THREAD

**Issue by zhaojinzhou** [libra/libra#163]
# 🚀 Feature Request

## Motivation

**simple docker dev  environment to avoid wasting time.**
  
docker pull zhaojinzhou/fb-libra-dev  
dir:  
/root/libra

**Comment by sashidhar** [comment]
@zhaojinzhou , I would like to work on this feature. Can you guide me on the code set up ?

**Comment by 0-o-0** [comment]
There is already a docker file for the client. Check it out in https://github.com/libra/libra/tree/master/docker/client

You can simply run
```
./docker/client/build.sh
docker run -it libra_client:latest
```

**Comment by starzhouchina** [comment]
libra can growing up a standard product , so need use docker to deploy it!!!!
very important and useful
nice!

**Comment by kphfb** [comment]
Closing as this exists: https://community.libra.org/t/improving-developer-experience-using-libra-command-line-client/441
