### ISSUE TITLE
[cluster test] Measure and report discarded transactions count during experiment

### ISSUE THREAD

**Issue by andll** [libra/libra#1638]
When cluster test TxEmitter fails to commit transaction it retries attempt.
However, we want to track number of such discarded transactions and report this in performance report to catch regressions
 
Code pointers:
see `main.rs: measure_performance` for performance report generation
see `tx_emitter.rs:  SubmissionThread::run` for retry code

This will allow to surface issues such as https://github.com/libra/libra/issues/1625

**Comment by dltmd6262** [comment]
This issue looks like something I can take up. Can you assign this issue to me so I can start working on it?

**Comment by andll** [comment]
Hi @dltmd6262 
Right now no one is working on the issue, you are welcome to make a PR, and we will be happy to take a look at it :)

**Comment by dltmd6262** [comment]
great! Ill get started tomorrow :)

**Comment by dltmd6262** [comment]
Hi @andll I've been trying to run the cluster test with AWS to get Prometheus up, but the entire cluster is costing too much for me to continue working on this :[ I'm really sorry but I think I should let someone else work on this.

**Comment by andll** [comment]
So in theory you don't need AWS or Prometheus setup to work on this specific task
You could just have atomic counters in EmitterJob and use them to calculate statistics.

**Comment by tommyyama2020** [comment]
i want to take over this based on your advices.

**Comment by dltmd6262** [comment]
@tommyyama2020 Thank you I'm not sure how you would go about this without Prometheus because `measure_performance` reads all stats from Prometheus..

**Comment by tommyyama2020** [comment]
@andll mentioned that Prometheus is not needed in previous threads.

**Comment by andll** [comment]
Yes, so prometheus metrics are server side metrics
In addition to them it would be nice to actually have client side metrics, e.g. metrics measured from tx_emitter threads, vs ones reported by servers.

It should not be different for TPS, but, for example, for latencies I can anticipate some difference.
Also I am not sure we have good server-side metrics for discarded transactions that we are talking about in this issue, so they are also probably good to measure on tx_emitter side

**Comment by tommyyama2020** [comment]
It's like atomic-counter ? Sorry for a silly question. but i am relatively/shamelessly  newbie in blockchain.

**Comment by andll** [comment]
Yes, we can use atomic counter with Relaxed

**Comment by tommyyama2020** [comment]
Can I insert below in tx_emitter.rs ? 

pub struct RelaxedCounter(AtomicUsize);

impl RelaxedCounter {

    /// Creates a new counter with initial_value
    pub fn new(initial_count: usize) -> RelaxedCounter {
        RelaxedCounter(AtomicUsize::new(initial_count))
    }
}

impl AtomicCounter for RelaxedCounter {
    type PrimitiveType = usize;

    fn inc(&self) -> usize {
        self.add(1)
    }

    fn add(&self, amount: usize) -> usize {
        self.0.fetch_add(amount, Relaxed)
    }

    fn get(&self) -> usize {
        self.0.load(Relaxed)
    }

    fn reset(&self) -> usize {
        self.0.swap(0, Relaxed)
    }

    fn into_inner(self) -> usize {
        self.0.into_inner()
    }
}

**Comment by andll** [comment]
It seem this wrapper just renames and/or abbreviates methods from AtomicUsize?
I personally would prefer to just use AtomicUsize(or, better specify size and use AtomicU64)

**Comment by tommyyama2020** [comment]
okay. thanks a lot for your pointer. I learn a lot here.

**Comment by tommyyama2020** [comment]
> ` better specify size and use AtomicU64)`
What sizes  would be to specify with the use of AtomicU64? 🙇🏻‍♀️

**Comment by andll** [comment]
I mean, AtomicU64 already has specific size(64 bits), unlike AtomicUsize which size depends on architecture
