### ISSUE TITLE
[Bug] Minting coins [ERROR] Error minting coins: invalid digit found in string

### ISSUE THREAD

**Issue by deepanshu-jha-27** [libra/libra#165]
**Console Output:**

libra% account mint 1 200

>> Minting coins
[ERROR] Error minting coins: invalid digit found in string

If anyone could confirm this issue or there's something I am doing wrong?

**Comment by icarter09** [comment]
@deepanshu-jha-27 do you have an account 1? What does `account list` show?

**Comment by kphfb** [comment]
@deepanshu-jha-27 can you please provide the entire set of commands run?  Starting with account creation please

**Comment by devos50** [comment]
I also observed this error when setting up some validator nodes. For me, it was solved when I passed the `--faucet_key_file_path` flag pointing to the minting keypair when starting the client.

**Comment by bmwill** [comment]
This shouldn't be an issue anymore, if you're still running into problems please let us know.

**Comment by devos50** [comment]
Haven't seen this error recently 👍
