### ISSUE TITLE
coin lost in earmark example, how to verify bytecode?

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#166]
public create(coin: R#LibraCoin.T, recipient: address) {
    let t: R#Self.T;

    t = T {
      coin: move(coin),
      recipient: move(recipient),
    };
// I comment this line, the compiler doesn't report error.
// That means the coin will get lost???
// how can I verify the byte code is correct?
// will the compiler verify the byte code?

    //move_to_sender<T>(move(t));
    return;
  }

**Comment by sblackshear** [comment]
When I comment out the line `move_to_sender<T>(move(t));` in the `EarmarkedLibra` [code](https://github.com/libra/libra/blob/master/language/functional_tests/tests/testsuite/move_getting_started_examples/earmarked_libra.mvir) and run:

 `./libra/target/debug/compiler earmarked_libra.mvir`

, the bytecode verifier rejects the code with

```
Verification failed. Errors below:
VerificationError { kind: FunctionDefinition, idx: 0, err: RetUnsafeToDestroyError(4) }
```

as I would expect. If you are seeing different behavior, would you mind reopening with a complete Move file and the command you are running?
