### ISSUE TITLE
[cluster-test] Run cluster test from docker

### ISSUE THREAD

**Issue by andll** [libra/libra#1669]
We need to be able to run cluster test from inside docker container.

- Access mint key from docker container
- Access libra_rsa ssh key from docker container
- Update cluster_test.Dockerfile (most likely outdated since we never used it)

**Comment by dltmd6262** [comment]
It would be great if we can have this soon.. I'm on a mac working on #1638 but I just can't get the cluster test to run locally on docker with local swarm :[

**Comment by andll** [comment]
@dltmd6262 you should be able to run tx emitter with docker swarm
If you do
```cargo run -p libra-warm```
it will print out command line for running cluster test with tx emitter

**Comment by dltmd6262** [comment]
right but I can't print performance stats because I can't use prometheus with that setup :(

**Comment by dltmd6262** [comment]
I'm just going to use aws in the meantime but this feature would be awesome
