### ISSUE TITLE
how to check the total coin balance for earmarked example?

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#167]
when an account has a libra coin,  I can check the balance.
But now I move part of the fund to the earmarked resource, the coin is embeded.
It seems I am unable to report the balance any more.

In etherem, ERC20, you can just call balanceOf for either plain address or contract wallet.
Now I can no longer check the earmarked since it is just a blackhole.

**Comment by icarter09** [comment]
@kphfb do you have any suggestions on best course of action for this issue?

**Comment by kphfb** [comment]
I'm not entirely sure I understand what is being asked.  @sblackshear can you help with this one?

**Comment by jolestar** [comment]
I also want to know how to save a global state with Move. Keep a resource in the owner's account is a method, but how to allow other users to update it?

**Comment by sblackshear** [comment]
> when an account has a libra coin, I can check the balance.
But now I move part of the fund to the earmarked resource, the coin is embeded.
It seems I am unable to report the balance any more.

In the `EarmarkedLibraCoin` example from the Move [overview](https://developers.libra.org/docs/move-overview#writing-modules), we could make it possible for anyone to check the balance of the earmarked coin by adding a procedure like

```
public balance(earmarked_coin_address: address): u64 {
  let t_ref: &mut R#Self.T;
  let coin_ref: &R#LibraCoin.T;
  let balance: u64;

  t_ref = borrow_global<T>(move(earmarked_coin_address));
  coin_ref = &move(t_ref).coin;
  balance = LibraCoin.value(move(coin_ref));

  return move(balance);
}
```

to the `EarmarkedLibraCoin` module.

> I also want to know how to save a global state with Move. Keep a resource in the owner's account is a method, but how to allow other users to update it?

Here are two examples from the Libra Discourse that demonstrate this sort of pattern. Hope this helps!

https://community.libra.org/t/how-to-implement-a-state-machine-with-move/757/3
https://community.libra.org/t/conditional-payments-in-move/414/5
