### ISSUE TITLE
[network] Refactor LibraNet for end-to-end QoS fairness and backpressure isolation

### ISSUE THREAD

**Issue by bothra90** [libra/libra#1670]
# 🚀 Feature Request

## Motivation

Today, due to various queues in the LibraNet stack (e.g. PeerManager -> RPC, etc.) which are shared across peers/connections, it is difficult to guarantee fairness to peers and ensuring that back-pressure from one peer does not affect other peers. We need a way to solve both of these problems.

## Pitch

**Describe the solution you'd like**

We can achieve full end-to-end fairness and QoS by spawning a new stack of network actors (RPC + DirectSend + SubstreamMuxer(new))per peer. In some sense, we already do this in DirectSend by spawning a separate tasks per peer. The proposed solution will just take this notion to the entire stack.

The existing `PeerManager` actor will be split into 2 new actors: A `SubstreamMuxer` for opening and listening for new substreams from a particular peer, and a new `PeerManager` which only dials and listens for new connections.

**Describe alternatives you've considered**

Another way of achieving this would have been to have all the queues in the stack be aware of all peers and provide fair queueing. Isolating back-pressure in this case would also have been challenging.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

cc: @phlip9

**Comment by bmaurer** [comment]
Does "peer" here mean a specific peerid / account, or a network connection? I could see really subtle bugs pop up if we try to coordinate backpressure across multiple network connections (realistic example: in Linux when you coredump you only reset the tcp connection once the core dump is complete. This frequently causes servers to live on for minutes after they are destined for death, not reading the socket. Imagine while this is happening a new prospective version of this peer comes to life)

**Comment by bothra90** [comment]
@bmaurer : The way this is currently imagined, it would mean connection. If we ever go into a world where we can have multiple connections per peer, I don't think we'd try to coordinate backpressure across all the connections.
