### ISSUE TITLE
Build on the Nyzo chain (new proof of diversity consensus)

### ISSUE THREAD

**Issue by 0xSnipe** [libra/libra#17]
As detailed here: https://medium.com/@nyzoco/the-nyzo-mesh-time-and-diversity-as-a-currency-85c676631516

Don't censor again.

**Comment by 0xSnipe** [comment]
Before you downvote read it

**Comment by ericnakagawa** [comment]
If you'd like to discuss our approach for consensus, please start a thread on https://community.libra.org

**Comment by 0xSnipe** [comment]
Stop censoring

**Comment by marcusnewton1** [comment]
@0xSnipe the thread is not locked
