### ISSUE TITLE
does it need a  key to create_account(copy(payee));

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#172]
I noticed in the example, there is a way to create account dynamically.
create_account(copy(payee));

can we just create any account with any address without a key associated with it?

**Comment by ladiJ2N** [comment]
In Libra, every account must have an address and authentication key associated to it.

The create_account method accepts an address and sets the authentication key to match the address. You also have the ability to rotate your authentication key if you would like to use a different public key to authenticate your transactions, e.g. if you feel your old keypair has been compromised.

Hope this helps.

**Comment by icarter09** [comment]
@aihuawu, did @ladiJ2N comemnt help you with this issue?

**Comment by davidiw** [comment]
issue no longer applies
