### ISSUE TITLE
[network] Harden substream handling and negotiation

### ISSUE THREAD

**Issue by phlip9** [libra/libra#1723]
+ Our maximum number of inbound substreams is definitely too high (default 8192). Once we complete the network-internal protocol refactor (#1516) and the QoS refactor (#1670) we can probably restrict the max # substreams to (1 (direct-send) + max_concurrent_inbound_rpc + max_concurrent_outbound_rpc + some margin?).

+ We can likely harden inbound negotiation by reducing the length-prefix from a u16-prefix to a u8-prefix. I don't believe there are any use cases where our `ProtocolId`'s are > 255 bytes. Similarly, we should have a timeout for an inbound and outbound negotiation to complete. We also exchange all supported protocols during the `Identify` step in the handshake, so we should be able to only accept optimistic negotiation for inbound substreams.

+ This issue is in a similar vein to (#1517), which would add timeouts to inbound and outbound direct-send messages.

cc @bothra90 @bmwill

**Comment by bothra90** [comment]
This is stale now, since we've migrated to the new wire protocol
