### ISSUE TITLE
is it possible to delete my account on the blockchain?

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#173]
is it possible to delete my account on the blockchain?
Then how about the coin held in my account if deleted?

**Comment by ladiJ2N** [comment]
Hi @aihuawu,

It is currently not possible to delete your account on the blockchain. We have a proposal for how to do so, but it has not been implemented yet.

Stay tuned.

**Comment by ericnakagawa** [comment]
Hi @aihuawu, I wanted to also note that we plan on refreshing the testnet periodically. All accounts should be purged by this action.

As @ladiJ2N mentioned above, additional functionality is coming.
