### ISSUE TITLE
[Bug]error: linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by download8866** [libra/libra#175]
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/root/libra/target/debug/deps/secret_service-6a35e80a981e7522.11hr4ft1idaaf8ps.rcgu.o" "/root/libra/target/debug/deps/secret_service-6a35e80a981e7522.1owuxzfmrfchu165.rcgu.o" "/root/libra/target/debug/deps/secret_service-6a35e80a981e7522.1ror7qzv5ikj145c.rcgu.o" "/root/libra/target/debug/deps/secret_service-6a35e80a981e7522.1v4kqz91kc4ielwm.rcgu.o" "/root/libra/target/debug/deps/secret_service-6a35e80a981e7522.2v359rvvxd7kdxfo.rcgu.o" "/root/libra/target/debug/deps/secret_service-6a35e80a981e7522.2ze7esli8jhcfido.rcgu.o" "/root/libra/target/debug/deps/secret_service-6a35e80a981e7522.3i9tlw7woi2kri5t.rcgu.o" "/root/libra/target/debug/deps/secret_service-6a35e80a981e7522.3wq3hfiknsmyfbyx.rcgu.o" "/root/libra/target/debug/deps/secret_service-6a35e80a981e7522.5if5794dqqvrd1q.rcgu.o" "/root/libra/target/debug/deps/secret_service-6a35e80a981e7522.myyoud85n7xpup9.rcgu.o" "-o" "/root/libra/target/debug/deps/secret_service-6a35e80a981e7522" "/root/libra/target/debug/deps/secret_service-6a35e80a981e7522.ha02qrl9m0rgleg.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/root/libra/target/debug/deps" "-L" "/root/libra/target/debug/build/clear_on_drop-146b1f0aaeed2a2e/out" "-L" "/root/libra/target/debug/build/backtrace-sys-2bab103e4824753f/out" "-L" "/root/libra/target/debug/build/grpcio-sys-49db958d0db045e1/out/build" "-L" "/root/libra/target/debug/build/grpcio-sys-49db958d0db045e1/out/build/third_party/cares/cares/lib" "-L" "/root/libra/target/debug/build/grpcio-sys-49db958d0db045e1/out/build/third_party/zlib" "-L" "/root/libra/target/debug/build/grpcio-sys-49db958d0db045e1/out/build/third_party/boringssl/ssl" "-L" "/root/libra/target/debug/build/grpcio-sys-49db958d0db045e1/out/build/third_party/boringssl/crypto" "-L" "/root/libra/target/debug/build/grpcio-sys-49db958d0db045e1/out" "-L" "/root/libra/target/debug/build/jemalloc-sys-b04a9f5f54ecf6a0/out/build/lib" "-L" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/root/libra/target/debug/deps/libsecret_service-31e71a172b2d98e3.rlib" "/root/libra/target/debug/deps/libgrpc_helpers-aadf3f9dcb0e1596.rlib" "/root/libra/target/debug/deps/libfutures-a149e6ce46ac0589.rlib" "/root/libra/target/debug/deps/libfutures_executor-ffac4d3a9ad16f31.rlib" "/root/libra/target/debug/deps/libfutures_util-03239ba392ecd47c.rlib" "/root/libra/target/debug/deps/libproc_macro_nested-f5fcf4d0afd2e89d.rlib" "/root/libra/target/debug/deps/libfutures_io-916ae378206562e1.rlib" "/root/libra/target/debug/deps/libfutures_sink-f0c82c5606a6a849.rlib" "/root/libra/target/debug/deps/libfutures_channel-d98cfe08d63c42d9.rlib" "/root/libra/target/debug/deps/libpin_utils-0399b43a897a0ed1.rlib" "/root/libra/target/debug/deps/libfutures_core-16bfbc993335c612.rlib" "/root/libra/target/debug/deps/libdebug_interface-a136346dc48b2cce.rlib" "/root/libra/target/debug/deps/libjemalloc-6480b81ea4430051.rlib" "/root/libra/target/debug/deps/libjemallocator-1f571446df06eb62.rlib" "/root/libra/target/debug/deps/libjemalloc_sys-12ebd2a711a4d8cd.rlib" "/root/libra/target/debug/deps/libnextgen_crypto-aa011596e3ce8e85.rlib" "/root/libra/target/debug/deps/libregex-d009f4ff36bcdc51.rlib" "/root/libra/target/debug/deps/libutf8_ranges-00c0b767bcc083a9.rlib" "/root/libra/target/debug/deps/libaho_corasick-78159062084e42d1.rlib" "/root/libra/target/debug/deps/libmemchr-332c901485356ccb.rlib" "/root/libra/target/debug/deps/libthreshold_crypto-d8a091a9c6b8c31c.rlib" "/root/libra/target/debug/deps/libhex_fmt-7329c4f1e2950674.rlib" "/root/libra/target/debug/deps/librand04_compat-e58b7496862f4baf.rlib" "/root/libra/target/debug/deps/librand04-d9f0b6c4424f5900.rlib" "/root/libra/target/debug/deps/libmemsec-8cc0d01959f79f71.rlib" "/root/libra/target/debug/deps/libgetrandom-d8e4bfe59c38007b.rlib" "/root/libra/target/debug/deps/libpairing-e4bc2687a1429ae0.rlib" "/root/libra/target/debug/deps/librand-df193064469fa239.rlib" "/root/libra/target/debug/deps/libexecutable_helpers-121b9c58d2d29fcb.rlib" "/root/libra/target/debug/deps/libcrash_handler-f1e75ea7d0cb985e.rlib" "/root/libra/target/debug/deps/libmetrics-25cf8b303d6f3a0c.rlib" "/root/libra/target/debug/deps/libgrpcio-26097629cc7f5b43.rlib" "/root/libra/target/debug/deps/libgrpcio_sys-24b36a1c85d393d6.rlib" "/root/libra/target/debug/deps/libprometheus-ff6950baf26c99f2.rlib" "/root/libra/target/debug/deps/libspin-7091f760a1851a56.rlib" "/root/libra/target/debug/deps/libquick_error-f4e137951cf4b46d.rlib" "/root/libra/target/debug/deps/liblazy_static-97d7050227855834.rlib" "/root/libra/target/debug/deps/libhyper-6353275a2beec9cc.rlib" "/root/libra/target/debug/deps/libmime-70c841cbb9796514.rlib" "/root/libra/target/debug/deps/liblanguage_tags-70c4ac17ad913038.rlib" "/root/libra/target/debug/deps/libsolicit-0d3be09d0256cbe8.rlib" "/root/libra/target/debug/deps/libhpack-85a9c700ca4cf119.rlib" "/root/libra/target/debug/deps/libtypeable-9befd570115badd7.rlib" "/root/libra/target/debug/deps/libtraitobject-2addd6c17b5d909c.rlib" "/root/libra/target/debug/deps/libunicase-ed779d4135d1da48.rlib" "/root/libra/target/debug/deps/libcookie-9d931832ce646828.rlib" "/root/libra/target/debug/deps/librustc_serialize-79eb6ae02f5681e3.rlib" "/root/libra/target/debug/deps/libconfig-95b146905eac1ea6.rlib" "/root/libra/target/debug/deps/libget_if_addrs-77215c88549e88a5.rlib" "/root/libra/target/debug/deps/libc_linked_list-09ef93459ff9216f.rlib" "/root/libra/target/debug/deps/libtypes-c071837ff93dccb0.rlib" "/root/libra/target/debug/deps/libbech32-9b9ab8a713a35cb0.rlib" "/root/libra/target/debug/deps/libradix_trie-180b5b2852234cb7.rlib" "/root/libra/target/debug/deps/libnibble_vec-4116c3413164ad56.rlib" "/root/libra/target/debug/deps/libendian_type-1f4174bb14f68264.rlib" "/root/libra/target/debug/deps/libcanonical_serialization-30e07809ed4f0b69.rlib" "/root/libra/target/debug/deps/libtoml-38f380d8ba443b1a.rlib" "/root/libra/target/debug/deps/liblogger-44c5f6e71af8944a.rlib" "/root/libra/target/debug/deps/libmime-789d10ad4be16619.rlib" "/root/libra/target/debug/deps/libunicase-84eb6956ebc19aad.rlib" "/root/libra/target/debug/deps/libcrossbeam-2e325ea986350342.rlib" "/root/libra/target/debug/deps/libcrossbeam_deque-2e8e1c22d9791017.rlib" "/root/libra/target/debug/deps/libcrossbeam_epoch-83893a47de937fab.rlib" "/root/libra/target/debug/deps/libcrossbeam_channel-06d96eabe5dce66b.rlib" "/root/libra/target/debug/deps/libparking_lot-3a5fdc8cf96b4fbf.rlib" "/root/libra/target/debug/deps/libparking_lot_core-21c4afc50e5df779.rlib" "/root/libra/target/debug/deps/librand-878e6001846aaad0.rlib" "/root/libra/target/debug/deps/libcrossbeam_utils-799d63a26084de3a.rlib" "/root/libra/target/debug/deps/libcrossbeam_epoch-d43b145ba0edc04f.rlib" "/root/libra/target/debug/deps/libslog_envlogger-0027c87666cef7c2.rlib" "/root/libra/target/debug/deps/libslog_async-632e6b16aed8f43b.rlib" "/root/libra/target/debug/deps/libtake_mut-523a97a180a56f4c.rlib" "/root/libra/target/debug/deps/libslog_stdlog-b03ee3cf6829f960.rlib" "/root/libra/target/debug/deps/liblog-6984c27103674931.rlib" "/root/libra/target/debug/deps/libregex-94aeeb60317f53c3.rlib" "/root/libra/target/debug/deps/libutf8_ranges-a33319d9409f145f.rlib" "/root/libra/target/debug/deps/libregex_syntax-5d68455c9f7a2461.rlib" "/root/libra/target/debug/deps/libthread_local-9db4663aea3f4de9.rlib" "/root/libra/target/debug/deps/libthread_id-7452e193c7d727f8.rlib" "/root/libra/target/debug/deps/libaho_corasick-1b4fe43ccc27cfd2.rlib" "/root/libra/target/debug/deps/libmemchr-637b7723e8d9e198.rlib" "/root/libra/target/debug/deps/libhyper-c8013ec574c54378.rlib" "/root/libra/target/debug/deps/libwant-06e81b0be054b654.rlib" "/root/libra/target/debug/deps/libtry_lock-23aff9ce6561c1bf.rlib" "/root/libra/target/debug/deps/libtokio-ae2b1f663ce7bc4a.rlib" "/root/libra/target/debug/deps/libtokio_trace_core-99d64176dc834037.rlib" "/root/libra/target/debug/deps/libtokio_uds-5de069bc3ee7311b.rlib" "/root/libra/target/debug/deps/libmio_uds-20aece3a5decab4e.rlib" "/root/libra/target/debug/deps/libtokio_udp-aa6185fedda0735d.rlib" "/root/libra/target/debug/deps/libtokio_timer-632465d505786899.rlib" "/root/libra/target/debug/deps/libtokio_tcp-a3e5a7cd5a9ddbfd.rlib" "/root/libra/target/debug/deps/libtokio_reactor-761d697b1acf375d.rlib" "/root/libra/target/debug/deps/libtokio_sync-ce61c49b71a69601.rlib" "/root/libra/target/debug/deps/libtokio_fs-2cd20947ff3ce5c3.rlib" "/root/libra/target/debug/deps/libtokio_threadpool-9b609453142c4bfc.rlib" "/root/libra/target/debug/deps/libcrossbeam_queue-82f86a55c25f0538.rlib" "/root/libra/target/debug/deps/libcrossbeam_deque-390d5eb7df8ad059.rlib" "/root/libra/target/debug/deps/libtokio_current_thread-93f1f7d724fd17bc.rlib" "/root/libra/target/debug/deps/libtokio_executor-64e24250daf82a25.rlib" "/root/libra/target/debug/deps/libmio-6c4b688abee9bc31.rlib" "/root/libra/target/debug/deps/libnet2-24a8048f83525af6.rlib" "/root/libra/target/debug/deps/libhttparse-650c3e85bb8d6d5d.rlib" "/root/libra/target/debug/deps/libhttp_body-fbf1f9b7a1ce303d.rlib" "/root/libra/target/debug/deps/libtokio_buf-e4978fe7249b400b.rlib" "/root/libra/target/debug/deps/libh2-97291fa39e58c8b5.rlib" "/root/libra/target/debug/deps/libindexmap-beccd5428c82a108.rlib" "/root/libra/target/debug/deps/libstring-e3c61b97b1dbdea2.rlib" "/root/libra/target/debug/deps/libslab-c124733a2d581a0c.rlib" "/root/libra/target/debug/deps/libhttp-2057ada5f1e916d7.rlib" "/root/libra/target/debug/deps/libfutures_cpupool-8dd89c7bb4e18d8a.rlib" "/root/libra/target/debug/deps/libslog_scope-828bf38e3567d568.rlib" "/root/libra/target/debug/deps/libcrossbeam-f7ba58950a6db838.rlib" "/root/libra/target/debug/deps/libparking_lot-c3d340c33aa5dba4.rlib" "/root/libra/target/debug/deps/libparking_lot_core-4f13e6c6f9f74a8f.rlib" "/root/libra/target/debug/deps/liblock_api-339efa51dec0d9c9.rlib" "/root/libra/target/debug/deps/libowning_ref-7dc686641c04fa20.rlib" "/root/libra/target/debug/deps/libstable_deref_trait-4b72ed990ca99295.rlib" "/root/libra/target/debug/deps/libnum_cpus-ba5b5491d94dcf36.rlib" "/root/libra/target/debug/deps/libcrossbeam_channel-be38b4341453b276.rlib" "/root/libra/target/debug/deps/libcrossbeam_deque-5a18dd27e4250041.rlib" "/root/libra/target/debug/deps/libcrossbeam_epoch-c7218c8f9d779800.rlib" "/root/libra/target/debug/deps/libscopeguard-b01727e906ba1141.rlib" "/root/libra/target/debug/deps/libmemoffset-16374095567df475.rlib" "/root/libra/target/debug/deps/libcrossbeam_utils-4568bb48f955fe56.rlib" "/root/libra/target/debug/deps/libarrayvec-6d1703030fa9b7e5.rlib" "/root/libra/target/debug/deps/libserde_json-a9a80b0d02923e8e.rlib" "/root/libra/target/debug/deps/libryu-834f1e71e012bf4b.rlib" "/root/libra/target/debug/deps/libitoa-0037a091d9afeb8f.rlib" "/root/libra/target/debug/deps/libthread_id-4e893c0abbe9ddc8.rlib" "/root/libra/target/debug/deps/libslog_term-67fe4cea3ebf9697.rlib" "/root/libra/target/debug/deps/libthread_local-0ac72fd9919802f7.rlib" "/root/libra/target/debug/deps/libterm-eb1526aa559391c6.rlib" "/root/libra/target/debug/deps/libdirs-aa94423ca8395f41.rlib" "/root/libra/target/debug/deps/libisatty-b35c5076ffc050c5.rlib" "/root/libra/target/debug/deps/libitertools-f3a8a1049d3bf6cb.rlib" "/root/libra/target/debug/deps/libchrono-24716e16350f832e.rlib" "/root/libra/target/debug/deps/libnum_integer-1864461d6b306f11.rlib" "/root/libra/target/debug/deps/libnum_traits-57a01e3e5cd0394f.rlib" "/root/libra/target/debug/deps/libtime-decc76b1bf68d469.rlib" "/root/libra/target/debug/deps/libslog-ca4e0b1ed1a8805a.rlib" "/root/libra/target/debug/deps/libcrypto-4b5851ad3e96195a.rlib" "/root/libra/target/debug/deps/libhex-e6bd00ad9731dcf6.rlib" "/root/libra/target/debug/deps/libx25519_dalek-2b71d6fedb701832.rlib" "/root/libra/target/debug/deps/libproptest-efb5afc23cc1eb7c.rlib" "/root/libra/target/debug/deps/libregex_syntax-bb92dd287ef165cf.rlib" "/root/libra/target/debug/deps/libucd_util-d42778bbe42950a1.rlib" "/root/libra/target/debug/deps/librusty_fork-734a72e204bb5e5b.rlib" "/root/libra/target/debug/deps/libwait_timeout-29b86a559b1f5128.rlib" "/root/libra/target/debug/deps/libtempfile-5d49b4eac0e38ec7.rlib" "/root/libra/target/debug/deps/libremove_dir_all-d4e6ab6b8ffdc13f.rlib" "/root/libra/target/debug/deps/libfnv-c0f98b033dfce0dc.rlib" "/root/libra/target/debug/deps/libquick_error-2be68e5f31037645.rlib" "/root/libra/target/debug/deps/libbit_set-7a2fd74556c0a4c2.rlib" "/root/libra/target/debug/deps/libbit_vec-0a5fceabd14061de.rlib" "/root/libra/target/debug/deps/libed25519_dalek-b1e3eb66a5587963.rlib" "/root/libra/target/debug/deps/libcurve25519_dalek-71799527ee8ba252.rlib" "/root/libra/target/debug/deps/libsubtle-6e83a3b3986bd3e0.rlib" "/root/libra/target/debug/deps/libclear_on_drop-9e372ff34063912f.rlib" "/root/libra/target/debug/deps/libbincode-98182bff633c0d72.rlib" "/root/libra/target/debug/deps/libhmac-553da7e744f40122.rlib" "/root/libra/target/debug/deps/libtiny_keccak-0bbf9b0ae0e76a08.rlib" "/root/libra/target/debug/deps/libcrunchy-36711f20e4afc54f.rlib" "/root/libra/target/debug/deps/libproto_conv-cd0e405f536288af.rlib" "/root/libra/target/debug/deps/libprotobuf-aef34cd7969b8671.rlib" "/root/libra/target/debug/deps/liblazy_static-e1b74b0446f2105f.rlib" "/root/libra/target/debug/deps/libfailure_ext-bb5ea50625b38e15.rlib" "/root/libra/target/debug/deps/libfailure_macros-f13ada09ef249258.rlib" "/root/libra/target/debug/deps/libfailure-c1d1c696a70c4fa1.rlib" "/root/libra/target/debug/deps/libbacktrace-3d57486fa0ba5730.rlib" "/root/libra/target/debug/deps/libbacktrace_sys-ca5ca3859ff43ec4.rlib" "/root/libra/target/debug/deps/librustc_demangle-d8a30151188b5bc0.rlib" "/root/libra/target/debug/deps/libparity_multiaddr-abde25b0106781e9.rlib" "/root/libra/target/debug/deps/liburl-2f0ed83e43c5e113.rlib" "/root/libra/target/debug/deps/libpercent_encoding-0fa2a5fcf2b9aedd.rlib" "/root/libra/target/debug/deps/libidna-dc89da430bc76cfd.rlib" "/root/libra/target/debug/deps/libunicode_normalization-7f68bf7e9f9d1fc9.rlib" "/root/libra/target/debug/deps/libsmallvec-54e86b6ad2e783c5.rlib" "/root/libra/target/debug/deps/libunicode_bidi-29e9ed0eca6004d8.rlib" "/root/libra/target/debug/deps/libmatches-8acc3af12049ab9e.rlib" "/root/libra/target/debug/deps/libserde-bac9a0c523793a05.rlib" "/root/libra/target/debug/deps/libdata_encoding-ea568b8127d380d6.rlib" "/root/libra/target/debug/deps/libbs58-074bb41e22ab1d2c.rlib" "/root/libra/target/debug/deps/libarrayref-10ef5098d87da617.rlib" "/root/libra/target/debug/deps/libparity_multihash-8fcf358df98c30e9.rlib" "/root/libra/target/debug/deps/librand-2b92945c29ee95c9.rlib" "/root/libra/target/debug/deps/librand_xorshift-541cabf5cdd58ea7.rlib" "/root/libra/target/debug/deps/librand_pcg-116b5127276bdc25.rlib" "/root/libra/target/debug/deps/librand_hc-582495ced219b404.rlib" "/root/libra/target/debug/deps/librand_chacha-ea41dcabc2db64b1.rlib" "/root/libra/target/debug/deps/librand_isaac-dadbddaa89781ce0.rlib" "/root/libra/target/debug/deps/librand_core-5ef12358711b34a9.rlib" "/root/libra/target/debug/deps/librand_os-114e37c5f6ef7df4.rlib" "/root/libra/target/debug/deps/librand_jitter-0ecb5a648fa88900.rlib" "/root/libra/target/debug/deps/librand_core-30f56235ea071326.rlib" "/root/libra/target/debug/deps/libblake2-c326d36ed43fffd2.rlib" "/root/libra/target/debug/deps/libcrypto_mac-a059755ae9b4b479.rlib" "/root/libra/target/debug/deps/libsubtle-f957332faf47846d.rlib" "/root/libra/target/debug/deps/libsha3-d43ca31d62608ab6.rlib" "/root/libra/target/debug/deps/libkeccak-bbc73b3c1b50033d.rlib" "/root/libra/target/debug/deps/libsha1-b68e1ef6380cce55.rlib" "/root/libra/target/debug/deps/libunsigned_varint-8d4e5a511661157e.rlib" "/root/libra/target/debug/deps/libtokio_codec-05811112175f5dfc.rlib" "/root/libra/target/debug/deps/libtokio_io-4b7becb1b1d59cf2.rlib" "/root/libra/target/debug/deps/libfutures-d9062469bef61e24.rlib" "/root/libra/target/debug/deps/liblog-ab5b0d19bb892557.rlib" "/root/libra/target/debug/deps/libcfg_if-53828a0f655551d3.rlib" "/root/libra/target/debug/deps/libbytes-6c51c23ae709e0eb.rlib" "/root/libra/target/debug/deps/libeither-727927a58a61947c.rlib" "/root/libra/target/debug/deps/libiovec-747900562493a58e.rlib" "/root/libra/target/debug/deps/libsha2-daa44ca7c8edd059.rlib" "/root/libra/target/debug/deps/libdigest-82e2b884ae0837aa.rlib" "/root/libra/target/debug/deps/libopaque_debug-91232e31220ebed8.rlib" "/root/libra/target/debug/deps/libfake_simd-a377148933b9cef7.rlib" "/root/libra/target/debug/deps/libblock_buffer-7c1b7187f0cd7f21.rlib" "/root/libra/target/debug/deps/libgeneric_array-197dc45e271fbeca.rlib" "/root/libra/target/debug/deps/libtypenum-40289e6fe7978280.rlib" "/root/libra/target/debug/deps/libblock_padding-2c324c5ab38df866.rlib" "/root/libra/target/debug/deps/libbyte_tools-62b89c3226c0ffaf.rlib" "/root/libra/target/debug/deps/libbyteorder-523b4452e5ae613d.rlib" "/root/libra/target/debug/deps/libclap-1dc9723e063e1874.rlib" "/root/libra/target/debug/deps/libvec_map-8fc6bda3fa9e1f60.rlib" "/root/libra/target/debug/deps/libtextwrap-203295e1fcdc708f.rlib" "/root/libra/target/debug/deps/libunicode_width-5bcfaa01daa85057.rlib" "/root/libra/target/debug/deps/libstrsim-1272bbc88b16286c.rlib" "/root/libra/target/debug/deps/libbitflags-207b97202925f99a.rlib" "/root/libra/target/debug/deps/libatty-fbc44f8b54538385.rlib" "/root/libra/target/debug/deps/liblibc-a2020e40af7086df.rlib" "/root/libra/target/debug/deps/libansi_term-d3edc7529a965868.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-554e80d52aa2568d.rlib" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-0a01681c7f544bbb.rlib" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-58768cdfc2174d1c.rlib" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-431d4739a3dd145b.rlib" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-6f0ae807e0bf325a.rlib" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-66c8af4545d589da.rlib" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-cfb33143e594d5c7.rlib" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-42e5ad7e7a0cb73c.rlib" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-da67c1aba5bef9b1.rlib" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-a01c4b87c4503fad.rlib" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-e6b0ad9835323d10.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-9f017ec8fa4a83a1.rlib" "-Wl,-Bdynamic" "-lpthread" "-lstdc++" "-lutil" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: collect2: fatal error: ld terminated with signal 9 [Killed]
          compilation terminated.

error: aborting due to previous error

error: Could not compile `secret_service`.

**Comment by wqfish** [comment]
> = note: collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.

This is likely because it ran out of memory. This is a fairly complex system consisting of many components, so it does require some resource to build.

**Comment by download8866** [comment]
@wqfish how cost is memory for libra ?

**Comment by mortedark** [comment]
Up ?

**Comment by icarter09** [comment]
@download8866 are you still experiencing this issue?
