### ISSUE TITLE
[Bug] Local validator not working

### ISSUE THREAD

**Issue by ProgramAPE** [libra/libra#1756]
# 🐛 Bug
I want a local validator :
 cargo run -p libra-swarm -- -s
the output:

Finished dev [unoptimized + debuginfo] target(s) in 3.28s
     Running `target/debug/libra-swarm -s`
Faucet account created in (loaded from) file "/tmp/2199a0c481798a039adf3a4fa5c8fb39/temp_faucet_keys"
Base directory containing logs and configs: Temporary(TempPath { path_buf: "/tmp/dff5b2b4639f474b32e47b44d9fbfd44", persist: false })

no the libra% prompt.

## System information

**Please complete the following information:**
- 
- 
-

**Comment by ProgramAPE** [comment]
when cargo run -p libra-swarm commands runs . the computer's memory consuming fast. From 0 to 6+Gb just in several minutes. 
Actually. How much memory should I to prepare for running a local node?
can someone help me ? Thanks a lot.

**Comment by tommyyama2020** [comment]
this has similarities. hope it helps
https://community.libra.org/t/error-running-local-validator-node/434

**Comment by bmwill** [comment]
libra-swarm ends up spending lots of time building the artifacts it needs to run before outputting anything but it should eventually finish building and begin running. If you still see issues please let us know.
