### ISSUE TITLE
[Consensus] Introduce SyncInfoUnverified to hide the functionality of SyncInfo

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#1762]
We are going to postpone the verification of SyncInfo until later stages inside EventProcessor. It might be dangerous and fragile to let the unverified structure to be passed around in the code because we now depend on the caller to remember that verification is required prior usage.

We could introduce a `SyncInfoUnverified` structure similar to `ProposalMsgUnverified` that we're using today.

**Comment by zekun000** [comment]
there's VerifiedEvent now, but sync info still being the only one delayed verification just for optimization
