### ISSUE TITLE
[network] Add integration tests for gossip-based discovery

### ISSUE THREAD

**Issue by bothra90** [libra/libra#1771]
The current discovery protocol doesn't have any integration tests, and is therefore susceptible to bugs which cannot be checked for in unit tests. #1770 fixes one such bug where the Discovery protocol was no longer being advertised after refactoring, and we ended up in a state where only the seed nodes were being connected to by all peers.

cc: @phlip9

**Comment by tommyyama2020** [comment]
Sorry for a silly question.  is there any sample for similar issues? i want to refer to it

**Comment by bothra90** [comment]
@tommyyama2020 : You can look at https://github.com/libra/libra/blob/master/network/src/validator_network/test.rs for other integration tests.

**Comment by nikakis** [comment]
@tommyyama2020 Can i take a look a this issue if you haven't started yet ?

**Comment by nikakis** [comment]
@bothra90 @tommyyama2020 I just opened a pull request with a first attemp regarding the discovery protocol integration tests -> https://github.com/libra/libra/pull/2138

**Comment by davidiw** [comment]
Largely handled by smoketests, so not critical.
