### ISSUE TITLE
[consensus] Add signature verification counters and tests

### ISSUE THREAD

**Issue by aching** [libra/libra#1775]
Malicious validators can attempt to force honest validators to waste lots of CPU on signature verifications - either on old messages or invalid ones.  This can slow down the system and is a vector of attack.  It is also possible that an accidental code change causes the number of signature checks to rise accidentally.  We should have counters to help detect when either of these circumstances occur and unit tests to check when unexpected verifications are added.

This issue proposes counters for TC/QC/SyncInfo/VoteData/LedgerInfo signature checks successful and failed.  Additionally there should be unittests to verify expected verifications for each structure and in groups of operations (e.g. a vote aggregator).

**Comment by rentenmark** [comment]
You could start tracking system wide signatures by bumping a `lazy_static` `AtomicU64` [here](https://github.com/libra/libra/blob/master/crypto/crypto/src/traits.rs#L161) and [here](https://github.com/libra/libra/blob/master/crypto/crypto/src/traits.rs#L169)

Not sure how you would want to expose it though.

Would this be an acceptable strategy?

**Comment by zekun000** [comment]
we have general error rate counter which includes verification failure
