### ISSUE TITLE
compare move and more ir

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#1779]
I understand move is still in very early stage.
If I start to develop on libra, should I use move or move ir?
What's the main syntax difference between them?

If I start with move ir, will libra develop some tool to convert it to move after move matures.

george wu

**Comment by bob-wilson** [comment]
The Move source language and the Move IR both compile down to Move bytecode, so you can use either one. We developed the Move IR as a temporary solution until the Move source language was ready for use. We're getting closer to that, but for right now, the Move IR is still more stable. The main difference is that the source language is intended to have a syntax that is easier to use. We're still iterating on some of those differences, so I won't elaborate on them here. These kinds of questions would be more appropriate for the discussion forums (https://community.libra.org) so if you have follow ups, please ask there.
