### ISSUE TITLE
[Bug] Validator can not restart repeating [state sync] request next chunk

### ISSUE THREAD

**Issue by andll** [libra/libra#1782]
Log of node that is failing to start:
>D1118 20:27:43.939242 140195592664832 state-synchronizer/src/coordinator.rs:544] [state sync] request next chunk. peer_id: 557295fc, known_version: 2279, timeout: 0

https://gist.github.com/4c2b2f4918f7ee312979b4ef03b705d6

First suspect is https://github.com/libra/libra/pull/1743

**Comment by dmitri-perelman** [comment]
Transaction size has grown >10x to 6.79KB, so 1000 txns chunk is larger than the 4MB GRPC limit.

**Comment by dmitri-perelman** [comment]
The immediate problem is solved with a workaround of reducing the state synchronization chunk size, opened issues for a proper solution.
