### ISSUE TITLE
Docker image build scripts can't be executed from within their directories

### ISSUE THREAD

**Issue by philippgille** [libra/libra#179]
This is only a minor issue and not really a bug, but I wanted to create an issue anyway to be able to properly link to it in a PR.

## To reproduce

```bash
git clone https://github.com/libra/libra.git
cd libra/docker/client/
./build.sh
```

Leads to:

```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /path/to/libra/docker/client/docker: no such file or directory
```

## Expected Behavior

I think the build scripts should be able to be executed from anywhere, especially from within their directories.

## System information

**Please complete the following information:**
- Libra master branch, commit bd8e6dc5434d39bd6b56a3502076353d0787a7ef
- Ubuntu 16.04.6 LTS

## Additional context

I've got a fix in my fork and will create a PR linking to this issue.

**Comment by huitseeker** [comment]
Fixed in 7898828
