### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Zeebrow** [libra/libra#184]
# 🐛 Bug

## To reproduce

** Code snippet to reproduce **
```
On CentOS 7 18.10 minimal:
yum update
yum install git
git clone https://github.com/libra/libra.git && cd libra
./scripts/dev_setup.sh
```

** Stack trace/error message **
```
Installing Go......
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: reflector.westga.edu
 * extras: reflector.westga.edu
 * updates: mirror.dal.nexril.net
No package golang available.
Error: Nothing to do
```

## Expected Behavior

1) Go is installed
2) On failure, the script tells you what has been installed and what has not, before exiting.

## System information

**Please complete the following information:**
- 
- Rust Version 1.35.0
- OS: CentOS 7 Linux 3.10.0-957.el7.x86_64

## Additional context
epel-release was not installed

**Comment by wayne-china** [comment]
Update your YUM Install other YUM source.

**Comment by icarter09** [comment]
@Zeebrow did @wayne-china suggestion fix your issue?

**Comment by Zeebrow** [comment]
Sorry for the delay.

@wayne-china @icarter09 Yes, yum install epel-release before cloning and running ./scripts/dev_setup.sh solved the issue.

**Comment by icarter09** [comment]
@Zeebrow no worries! Thanks for following up on the issue.
