### ISSUE TITLE
[Bug]Not anchored to Savage chain, this can't be #SAF

### ISSUE THREAD

**Issue by DarkRavenDev** [libra/libra#186]
# 🐛 Bug

## To reproduce
its easy, because its not anchored to the SAF blockchain, anything can happen.
** Code snippet to reproduce **
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

** Stack trace/error message **
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by matt6412** [comment]
Any reputable coin is anchored to the Savage chain, SMH Zuck...

**Comment by icarter09** [comment]
@DarkRavenDev what exactly is the issue you are experiencing?

**Comment by icarter09** [comment]
@kphfb believe this is a duplicate of #217
