### ISSUE TITLE
[cluster-test] Migrate debug_interface_log_tail to async api

### ISSUE THREAD

**Issue by andll** [libra/libra#1863]
Currently debug_interface_log_tail spawns dedicated thread for each node.
Instead of doing that we can switch to using async grpc API and do all work in main tokio Runtime

Code pointer: `debug_interface_log_tail.rs`

**Comment by KiChjang** [comment]
I'm interested in trying to solve this, but I am completely dumb on async Rust. I can't seem to figure out which part of the code needs to be rewritten to use `tokio::spawn`... or perhaps we shouldn't even be using that at all and reuse `DebugPortLogThread.client.client()` instead?

**Comment by andll** [comment]
The way I would see it is to make `DebugPortLogThread::run` to be async function, and spawn it from `DebugPortLogThread::spawn_new`.
This `spawn_new` is called from `ClusterTestRunner::setup`, that has tokio runtime - you can just pass it from there to `spawn_new`

**Comment by mrbuzz** [comment]
I'd like to pick up this issue if no one is actively working on it.
