### ISSUE TITLE
We need a coin standard for libra blockchain similar to ERC20

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#187]
When I read the coin code for libra, it  says:

    // A resource that grants access to `LibraCoin.mint`. Only the Association account has one.
    resource MintCapability {}

Basically it is a system coin, and it is not available for common developer to issue or mint a coin.

I believe a standard similar to ERC20 on ethereum is important so that every one is able to issue a coin on the libra chain.

**Comment by TomHamer** [comment]
I think this could be seen as a sub-issue of having user defined smart contracts, which according to the white paper is on the backlog. Once there are user defined smart contracts then we can have any number of standards for tokens. 

The white paper claims: "Transactions are based on predefined and, in future versions,
user-defined smart contracts in a new programming language called Move." If we can push through the user defined smart contract before launch I think that would be really helpful.

**Comment by aihuawu** [comment]
I believe the smart contract is already there. Just you have to use move mvir language instead of
move source language.  I agree it is better to have the high level language be available as soon as possible even if it is just alpha version. mvir is kind of low to develop bigger application.

**Comment by TomHamer** [comment]
I just had some responses to my other question - user defined contracts are available for local nodes, just not in the current testnet. We should definitely start work on this - has anyone deployed an ERC20 contract and had that work on their local environment?

**Comment by LeoBluuee** [comment]
@TomHamer Yes, the guys from eToken already made something similar to an ERC-20 compliant token.

For more information, they posted here first: https://community.libra.org/t/implemented-basic-token-using-move-ir/526
And the repository: https://github.com/etoroxlabs/etoken-libra

**Comment by sunrye** [comment]
> I just had some responses to my other question - user defined contracts are available for local nodes, just not in the current testnet. We should definitely start work on this - has anyone deployed an ERC20 contract and had that work on their local environment?

Hi, can you share the idea about how to publish user define module on local node?
