### ISSUE TITLE
[Consensus] Fix round interval calculation right after state-sync

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#1873]
Accidentally noticed that the round interval calculation doesn't properly account for state synchronization.
Today the round interval is calculated by the pacemaker based on the information provided by consensus about the highest commit. The motivation is to determine the interval based on the gap between the current round and the highest committed round.
When consensus runs state synchronization, its highest committed round is upgraded, but pacemaker is not going to be notified about that: as a result the interval right after state sync is set up to a the highest possible value.

**Comment by zekun000** [comment]
it's already fixed today, sync_up would trigger process_certificate
