### ISSUE TITLE
[Bug] Testnet faucet stuck on majorStatus 4017

### ISSUE THREAD

**Issue by olibaron** [libra/libra#1876]
# 🐛 Bug

It seems the faucet service of Testnet is stuck in a majorStatus 4017 error. All mint transactions are failing

## To reproduce

Mint an amount for any address

## Expected Behavior

A majorStatus 4001 is returned

## Current behaviour 

A majorStatus 4017 is returned

## Extra information 

Since transaction version 111196 the faucet service is returning majorStatus 4017

**Comment by davidiw** [comment]
Likely resolved, please reopen otherwise.
