### ISSUE TITLE
User Defined Smart Contracts

### ISSUE THREAD

**Issue by TomHamer** [libra/libra#189]
# 🚀 Feature Request

User defined smart contracts will be extremely useful for users of the Libra platform, similarly to how they have found great use in extending Ethereum from just a cryto currency to a distributed computer which has many uses. 

In the white paper it says user defined smart contracts will be "eventually" implemented - does this mean they will be implemented in the coming months before launch? 

If someone were to do a pull request for the code for user defined smart contracts in the next few months would it be considered/accepted?

**Comment by aihuawu** [comment]
I believe the smart contract is already there. Just you have to use move mvir language instead of
move source language.  I agree it is better to have the high level language be available as soon as possible even if it is just alpha version. mvir is kind of low to develop bigger application.

**Comment by TomHamer** [comment]
@aihuawu thanks for your response. Is it possible to deploy a mvir contract on the testnet currently? On the documentation it says "Custom Move programs are not supported in the initial testnet release, but these features are available for you to try out locally." 

Is there any way to use mvir to deploy a custom smart contract to the main testnet?

**Comment by lucasverra** [comment]
> Is there any way to use mvir to deploy a custom smart contract to the main testate?

no, only to your local node. src here : https://community.libra.org/t/publishing-modules/118/2?u=lucas

<img width="924" alt="image" src="https://user-images.githubusercontent.com/11323803/59968963-484f1300-9543-11e9-9f9f-7a0a4efc2a1b.png">

**Comment by TomHamer** [comment]
thanks for the feedback, I got confused by the documentation
