### ISSUE TITLE
Confused naming in examples

### ISSUE THREAD

**Issue by LingTian** [libra/libra#190]
# 🚀 Feature Request

In the Move testsuite exmaples, there is one example called simple.mvir. Though there is a comment // check: VerificationError inside. However please name it checkVerificationError or something. 

## Motivation

It is confusing to run an example called simple and it cannot complie. I do double check of all my environment because I think there must be some mistakes in the setup process that why I cannot compile my first move script called simple.mvir

## Pitch

So I suggest to change the name of the script if possible. It may confused the future devs.

**Comment by davidiw** [comment]
feel free to open new issues as the framework has improved vastly since this issue was filed.
