### ISSUE TITLE
make Libra RPC available as soon as possible

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#192]
Once you make RPC available, we can develop dapp with libra.

**Comment by lucasverra** [comment]
there is already gRPC implementation. Ppl are using it to create wrappers like this one https://community.libra.org/t/libra-grpc-the-libra-client-for-javascript-lovers/691?u=lucas

**Comment by egorsmkv** [comment]
Or like this one https://github.com/egorsmkv/libra-grpc-py

**Comment by kphfb** [comment]
Please take a look at the gRPC interfaces provided.  I believe those should meet the needs you require

**Comment by perfectmak** [comment]
Or you could also check this one out: https://www.npmjs.com/package/libra-core

**Comment by philippgille** [comment]
Or for Go: https://github.com/philippgille/libra-sdk-go

Which also includes the Go code generated by Libra's proto files in the `rpc` subpackage.
