### ISSUE TITLE
[language] Beginner paper cuts when writing Move IR

### ISSUE THREAD

**Issue by phlip9** [libra/libra#1922]
As I was recently writing a bunch of Move IR code for the first time ever, I decided to note down some of the paper cuts and stumbling blocks I experienced. Hopefully, my experience as a Move n00b can help improve the on-ramping process for other Move n00bs.

1. When I first encountered `borrow_global` and friends, I wondered what would happen if you tried to `borrow_global` a resource that didn't exist. As I later found out, it aborts the transaction, which makes sense. We should probably include this in the Move tutorial.

2. The meaning of `UnboundTypeParameter` error was not super clear.

3. In general, I wish compiler errors showed the original line number. It seems that the bytecode verifier doesn't know about line numbers in the input IR?

4. Likewise, human-readable error strings would be nice.

5. There wasn't much documentation on novel Move syntax and their meaning. For example, it's not clear initially what `acquires MyResource` means, though I eventually discovered this was necessary for `borrow_global` and friends by asking some people.

6. It seems you can't return a struct ref in a public function? that acquires? Not sure why...

7. I didn't realize you needed to rebuild genesis after modifying stdlib modules. It also wasn't immediately obvious how to build genesis.

8. I'm still not sure how the ref/move/copy semantics work here, since it seems slightly different than rust. For example, in the [`validator_set/register_validator.mvir`](https://github.com/libra/libra/blob/master/language/functional_tests/tests/testsuite/validator_set/register_validator.mvir#L48) functional test:

```rust
let config: ValidatorConfig.Config;

// here, the variable config: ValidatorConfig.Config, returned "by-value".
// Rust semantics would say this is "moved" into local config variable.
config = ValidatorConfig.config(get_txn_sender());
assert(ValidatorConfig.consensus_pubkey(&config) == h"10", 11);

// this changes a field in the underlying resource
ValidatorConfig.rotate_consensus_pubkey(h"70");

// but then the change somehow shows up in our local config ref
// => move is returning by ref??
assert(ValidatorConfig.consensus_pubkey(&config) == h"70", 12);
```

9. You have to run `script/circle_validate_configs.sh` after modifying genesis. Fortunately, it looks like this script is run in CI.

10. I'm still not sure what the `JOIN_FAILURE` error is (from `bytecode-verifier`) and why the second case triggers it but the last doesn't:

```rust
let validator_set_ref: &mut Self.ValidatorSet;
let validators_vec_ref: &mut Vector.T<Self.ValidatorInfo>;
let validator_set_changed: bool;

// snip

// SUCCESS

if (move(validator_set_changed)) {
    LibraAccount.emit_event<Self.ValidatorSetChangeEvent>(
        &mut move(validator_set_ref).change_events,
        ValidatorSetChangeEvent {
            new_validator_set: *move(validators_vec_ref),
        },
    );
    return;
} else {
    return;
}

// ERROR: JOIN_FAILURE

if (move(validator_set_changed)) {
    LibraAccount.emit_event<Self.ValidatorSetChangeEvent>(
        &mut move(validator_set_ref).change_events,
        ValidatorSetChangeEvent {
            new_validator_set: *move(validators_vec_ref),
        },
    );
}

return;

// SUCCESS

if (move(validator_set_changed)) {
    LibraAccount.emit_event<Self.ValidatorSetChangeEvent>(
        &mut copy(validator_set_ref).change_events,
        ValidatorSetChangeEvent {
            new_validator_set: *copy(validators_vec_ref),
        },
    );
}

return;
```

11. Why does `borrow_global<MyResource>` not require `Self.MyResource`? The syntax feels inconsistent with other generics requiring `Self.`.

**Comment by bob-wilson** [comment]
Philip, thanks for writing these things down. I know that a few people looked at your feedback earlier.

Since we now have the Move source language, the Move IR is only targeted for internal testing purposes, and I suspect most of these problems are less important.

Sam, Todd: do you see anything here that we need to address in documentation for Move? Any other reasons to keep this open?

**Comment by sblackshear** [comment]
I think we can close this; we have looked through all of the feedback here and either fixed  the corresponding bug or addressed the issue in the source lang.
