### ISSUE TITLE
Without move_to, What's the best pattern to transfer assets to other people? earmark?

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#194]
Without move_to, you are unable to send an asset to someone unless she has the asset.
you can only modify other people's assets, you can't create the assets.

This pattern is totally different from what etherum ERC20 does.
What's the best pattern to transfer assets to other people?
Just use the earmark pattern in the example?
What's the guide line?

**Comment by sblackshear** [comment]
The pattern suggested in the `Earmark` example is one way. This discourse [post](https://community.libra.org/t/move-to-sender-but-with-a-specified-address/201) suggests a technique for fungible assets, which I'll partially quote here:

```
module CustomCoin {
  resource T { value: u64 }

  public zero(): R#Self.T {
    return T { value: 0 };
  }

  // anyone can publish a coin with value zero
  public publish() {
    let zero_coin: R#Self.T;

    zero_coin = Self.zero();
    move_to_sender<T>(move(zero_coin));

    return;
  }

  public deposit(coin: R#Self.T, recipient: address) {
    // do BorrowGlobal<T>(move(recipient)), call logic for merging T's
  }

  // ... remainder of the logic for the custom coin, including splitting/merging T's
}
```
