### ISSUE TITLE
[Bug] Flaky test: chained_bft::chained_bft_smr_test::reconfiguration_test

### ISSUE THREAD

**Issue by vgao1996** [libra/libra#1979]
# 🐛 Bug
This test seems to be flaky. It failed on CI when I submitted my PR (#1978), but a subsequent bors-libra run was successful. Here's the log:
https://circleci.com/gh/libra/libra/22164#tests/containers/2
```
test chained_bft::chained_bft_smr_test::secondary_proposers ... ok
test chained_bft::chained_bft_smr_test::aggregate_timeout_votes ... ok
test chained_bft::chained_bft_smr_test::chain_with_nil_blocks ... ok
test chained_bft::chained_bft_smr_test::reconfiguration_test ... test chained_bft::chained_bft_smr_test::reconfiguration_test has been running for over 60 seconds

Too long with no output (exceeded 10m0s): context deadline exceeded
```

## To reproduce
Not sure if this can be easily reproduced.

## Expected Behavior
Test should pass.

**Comment by aching** [comment]
This happened again recently - https://circleci.com/gh/libra/libra/24207#tests/containers/2
