### ISSUE TITLE
Cargo test  Error

### ISSUE THREAD

**Issue by flydragon2018** [libra/libra#2042]
# 🐛 Bug

I followed :
$ git clone https://github.com/libra/libra.git
$ cd libra
$ ./scripts/dev_setup.sh
$ source ~/.cargo/env
$ cargo build
$ cargo test

everything fine but the last step: cargo test,
I got this error:

Compiling storage-service v0.1.0 (/home/zzl/libra/storage/storage-service)
error[E0432]: unresolved import `libradb::test_helper`
  --> storage/storage-service/src/storage_service_test.rs:12:14

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by bmwill** [comment]
Due to cargo's feature unification bug you'll need to run cargo xtest in order to run tests with no compile errors.
