### ISSUE TITLE
[Feature Request] Allow querying for individual transactions

### ISSUE THREAD

**Issue by taarushv** [libra/libra#206]
# 🚀 Feature Request
Currently, there's no way to query information about a particular transaction unless the tx is initiated by one of the accounts on the client (querying via sequence numbers). Query command to lookup individual transactions by the transaction id (public_key?) would be useful to integrate tools for the ecosystem unless there are plans to make a full-fledged API for the chain.

**Comment by kphfb** [comment]
Hi @taarushv, there are a few ways to query for transactions.

To query by a specific version for a single transaction:
q txn_range 5523 1 true

Query for a transaction at a specific sequence number for any account (even if it isn't stored locally):
q ts ff403748484833b95ceb4d9ca4c7f887fa5d57a505ae844aebd825208367a00c 0 true

Get all events sents from this account:
q ev ff403748484833b95ceb4d9ca4c7f887fa5d57a505ae844aebd825208367a00c sent 0 true 10

**Comment by taarushv** [comment]
@kphfb is there any way to retrieve info based on the transaction public key rather than account? Say for cases when you know a transaction public key but don't know the parties involved in the transaction.

**Comment by kphfb** [comment]
Can you specify what exactly you mean by "transaction public key"?  Are you asking about the hash of the transaction?  The sender's public key?

**Comment by taarushv** [comment]
@kphfb The hash of the transaction. For example "bc953e76f50b50969cf6676efe27aee027c4d0eaf5d3e9a2631d81bbd646a8db" this is a hash of a peer to peer transaction. The ability to lookup tx info based on this info would be useful in building a block explorer without having to store and looking up all blocks.

**Comment by kphfb** [comment]
Ok, understood.  I'll re-open the feature request then

**Comment by davidiw** [comment]
I don't see how this would be particularly feasible without a substantial change to the storage layer or by creating some sort of index. It is probably better that it is created externally.

**Comment by taarushv** [comment]
@davidiw fair enough, I just want to highlight that not having a method that lets you query tx data by its hash natively would be a pain point for developers who build on top of libra. 

For example, if I were to build a block explorer or a dashboard for analytics/the mempool, apart from already running the libra client, I would have to iterate through all blocks mined so far and store the transactions by their hashes in a database (to query it whenever I want). This can quickly get expensive and is definitely time consuming to maintain. I hope libra offers an API service akin to Infura + web3 for these queries or building it from scratch can get prohibitive. 

For reference, both bitcoin ([getrawtransaction](https://github.com/bitcoin/bitcoin/blob/d692d192cda37fda6359ad0736b85de20383db73/src/rpc/rawtransaction.cpp#L70)) and go-ethereum ([GetRawTransactionByHash](https://github.com/ethereum/go-ethereum/blob/c1544423d655f540b55bb6ec0e7167dad9683c42/internal/ethapi/api.go#L1389)) offer an API to query transaction data by the hash.
