### ISSUE TITLE
compile fail

### ISSUE THREAD

**Issue by zhongxigong** [libra/libra#207]
error: failed to run custom build command for `network v0.1.0 (~/souce/study/libra/network)`

Caused by:
  process didn't exit successfully: `~/souce/study/libra/target/debug/build/network-267ca6ea5a198f61/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/network.proto
cargo:rerun-if-changed=src/proto/mempool.proto
cargo:rerun-if-changed=src/proto/consensus.proto

--- stderr
thread 'main' panicked at 'protoc: Custom { kind: NotFound, error: StringError("failed to spawn `\"protoc\" \"--version\"`: No such file or directory (os error 2)") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by jayphbee** [comment]
@zhongxigong You may not have protobuf tool chain installed or have older version

**Comment by zhongxigong** [comment]
> @zhongxigong You may not have protobuf tool chain installed or have older version

You are right.Thanks a lot

**Comment by otembajelle** [comment]
Today I had the same issue. I did install protobuf but that did not work out for me.
