### ISSUE TITLE
A standalone functionality to generate a genesis LedgerInfo

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#2082]
A waypoint for genesis is constructed from the genesis LedgerInfo.
Today in order to generate a LedgerInfo for genesis one needs to actually run a node (full node or a validator): the constructor of executor is then going to execute a genesis txn and commit the resulting LedgerInfo.
The goal of this issue is to generate a genesis LedgerInfo in a standalone fashion: we need to generate a Waypoint and put it in the configs **before** we even start the node.

In order to do that we should move out the init_genesis functionality out of the executor: the function should have some "empty" implementation for the `StorageRead` and execute a given `genesis_txn`.

Setting it up as a separate issue, serving the bigger purpose of the waypoint issue described in #1384.

**Comment by zekun000** [comment]
https://github.com/libra/libra/pull/3528
