### ISSUE TITLE
[libra_channel] Use `NonZeroUsize` instead of assert for usize that should be > 0

### ISSUE THREAD

**Issue by bothra90** [libra/libra#2084]
Currently the requirement that `max_queue_size_per_key` in `PerKeyQueue` is greater than 0 is enforced at run-time using an `assert` statement. We can instead enforce this at compile-time using the standard library's `NonZeroUsize` type.

**Comment by nikakis** [comment]
Hello! Can i take up this?

**Comment by ankushagarwal** [comment]
@nikakis Sure!

**Comment by nikakis** [comment]
Great! I will start asap.

**Comment by nikakis** [comment]
I just opened a PR. https://github.com/libra/libra/pull/2113
Thanks !
