### ISSUE TITLE
 run start_cli_testnet.sh failed on CentOS 6

### ISSUE THREAD

**Issue by ytgcljj** [libra/libra#209]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discourse](https://community.libra.org)
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: Could not compile `libc`.
warning: build failed, waiting for other jobs to finish...
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: Could not compile `syn`.
warning: build failed, waiting for other jobs to finish...
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: Could not compile `proc-macro2`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by khetanvallurupalli** [comment]
Please make sure you have enough space on your instance volume. I would suggest 12 to 15 GB of volume. That solved my issue.

**Comment by wqfish** [comment]
Hi @ytgcljj, it looks like you need to install a C compiler like `gcc`.

**Comment by DanielKellerM** [comment]
sudo apt install gcc-multilib

**Comment by raguiar2** [comment]
For CentOS, the default installer is yum, not apt. try `yum install gcc-multilib`

**Comment by bmwill** [comment]
The external dependencies needed to build Libra have been simplified and should only require Rust now so this shouldn't be an issue anymore on master. If it is, please let us know.
