### ISSUE TITLE
[Bug] ./scripts/dev_setup.sh on Ubuntu 18.04: "protoc version is too old. Update protoc to 3.6.0 or above. Abort"

### ISSUE THREAD

**Issue by AronVanAmmers** [libra/libra#21]
# 🐛 Bug

When running `./scripts/dev_setup.sh` on Ubuntu 18.04 (Vagrant VM `ubuntu/bionic64`, which I think is representative for other Ubuntu 18.04 installs), the script fails with:

```
protoc version is too old. Update protoc to 3.6.0 or above. Abort
```

I would expect this to complete successfully on the latest Ubuntu LTS release.

## To reproduce

* Create a fresh Ubuntu 18.04 VM with Vagrant: `vagrant init ubuntu/bionic64 && vagrant up`
* Follow instructions from https://developers.libra.org:
 * `git clone https://github.com/libra/libra.git && cd libra`
 * `./scripts/dev_setup.sh`

** Stack trace/error message **
After successfully installing many components:
```
protoc version is too old. Update protoc to 3.6.0 or above. Abort
```

## Expected Behavior

Script completes successfully

## System information

Libra Version: latest version cloned from GitHub
Computer OS: Ubuntu 18.04 in a Vagrant VM `ubuntu/bionic64`

**Comment by nwilson1412** [comment]
I had the same issue, you can manually install Protoc (As seen here: https://askubuntu.com/questions/1072683/how-can-i-install-protoc-on-ubuntu-16-04)

You may need to remove lines 120-129 in `./scripts/dev_setup.sh` as after you install Protoc manually, the check error outs:
`   120  if [[ -f /etc/debian_version ]]; then
   121          PROTOC_VERSION=`protoc --version | cut -d" " -f2`
   122          REQUIRED_PROTOC_VERSION="3.6.0"
   123          PROTOC_VERSION_CHECK=`dpkg --compare-versions $REQUIRED_PROTOC_VERSION "gt" $PROTOC_VERSION`
   124
   125          if [ $? -eq "0" ]; then
   126                  echo "protoc version is too old. Update protoc to 3.6.0 or above. Abort"
   127                  exit 1
   128          fi
   129  fi
`

**Comment by 0-o-0** [comment]
Unfortunately, apt-get only has protoc 3.0. Please follow the instructions from protobuf to update it to 3.6.0 or above. https://github.com/protocolbuffers/protobuf/tree/master/src

**Comment by maxb14** [comment]
Here is a simple solution to solve this bug :

**Mac OS :**
`brew install protobuf`
`brew upgrade protobuf`

**Linux :**
`PROTOC_ZIP=protoc-3.7.1-osx-x86_64.zip`
`curl -OL https://github.com/google/protobuf/releases/download/v3.7.1/$PROTOC_ZIP`
`sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc`
`sudo unzip -o $PROTOC_ZIP -d /usr/local include/*`
`rm -f $PROTOC_ZIP`

And finally run :
`./scripts/dev_setup.sh`
`./scripts/cli/start_cli_testnet.sh`

**Comment by iamonuwa** [comment]
@maxb14 solution worked fine for me

**Comment by damianoazzolini** [comment]
With [this solution]( https://askubuntu.com/questions/1072683/how-can-i-install-protoc-on-ubuntu-16-04/1072684 i) was able to install it.

**Comment by AronVanAmmers** [comment]
Thanks @maxb14. The updated version below (with corrected binary for Linux) works for me on Ubuntu 18.04.

```
PROTOC_ZIP=protoc-3.8.0-linux-x86_64.zip
curl -OL https://github.com/google/protobuf/releases/download/v3.8.0/$PROTOC_ZIP
sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
sudo unzip -o $PROTOC_ZIP -d /usr/local include/*
rm -f $PROTOC_ZIP
```

I suggest the Libra devs add detection the presence of the version of `protoc` and install the one for the correct architecture (32/64 bit) within `dev_install.sh`.

**Comment by maraoz** [comment]
Works! Note that the last command should be `sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'` if your shell is `fish`

**Comment by realityenigma** [comment]
> Here is a simple solution to solve this bug :
> 
> **Mac OS :**
> `brew install protobuf`
> `brew upgrade protobuf`
> 
> **Linux :**
> `PROTOC_ZIP=protoc-3.7.1-osx-x86_64.zip`
> `curl -OL https://github.com/google/protobuf/releases/download/v3.7.1/$PROTOC_ZIP`
> `sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc`
> `sudo unzip -o $PROTOC_ZIP -d /usr/local include/*`
> `rm -f $PROTOC_ZIP`
> 
> And finally run :
> `./scripts/dev_setup.sh`
> `./scripts/cli/start_cli_testnet.sh`

The PROTOC_ZIP variable needs to be
PROTOC_ZIP=protoc-3.7.1-linux-x86_64.zip

the current variable is pointing to an OSX binary.

**Comment by modavidc** [comment]
For Linux, the 

> > Here is a simple solution to solve this bug :
> > **Mac OS :**
> > `brew install protobuf`
> > `brew upgrade protobuf`
> > **Linux :**
> > `PROTOC_ZIP=protoc-3.7.1-osx-x86_64.zip`
> > `curl -OL https://github.com/google/protobuf/releases/download/v3.7.1/$PROTOC_ZIP`
> > `sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc`
> > `sudo unzip -o $PROTOC_ZIP -d /usr/local include/*`
> > `rm -f $PROTOC_ZIP`
> > And finally run :
> > `./scripts/dev_setup.sh`
> > `./scripts/cli/start_cli_testnet.sh`
> 
> The PROTOC_ZIP variable needs to be
> PROTOC_ZIP=protoc-3.7.1-linux-x86_64.zip
> 
> the current variable is pointing to an OSX binary.

For Ubuntu 18.04 this is the solution. It's worked.

**Comment by c-edw** [comment]
Few notes here:

- The script doesn't give `protoc` version warnings on Fedora/yum-based distros (this may thoroughly confuse some people!)
- The `protoc` version on Fedora is outdated anyway, so I had to use one of the solutions above. I'm closing #53 since this effectively makes it pointless.

I'd say we should just make this the default and grab `protoc` directly from Google's repository. The binary can be put into a gitignored local directory.

**Comment by richbodo** [comment]
Thanks @maxb14.

Made a gist for deb 9 to upgrade to 3.7.1:

https://gist.github.com/richbodo/08974a4a818aa047cb0e3cb429c24b95

**Comment by ericnakagawa** [comment]
Hi folks, thanks for chiming in here. These issues should be resolved by code in `master`. If not, please tag me and I'll follow up.
