### ISSUE TITLE
Error Minting Coins gives (error 429 too many requests)

### ISSUE THREAD

**Issue by khetanvallurupalli** [libra/libra#211]
# 🐛 Bug

When I tried to Mint coins for different accounts I see this error.

To report a security issue, please email security@libra.org.  -->

## To reproduce

* Create multiple accounts
* Try to mint coins to those wallets one after other

I am adding Error snippet:
![image](https://user-images.githubusercontent.com/32341967/60020074-44171880-965d-11e9-8acf-7864fb6a0c46.png)

**Comment by icarter09** [comment]
@khetanvallurupalli that's pretty interesting. A couple of questions:
 1. How many accounts did you create?
 2. Were you minting the coins through a script or you were just typing the `mint` cmd each time?
 3. Were you able to successfully mint any coins?

**Comment by bmwill** [comment]
This is expected behavior. If you're trying to issue too many requests to the system you'll get a 429 response indicating that you're being rate limited.  Just try to wait a minute or two then try to issue more requests.
