### ISSUE TITLE
[libra_channel] Make libra_channel::Sender cloneable even if message type M is not

### ISSUE THREAD

**Issue by bothra90** [libra/libra#2122]
Multiple senders running in different futures/threads should be able to send on a libra_channel.

**Comment by bothra90** [comment]
Looks like this was already implemented by @christinacelee.

**Comment by bothra90** [comment]
explicitly implementing `Clone` for `libra_channel::Sender` is better than `#[derive(Clone)]` because the latter requires all generic types to also be `Clone`able.

**Comment by nikakis** [comment]
Hello! Can I take a look at this ?

**Comment by bothra90** [comment]
@nikakis : Sorry, I already had this in progress when I filed the issue. Will forward other items your way if you're interested.
