### ISSUE TITLE
[Bug] Inconsistency between storage DB and consensus DB

### ISSUE THREAD

**Issue by aching** [libra/libra#2153]
# 🐛 Bug

Node fails to come up - https://gist.github.com/aching/71e495c396c8f5be8538d7fb332af4c3
It looks like storage and consensus can't agree on a block to resume from.

**Comment by lightmark** [comment]
@zekun000 do you want close it since it seems not a bug?

**Comment by zekun000** [comment]
state sync assumes no empty blocks while the bug fixed by https://github.com/libra/libra/pull/2039 may cause metadata txn fail and result in empty blocks and inconsistency between storage and consensus.
