### ISSUE TITLE
[Bug] Cannot run validator locally due to missing directory

### ISSUE THREAD

**Issue by princeulrich2** [libra/libra#2155]
# 🐛 Bug

I have been trying unsuccessfully to run validator nodes locally on Ubuntu 18.04 with docker by running the docker/validator/run.sh command but it fails because the script refers to a directory which does not exist(/../../terraform/validator-sets/dev/). This directory was removed in commit acc5798084cd961ef7ead3abca5d8e24bccd1a80 back in August 2019. I reverted to that commit and even previous commits but the build failed due to compatibility issues(for example with rust). So I am wondering how everyone else is able to run validator nodes locally without encountering this issue? Please let me know if I am missing something.

## To reproduce
I did the following:

1. Download and install Docker.
2. From the top level directory, run docker/validator/build.sh
3. From the top level directory, run docker/mint/build.sh
4. To test the validator image locally, run docker/validator/run.sh
This is where it fails.

**Stack trace/error message**
```
$ ./docker/validator/run.sh
+ IMAGE=libra_e2e:latest
+ dirname ./docker/validator/run.sh
+ CONFIGDIR=./docker/validator/../../terraform/validator-sets/dev/
+ sed s,SEED_IP,172.18.0.10, ./docker/validator/../../terraform/validator-sets/dev//seed_peers.config.toml
sed: can't read ./docker/validator/../../terraform/validator-sets/dev//seed_peers.config.toml: No such file or directory
+ SEED_PEERS=

```

## Expected Behavior

Docker container running the validator node image started

## System information

**Please complete the following information:**
- Libra Version: latest from master branch
- Rust Version: 1.39.0
- Computer OS: Ubuntu 18.04.3 LTS

**Comment by davidiw** [comment]
We should delete the run.sh from docker/validator. Instead, continue the process by building the docker/validator-dynamic and using the run script within there.

**Comment by princeulrich2** [comment]
Thanks for your reply @davidiw , I appreciate. I was able to build and run the validator nodes using the validator-dynamic scripts. I am also able to build the mint image but I cannot run it with
  `docker/mint/run.sh` because of the same issue, the directory libra/terraform/validator-sets/dev/ does not exist. consequently I cannot add coins to the accounts which I created... could you please suggest an alternative to this? Is there a way to run the mint container differently?

**Comment by milonite** [comment]
@princeulrich2 did you find a solution for this? 
Btw @davidiw  in validator-dynamic there are some seems unused scripts (build.sh)

when I try to run docker-run-dynamic I get:

> + declare -a params
> + '[' -n '' ']'
> + '[' -n '' ']'
> + '[' -n '' ']'
> + '[' -n '' ']'
> + '[' -n '' ']'
> + '[' -n '' ']'
> + '[' -n '' ']'
> + '[' -n '' ']'
> + /opt/libra/bin/config-builder validator --data-dir /opt/libra/data/common --output-dir /opt/libra/etc/
> docker/validator-dynamic/docker-run-dynamic.sh: line 33: /opt/libra/bin/config-builder: No such file or directory
>

**Comment by davidiw** [comment]
> Thanks for your reply @davidiw , I appreciate. I was able to build and run the validator nodes using the validator-dynamic scripts. I am also able to build the mint image but I cannot run it with
> `docker/mint/run.sh` because of the same issue, the directory libra/terraform/validator-sets/dev/ does not exist. consequently I cannot add coins to the accounts which I created... could you please suggest an alternative to this? Is there a way to run the mint container differently?

This is unfortunate, let me flag a couple people and see if we cannot fix this... but the short stick of it is that this should likely be using config-builder too, I am confused as to why it is not.

**Comment by davidiw** [comment]
@milonite, this seems unrelated to the issue above and I should have probably closed it and asked @princeulrich2 to open a new issue.

Could you open a new issue, feel free to assign to me, detailing how you built your docker container? Because I don't see any reason for your error otherwise.

**Comment by princeulrich2** [comment]
@milonite yes I was able to run the validator nodes using the validator dynamic scripts:
docker/validator/build.sh
docker/validator-dynamic/build-dynamic.sh
@davidiw indeed I will close this bug

**Comment by milonite** [comment]
@princeulrich2  Thanks, may I ask you to post the output of docker/validator/build.sh and how do you connect the cli to it?  eg.cargo run --bin cli -- -u http://localhost:6180
