### ISSUE TITLE
Why not use LCS to serialize transaction_info and ledger_info to storage?

### ISSUE THREAD

**Issue by yuan-xy** [libra/libra#2166]
# 🚀 Feature Request

I suggest using LCS to serialize transaction_info and ledger_info_with_sigs to storage.

## Motivation

**Is your feature request related to a problem? Please describe.**

Transactions are saved in storage with lcs format.
```
impl ValueCodec<TransactionSchema> for Transaction {
    fn encode_value(&self) -> Result<Vec<u8>> {
        lcs::to_bytes(self).map_err(Into::into)
    }

    fn decode_value(data: &[u8]) -> Result<Self> {
        lcs::from_bytes(data).map_err(Into::into)
    }
}
```

while transaction_info and ledger_info are serailized with protobuf types.
```
impl ValueCodec<TransactionInfoSchema> for TransactionInfo {
    fn encode_value(&self) -> Result<Vec<u8>> {
        let event: libra_types::proto::types::TransactionInfo = self.clone().into();
        Ok(event.to_vec()?)
    }

    fn decode_value(data: &[u8]) -> Result<Self> {
        libra_types::proto::types::TransactionInfo::decode(data)?.try_into()
    }
}
```
This is inconsistent.

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes.

**Comment by davidiw** [comment]
@wqfish, how does this sound?

**Comment by wqfish** [comment]
yeah agree it's definitely some inconsistency there, we can probably change some to LCS.
