### ISSUE TITLE
[Feature Request] First Libra onlineIDE https://libraide.com

### ISSUE THREAD

**Issue by LingTian** [libra/libra#218]
# 🚀 Feature Request

We build the first Libra IDE which can help developers from the world to have a quick try in 3 seconds. If you are interesting in Libra and Move, our onlineIDE will save hours to do initial setup and environment. It is free and we hope to bring more developers know Libra quickly!

## Motivation

We create a free onlineIDE which allow developers to code & compile without initial setting! If we help 1 dev save 1hr to setup, we can save years around the world! 

## Pitch

Our website is https://libraide.com, please have a try. We want to help more people get into Libra!

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by Nikolaj-K** [comment]
Cool, keep it up. 
The "Compile*d* File" is also confusing as it first looks like that is the compile button. And I'd maybe turn the compile button into one that recognizes the currently open file and avoid the dropdown menu - but not sure about this. 
Can one inspect the bytecode itself? (Among other things, I'd like to know how the typing on bytecode level, as mentioned in the whitepaper, comes into play).

**Comment by goldenkarma88** [comment]
Good start. Thank you.  How about some sample/example files and a HELP resource.

**Comment by LingTian** [comment]
Aha~ Examples are in the case templates on the left~ the resources are in the setting you can find extra infomation~ We will keep working on the IDE and make it better~

**Comment by LuisEGV** [comment]
Love it. Is your project OpenSource, if so a link for its Github Repo would be helpful.

**Comment by LingTian** [comment]
Thank you ! We will continue work on more features to help the Libra developers! We are not OpenSource now because we finish ChainIDE in a hurry! I will discuss with team and at least clean the code before we make it OpenSource XD We will make ChainIDE free for everyone to use for sure! Feel free to contact me at danjinxiangsi@gmail.com if you have any comments!
![image](https://user-images.githubusercontent.com/4249432/60303604-71b7d680-9969-11e9-9b7a-1a53717679aa.png)

**Comment by alburtwang** [comment]
looks cool !

**Comment by asdgh1000** [comment]
So ,can you remove the limit about the chain. If that you can use your own chain to upload contract

**Comment by csunny** [comment]
so cool!
