### ISSUE TITLE
[Bug] Running mint node with docker fails

### ISSUE THREAD

**Issue by maxi-son** [libra/libra#2183]
# 🐛 Bug

I am facing an issue when running the faucet locally with docker. I followed the steps in the documentation at https://github.com/libra/libra/tree/master/docker. Could you please help with this? Maybe I am doing something wrong?

## To reproduce

1. run docker/mint/build.sh
2. run docker/mint/run.sh libra_mint:latest 178.18.0.1 30307 info
```

**Stack trace/error message**
```
    + /opt/libra/bin/faucet-config-builder -o /opt/libra/etc -n -s
    error: The argument '--seed <seed>' requires a value but none was supplied

    USAGE:
        faucet-config-builder --nodes <nodes> --output-dir <output-dir> --seed <seed>

    For more information try --help
```

## Expected Behavior

The mint node will be started correctly

## System information

**Please complete the following information:**
- Libra Version: latest
- Rust Version: 1.40.0
- Computer OS: Ubuntu 18.04

**Comment by davidiw** [comment]
This was recently resolved.
