### ISSUE TITLE
[Bug]CentOS Linux release 7.6.1810:./scripts/cli/start_cli_testnet.sh 

### ISSUE THREAD

**Issue by 2752381230** [libra/libra#22]
-- Looking for writev - found
-- Found Perl: /usr/bin/perl (found version "5.16.3") 
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Configuring done
-- Generating done
-- Build files have been written to: /root/Project/src/libra/target/debug/build/grpcio-sys-c998cb3e25589d95/out/build

--- stderr
CMake Warning at cmake/protobuf.cmake:48 (message):
  gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:140 (include)

CMake Warning at cmake/gflags.cmake:26 (message):
  gRPC_GFLAGS_PROVIDER is "module" but GFLAGS_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:142 (include)
........

and so on

**Comment by jsonsivar** [comment]
I got the same error on Ubuntu 19.04 and it went away after I did `sudo apt-get update` and `sudo apt-get upgrade`

**Comment by wqfish** [comment]
Hi @2752381230 it's likely that your `cmake` is too old. Can you try installing the latest `cmake`?

**Comment by icarter09** [comment]
@2752381230 were you able to get past your issue with @wqfish comment?

**Comment by chensonglovelife** [comment]
I am Mac Pro,Mojave 10.14.5
run ./scripts/cli/start_cli_testnet.sh
a bug come out,
info is 
Generating err_data.c

--- stderr
CMake Warning at cmake/protobuf.cmake:48 (message):
  gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:140 (include)


CMake Warning at cmake/gflags.cmake:26 (message):
  gRPC_GFLAGS_PROVIDER is "module" but GFLAGS_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:142 (include)


CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   zlib

This warning is for project developers.  Use -Wno-dev to suppress it.

failed MSpanList_Insert 0x94d000 0x1357fa1c6458 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x637250, 0x10)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbfeac0 sp=0x7ffeefbfeaa8
runtime.(*mSpanList).insert(0x893688, 0x94d000)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:933 +0x293 fp=0x7ffeefbfeaf0 sp=0x7ffeefbfeac0
runtime.(*mheap).freeSpanLocked(0x892e80, 0x94d000, 0x100, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:809 +0x4be fp=0x7ffeefbfeb58 sp=0x7ffeefbfeaf0
runtime.(*mheap).grow(0x892e80, 0x8, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:675 +0x2a0 fp=0x7ffeefbfebb0 sp=0x7ffeefbfeb58
runtime.(*mheap).allocSpanLocked(0x892e80, 0x1, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:553 +0x4e3 fp=0x7ffeefbfec08 sp=0x7ffeefbfebb0
runtime.(*mheap).alloc_m(0x892e80, 0x1, 0x15, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:437 +0x119 fp=0x7ffeefbfec38 sp=0x7ffeefbfec08
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:502 +0x41 fp=0x7ffeefbfec68 sp=0x7ffeefbfec38
runtime.systemstack(0x7ffeefbfec88)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbfec70 sp=0x7ffeefbfec68
runtime.(*mheap).alloc(0x892e80, 0x1, 0x10000000015, 0x9bdbf)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:503 +0x63 fp=0x7ffeefbfecb8 sp=0x7ffeefbfec70
runtime.(*mcentral).grow(0x894a80, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mcentral.go:209 +0x93 fp=0x7ffeefbfed20 sp=0x7ffeefbfecb8
runtime.(*mcentral).cacheSpan(0x894a80, 0x88d498)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mcentral.go:89 +0x47d fp=0x7ffeefbfed60 sp=0x7ffeefbfed20
runtime.(*mcache).refill(0x949000, 0x15, 0x7ffeefbfedc8)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mcache.go:119 +0xcc fp=0x7ffeefbfed98 sp=0x7ffeefbfed60
runtime.mallocgc.func2()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/malloc.go:642 +0x2b fp=0x7ffeefbfedb8 sp=0x7ffeefbfed98
runtime.systemstack(0x7ffeefbfee58)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbfedc0 sp=0x7ffeefbfedb8
runtime.mallocgc(0x180, 0x5d0b60, 0x0, 0x800000000)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/malloc.go:643 +0x869 fp=0x7ffeefbfee98 sp=0x7ffeefbfedc0
runtime.newobject(0x5d0b60, 0x88db90)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/malloc.go:781 +0x42 fp=0x7ffeefbfeec0 sp=0x7ffeefbfee98
runtime.malg(0x8000, 0x88df40)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:2634 +0x27 fp=0x7ffeefbfeef8 sp=0x7ffeefbfeec0
runtime.mpreinit(0x88e700)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_darwin.go:140 +0x1f fp=0x7ffeefbfef10 sp=0x7ffeefbfeef8
runtime.mcommoninit(0x88e700)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:494 +0x105 fp=0x7ffeefbfef58 sp=0x7ffeefbfef10
runtime.schedinit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:434 +0x79 fp=0x7ffeefbfefa0 sp=0x7ffeefbfef58
runtime.rt0_go(0x7ffeefbfefd8, 0x3, 0x7ffeefbfefd8, 0x0, 0x0, 0x3, 0x7ffeefbff2e0, 0x7ffeefbff2f2, 0x7ffeefbff2f6, 0x0, ...)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:138 +0x132 fp=0x7ffeefbfefa8 sp=0x7ffeefbfefa0
make[3]: *** [third_party/boringssl/crypto/err/err_data.c] Error 2
make[3]: *** Deleting file `third_party/boringssl/crypto/err/err_data.c'
make[2]: *** [third_party/boringssl/crypto/err/CMakeFiles/err.dir/all] Error 2
make[1]: *** [CMakeFiles/grpc.dir/rule] Error 2
make: *** [grpc] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /Users/chen-song/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.40/src/lib.rs:832:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by lucasverra** [comment]
same here :( 

```ubuntu:~/environment/AWS-Libra-Blockchain/Phase 1 - My First Transaction (on Cloud9)/libra (master) $ cmake --versioncmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by chinglinwen** [comment]
I'd expect Libra to write in Go :joy: , so kind of this mess

**Comment by bmwill** [comment]
The external dependencies needed to build Libra have been simplified and should only require Rust now so this shouldn't be an issue anymore on master. If it is, please let us know.
