### ISSUE TITLE
[Bug] While reading the libra association council principles, Table of content fails to update

### ISSUE THREAD

**Issue by tatianajiselle** [libra/libra#230]
https://libra.org/en-US/association-council-principles/#social_impact_advisory_board

on left side nav bar which includes: 
Overview: The Association & Council
1: Goals and Principles
2: Libra Association Council
3: Libra Association Board
4: Social Impact Advisory Board
5: The Association’s Executive Team

when scrolling between 2, 3, and 4 in the reading, 3 is skipped and not highlighted on the TOC, even when 3 is active.

**Comment by raguiar2** [comment]
I'm not able to reproduce this. Which browser are you using, and can you send a screenshot?

**Comment by JR463** [comment]
> https://libra.org/en-US/association-council-principles/#social_impact_advisory_board
> 
> on left side nav bar which includes:
> Overview: The Association & Council
> 1: Goals and Principles
> 2: Libra Association Council
> 3: Libra Association Board
> 4: Social Impact Advisory Board
> 5: The Association’s Executive Team
> 
> when scrolling between 2, 3, and 4 in the reading, 3 is skipped and not highlighted on the TOC, even when 3 is active.

Did this get resolved?

**Comment by tatianajiselle** [comment]
It seems like its flakey -- i was able to reproduce it once right now (maybe its some sort of race condition) 

Im on a chrome browser and my steps were:
Scroll up to header 2. Click header 3. (see image attached)
<img width="1163" alt="Screen Shot 2019-07-17 at 10 58 57 AM" src="https://user-images.githubusercontent.com/13118794/61399034-2155d980-a882-11e9-83c5-cae1a6a996bd.png">
