### ISSUE TITLE
[Bug]--mnemonic-file parameter not working

### ISSUE THREAD

**Issue by Steve-Mc** [libra/libra#234]
The --mnemonic-file parameter does not seem to work when loading a mnemonic file on startup

**Comment by xfyfb** [comment]
@Steve-Mc can you share more details and the content of your mnemonic file?

**Comment by JR463** [comment]
did this get resolved?

**Comment by Steve-Mc** [comment]
@xfyfb sure. The command I'm trying to run is:

`cargo run -p libra_swarm -- -s --mnemonic_file /path/to/file.mnemonic`

 I have also tried:

`cargo run -p libra_swarm --  --mnemonic_file /path/to/file.mnemonic -s`

and:

`cargo run -p libra_swarm --mnemonic_file /path/to/file.mnemonic -s`

When I run the above command I receive:

`error: Found argument '--mnemonic_file' which wasn't expected, or isn't valid in this context`

The contents of the mnemonic file itself ends in `;3`, not sure if that is expected or not.

**Comment by Steve-Mc** [comment]
finally got it working with:

`cargo run -p client --bin client -- -n /path/to/wallet.mnemonic --host ac.testnet.libra.org --port 8000 --validator_set_file /libra/scripts/cli/trusted_peers.config.toml
`

**Comment by xfyfb** [comment]
Oh, I see. Yes, --mnemonic_file is the argument of client, not libra_swarm. So cargo run -p libra_swarm -- -s --mnemonic_file /path/to/file.mnemonic will not work. Can you close this one if there is no other issue?
