### ISSUE TITLE
[Bug] Transactions were not committed before expiration

### ISSUE THREAD

**Issue by andll** [libra/libra#2364]
In some very rare cases we can see `Transactions were not committed before expiration` when running cluster test.

This means transaction that was accepted by AC was not committed. No failures are injected in the system during this time and no sequence number concurrency is happening from client side, so expectation is that such transaction should always be committed.

Narrowing down shows that problem is in rare race condition in consensus-mempool-statesync communication.

Quoting @dmitri-perelman 
>The problem is that during the state-sync consensus doesn't notify MP about the committed transactions, hence if a proposer just finished state-sync, it might pull an already-committed transaction for a new block.
We already knew our state-sync doesn't work well with MP notifications (we even have a tech-debt task! https://github.com/libra/libra/issues/1874), but didn't realize the full scale of the problems.
@phoenix-antigravity  says that they already have plans to rebuild the notification pipeline to notify MP via state-sync anyway. In this case the notifications about the committed txns during state-sync will be added for free and life will be awesome again.

**Comment by phoenix-antigravity** [comment]
fixed by https://github.com/libra/libra/commit/a3367f6d855c6a733254d0e89f4284363bc686be
