### ISSUE TITLE
client dev compile does not consider parameter output_file_path

### ISSUE THREAD

**Issue by ReinhardFreiler** [libra/libra#2375]
Hi!

When compiling move modules/scripts on a local network one has following command documentation:

compile | c <sender_account_address>|<sender_account_ref_id> <file_path> <module|script> [output_file_path (compile into tmp file by default)]
	Compile move program

But when you want to use the last (optional) parameter "output_file_path" to specify your own file name, the standard temp file name (randomly generated) is still used.

In client/cli/src/client_proxy.rs in function compile_program the element at the 4th index of the array input parameter space_delim_strings would contain the custom "output_file_path" value, but it isn't considered.

Thank you.

**Comment by bob-wilson** [comment]
This is the same issue as #2447
