### ISSUE TITLE
[monitoring] Log store and support for structured logs

### ISSUE THREAD

**Issue by andll** [libra/libra#2436]
We want to have better solution for storing logs
- ELK support [@sherry-x]
- Structured logs - reuse `event!` macro?
- Evaluate whether we still need libra-logging crate
- Prometheus federation for prod?

**Comment by nruppatel133** [comment]
Executables should choose a logger implementation and initialize it early in the runtime of the program. Logger implementations will typically include a function to do this. Any log messages generated before the logger is initialized will be ignored. The executable itself may use the log crate to `log` as well.

**Comment by davidiw** [comment]
@andll any update here? I'm going to start exploring a light weight facade over the log and env-logger for TCB in the hopes that it can replace what we currently have but it would be nice to ensure that it can be used across the code base.

**Comment by andll** [comment]
As I heard yesterday, @bschwab's team was going to work on that, assigning to him for dispatch
