### ISSUE TITLE
Tooling to detect breaking changes

### ISSUE THREAD

**Issue by zekun000** [libra/libra#2438]
We need a tooling/linter to identify breaking changes on commits so that proper actions could be taken.

**Comment by thefallentree** [comment]
I'm looking at https://github.com/facebookexperimental/MIRAI  , maybe this is something that can be used.

**Comment by matbd** [comment]
I made a pull request that should help: https://github.com/libra/libra/pull/2867

**Comment by thefallentree** [comment]
🥇 , and I wrote an flexible  python deserilizer  that utilize this spec today under an hour.

Having this would not only 
1. enable flexible LCS ser/de Implementations (just update spec file and everything will work automagically)  .
2.  Allows us to track changes to the spec.
3.  it also enables multiple cross language projects uses LCS as an default messaging struct . see
 https://github.com/calibra/libra-client-dev/pull/76/files For my toy deserilizer implementation  and the example output at https://our.internmc.facebook.com/intern/paste/P127386287
