### ISSUE TITLE
Rollover the account state with new genesis

### ISSUE THREAD

**Issue by zekun000** [libra/libra#2439]
To support breaking changes, we need a mechanism to start a new chain.

The existing account state would be transformed to the new format if the format changes(may incur downtime), a new genesis would be applied to the state and stamped with waypoint. Validators would start from this waypoint, and archived transaction has to be transformed in new format or a different binary is needed to provide the archived transaction access.

**Comment by msmouse** [comment]
A basic form of the tool would be like this:

Inputs:
- a state tree backup
  - including state tree root hash
- a genesis transaction in binary form

Outputs:
- a waypoint at version 0

It runs like:
- It can run on an empty db or a partly done db (resumable).
- Main part of the work is recovery of a backed up state tree, which by itself is resumable.
    - if state tree root node is not present, the state tree recovery has not completed yet.
- On top of the recovered state tree, the input genesis txn should be executed and committed.
    - if latest ledger info in the db exists (and it should be at version 0), this step is already completed from previous run. Note that we assume the whole step is done in one DB transaction.
- Output waypoint at version 0.

**Comment by msmouse** [comment]
For the record the CLI tool is #3528
