### ISSUE TITLE
[Bug]the Hkdf result is not correct

### ISSUE THREAD

**Issue by yqsailor** [libra/libra#244]
# 🐛 Bug

the Hkdf::<Sha3_256> generate hex is not correct, I try it by [nodejs](https://github.com/perfectmak/libra-core), [go](https://github.com/philippgille/libra-sdk-go), and `python`, All the Check child_0 key derivation result is `87bedfb241a2aa44a93588efdd52d39894eac21cec3f82c8be2af875638e00e2`; but the rust is `358a375f36d74c30b7f3299b62d712b307725938f8cc931100fbd10a434fc8b9`;
the code is below.

## To reproduce

** Code snippet to reproduce **
```rust
let data = hex::decode("7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f").unwrap();
    let mnemonic = Mnemonic::from("legal winner thank year wave sausage worth useful legal winner thank year wave sausage worth useful legal will").unwrap();
    assert_eq!(
        mnemonic.to_string(),
        Mnemonic::mnemonic(&data).unwrap().to_string()
    );
    let seed = Seed::new(&mnemonic, "LIBRA");

    let key_factory = KeyFactory::new(&seed).unwrap();
    assert_eq!(
        "16274c9618ed59177ca948529c1884ba65c57984d562ec2b4e5aa1ee3e3903be",
        hex::encode(&key_factory.master())
    );

    // Check child_0 key derivation.
    let child_private_0 = key_factory.private_child(ChildNumber(0)).unwrap();
    assert_eq!(
        "358a375f36d74c30b7f3299b62d712b307725938f8cc931100fbd10a434fc8b9",
        hex::encode(&child_private_0.private_key.to_bytes()[..])
    );
```

**Comment by perfectmak** [comment]
@yqsailor I noticed you mentions [libra-core](https://github.com/perfectmak/libra-core) in your description.
there was some discrepancy with how Libra core implemented the hkdf for generating accounts. It has been fixed now. Use the latest version `1.0.2`, it has the fixes. See full changelog [here](https://github.com/perfectmak/libra-core/releases/tag/1.0.2)

**Comment by kchalkias** [comment]
I guess this was related to libra-core and not libra's `Hkdf::<Sha3_256>`, which according to @perfectmak it is fixed now. Thank you both, @aching we can safely close this ticket.
