### ISSUE TITLE
[Feature Request] Muh raspberry pi

### ISSUE THREAD

**Issue by jdimarco218** [libra/libra#246]
# 🚀 Feature Request

I would like to tinker with libra on my raspberry pi.

## Motivation

```
admin@jeffpi:~/code/libra $ ./scripts/dev_setup.sh
Unknown OS. Abort.
admin@jeffpi:~/code/libra $ uname -a
Linux jeffpi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
admin@jeffpi:~/code/libra $ cat /etc/*release*
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by icarter09** [comment]
@jdimarco218 did you try other Raspberry Pi OS's? I wonder if Ubuntu MATE would work. Another question is what Raspberry Pi model did you try this out on?

**Comment by kphfb** [comment]
Hi @jdimarco218, we aren't currently targeting Raspberry Pi for the validators.  To ensure high throughput/performance, we are expecting the validator nodes to run on higher-end systems, so we likely won't be focusing on adding Raspberry Pi support in the near-term
