### ISSUE TITLE
Is libra codebase compilable against arm

### ISSUE THREAD

**Issue by zjshen14** [libra/libra#247]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discourse](https://community.libra.org)

If not, any plan to support arm in the future? Thanks!

**Comment by aching** [comment]
Hi! =)

Currently, there is no plan to include ARM support, sorry.

**Comment by zjshen14** [comment]
Hm... okay, thanks for the confirmation :-)

**Comment by zjshen14** [comment]
@aching FYI, tested that vm is runnable on aarch64
