### ISSUE TITLE
[network][metrics] record # dialer vs. listener connections 

### ISSUE THREAD

**Issue by phlip9** [libra/libra#2472]
To help debug NAT / connectivity issues where, e.g., nobody can dial my validator we should:

+ Add a label to the connected peers metric, "origin", that can be either "dialer" or "listener".
+ When a new connection opens and successfully negotiates, I will increment the "dialer" label if I am the dialer and the "listener" label if I am the listener.
+ On the graphana dashboard, we can show "dialer" + "listener" for the total connected peers and then a stacked area graph or something to show # "dialer" vs # "listener" connections.

If other validators can't dial us, it should show # "listener" = 0 and # "dialer" = # connected. Likewise, if there is a problem listening for connections, it should show # "dialer" = 0.

That's not to say there are no false-positives/-negatives, but it will probably help us debug some connectivity issues.

Relevant code: 

https://github.com/libra/libra/blob/master/network/src/peer_manager/mod.rs#L611

**Comment by gregnazario** [comment]
We now do this as `inbound` and `outbound` connections!
