### ISSUE TITLE
Connecting to the local validator independently without the -s flag

### ISSUE THREAD

**Issue by hvram1** [libra/libra#249]
Hi
   I ran the following command
<code>
cargo run -p libra_swarm -- -n 2 -d fals
</code>

From the logs I could see the server running at port 41135 and was able to confirm using 
<code>
netstat -peanut
</code>

I tried the following command

<code>
cargo run -p client -- --host 0.0.0.0 --port 41135 -s /tmp/.tmpG8Hwqe/trusted_peers.config.toml
</code>

From the main.s I can see that the interactive client has the paramters from the faucetkeyfile . 

Is there a separate program to connect to the local client using the cli ? Or should I write a program to accept these parameters and launch the client ?

**Comment by kphfb** [comment]
The suggested way to do this is still to run libra_swarm with -s, but if for some reason you wish to not do this, you can run the client similar to what you mentioned.  You'd want to check the config file for the port, use the same faucet key file as the swarm is using, and pass the same validator set file as well.
