### ISSUE TITLE
Question about transaction timestamp

### ISSUE THREAD

**Issue by sauliusdainys** [libra/libra#250]
Does transaction execution or confirmation timestamp exists in "Libra" blockchain? For  example on Ethereum there is a timestamp when the block was mined. Does "Libra" transaction contains something similar and is it possible to retrieve it using "Libra client". The transaction "expiration date" I assume has a different meaning.

**Comment by aching** [comment]
There is a timestamp created when a block is proposed.  The block timestamp is guaranteed to be higher than the preceding parent block's timestamp.  It is also guaranteed that if the block is accepted, that > 2/3 of the voting power agreed that timestamp was in the past.  We will be working to expose the timestamps to clients prior to V1 launch and on other improvements to the timestamp protocol.  Transaction expiration is related in the sense that transactions won't be proposed (or accepted) if they violate the timestamp protocol - i.e. older than the block's timestamp.

**Comment by amavashev** [comment]
So how do you get timestamp of a transaction? I am assuming (based on response) tx timestamp is currently not available and if so a fairly significant limitation.

**Comment by davidiw** [comment]
on chain, there is a blockmeta data transaction before a set of user transactions, that contains this type of information.
