### ISSUE TITLE
exchange data efficiently between 2 modules in move language

### ISSUE THREAD

**Issue by crabex** [libra/libra#2503]
As I know,  In move language, a method in module A can't access directly the struct data field in module B.
That means I must implements get/set methods for all the data field. The code will look very ugly.

Is there any way that will make the code clean?

Thanks.

**Comment by sblackshear** [comment]
No. We may provide source language support for generating getters and setters at some point. You can also expose a single procedure `get_f(t: &mut T): &mut u64` (assuming `T` is resource T { f: u64 }`) that will let a caller either read or write the field. 

But in general, we don't expect Move programmers to be writing code like this. A module typically wants to enforce some strong invariants on its fields and thus must prevent other modules from mutating the fields arbitrarily (e.g., via a setter).
