### ISSUE TITLE
[network][discovery] Support removing peers during reconfig for gossip-discovery

### ISSUE THREAD

**Issue by phlip9** [libra/libra#2506]
### Context

Gossip-discovery has two key pieces of state:

+ `known_peers: HashMap<PeerId, VerifiedNote>`
  - `known_peers` contains the most recent `VerifiedNote` for each peer
  - when we receive a new `DiscoveryMsg` from another peer, we choose the most recent notes to merge into our `known_peers`
+ `trusted_peers: Arc<RwLock<HashMap<PeerId, NetworkPublicKeys>>>`
  - the set of peers we will accept connections from and attempt to dial. if we're a validator, this is the current validator set (that we know of).

### Problem

It looks like we're not filtering `known_peers` so that `known_peers ⊆ trusted_peers`. In other words, if there's a reconfiguration that removes a validator, we'll keep that validator's old note in our known_peers map. When we go to send a `DiscoveryMsg` to one of our peers, we'll actually include that old note in the message. When that peer tries to verify our notes, they'll reject the whole message because this stale note's signature doesn't verify.

### Solution

This leads to at least two action items:

- [ ] Always filter out from `known_peers` any peers ∉ `trusted_peers` when we `compose_discovery_msg`.
- [ ] Just filter out items that fail to verify from `DiscoveryMsg` instead of rejecting the whole message. Log verification errors. If all the items fail, probably log a warning. Also increment a metrics counter for each note that fails to verify.

**Comment by davidiw** [comment]
alternatively deprecate gossip discovery :P
