### ISSUE TITLE
[Consensus] Cleanup Event Loop in Chained BFT SMR

### ISSUE THREAD

**Issue by ZhenjieRuan** [libra/libra#2518]
Currently the way we are handling events in the main event loop in `chained_bft_smr` is very verbose with quite a bit code duplication. The main reasons are: 
1. We are mixing extracting out event message and actually handling them.
2. We are putting both messages that are handled by `event_processor` and messages that are handled by `epoch_manager` into one giant `select!`
In order to clean this up, we can have following small steps:
- [ ] Move messages that should be handled by `epoch_manager` into it's own `select!`
- [ ] Have an enum that can hold various message types and is responsible for dispatching the messages to their corresponding handlers

**Comment by davidiw** [comment]
There's a lot of nuance here. The one issue with select statements is that you end up with one thread per select statement. I think we should explore solutions that move us closer to a single thread. See https://github.com/libra/libra/issues/2152 and the thread in there where Dmitri calls out other concerns. Good eye though on the ... situation :).

**Comment by phlip9** [comment]
just a small nit: it doesn't _have_ to be one thread per select statement. for example, the following runs both Actor1 and Actor2 on the same task and so the same thread:

```rust
struct Actor1;

impl Actor1 {
    // actor 1 event loop future
    async fn start(self) {
        loop {
            futures::select! {
                // select b/w some streams
            }
        }
    }
}

struct Actor2;

struct Actor2 {
    async fn start(self) {
        loop {
            futures::select! {
                // more select stuff here
            }
        }
    }
}

fn spawn_actors(executor: Handle) {
    let actor1 = Actor1;
    let actor2 = Actor2;
    let f_join = future::join(actor1.start(), actor2.start());
    executor.spawn(f_join);
}
```
