### ISSUE TITLE
Libra Execution Correctness (LEC)

### ISSUE THREAD

**Issue by lightmark** [libra/libra#2519]
# LEC Design

## Motivation
This issue describes the plan to build Libra Execution Correctness TCB for the Exec/VM which is a building block of Libra Core TCB presented in issue #2326. The goal of TCB is to isolate critical properties in a finite space that collectively ensures the correctness of the Libra blockchain. As a crucial module to TCB, LEC has to guarantee the correctness of execution - All agreed upon transactions within a block execute in order and correctly (Always execute transactions correctly). The current implementation of Executor is not isolated from the rest modules of Libra Core so It has to be refactored.

### Assumptions
- TCB only requires Execution Correctness of blocks but doesn’t trust storage so committing is not its concern. Therefore LEC in TCB framework does not necessitate functionalities related to chunks in state sync procedure or committing any execution results to storage.
- The architecture of full nodes is simplified over validators in the sense that full nodes don’t need TCB. However, they should be able to monitor the progress of the blockchain and to catch up via some mechanism w/o TCB involved. 
- Both full nodes and validators will have a single storage.
- As the figure shows, LSR, LEC and other non-TCB components are isolated into separate processes, or even containers. Also, it is only LSR that is allowed to talk to LEC.
### Implications
- Anything functionalities in executor related to state_sync and committing will be in non-TCB part but that related to block execution will be the LEC.
- Full nodes can fully rely on the non-TCB executor to be functional.
- The validator will have two executors which must share a consistent state with one single storage.
Separated containers implies any shared-memory data exchange is not practical. The crash-recovery process has to be comprehensive since Consensus, LSR and LEC must be consistent in terms of multiple pieces of data, including block tree structure, latest committed state, etc.  The isolation turns them into individual micro services communicating through serializable messages, which adds complications onto the consistency between them because any one can crash at any time but the others are not aware of the crashing. The good news is, from the perspective of LEC, its state is in memory and easily recoverable from Consensus/LSR. A intuitive, simple but not optimized approach is just reconstruct the whole block tree if a block is not found. While the other executor in non-TCB is stateless so it is less concerned with.

![LEC](https://user-images.githubusercontent.com/1549573/75594827-0580fb80-5a3f-11ea-846c-4a9e818cb4a0.png)

## Plan
The introduction of LEC requires the factoring of multiple components of the Libra Core. To to specific, it entails multiple sub-projects:
- Breaking Executor into LEC and SyncExecutor(chunk execution and committing only used by StateSynchronizer)
- LEC Interface definition and isolation
- LEC Process
- Storage Service Refactoring 

### Splitting Executor into 2 parts
We name them SyncExecutor and LEC, respectively. This work requires clear isolation but maximum code reuse to avoid execution inconsistency between the two executors. It would be better to merge the APIs of both chunk and block execution as much as possible.

### Execution Interface
The current implementation of `executor` is highly coupled to `consensus` and `state_synchronizer`. In order to achieve the independence of LEC, it has to be decoupled according to the following tasks:
- Define LEC interface that talks to storage and LSR. Build corresponding client and server modules.
- Replace the dependencies on Executor of any module with the dependencies on LEC client.
- Refactor Consensus, LSR, Storage and Executor to be able to communicate only via serializable messages.
 - Refactor block tree to remove all the unserializable or serialization-unfriendly speculative result.
 - Move all the aforementioned results back to LEC and cache them there.
 - Finish the LEC-related message flow according to the TCB diagram based on the C/S architecture of LEC.

### Execution Process
LEC will eventually be run in a container (Docker) which requires a self-contained application implementation. The process includes:
- Endpoint definition according to the interface defined like [this](https://github.com/libra/libra/blob/master/consensus/safety-rules/src/serializer.rs)
- The inclusion of networking stack.
- Message specification and serializer/deserializer

### Storage Servicing Refactoring
The two executors are the only components in Libra Core that are allowed to write to storage among which LEC is designed to have as less dependencies as possible to facilitate code auditing and to reduce the risk of buggy code. However, the current storage C/S implementation failed to remove the dependencies on server of client, which indirectly adds heavy dependencies of storage to LEC. This sub-project aims to:
- Refactoring Storage Service, including both server and client sides, to offer the minimum dependencies on other crates of storage client.
- If possible, replace GRPC service with LibraNet.

## Milestone
- Execution Refactoring
1. Separate out executor interface to its own crate `Executor-types`.
2. Create block tree in executor with speculation results, including massive changes in Consensus and StateSync.
3. Split Executor.
4. Redefine the interfaces of executor and create LEC client and server.

- Execution Process Isolation
1. Define message format according to the new interfaces.
2. Include networking stack.

- Storage
1. Refactor storage client to have the minimum dependency.
2. Replace GRPC with LibraNet.

**Comment by davidiw** [comment]
This is great! Thanks for initiating it. Have you had a chance to explore cargo geiger / cargo tree within the executor crate? Some things that stood out to me in a perusal of it from the safety rules perspective:
* Executor is built on top of Tokio but is intended to be synchronous
* Executor <-> storage interface is based upon tonic whereas a simple interface like [the one](https://github.com/libra/libra/blob/master/consensus/safety-rules/src/serializer.rs) exposed by safety rules and likely used between executor and safety rules will suffice -- in addition it might be valuable to support a single binary / Rust only interface
* Storage client is not crate separated from storage service and brings in RocksDB as a dependency

Also I'm curious to dig into the benefits of using the same executor for consensus versus state sync. The primary reason for consensus is so we have trusted output for epoch changes. In the state sync case, we likely already have an agreed upon checkpoint, I'm not sure if having the same level of scrutiny is worthwhile, but I'm curious about your perspective. Also it might be worth exploring this space with our VM party @dariorussi, @sblackshear, @DavidLDill

**Comment by lightmark** [comment]
@davidiw Anything about storage may lend itself to another topic but not the issue here. I am drafting a more fleshed doc which splits the executor into two used by TCB and Non-TCB respectively.

**Comment by davidiw** [comment]
> @davidiw Anything about storage may lend itself to another topic but not the issue here. I am drafting a more fleshed doc which splits the executor into two used by TCB and Non-TCB respectively.

Not sure I follow, the interface between LEC and Storage is part of the TCB. So ideally we eliminate the grpc interface, but we can chat after your doc is online :).

**Comment by davidiw** [comment]
Nice writeup!

**Comment by davidiw** [comment]
fantastic work here, really fantastic!
