### ISSUE TITLE
[Feature Request] Let's turn on dependabot and stay up to date

### ISSUE THREAD

**Issue by rexhoffman** [libra/libra#2559]
# 🚀 Feature Request

Turn on dependabot to open prs to attempt to keep us up to date:

https://app.dependabot.com/

## Motivation

Now that we've done some automated/manual dependency updating it's the perfect time to turn on dependabot.   I expect us to only see 5 prs openned.

https://github.com/rexhoffman/libra/pulls

## Pitch

Prs to keep libra up to date and exercise our ci/audit capability.    Plus ability to navigate prs that break to owning teams.

The alternative is that we let our deps slowly rot until someone decides to update them.

This must be done via a team member in the dependabot ui.

**Comment by metajack** [comment]
I've added `libra/libra`.

**Comment by metajack** [comment]
We also need to whitelist the bot in the CLA checking tool.

**Comment by rexhoffman** [comment]
This is all done (including whitelisting) except for posting out the update to internal/external groups.  Closing the feature request.   Waiting on feedback from @ericnakagawa and @davidiw before posting - and seeing if Eric has a good public place to post the update.
