### ISSUE TITLE
[Consensus] Avoid pulling transactions of a block if its execution failed

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#2568]
@dariorussi brought an interesting case, in which the whole system was stuck for a while.

* There was some bug, which caused the executor to fail a block execution because of a specific transaction.
* As a result, the block with the failed transaction was not added to the `BlockStore` in Consensus.
* Every time a proposer was trying to pick a new proposal it would pick the same problematic transaction from the Mempool over and over.
* It happens because today Consensus filters out only the transactions that are pending in its BlockStore.

One thing we could do to harden the system in this case would be to filter out the transactions from the blocks that failed execution. It might filter out benign transactions as well, but at least it would reduce the probability of repeating the same problematic transaction more than once.

**Comment by dariorussi** [comment]
@runtian-zhou who is the one following the original SEV. @wqfish who was also following up
I am sure they both care...

**Comment by zekun000** [comment]
we do discard failed transactions, but this case it exposed a bug in VM, I think we should fail loudly instead of silently filtering it out. imo we should probably purge the mempool manually to mitigate the problem.

**Comment by dmitri-perelman** [comment]
I agree on the part of not failing silently. We should have corresponding monitoring metrics / alerts / logging.
However, purging things manually from Mempool sounds like a very heavyweight solution for the oncall (of every node?): doesn't it make sense for the system to not be stuck because of problematic transactions that cause execution failure? Hence this task :).
