### ISSUE TITLE
[Feature Request] Support pluggable consensus

### ISSUE THREAD

**Issue by jolestar** [libra/libra#262]
# 🚀 Feature Request

## Motivation

Hope to support pluggable consensus so that different consensus can be used in different scenarios. Such as using a simple consensus in the development environment like ethereum for reducing compute resource consume.

**Is your feature request related to a problem? Please describe.**

Libra use too many CPU in the local development environment, may cause the computer to hang.

<img width="793" alt="Libra cpu" src="https://user-images.githubusercontent.com/77268/61274672-d6cf5100-a7de-11e9-8432-f793c938e9a7.png">

## Pitch

**Describe the solution you'd like**

Implements a pluggable consensus framework.

**Describe alternatives you've considered**

Just provide a simple consensus for development environment.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

**Comment by kphfb** [comment]
The system is designed such that this is actually possible.  All components are connected via gRPC so you could in theory plug in any consensus module that you desired as long as you complied with the specified interface.  The same could be said of any component in the system
