### ISSUE TITLE
How to setup myown libra develop test net?

### ISSUE THREAD

**Issue by nkbai** [libra/libra#264]
## ❓ Questions and Help
`./scripts/cli/start_cli_testnet.sh` only start a client to connect to an existing libra testnet.
But how to setup a my own testnet. I want to runniing my own Libra node.

**Comment by Lewuathe** [comment]
You own validator node can be run by using `libra_swarm` in your local machine.

See: https://developers.libra.org/docs/my-first-transaction#run-a-local-validator-node

**Comment by asdgh1000** [comment]
You can read this: docker/validator/validator.Dockerfile

**Comment by nyetwurk** [comment]
This is useless for deploying a larger, distributed, "real" testnet.
