### ISSUE TITLE
dynamic add node

### ISSUE THREAD

**Issue by asdgh1000** [libra/libra#268]
How to add a node without restart swarm or nodes? I want to add node dynamic.

**Comment by kphfb** [comment]
This is something that we are currently building.  Stay tuned!

**Comment by sunrye** [comment]
looking forward for this feature

**Comment by ekryski** [comment]
@kphfb I assume the reciprocal dynamic removal is coming too?

**Comment by kphfb** [comment]
@ekryski That is correct

**Comment by bmwill** [comment]
I believe support for reconfiguration was just landed a while ago so this feature should be available in some form now.
