### ISSUE TITLE
[Crypto] Harden crate

### ISSUE THREAD

**Issue by davidiw** [libra/libra#2683]
As part of ongoing discussions for launch readiness, the following has been planned for the crypto crate:
- [x]  Eliminate or move non-production components into features (bls, threshold crypto, vrf, slip) -- this pulls unused dependencies into the TCB adding unnecessary crates to our audit load.
- [x]  Remove cryptoproxies and generics (traits) from the existing interfaces (e.g., libra types), everything should unify into a specific key type (Ed25519) but leverage the appropriate trait interface. This simplifies the interface reducing complexity in auditing the code.
- [x]  Evaluate alternative hashing algorithms (sha2, cShake). Determine crypto hardiness versus performance.
- [x]  Remove compat interface from all types
- [x]  Rename Uniform::generate_for_testing to generate and add comments that imply that unsafe usage of this can result in weak keys
- [x]  Implement a clean means for handling multisig within Ed25519
- [ ]  Make composite traits in Crypto (VerifyingKey should be a PublicKey, SigningKey should be a PrivateKey, etc)
- [ ]  Replace Sha2 in HKDF with Sha3 and evaluate if we want digest crate... seems unnecessary.

**Comment by davidiw** [comment]
Confirmed with @zekun000 and @aching on removal of cryptoproxies.

**Comment by kchalkias** [comment]
@davidiw and @aching Note that a PR around the MultiEd25519 scheme will soon be pushed (the default scheme which will allow multi sig). We can work on the trait removals when this PR is available.

**Comment by lucasverra** [comment]
> As part of ongoing discussions for launch readiness,
What launch ?

**Comment by davidiw** [comment]
> > As part of ongoing discussions for launch readiness,
> 
> What launch ?

Good question! These are the remaining goals to stabilize the create to call it "shippable" or "ready for launch." I've updated the title to be a bit more clear on what was intended.

**Comment by lucasverra** [comment]
any estimate on official launch ? 🥇

**Comment by davidiw** [comment]
> any estimate on official launch ? 🥇

This issue is about hardening the crypto crate, any thoughts on that matter?

**Comment by davidiw** [comment]
not going to address the last two points, I realized they are too incremental and don't really add value without substantial thinking...

**Comment by mimoo** [comment]
> Evaluate alternative hashing algorithms

We're still there :) I think we should have a serious convo about replacing SHA-3 with K12

**Comment by davidiw** [comment]
> > Evaluate alternative hashing algorithms
> 
> We're still there :) I think we should have a serious convo about replacing SHA-3 with K12

My concern would be that we make already challenging support for HSMs even more so. Maybe this isn't an issue if we first separate signing from hashing.

**Comment by kchalkias** [comment]
> > Evaluate alternative hashing algorithms
> 
> 
> 
> We're still there :) I think we should have a serious convo about replacing SHA-3 with K12

I also believe we shouldn’t change on anything else than sha2 or sha3 for the time being (maybe shake as well). 

It’s a) HSM support, b) extra work for custody, c) standardization questions we might be asked, d) unlikely that K12 will have hardware instructions in the future, e) mobile client wallet native SDK support etc.

**Comment by mimoo** [comment]
> My concern would be that we make already challenging support for HSMs even more so 

Is SHA-3 even supported by HSMs?

> unlikely that K12 will have hardware instructions in the future

I think that's a legitimate issue, I really hope that they end up supporting the permutation and not the algorithm

**Comment by kchalkias** [comment]
> > My concern would be that we make already challenging support for HSMs even more so 
> 
> 
> 
> Is SHA-3 even supported by HSMs?
> 
> 
> 
> > unlikely that K12 will have hardware instructions in the future
> 
> 
> 
> I think that's a legitimate concern, I really hope that they end up supporting the permutation and not the algorithm 

Gemalto supports sha3 since April 2018

https://data-protection-updates.gemalto.com/2018/04/27/product-release-safenet-protecttoolkit-5-6/

**Comment by mimoo** [comment]
ah nice! That's pretty awesome.
