### ISSUE TITLE
Failed to perform transaction Validation UnknownScript

### ISSUE THREAD

**Issue by jonasbuggs** [libra/libra#273]
## ❓ Failed to perform transaction Validation UnknownScript

Guys help me with this 

 Everything was fine until i made the first transaction 

please check the screenshot and guide through what is happening here

![Screenshot](https://user-images.githubusercontent.com/25316698/61558631-3c446b80-aa85-11e9-80e7-15f99a0f1dda.png)

Please contact the development team on [Discourse](https://community.libra.org)

**Comment by sblackshear** [comment]
See https://community.libra.org/t/transaction-failed/1303/6 for the explanation: tesnet clients need to be built from the `testnet` branch on GitHub rather than the `master` branch.
