### ISSUE TITLE
Transaction signature Ed25519 or BLS12381 ?

### ISSUE THREAD

**Issue by NabilNoaman** [libra/libra#276]
Hi,

In https://developers.libra.org/docs/crates/crypto :

It is clearly mentioned that "**Ed25519** to perform signatures. It is used both for **consensus signatures** and for **transaction signatures**."

But in current repo https://github.com/libra/libra/blob/master/crypto/nextgen_crypto/README.md we have : 

**Ed25519** performs signatures using the new API design based on ed25519-dalek library with additional security checks (e.g. for malleability).
**BLS12381** performs signatures using the new API design based on threshold_crypto library.

I want to know which signature to be used for transaction signing Ed25519 or BLS12381 ?

Br,
Nabil

**Comment by asdgh1000** [comment]
Ed25519

**Comment by NabilNoaman** [comment]
Thanks asdgh1000.

So what is the usage of BLS12381 ? Is Libra association will use it in future for Tx signature ?

Br,
Nabil

**Comment by kchalkias** [comment]
Hi @NabilNoaman, Pure EdDSA Ed25519 is the sole scheme currently used either in consensus or transaction signing. The `nextgen_crypto` package was originally there to distinguish between current and future crypto primitives and BLS is one of the schemes we're evaluating., but it's not used. We will soon update the package structure and EdDSA will be moved from `nextgen_crypto` so it's more clear.
