### ISSUE TITLE
[types] Shorter account addresses

### ISSUE THREAD

**Issue by sblackshear** [libra/libra#2764]
#  Shorter account addresses

Reduce Libra address size from 256 bits to 128 bits

## Motivation

Libra account addresses are big: 256 bits. Address size has an impact on the size of transactions, account state blobs, and Move bytecode. Each of these constructs typically contains multiple addresses. In addition, off-chain protocols have struggled to meet size-based requirements (e.g. “a transaction should fit in an SMS message”) because addresses occupy so much space.

## Pitch

- We recommend a reduction in address size from 256 bits to 128 bits. However, we believe that values between 96 and 128 bits would also be valid (and safe) choices.
- The reduction in address size does not change the security of cryptographic keys used for spending (which will remain 256 bits). 
- The reason this is possible/safe is (a) Libra has a distinction between account addresses (the  identifier for an account) and account authentication keys (a piece of data stored under the account address). Account authentication uses the 256 bit authentication key, not the 128 bit account address.
- The reduction in address size does force clients to distinguish between creating a new account and paying to an existing account (See “distinguishing account creation and payments” section).
- Benefits of 128 bit addresses:
-- Addresses fit in a V1 QR code (not true for any existing blockchain address)
-- Peer-peer payment transactions are 384 bits smaller
-- Event keys are 128 bits smaller. Combined with shorter addresses, this means that a payment sent/received event will be 256 bits smaller (and note that each payment transaction emits two such events)
-- Transactions more likely to fit in an SMS (important for financial inclusion use-cases like Libra Money Orders)
-- Enable 12 word mnemonics, which may be possible for some to remember

In the remainder of this document, we:
- Present background on Bitcoin/Ethereum/Libra addresses, 
- Explains the attacks and math behind these address lengths
- Explains why the attack calculus is different for Libra addresses (in short: because we distinguish between account addresses and account authentication keys) 
- Explains the tradeoffs between different Libra address lengths

### Bitcoin, Ethereum, and Libra addresses
Both Bitcoin and Ethereum account addresses are 160 bits. Addresses are computed by shortening a 256 bit public key:
Bitcoin: `ripemd160(sha2-256(<256 bit ECDSA public key>))` plus additionally 4 checksum bytes (see [here](https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses))
Ethereum: pick rightmost 160 bits of `keccak256(<256 bit ECDSA public key>)`
Libra: `sha3-256(<256 bit EDDSA public key>)` (no shortening step)

### Single and multi-target preimage attacks
- In Ethereum, a successful single-target preimage attack on a specific address A means that the attacker can send an arbitrary transaction from address A (e.g., steal the account’s funds)
- In Ethereum, a successful multi-target preimage attack on the set of existing account addresses A_1, … A_n means that the attacker can send an arbitrary transaction from some A_i (they cannot pick which one)
- In Libra, collisions are much less problematic because Libra accounts distinguish between account addresses (which are always the same) and authentication keys (which can be rotated as often as the user likes). When the Libra system checks the signature on a transaction, it looks at the account authentication key, not the account address. For an attacker to send an arbitrary transaction from a Libra address A, they would need to find a collision with A’s 256 bit authentication key, not with A itself (note: we are not proposing to shorten authentication keys!).
- However, the following attack is possible in Libra. If an attacker knows that some user intends to create an address A at some point in the future (e.g., because a smart contract has earmarked funds for that address) and the attacker can find a collision, the attacker can claim A with its own auth key. Note that finding a collision with an already-occupied address doesn’t let the attacker do anything; this only works if an account has not yet been created at A. This can be mitigated by earmarking for a commitment to an address.
- Multi-target attack: we cannot think of any compelling attack scenarios here
- Multi-target accidental collision: If an honest user (i.e., a custodial service) generates a new key, there is some probability that the fresh address will match an existing address in the blockchain and thus it will be discarded. The latter will cause confusion, more importantly because some key generation ceremonies are air-gapped and expensive, which means one will only know if there is a collision after the end of the key generation process.

Thus: single-target collisions seem potentially problematic (though not as bad as platforms where finding a collision leads to stolen funds), but multi-target collisions don’t.

**Comment by bob-wilson** [comment]
This is done now, right?
