### ISSUE TITLE
[network] Transport should be derived from advertised address

### ISSUE THREAD

**Issue by bothra90** [libra/libra#2771]
At present, the `transport` used for listening and dialing has to be configured manually (as `TcpNoise`, `Memory`, etc.). This means that there is room for programmer error, where we configure a transport that differs from the one that's advertised as part of the discovery protocol. 

To avoid this pitfall, it'll be nice to derive the transport programmatically from the advertised (or dialed, in case of clients) address. For example, `/ip/127.0.0.1/tcp/8080/noise_ik/2a38e78f6/` will automatically be configured as a `TcpNoise` transport.

**Comment by phlip9** [comment]
base transport (tcp, memory) is now derived from the `listen_address: NetworkAddress` field: https://github.com/libra/libra/pull/3849

@davidiw and I also concluded that it was cleaner (at least for now) to derive the trailing protocols w/ a separate configuration field (now called `AuthenticationMode`)

**Comment by phlip9** [comment]
closing for now. we might revisit this later when/if our protocol version upgrading needs become more pressing
