### ISSUE TITLE
[Bug] Error when transfering coins between accounts

### ISSUE THREAD

**Issue by ccastromar** [libra/libra#278]
# 🐛 Bug

When the user transfer coins between two accounts, an error is thrown: 
[ERROR] Failed to perform transaction: Transaction failed with vm status: Validation(UnknownScript)

## To reproduce

** Code snippet to reproduce **
```t 0 1 199```

** Stack trace/error message **
```
[ERROR] Failed to perform transaction: Transaction failed with vm status: Validation(UnknownScript)```

## Expected Behavior

It should transfer the coins 

**Please complete the following information:**
- <!-- Libra Version -->
Cloned current git version
- <!-- Rust Version -->
cargo 1.37.0-nightly (4c1fa54d1 2019-06-24)
release: 1.37.0
rustup 1.18.3 (435397f48 2019-05-22)

- <!-- Computer OS -->
Ubuntu 16.04.3 LTS

## Additional context

Any ideas?

**Comment by lucasverra** [comment]
check community, you need to deploy `testnet branch` client

**Comment by ccastromar** [comment]
Correct. Downloading testnet branch worked.

**Comment by kraisorna** [comment]
Seems testnet branch isn't merge to master yet. When will it merge into master?

**Comment by wqfish** [comment]
The testnet branch corresponds to the commit which we use to deploy the current validator servers. It won't be merged into master.
