### ISSUE TITLE
I Deploy a local  testnet with four validator use docker, but can't run mint command.

### ISSUE THREAD

**Issue by csunny** [libra/libra#280]
## ❓ Questions and Help

Recently I read the libra docs and codes,  I want to run a local testnet with multi-validator. 
First. I use command `cargo run -p libra_swarm -- -s` to run a local testnet with one validator, but it failed.  The problem just like this #277.   

With that problem, I change another way, I run four node with docker [Docker testnet](https://github.com/csunny/libra_toolchain/tree/master/deploy/testnet),  and everything goes ok,  but when i connect with client and run command `account mint 1 52` error raised. 

```
./start_cli_testnet.sh
Building and running client in debug mode.
    Finished dev [unoptimized + debuginfo] target(s) in 0.38s
     Running `/data/workspace/libra/libra/target/debug/client --host 127.0.0.1 --port 30307 -s ./trusted_peers.config.toml`
Connected to validator at: 127.0.0.1:30307
usage: <command> <args>

Use the following commands:

account | a
	Account operations
query | q
	Query operations
transfer | transferb | t | tb
	<sender_account_address>|<sender_account_ref_id> <receiver_account_address>|<receiver_account_ref_id> <number_of_coins> [gas_unit_price_in_micro_libras (default=0)] [max_gas_amount_in_micro_libras (default 10000)] Suffix 'b' is for blocking.
	Transfer coins (in libra) from account to another.
submit | submitb | s | sb
	<signer_account_address>|<signer_account_ref_id> <path_to_raw_transaction> Suffix 'b' is for blocking.
	Load a RawTransaction from file and submit to the network
help | h
	Prints this help
quit | q!
	Exit this client


Please, input commands:

libra% account list
No user accounts
libra% account create
>> Creating/retrieving next account from wallet
Created/retrieved account #0 address e3de4ee8018b2e76a00310df9180c16e0bc2d6f105d57d7d6e907a2e2ed6320b
libra% account create
>> Creating/retrieving next account from wallet
Created/retrieved account #1 address 6dc57872b0f2b7a8e6ee9255efa15fdb5cf4df7e23f79a61d22049aa059cf646
libra% account list
User account index: 0, address: e3de4ee8018b2e76a00310df9180c16e0bc2d6f105d57d7d6e907a2e2ed6320b, sequence number: 0, status: Local
User account index: 1, address: 6dc57872b0f2b7a8e6ee9255efa15fdb5cf4df7e23f79a61d22049aa059cf646, sequence number: 0, status: Local
libra% account mint 0 10
>> Minting coins
[ERROR] Error minting coins: error trying to connect: Connection refused (os error 111)
libra%
```
How can I fix this, and where is the source code?

**Comment by fbandersnatch** [comment]
Your client does not have the faucet key to mint coins.

You can either start an additional docker container for the faucet (docker file located in `docker/mint`) and pass the address to the client with `-f <address>` argument, or pass the faucet key to your client using the `-m <faucet_key>` command line option.

**Comment by SriRuleZ** [comment]
I face the same issue. I'm running a 4 node network via docker in my dev machine. I used the client to connect to the instance via faucet_key for dev i.e. mint.key in terraform/validator-sets/dev but the client shows error 

$ target/debug/client --host localhost --port 8000 --validator_set_file terraform/validator-sets/dev/trusted_peers.config.toml -m terraform/validator-sets/dev/mint.key

Error: Custom { kind: Other, error: "failed to fill whole buffer" }

I tried to build a mint node and bring it up via docker as well. It also shows the same error.

How do we mint within local instance of libra?

**Comment by caesarchad** [comment]
@SriRuleZ . 
Hi bro, how did you get the docker up and running, I could never make it happen, I got frustrated.
Are you using the docker/validator/build.sh and docker/validator/run.sh?

**Comment by csunny** [comment]
@caesarchad   No, I just custome it by myself,  you can view this https://github.com/csunny/libra_toolchain/tree/master/deploy/testnet.  maybe It can help you to solver your problem.

**Comment by princeulrich2** [comment]
Hi @csunny, I am also facing the same issue. Could you please let me know if you were able to solve it?

**Comment by princeulrich2** [comment]
Hi @caesarchad, I was also not able to run it using docker/validator/run.sh. You can use docker/validator-dynamic/build-dynamic.sh and docker/validator-dynamic/run.sh instead

**Comment by davidiw** [comment]
closing at as this has hopefully been resolved.
