### ISSUE TITLE
[Feature Request] Add configurable prefix for Vault secrets

### ISSUE THREAD

**Issue by mgorven** [libra/libra#2803]
# 🚀 Feature Request

The Vault client should support a configurable prefix for the key names created in Vault.

## Motivation

For the testnet usecase we should be able to run a single Vault instance which all validators use, for which we need unique keys per validator. For production with a shared Vault deployment, operators need to be able to namespace the validator's secrets in Vault.

## Pitch

Configuration:
```
[consensus.safety_rules.backend.vault]
key_prefix = "validator-1/"
```

LSR would create keys like `secret/validator-1/round`.

**Comment by davidiw** [comment]
Resolved
