### ISSUE TITLE
remove custom_test_frameworks nightly feature

### ISSUE THREAD

**Issue by bmwill** [libra/libra#285]
The `custom_test_frameworks` nightly feature needs to be removed from the codebase so that we can migrate to using the stable rust compiler.

See #270 for more information.

**Comment by sunshowers** [comment]
(I'd consider removing the feature nice to have but not blocking, as we always have the RUSTC_BOOTSTRAP workaround available for test code.)

**Comment by sunshowers** [comment]
https://github.com/commure/datatest/issues/4 has landed, so this should be possible now.

**Comment by bmwill** [comment]
Awesome! So the real blocker is #284 then. Also just to clarify, this should also work in the event we transition to beta next cycle?

**Comment by sunshowers** [comment]
Yeah, sorry about not being clear -- stable includes beta.
