### ISSUE TITLE
Ensure that all Boogie names are prefixed with $

### ISSUE THREAD

**Issue by wrwg** [libra/libra#2852]
Names used by Boogie internals need to be disjoint from names in the Move program. As Boogie allows `$` in names, to achieve this, we currently prefix those names with `$` which is not allowed in Move identifiers.

The `$` prefixing discipline is currently only applied for a subset of Boogie code. Specifically, it is not applied for procedures associated with byte code instructions and with types.

This work item is about using `$` prefixes systematically for all names declared in `src/prelude.bpl`.

**Comment by DavidLDill** [comment]
Could you be a bit more specific about where we need to add $'s? This is to avoid name clashes, so where might there be name clashes?

**Comment by emmazzz** [comment]
Just to confirm, this change should apply to all the (global)identifiers in prelude, including global consts/variables, function names, procedure names and type names such as `Path`?

**Comment by wrwg** [comment]
Yes, all global names.

One thing to check perhaps before doing this change is whether someone has outstanding commits because it would cause ugly merge conflicts. Also, when doing, it should likely be a swift surgery for the same reasons.
