### ISSUE TITLE
[RFC] Structured logging via log macros

### ISSUE THREAD

**Issue by andll** [libra/libra#2885]
This RFC proposes how we can extend our current logging macro to support structured logging

# Overview

Currently we use log macros such as `warn!`, `info!`, etc to produce textual logs.
Typical log line will look like
```
            debug!(
                "Peer {} is at round {} with hqc round {}, sending it {}",
                peer.short_str(),
                remote_round,
                remote_hqc_round,
                sync_info,
            );
```

This produces textual log, but this information is not structured.

# Proposal

We can adjust logging macro so that they can allow including argument names, such as:
```
            debug!(
                help_remote, # short event name
                "Peer {peer} is at round {round} with hqc round {hqc_round}, sending it {sync_info}",
                peer = peer.short_str(),
                round = remote_round,
                hqc_round = remote_hqc_round,
                sync_info = sync_info,
            );
```

This macro would then produce two separate entries
- Human-readable textual log, same as before
- Structured log entry such as
```
{"type": help_remote,
"peer": "...",
"round": ...,
...
}
```

# Benefits
There are few benefits of this approach
- It gives both structured and unstructured log with single macro invocation
- It allows gradually switching from textual logs to structured logs. You only need to slightly adjust existing logging macro to convert it to structured logging
- It allows fine grained slice and dice control over what is logged. For example, you could push logging config such as `only log help_remote for peer equal to xxx`. Having those expressions as macro would allow to build a very fast filtering for this type of configs.

**Comment by aching** [comment]
This is exciting to see this extension.  I suppose that timestamp as an implicit field could be represented in a human-readable format for human parseable logs, for example "2020-03-13 19:38:23:0001" for example and in machine logs as "timestamp": "1584153532521".  Or perhaps the machine logs could have both formats if it is useful.

**Comment by aching** [comment]
Also over time, there can be a way to associate valid values for a given key.  For example, a round should only take a u64 and not a string.  This would help with ensuring valid and useful keys and values for logs.

**Comment by davidiw** [comment]
This is now implemented. Time to close this out!
