### ISSUE TITLE
[Bug] failed to run custom build command for `network v0.1.0

### ISSUE THREAD

**Issue by Chanutg** [libra/libra#29]
# 🐛 Bug

## To reproduce

** Code snippet to reproduce **
```rust
./scripts/cli/start_cli_testnet.sh
```

** Stack trace/error message **
```
  process didn't exit successfully: `/libra/target/debug/build/network-3bce66de4ba49a2b/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/network.proto
cargo:rerun-if-changed=src/proto/mempool.proto
cargo:rerun-if-changed=src/proto/consensus.proto

--- stderr
thread 'main' panicked at 'protoc: Custom { kind: NotFound, error: StringError("failed to spawn `\"protoc\" \"--version\"`: No such file or directory (os error 2)") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

## Expected Behavior

Juste wanted to build the system and connect to a node in testnet.

## System information

**Please complete the following information:**
-  
- 
- Fedora release 29

**Comment by mwawrusch** [comment]
Same error on MacOS.

**Comment by jeamick** [comment]
Did you checked if you have all the dependencies as mentioned in the Readme ?

Installs **rustup** — rustup is an installer for the Rust programming language, which Libra Core is implemented in.
Installs the required versions of the **rust-toolchain**.
Installs **CMake** 
Installs **protoc** 
Installs **Go** 

@mwawrusch @Chanutg 

I had this problem and installing the dependencies solved the issue.

**Comment by Chanutg** [comment]
They are installed with the first script following this tutorial : https://developers.libra.org/docs/my-first-transaction#step-1-check-if-the-cli-client-is-running-on-your-system

**Comment by jeamick** [comment]
Did you verified the troubleshooting section?

**Comment by aecdanjun** [comment]
i just tried to run this command: https://developers.libra.org/docs/my-first-transaction#build-libra-cli-client-and-connect-to-the-testnet

and I got this error:

```
error: failed to run custom build command for `network v0.1.0 (/home/aecio/workspace/libra/libra/network)`

Caused by:
  process didn't exit successfully: `/home/aecio/workspace/libra/libra/target/debug/build/network-3bce66de4ba49a2b/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/network.proto
cargo:rerun-if-changed=src/proto/mempool.proto
cargo:rerun-if-changed=src/proto/consensus.proto

--- stderr
google/protobuf/wrappers.proto: File not found.
transaction.proto: Import "google/protobuf/wrappers.proto" was not found or had errors.
transaction.proto:160:5: "google.protobuf.UInt64Value" is not defined.
mempool.proto: Import "transaction.proto" was not found or had errors.
mempool.proto:17:12: "types.SignedTransaction" is not defined.
thread 'main' panicked at 'protoc: Custom { kind: Other, error: StringError("protoc (\"protoc\" \"-I../types/src/proto\" \"-Isrc/proto\" \"--descriptor_set_out=/tmp/protoc-rust3Ux22n/descriptor.pbbin\" \"--include_imports\" \"src/proto/network.proto\" \"src/proto/mempool.proto\" \"src/proto/consensus.proto\") exited with non-zero exit code") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

More info: 

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

```


`Linux casa 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Chanutg** [comment]
I think problem is from protobuf-compiler, either it's not installed, or maybe there is multiple protobuf in our system ?

**Comment by Chanutg** [comment]
http://google.github.io/proto-lens/installing-protoc.html

Working thanks
