### ISSUE TITLE
[Bug] [move-prover] Prover produces false counterexamples on multiplication of two u64 (or u128) / Boogie does not distinguish undefined SAT result of Z3

### ISSUE THREAD

**Issue by junkil-park** [libra/libra#2953]
# 🐛 Bug
Prover produces false counterexamples for the cases of multiplication of two integers. The concrete examples are the test cases called `overflow_u64_mul_ok` and `overflow_u128_mul_ok`
in `/path/to/libra/language/move-prover/tests/sources/arithm.move`.

## To reproduce
First, uncomment the specifications of functions `overflow_u64_mul_ok`(`overflow_u128_mul_ok`) in `/path/to/libra/language/move-prover/tests/sources/arithm.move`.

Next, do the following commands:
```
cd /path/to/libra/language/move-prover
cargo run tests/sources/arithm.move 
```

**Stack trace/error message**
```
error:  A postcondition might not hold on this return path.

     ┌── tests/sources/arithm.move:185:9 ───
     │
 185 │         aborts_if x * y > 18446744073709551615u64;
     │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     │
     =     at tests/sources/arithm.move:181:5: overflow_u64_mul_ok (entry)
     =     at tests/sources/arithm.move:182:11: overflow_u64_mul_ok
     =         x = 3809,
     =         y = 512,
     =         result = 1949696
     =     at tests/sources/arithm.move:181:5: overflow_u64_mul_ok (exit)
```

## Expected Behavior

Either it is proved, not reporting any error/counterexample, or Prover hangs on it because it involves non-linear arithmetic which is understood as an obstacle to Prover in general.

## Additional context

**Comment by shazqadeer** [comment]
I looked into this issue.  I see that Z3 reports SAT with

(:reason-unknown "(incomplete (theory arithmetic))")

It is strange that the incompleteness shows up only with U64 and U128 but not with U8.

**Comment by shazqadeer** [comment]
This post explains how Z3 deals with integer non-linear arithmetic: https://stackoverflow.com/questions/13898175/how-does-z3-handle-non-linear-integer-arithmetic?rq=1.  The explanation there does seem to explain why U8 is verified but not the larger sizes.

**Comment by wrwg** [comment]
Conclusion: we should investigate how we can mitigate this, including running tests to validate counter examples.

**Comment by junkil-park** [comment]
@shazqadeer, @wrwg, @DavidLDill, The newer version (4.8.8) of Z3 reimplemented the non-linear integer arithmetic (https://github.com/Z3Prover/z3/blob/48a2d3d5b60cbaeee4d9dcce1670d6c2e261b981/RELEASE_NOTES#L19). I tested, and it seems that it resolves our multiplication problem of this github issue. It would be good if someone could double check this. If that is the case, could we close this issue, and thinking about upgrading Z3 to 4.8.8 all over the places?

**Comment by wrwg** [comment]
We should always use the latest official version of Z3, independent of whether it fixes something for us -- unless for some reason it breaks us. So I would suggest we just try whether we can upgrade. The upgrade would need to be tested locally, then our scripts would need to be updated, and at the same time MIRAI bot.

**Comment by junkil-park** [comment]
That sounds good! How about Boogie? Clark(@cbarrettfb) recently suggested to upgrade our Boogie version (2.5.7), which I also noticed, is quite lagged behind from the latest official one (https://www.nuget.org/packages/Boogie). It would be nice to keep our Boogie version up to date, but my only little concern is that Boogie is being updated quite often these days.

**Comment by wrwg** [comment]
We wouldn't update likely more frequently then every 1-2 month, after careful vetting that everything still works.
