### ISSUE TITLE
Could be built on Bismuth instead

### ISSUE THREAD

**Issue by hclivess** [libra/libra#3]
Why not start on a well-tested new, modern and established platform like $BIS #Bismuth? It is even written in Python, which is much more popular and readable than Rust.

**Comment by dfischer** [comment]
Python would be terrible for scalability and stability over Rust.

**Comment by hclivess** [comment]
Scalability is a design decision, it has nothing to do with the programming language itself. Same goes for stability. Python is more versatile because of the wide range of modules.

**Comment by ericnakagawa** [comment]
Hi folks, we're open to feedback. The best place to chat with our engineering team is on our [Community](https://community.libra.org)

**Comment by dfischer** [comment]
@hclivess Python is inherently less secure compared to Rust which is extremely important for a crypto related project :).
