### ISSUE TITLE
[Bug] ./scripts/dev_setup.sh --compare-versions

### ISSUE THREAD

**Issue by iamonuwa** [libra/libra#30]
# 🐛 Bug

When running ./scripts/dev_setup.sh on Ubuntu 18.04, the script fails with:

```./scripts/dev_setup.sh: line 121: /usr/local/bin/protoc: cannot execute binary file: Exec format error
dpkg: error: --compare-versions takes three arguments: <version> <relation> <version>

Type dpkg --help for help about installing and deinstalling packages [*];
Use 'apt' or 'aptitude' for user-friendly package management;
Type dpkg -Dhelp for a list of dpkg debug flag values;
Type dpkg --force-help for a list of forcing options;
Type dpkg-deb --help for help about manipulating *.deb files;

Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
```

## To reproduce

** Code snippet to reproduce **
 1. git clone https://github.com/libra/libra.git && cd libra
 2. ./scripts/dev_setup.sh

## System information

**Please complete the following information:**
-  latest version cloned from GitHub
-  rustc 1.36.0-nightly (50a0defd5 2019-05-21)
-  Ubuntu 18.04

**Comment by tvoegel** [comment]
Have the same problem

**Comment by modavidc** [comment]
Me too.

**Comment by modavidc** [comment]
I am using Ubuntu 18.04 and this solution work for my case. 

Steps: 

1. Uninstall last protoc versions. 

`whereis protoc
sudo rm -r /usr/local/bin/protoc 
and sudo rm -r allProtocLocation
`
2) Install protoc from https://google.github.io/proto-lens/installing-protoc.html 

> Use the Linux steps. 

3) Check the installation with: 

`protoc --version`

4) That is all.

**You can continue the libra tesnet steps **

**Comment by icarter09** [comment]
@iamonuwa are you still experiencing this issue?

**Comment by bmwill** [comment]
The dev-setup script has been simplified and only installs rust now, so this shouldn't be an issue anymore on master. If it is, please let us know.
