### ISSUE TITLE
[move-prover] [Feature Request] enable Rust code coverage for Move prover 

### ISSUE THREAD

**Issue by junkil-park** [libra/libra#3043]
# 🚀 Feature Request

Enable some relevant tools to analyze the code coverage of Move prover

Herman recommended:
* https://github.com/mozilla/grcov
* https://codecov.io/

## Motivation

To analyze the code coverage for Move prover

## Pitch

* grcov
* codecov

## Additional context

**Comment by bob-wilson** [comment]
This already exists:
https://codecov.io/gh/libra/libra/tree/master/language/move-prover

I don't know if the standard CI tests exercise the Move prover as much as you'd like for coverage. If not, you can also run it locally via scripts/coverage_report.sh or perhaps we could change CI to include that automatically.

**Comment by junkil-park** [comment]
Thank you for the information! These look good. It seems that the result from `codecov.io` is a bit different from that of `coverage_report.sh` (based on `gcov/lcov`). For example, the line coverage of `language/move-prover/src` is 62.3% according to `codecov.io` while `gcov` says it's 86%. Do you know which one is considered to be more accurate in general?

**Comment by bob-wilson** [comment]
The results on codecov.io are generated by running that script, so the numbers should be the same (modulo any changes in the time since codecov.io was updated). Perhaps you ran different tests than in CI?

**Comment by junkil-park** [comment]
I will close this issue after writing this comment for the sake of logging.

> It seems that the result from `codecov.io` is a bit different from that of `coverage_report.sh` (based on `gcov/lcov`). For example, the line coverage of `language/move-prover/src` is 62.3% according to `codecov.io` while `gcov` says it's 86%. Do you know which one is considered to be more accurate in general?

It turns out that the code coverage result by `codecov.io` is based on the analysis where Boogie is not invoked (because the env var `BOOGIE_EXE` is not set). Thus, doing the coverage analysis locally using `coverage_report.sh` with `BOOGIE_EXE` set should give a more accurate report. The instruction regarding local coverage test can be found in `libra/language/move-prover/tests/README.md`.
