### ISSUE TITLE
[move-prover][Feature Request] Show abortion points in execution traces

### ISSUE THREAD

**Issue by DavidLDill** [libra/libra#3140]
# 🚀 Feature Request

Clearly show where "abort" happens in debug trace.

## Motivation

When an abort fails, it is not always easy to figure out exactly what happened.  
## Pitch

It would be nice if the point where $abort_flag was set to true was clearly marked in the execution trace.

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by wrwg** [comment]
The prover explicitly generates code for tracking abortion points, and it used to work (in same cases). If you have a counterexample that would be great.
