### ISSUE TITLE
[Key Management] Managing Validator Config

### ISSUE THREAD

**Issue by valerini** [libra/libra#3161]
This issue outlines changes to move modules that are necessary for proper key management as described in[ this github issue](https://github.com/libra/libra/issues/2332).

## Background
Currently each validator has:
1) a top level [authentication_key](https://github.com/libra/libra/blob/883a2b92462f019a1b80c81a7608e640be729caa/language/stdlib/modules/libra_account.move#L18) managed by libra_account module and
2) ValidatorConfig::Config resource that includes the [consensus_pubkey](https://github.com/libra/libra/blob/bb4c7343083264a24c78cb74538093f177778113/language/stdlib/modules/validator_config.move#L9).

This issue introduces an intermediate key that will be stored as authentication_key under the delegated account, this key will be capable of rotating the ValidatorConfig::Config (including the consensus pubkey and network information).

This key will serve two purposes:
* for validator who are capable of deploying cold-warm-hot key hierarchy, this key will be warm key (cold = air-gapped, human operated for disaster recovery; warm = stored in the HSM used regularly; hot = used very frequently, stored in RAM).
* for validators who want to delegate running their nodes to third parties, the delegated account address will be a third-party's account.

## Design
The ValidatorConfig::Config resource will store additional fields:
```
        managing_delegated: bool,
        delegated_address: address,
```
The ValidatorConfig module will get an additional function:
```
    public fun rotate_consensus_pubkey_by_delegate(validator_address: address, new_consensus_pubkey: vector<u8>, proof: vector<u8>) acquires T {
        let t_ref = borrow_global_mut<T>(validator_address);
        Transaction::assert(!t_ref.managing_delegated, 11);
        Transaction::assert(Transaction::sender() == t_ref.delegated_address, 1);
        Transaction::assert(Vector::length(&new_consensus_pubkey) == 32, 12);
        let key_ref = &mut t_ref.config.consensus_pubkey;
        *key_ref = new_consensus_pubkey;
        // TODO: check the proof
    }
```

## Checking the proof
To check the proof we construct a byte-array:
m = sha3-256(sha3-256(b"ConsensusPubKeyRotation", [LIBRA_HASH_SUFFIX](https://github.com/libra/libra/blob/883a2b92462f019a1b80c81a7608e640be729caa/crypto/crypto/src/hash.rs#L103)) || validator_address)
And check that the proof is a valid signature on this message under the `new_consensus_pubkey`:
`Transaction::assert(!ed25519_verify(proof, new_consensus_pubkey, m), 1)`

## Milestones
M0: Implement the ACL in ValidatorConfig resource that will store the delegated_address. The sender from this address should be able to rotate the components of ValidatorConfig::Config.

M1: Figure out if it is possible simplify the LibraSystem module by moving rotation code out. Validators should still be able to ping the LibraSystem to reconfigure in case emergency reconfiguration is needed.

M2: Work on reconfiguration in LIbraSystem:
* Add a separate event to LibraSystem, ValidatorConfigsChangeEvent, it will be used to signal the changes to the validators' configs, the current event, ValidatorSetChangeEvent, will be used to change the set of addresses of the validators (e.g. when the Association adds/removes a validator).
* Reconfiguration in LibraSystem should copy ValidatorConfigs from validators accounts into the LibraSystem::ValidatorSet. If none of the configs have changed, the ValidatorConfigsChangeEvent is not emitted. This reconfiguration should occur at regular intervals as well as upon the invocation of the Libra Association's account.
* Each validator can fast-track the update of his config in the LibraSystem::ValidatorSet if at least some T amount of time has passed since the last reconfiguration.

M3: Add a proof for key ownership
Implement a verification check that proves the ownership of a Consensus key on each key rotation.

**Comment by davidiw** [comment]
Overall looks good. Haven't starred at the move code.
Some comments:
1) Interface to set / replace / disable delegation
2) Do we want a single interface that updates the entire ValidatorConfig or one for each individual field? e.g., one for each networking and one for consensus or just a composite that takes appropriate proof of correctness?
3) When generating this the first time, do we want a proof of correctness? What does the creation API look like as a result?

**Comment by davidiw** [comment]
A few other thigns:
*  a scheme field for crypto agility somewhere in the ValidatorSet(Resource) -- both in move and rust @zekun000 
* rotation policies
* cleaning up discovery* @phlip9 

We should probably call this managing ValidatorConfig with a subsection on key management.

**Comment by valerini** [comment]
Thanks for your comments, @davidiw!
1. I suggest the following 4 functions (this code compiles): set delegate, remove delegate, is delegated, get delegated address:
```
    public fun set_delegated_address(delegated_address: address) acquires T {
        Transaction::assert(LibraAccount::exists(delegated_address), 1);
        let t_ref = borrow_global_mut<T>(Transaction::sender());
        *(&mut t_ref.managing_delegated) = true;
        *(&mut t_ref.delegated_address) = delegated_address;
    }

    public fun remove_delegated_address() acquires T {
        let t_ref = borrow_global_mut<T>(Transaction::sender());
        *(&mut t_ref.managing_delegated) = false;
        *(&mut t_ref.delegated_address) = 0x0;  
    }

    public fun is_delegated_address_set(): bool acquires T {
        let t_ref = borrow_global<T>(Transaction::sender());
        t_ref.managing_delegated        
    }

    public fun get_delegated_address(): address acquires T {
        let t_ref = borrow_global<T>(Transaction::sender());
        t_ref.delegated_address
    }

```

2. I would prefer separate functions for updating parts of ValidatorConfig. Because for example, networking keys might be updated at different frequencies and by some different parts of the system.

3. By "proof of correctness" do you mean the proof of knowledge of the corresponding secret keys? This is a very interesting topic, we need to discuss this a bit more.

* For rotation policies I suggest adding a field `Y: u64` in libra_system and this will be the period of time for regular reconfigurations (i.e. after every Y blocks/hours, the reconfiguration will run and the keys will get copied from validators' accounts to the Association's account). So the suggestion for validators would be to rotate consensus_pubkey locally after every Y blocks/hours. What do you think?

**Comment by davidiw** [comment]
All seems good, I'd like to know if you think we should have is_delegated_address(address) or get_delegated_address... I think we can avoid a copy if we use is_delegated_address and we don't really need to export that data for other reasons afaik.

what resource / struct would you add the reconfiguration time to? I know that @christinacelee and @runtian-zhou are working on a on-chain config, would it belong there?

**Comment by valerini** [comment]
The linked pull-requests mostly resolved this issue (except for the proof of key ownership which we might substitute with the check that all keys in the validator set are distinct - TBD).

A new issue is up with remaining work items: [Issue 4676](https://github.com/libra/libra/issues/4676)
