### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DavidLDill** [libra/libra#3183]
# 🐛 Bug

The Move Prover generates Boogie ensures conditions that use "==" instead of "IsEqual" when comparing a vector reference to a slice of a vector.  This causes the assertion to fail when it should not.

When I looked at the translation code, it seems to consistently generate IsEqual, so I'm not sure where "==" is getting generated.

## To reproduce

**Code snippet to reproduce**
```rust
// dep: tests/sources/stdlib/modules/vector.move
module TestVector {
    use 0x0::Vector;


    fun sl<Element>(v: &mut vector<Element>): Element {
        Vector::pop_back(v) // inlining the built-in Boogie procedure
    }
    spec fun sl {
        ensures v == v[0..len(v)];  // gets an error, even t hough it's an identity.
	ensures v[0..len(v)] == old(v[0..(len(v)-1)]); // no error
    }
}
```

**Stack trace/error message**
```
cargo run  tests/sources/stdlib/modules/vector.move tests/sources/test-slice.move 
    Finished dev [unoptimized + debuginfo] target(s) in 0.45s
     Running `/Users/dill/Work/CODE/junkil-libra/libra/target/debug/move-prover tests/sources/stdlib/modules/vector.move tests/sources/test-slice.move`
error:  A postcondition might not hold on this return path.

    ┌── tests/sources/test-slice.move:10:9 ───
    │
 10 │         ensures v == v[0..len(v)];
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
    │
    =     at tests/sources/test-slice.move:6:5: sl (entry)
    =     at tests/sources/test-slice.move:7:17: sl
    =         v =
    =           &vector{
    =             152: <generic>,
    =             5751: <generic>,
    =             <generic>,
    =             else: <generic>},
    =         v =
    =           &vector{
    =             152: <generic>,
    =             5751: <undef>,
    =             <generic>,
    =             else: <generic>}
    =     at tests/sources/test-slice.move:6:5: sl (exit)

Error: exiting with boogie verification errors
```

## Expected Behavior

The ensures condition should hold.

## System information

**Please complete the following information:**
- 
- 
- 

## Additional context

Here is the Boogie spec for the offending function with ** around the == and IsEqual

procedure {:inline 1} $TestVector_sl ($tv0: TypeValue, v: Reference) returns ($ret0: Value)
requires $ExistsTxnSenderAccount($m, $txn);
ensures !$abort_flag ==> (b#Boolean(Boolean(($Dereference($m, v)) **==** ($slice_vector($Dereference($m, v), $Range(Integer(0), $vlen_value($Dereference($m, v))))))));
ensures !$abort_flag ==> (b#Boolean(Boolean(**IsEqual**($slice_vector($Dereference($m, v), $Range(Integer(0), $vlen_value($Dereference($m, v)))), old($slice_vector($Dereference($m, v), $Range(Integer(0), Integer(i#Integer($vlen_value($Dereference($m, v))) - i#Integer(Integer(1))))))))));

**Comment by junkil-park** [comment]
The bug fix for this issue is included in https://github.com/libra/libra/pull/3054.
