### ISSUE TITLE
[Bug] My First Transaction

### ISSUE THREAD

**Issue by pkrasam** [libra/libra#32]
# 🐛 Bug

## To reproduce
When going through “My First Transaction” using this developer documentation it is failing in Step 3.

** Code snippet to reproduce **

[Libra CLI](https://developers.libra.org)
./scripts/cli/start_cli_testnet.sh

// Paste the output here
<img width="998" alt="190618_libra_testnet_build_error" src="https://user-images.githubusercontent.com/4514654/59689041-3ce9a800-9222-11e9-94f2-aa1ffbe6b218.png">

**Comment by jpthor** [comment]
You are missing some dependencies. 

Run this:

```
brew install libsodium rocksdb pkg-config protobuf cmake
```

**Comment by wayne-china** [comment]
> You are missing some dependencies.
> 
> Run this:
> 
> ```
> brew install libsodium rocksdb pkg-config protobuf cmake
> ```

The same error occured to me in centos , what should i install?  The same command?

**Comment by wayne-china** [comment]
Someone meet the same error in CentOS ?

**Comment by icarter09** [comment]
@pkrasam and @wayne-china I went over the issue log and noticed a few tickets related to CentOS: #205, #184, #157, and #209. Please look them over and see if any of those contain a solution to your current issue. Thanks.

**Comment by raguiar2** [comment]
@wayne-china  For CentOS, have you tried sudo yum install libsodium rocksdb pkg-config protobuf cmake

**Comment by bmwill** [comment]
The external dependencies needed to build Libra have been simplified and should only require Rust now so this shouldn't be an issue anymore on master. If it is, please let us know.
