### ISSUE TITLE
[move-prover] Change numbering of result variables

### ISSUE THREAD

**Issue by shazqadeer** [libra/libra#3213]
Result variables should be 0-indexed, i.e., they should be result_0, result_1, ... rather than result_1, result_2, ...

**Comment by wrwg** [comment]
Can you explain why? Numbering often starts at 1 not at 0.

**Comment by shazqadeer** [comment]
I am not certain of my suggestion.  We should use the convention that the Move language team might already be using (or is comfortable with) for referring to return values at the bytecode.

**Comment by wrwg** [comment]
@tnowacki 

Ideally, if Move would have tuple selection, we would align with this and make it `result.i` instead of `result_i`. I guess in that case, if this feature is ever planned, starting at 0 would make sense.

**Comment by tnowacki** [comment]
Where exactly is this being used? I feel like I'm missing some context here. 

But brain dump on move "tuples"
- Move (the source language) doesn't really have tuples right now, it has these things that look like tuples, but are really a tracking of the top `n`-elements on the execution stack. 
- As a result from that implementation detail, the compiler does not support binding them to local variables or anything of the like
- I want tuples at the bytecode level, but they are low priority. Additionally, there would be a good bit of compiler work to then "inline" the tuples back onto the stack when I can (i.e. recreating the current behavior as an optimization)
- Adding something like `result.i` ala Rust seems like a good design decision, if we also add positional struct declarations (`struct Foo(u64, u64, bool)`). I could also see us doing `result[i]` if we don't add that feature, as it might feel weird having `result.i` as a standalone

**Comment by wrwg** [comment]
@tnowacki the context for this is referring to function results in spec conditions:

```
fun foo(x: u64): (u64, u4) { ... }
spec fun foo {
    ensures result_1 == x + 1;
    ensures result_2 == x + 2;
}
```

As you see we currently used a special symbol for this (which is just `result` if the function has a single return value).

We can stay with this until the point some kind of tuple notation is supported. `result[n]` wouldn't work because of heterogenous typing, and we use `[]` already for array indexing.

**Comment by tnowacki** [comment]
Can you do temporary bindings?

Like, 
```
let (r1, r2) = result;
ensures r1 == x + 1;
ensures r2 == x + 2;
```

**Comment by wrwg** [comment]
The current solution works well. Shaz and I where just discussing a tiny detail (start counting at 0 or 1), and in that context I brought up the question where the Move language is going here. There is no urgency, we can align once you actually introduce tuples (or stay with what we have).

As Move doesn't have tuples yet, in your suggestion it is unclear what type `result` would have. It also appears more verbose as it needs to be. As said what we have right now works.

**Comment by tnowacki** [comment]
I'd say that `result.i` syntax is definitely on the table. But I'd like to not add it unless we add all the other things that make my "tuples" into actual *tuples*
