### ISSUE TITLE
[JSON-RPC] Expose appropriate resources for key-manager

### ISSUE THREAD

**Issue by JoshLind** [libra/libra#3217]
## Motivation

The key-manager is responsible for periodically rotating the consensus key of each validator node. As all validator consensus keys are registered on the Libra blockchain, the key-manager must be able to read and write directly to the blockchain. For example, the key-manager must be able to: (i) on each rotation, write a transaction to the blockchain that updates the currently registered on-chain consensus key for each node; (ii) read the timestamp of the most recent reconfiguration event (to ensure a rotation has executed correctly); and (iii) read the latest validator config (to re-synchronize after a potential failure).

To read and write to the Libra blockchain, we propose using the JSON-RPC interface. However, the JSON-RPC interface does not currently expose all the on-chain resources required by the key-manager. To address this, we propose making several modifications to the JSON-RPC interface; specifically, we propose giving the key-manager access to: (i) the `validator_config_resource`; (ii) the `validator_set_resource`; and (iii) the `libra_timestamp_resource`. To achieve this, we argue for the following modifications:

#### (Client implementation): Provide the following new public methods to the JSON-RPC Client API:

1. `get_validator_config_state(validator_account: AccountAddress) -> Result<ValidatorConfigView>` (Returns the validator config associated with a given validator account.)
2. `get_validator_set_state(validator_set_account: AccountAddress) -> Result<ValidatorSetView>` (Returns the validator set for a given validator set address. The `ValidatorSetView` contains a list of validator info's -- one for each validator.)
3. `get_libra_timestamp_state(accounts: AccountAddress) -> Result<LibraTimestampView>` (Returns the Libra timestamp state associated with the given account.)

#### (Service implementation): Provide the following new methods on the JSON-Server API:

1. `get_validator_config_state(service: JsonRpcService, params: Vec<Value>) -> Result<Option<ValidatorConfigView>>` (Returns an optional validator config associated with a given validator account held in params.)
2. `get_validator_set_state(service: JsonRpcService, params: Vec<Value>) -> Result<Option<ValidatorSetView>>` (Returns the optional validator set for a given validator set address held in params.)
3. `get_libra_timestamp_state(service: JsonRpcService, params: Vec<Value>) -> Result<Option<LibraTimestampView>>` (Returns the optional Libra timestamp state associated with the given account.)

As part of this modification, we'll need to create and expose four new views: 

1. `ValidatorConfigView`: will expose each field held in the `ValidatorConfig` struct.
2. `ValidatorSetView`: will expose each field held in the `ValidatorSetResource` struct. Internally, we'll define another view (`ValidatorInfoView`, below) representing the corresponding `ValidatorInfo` for each validator in the set.
3. `ValidatorInfoView`: will expose each field held in the `ValidatorInfo` struct.
4. `LibraTimestampView`: will simply expose the single field in the `LibraTimestamp` struct.

## (Optional) Optimization 

We note that as the `LibraTimestampView` currently only holds a single field (the `microseconds` field), we could instead expose the `LibraTimestamp` resource for each account using an optional field in the already defined `AccountView`. Doing this would avoid having to implement an additional method/view for each of the above sections. 

However, it's currently unclear whether or not the `LibraTimestampResource` would grow to hold more values in the future. Moreover, given that this resource is currently exclusive to the `association_address`, it might not make sense to expose this for all addresses through the `get_account_state` client API call.. As such, I've noted the possibility for this, but any thoughts/opinions would be appreciated!

## Implementation Plan

Given that these changes are quite small and self contained, I'll make the modifications in a single PR, but we wanted to provide a place for feedback before doing this! Thanks!

**Comment by davidiw** [comment]
Overall looks good, some notes:
* LibraTimestamp currently isn't used in KeyManager, but it is already exposed via the get_metadata function
* Reconfiguration timestamp comes from the ValidatorSetResource
* We can propose either allowing us to read the ValidatorSetResource from any account or just the account that it is expect to reside on (which is in line with your proposed optimization)

Looks good!

@christinacelee, @sunmilee, @phoenix-antigravity, any comments?

**Comment by christinacelee** [comment]
This looks cool! I don't think these on-chain configs are not actually on-chain configs now, so we probably want to make that change first. This would include defining the access path under which these on-chain configs would be stored, so the client params may have to change accordingly

**Comment by thefallentree** [comment]
could we consolidate these together into get_metadata() ?  There are a lot of downside of separating it. because in naive implementations, different json-rpc request could hit different FN that is not in sync , also could return data that is in different version. 

So, unless there are strong concerns, we should keep just 1 method that returns everything .  add more flags if you want it to return some optional portion of it.

**Comment by davidiw** [comment]
> could we consolidate these together into get_metadata() ? There are a lot of downside of separating it. because in naive client implementations, people will send this as different json-rpc requests , which could be hitting different FN that are not in sync , which could return data that is under different block version. Which is going to be a big issue. The client would need to batch requests, and server need to also understand batching context (These are currently unfinished). And your method needs to specific version too. All these are pointless complexity that defeat the original intention have them as separate method in the first place.
> 
> That's why I say just extend get_metadata() , adding more fields are never an issue in the API, especially since we are not declared api V1 yet.
> 
> This is already an issue with other API method that we have , but those are less serve
> 
> So, unless there are strong concerns, we should keep just 1 method that returns everything . you can just add more optional bool parameters if you want it to not return some of it by default.

Two concerns:
1) ValidatorConfig is already per account, so it would need to be an explicit query
2) Size, get_metadata currently is tiny. ValidatorSet could be 50KB. A single ValidatorInfo could be 500B. I think leveraging what you're saying a reasonable approximation would be to include the get_metadata info into these individual queries?

**Comment by phoenix-antigravity** [comment]
I'd prefer it to stay in separate API. It doesn't look that info is necessary for average client in trustful setup and payload size increase is concerning. Clients that do need this data can easily batch it in single json-rpc request with `get_metadata` and it will be processed by the same server in single http request

On more general note, do we anticipate those endpoints to be widely used besides tooling like key-manager? I wonder if this approach is scalable. Do we plan to create new rpc endpoint for each new on-chain data structure that such sophisticated tooling may want to query? 
Alternatively, we can just provide general rpc endpoint that returns LCS bytes for given access path

**Comment by davidiw** [comment]
1) I don't think we'll have a need beyond this.
2) Batching with a get_metadata seems fine.
3) @thefallentree suggested deciphering ValidatorConfig as a portion of get_account and returning null otherwise, that seems fine -- but maybe... we just return back an LCS encoded blob... so let's not do 3 and let's focus on 4
4) I am okay if we provide a general purpose rpc endpoint that returns LCS bytes for a given access path or even just the account state blob. So perhaps the best solution is to just for now add a get_account_state_blob that returns the entire account in lcs format? (I personally would not like to add a flag to get_account_state that might return a blob).

**Comment by sunmilee** [comment]
Would payload size increase really be an issue if we are adding optional returns indicated by optional parameters? 

In terms of API cleanliness I would prefer keeping it separate, but Yucong makes a good point. If we are OK with trusting the client side to batch the request with get_metadata, keeping it separate is fine. Would want to indicate in some documentation that out of sync fetch may be an issue if not batched.

**Comment by phoenix-antigravity** [comment]
> 3. @thefallentree suggested deciphering ValidatorConfig as a portion of get_account and returning null otherwise, that seems fine -- but maybe... we just return back an LCS encoded blob... so let's not do 3 and let's focus on 4

it works, but really not sure if that's a right way going forward. Will we add optional fields for each potential thing that can be stored under account. Also not big fan of optional API

> 4. I am okay if we provide a general purpose rpc endpoint that returns LCS bytes for a given access path or even just the account state blob. So perhaps the best solution is to just for now add a get_account_state_blob that returns the entire account in lcs format? (I personally would not like to add a flag to get_account_state that might return a blob).

* why do you need whole blob instead of specific path here though?
* I think you can just call rpc method `get_account_state_with_proof`. As part of proof it should return you LCS for a whole account blob

**Comment by davidiw** [comment]
Oh I see, we already have this blob API, sorry, was looking at a document and not the code. The code indeed exists for what we need. Fantastic!

https://github.com/libra/libra/blob/master/json-rpc/src/methods.rs#L217

Thanks for everyone's input. I think there is no need to amend the API then. Unless there is value to exposing this information for other purposes?

**Comment by JoshLind** [comment]
Thanks everyone for the comments/pointers! Given that we can get access to the entire AccountStateBlob (through 'get_account_state_with_proof') and that there isn't an immediately obvious reason to expose additional JSON-RPC API calls (for now..), I don't think I'll need to make any JSON-RPC modifications.

I'll continue with my dependent tasks and assuming everything goes to plan close this issue in a few days. I'll keep it open in case I run into any unseen issues for now... Thanks again!
