### ISSUE TITLE
[network] Enhance message rate-limiting for better protection and observability

### ISSUE THREAD

**Issue by bothra90** [libra/libra#3255]
After #3251, the network module has the ability to rate-limit inbound messages from peers. This could be enhanced in several ways:
* Make the rate-limit parameters tune-able -- globally or even per-peer
* Add monitoring/alerts for when this limit is being hit for a peer
* The parameters can self-adjust dynamically to adapt to overall link saturation

**Comment by Rustinante** [comment]
Hi, could you please elaborate more on what making it tunable peer-to-peer would entail? Thanks.

**Comment by Rustinante** [comment]
Hi @bothra90 Do you have any suggestions on how to measure the overall link saturation?
