### ISSUE TITLE
[network] Improve directory structure of network crate

### ISSUE THREAD

**Issue by bothra90** [libra/libra#3343]
The directory structure of the network module no longer makes sense given the changes it has undergone since the original unveil. Some examples are:
  - `rpc` and `health_checker` are in the same directory, even though health_checker is now simply a network client. Similar argument holds for `discovery` and `connection_manager` (also see #775).
  - `NetworkProvider` module defined in `network/src/interface/mod.rs` is not the the network interface.
  - `ConnectionHandler` and `PeerManager` (or whatever it ends up being called) are in the same file. They should be in different modules since they have very different concerns - the former is solely responsible for handling inbound and outbound connections, where as `PeerManager` provides multiplexing of messages from and to different nodes and upstream clients.
  - The `NetworkSender` and `NetworkEvent` types which are the client-level structs should not be buried deep in `network/src/protocols/network/mod.rs`.
  - The wire spec modules (`handshake` and `messaging`) should be moved to a separate crate with minimal dependencies so it can be shared between LibraNet and other safe implementations.
  - The `validator_network` module is no longer useful and is a relic from a time when we only supported validator nodes on the network.

**Comment by gregnazario** [comment]
I think the content of this is no longer applicable, but the thought behind it is still applicable.  I'm going to close this though and we can open a new refactor networking issue.
