### ISSUE TITLE
[network] Improve error propagation and handling

### ISSUE THREAD

**Issue by bothra90** [libra/libra#3344]
- Using the `?` operator liberally across various protocol implementations means that it's not very clear what stage a function failed at. We need to start propagating context when returning a Result<> - this can be done by leveraging a crate like `anyhow`.
  - Also, `?` ends up making the code feel like when using exceptions in other languages, and the caller might need to perform pattern matching on a received error to know if/how it should handle it. This can be a source of bugs as also discussed in [http://sled.rs/errors](http://sled.rs/errors). We should definitely learn from the experience of the community here.

**Comment by gregnazario** [comment]
I think this is being driven from a project wide standpoint based on whenever Rust supports backtraces on the errors.
