### ISSUE TITLE
[network] Create network-specific node identifier instead of using PeerId

### ISSUE THREAD

**Issue by bothra90** [libra/libra#3346]
#### Motivation
`network::PeerId`, which is an alias for `libra_types::AccountAddress`, is only a reasonable identifier for validators, since their `PeerId` can be derived from the corresponding Noise static key that is determined from the Noise handshake.

Validator-operated and public full nodes will not have a verifiable PeerId. In addition, if we want to use LibraNet as a generic client-serve framework (e.g. `Validator` -> `LSR (Libra Safety Rules)` communication), we need a node identifier that is independent of the node being a validator.

#### Possible solution:
When using Noise, deriving the node identifier from the Noise key is a reasonable approach. 
When not using Noise, we have 2 options:

(a) self-declared node id: both nodes send each other their respective node id. This is good for consistency if a node connects to multiple other nodes and we want to observe the same id in all places;

(b) randomly generated node id: each node generates a random node identifier for the other node. This reduces chances of collision, but also makes tracing the behavior of a node harder, since the same node will receive different ids at different nodes and across different connections.

**Comment by phlip9** [comment]
closing in favor of #3960
