### ISSUE TITLE
Build broken for powerpc32

### ISSUE THREAD

**Issue by n4ss** [libra/libra#3362]
Due to a new dependency (`rust-prometheus`), the build of libra is broken for powerpc 32bits. `rust-prometheus` uses `std::atomicu64` etc.. which are not available on this architecture.

I also opened an issue there: https://github.com/tikv/rust-prometheus/issues/315

**Comment by thefallentree** [comment]
another Action item here is that : libra-types should not depends on libra-metrics

**Comment by davidiw** [comment]
Believe this has been resolved...

**Comment by n4ss** [comment]
It has, thanks a lot!
