### ISSUE TITLE
[Bug] Account mint error

### ISSUE THREAD

**Issue by kalpaj12** [libra/libra#34]
# 🐛 Bug

I was going through [this](https://developers.libra.org/docs/my-first-transaction#clone-and-build-libra-core).

In the minting process, I tried:

`account mint 0 999999`. [After creating an account]

**Error message**
```
[ERROR] Error minting coins: Failed to query remote faucet server[status=400 Bad Request]: "Exceeded max mint amount of 1000000000000"
```

## Expected Behavior
Expected a successful mint as my request is less than the limit.

However, when I tried `account mint 0 9`, it worked fine. 
## System information
- Libra Version: No idea, how do I find out Libra Version?
- Rust Version: 1.35.0
- OS: Ubuntu 19.04

**Comment by kphfb** [comment]
Hi kalpaj12, thank you for the bug report.  This issue has been fixed and will soon be resolved.  The client specifies transactions in units of "libra" whereas the limit returned by the faucet server is in "microlibra".  Please specify a smaller value and the mint command should work

**Comment by kalpaj12** [comment]
@kphfb , as stated above, it works fine for smaller values. :)

**Comment by kalpaj12** [comment]
P.s. how do I find out the libra version installed?

**Comment by kalpaj12** [comment]
@kphfb , how do I find out the installed libra version?

**Comment by kphfb** [comment]
@kalpaj12 yeah, it would work for smaller values.  You basically need to multiply anything you pass by 10e6 to see if it exceeds 1000000000000.  

Right now, the only way to see the installed version is to look at the git log
