### ISSUE TITLE
[Bug] testnet branch can't find the package wqfish/rust-rocksdb.

### ISSUE THREAD

**Issue by weimumu** [libra/libra#3556]
# 🐛 Bug

When i run the ./scripts/cli/start_cli_testnet.sh, it will report an error that "can,t found the package in https://github.com/wqfish/rust-rocksdb.git?branch=ro#984306b677428131209e16a9e9660d9413b7072b. I check the 
repository in wqfish/rust-rocksdb.git, I found that this no “ro" branch in wqfish/rust-rocksdb.git, which may be deleted by its author. 

So I think that it should change the libra/Cargo.lock and libra/storage/schemadb/Cargo.toml files as follows:
libra/storage/schemadb/Cargo.toml 
[dependencies]
anyhow = "1.0"
once_cell = "1.3.1"
libra-metrics = { path = "../../common/metrics", version = "0.1.0" }
libra-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
rocksdb = "0.14"

this is the same as those files in the libra master branch, and it is ok
## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by masonhunk** [comment]
Same issue here. Error:

root@instance-gy82dxnc:~/libra# cargo update
    Updating crates.io index
    Updating git repository `https://github.com/calibra/curve25519-dalek.git`
    Updating git repository `https://github.com/calibra/ed25519-dalek.git`
    Updating git repository `https://github.com/calibra/x25519-dalek.git`
    Updating git repository `https://github.com/wqfish/rust-rocksdb.git`
error: failed to load source for a dependency on `rocksdb`

Caused by:
  Unable to update https://github.com/wqfish/rust-rocksdb.git?branch=ro

Caused by:
  failed to find branch `ro`

Caused by:
  cannot locate local branch 'ro'; class=Reference (4); code=NotFound (-3)

**Comment by weimumu** [comment]
@masonhunk  
You can change the rocksdb-releated part of libra/Cargo.lock and libra/storage/schemadb/Cargo.toml in the testnet branch to that in master branch. For example：
libra/storage/schemadb/Cargo.toml
[dependencies]
anyhow = "1.0"
once_cell = "1.3.1"
libra-metrics = { path = "../../common/metrics", version = "0.1.0" }
libra-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
rocksdb = "0.14"

It can solve this problem

**Comment by wqfish** [comment]
The branch has been restored.
