### ISSUE TITLE
[Bug] use of unstable library feature 'matches_macro'  

### ISSUE THREAD

**Issue by weimumu** [libra/libra#3558]
# 🐛 Bug

## To reproduce
>> Compiling program
   Compiling move-core-types v0.1.0 (/home/inplus/blockchain/libra/language/move-core/types)
error[E0658]: use of unstable library feature 'matches_macro'
  --> language/move-core/types/src/identifier.rs:42:9
   |
42 |         matches!(c, '_' | 'a'..='z' | 'A'..='Z' | '0'..='9')
   |         ^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `move-core-types`.

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by wqfish** [comment]
The `matches` macro was stabilized in rust 1.42.0. Are you on an old branch that still uses older compiler? https://github.com/libra/libra/pull/2922 was about a month ago.

**Comment by wqfish** [comment]
Reopen if you get more detailed steps to reproduce.

**Comment by 4math2379** [comment]
i got the same issue.

**Comment by dtakis** [comment]
Same error:
env :
Distributor ID: Ubuntu
Description: Ubuntu 18.04.4 LTS
Release: 18.04
Codename: bionic

**Comment by andrewpdickson** [comment]
I'm running into this same issue on the same environment (Ubuntu 18.04.4)

Seems like it may be related to that Ubuntu version for some reason?

**Comment by jolestar** [comment]
Run cargo build at the project root, do not at sub crate.

**Comment by andrewpdickson** [comment]
For me the issue was that I needed to be on rust nightly

**Comment by bingli224** [comment]
For my case, on Windows 10, it's solved after `rustup update`.

**Comment by avindra** [comment]
@bingli224 Also fixed for me in Linux by doing `rustup update`. My rustc was at 1.41, now at 1.47.
