### ISSUE TITLE
[Questions] Support recover mnemonic from entropy

### ISSUE THREAD

**Issue by mmsqe** [libra/libra#359]
## ❓ Questions and Help

Is there any way to recover like in [bip39](https://github.com/bitcoinjs/bip39/blob/master/src/index.js#L98)

```
const mnemonic = 'sail verb knee pet prison million drift empty exotic once episode stomach awkward slush glare list laundry battle bring clump brother before mesh pair';
const expectedMnemonicOrdered = entropyToMnemonic(mnemonicToEntropy(mnemonic));
```

**Comment by kchalkias** [comment]
@mmsqe there is an `io_utils` function to recover from a file containing the mnemonic list of words, `pub fn recover<P: AsRef<Path>>(path: &P) -> Result<WalletLibrary>` which internally invokes `WalletLibrary::new_from_mnemonic(mnemonic: Mnemonic)`.
Let me know if this works for you.

**Comment by mmsqe** [comment]
I wasn't referring to recover from file(mnemonic.txt) but recover from master seed to mnemonic, which related to sha3-256 algorithm.

**Comment by kchalkias** [comment]
@mmsqe I see what you mean, no it's not in our api yet. This is an easy addition though, I will prioritize it accordingly and let you know. As a first step, we will probably only allow 256 bits of entropy to be compatible with `WalletLibrary::new()`.

**Comment by kchalkias** [comment]
@mmsqe trying to understand the business requirements on this one. In theory, you can just use the seed to generate the Mnemonic list of words outside Libra and use this list to recover, right?

**Comment by mmsqe** [comment]
@kchalkias Yes, since it’s more machine reable way, i.e. generating QR code to allow transfer from paper wallet.

**Comment by kchalkias** [comment]
@mmsqe note that after merging [[crypto] Update mnemonic rules for compatibility with BIP39 #417](https://github.com/libra/libra/pull/417) and in particular [`mnemonic.rs`](https://github.com/libra/libra/blob/master/client/libra_wallet/src/mnemonic.rs#L88) you can safely generate a mnemonic from entropy bytes. As in BIP39, we accept any of the following entropy sizes: 16, 20, 24, 28, 32.

In theory, if you want to recover from an entropy-generated QR, you just invoke `Mnemonic::mnemonic(entropy: &[u8])` which will produce the mnemonic from the input entropy. Then you can use/store this mnemonic to recover or generate a new wallet account.

```
    /// Generate mnemonic from entropy byte-array.
    pub fn mnemonic(entropy: &[u8]) -> Result<Mnemonic> {
```

Let me know if that helps.

**Comment by mmsqe** [comment]
Thanks for the support, I can also implement that logic in my application.
