### ISSUE TITLE
[Bug] no error reported when publishing a module to the wrong account

### ISSUE THREAD

**Issue by bob-wilson** [libra/libra#3658]
# 🐛 Bug

The "Troubleshooting" section of https://developers.libra.org/docs/run-move-locally mentions that you cannot publish a module to an account that is different than the account specified when compiling the module. I am not seeing this error.

(Note: It's possible that there is a separate issue in that document. The text says that you will get a "SendingAccountDoesNotExist" error when this happens. That doesn't seem like the right error to report in this situation.)

## To reproduce

Follow the steps in the "Run Move Locally" document up through the "Publish Compiled Module" section. Then create another account and publish the same module to that new account.

```
libra% dev publish 0 /var/folders/mb/jmfx4kzj5n79kq0wwrx755900000gn/T/2757b9720c00c29537359610ea616b82/transaction_0_module_MyModule.mv
waiting for dd0923ab5ea38771d167eead141140aa with sequence number 1INFO 2020-04-29 23:25:20 client/cli/src/libra_client.rs:225 Verified version change to: 1874
.........INFO 2020-04-29 23:25:20 client/cli/src/libra_client.rs:225 Verified version change to: 1875
..................INFO 2020-04-29 23:25:20 client/cli/src/libra_client.rs:225 Verified version change to: 1876
...................INFO 2020-04-29 23:25:21 client/cli/src/libra_client.rs:225 Verified version change to: 1877
..................INFO 2020-04-29 23:25:21 client/cli/src/libra_client.rs:225 Verified version change to: 1879
transaction is stored!
no events emitted
Successfully published module
libra% account create
>> Creating/retrieving next account from wallet
INFO 2020-04-29 23:25:34 client/cli/src/libra_client.rs:225 Verified version change to: 1935
Created/retrieved account #1 address ddac3b12711804f230c07daab32adc8b
libra% account mintb 1 66
>> Minting coins
waiting for 0000000000000000000000000a550c18 with sequence number 3INFO 2020-04-29 23:26:07 client/cli/src/libra_client.rs:225 Verified version change to: 2078
..............INFO 2020-04-29 23:26:07 client/cli/src/libra_client.rs:225 Verified version change to: 2079
...................INFO 2020-04-29 23:26:07 client/cli/src/libra_client.rs:225 Verified version change to: 2080
..................INFO 2020-04-29 23:26:07 client/cli/src/libra_client.rs:225 Verified version change to: 2081
..................INFO 2020-04-29 23:26:08 client/cli/src/libra_client.rs:225 Verified version change to: 2083
transaction is stored!
Finished minting!
libra% dev publish 1 /var/folders/mb/jmfx4kzj5n79kq0wwrx755900000gn/T/2757b9720c00c29537359610ea616b82/transaction_0_module_MyModule.mv
waiting for ddac3b12711804f230c07daab32adc8b with sequence number 1INFO 2020-04-29 23:26:39 client/cli/src/libra_client.rs:225 Verified version change to: 2221
.................INFO 2020-04-29 23:26:39 client/cli/src/libra_client.rs:225 Verified version change to: 2222
..................INFO 2020-04-29 23:26:40 client/cli/src/libra_client.rs:225 Verified version change to: 2223
.................INFO 2020-04-29 23:26:40 client/cli/src/libra_client.rs:225 Verified version change to: 2224
..................INFO 2020-04-29 23:26:40 client/cli/src/libra_client.rs:225 Verified version change to: 2226
transaction is stored!
no events emitted
Successfully published module
libra% 
```

The same module was successfully published in 2 different accounts (dd0923ab5ea38771d167eead141140aa and ddac3b12711804f230c07daab32adc8b)

## Expected Behavior

According to the document, this is supposed to be reported as an error.

## System information

**Please complete the following information:**
macOS at commit fab4a2547c
(Be sure to get #3655 before attempting to reproduce this)

**Comment by bob-wilson** [comment]
@dariorussi You said we had a check for this. Are you the best person to investigate? I'd be glad to dig into it a bit more if you would like me to experiment.

**Comment by dariorussi** [comment]
> @dariorussi You said we had a check for this. Are you the best person to investigate? I'd be glad to dig into it a bit more if you would like me to experiment.

I'd like to see what is going on because we should check.. I'll ping you on the repro

**Comment by bob-wilson** [comment]
After filing https://github.com/libra/libra/issues/3663, I had an idea about this one.... My hypothesis was that the VM is refusing to publish the module with the wrong address, but you can't tell from the CLI. (It shows "no events emitted" and "Successfully published module" regardless of whether the publishing was successful.) I tested this hypothesis by continuing through the steps of the "Run Move Locally" document but with 2 different accounts, one with the good module and the other with the wrong address. The script using the bad-address module failed to run. (I.E., the CLI showed "transaction is stored!" and "Successfully finished execution" but also "no events emitted".) I think that confirms my hypothesis. So, tl;dr: this is basically the same as #3663
