### ISSUE TITLE
[Move] Reconsider `Transaction::sender()` and `move_to_sender`

### ISSUE THREAD

**Issue by sblackshear** [libra/libra#3679]
Take a look at RFC PR https://github.com/libra/libra/pull/3673 which:
- Introduces the `Sender::T` resource, which is just a wrapper around an account address. It exposes a function that allows reading the inner address. You can think of `Sender::T` as the "sender capability"; it is the permission to know the sender's address + take actions that require  knowing this address.
- Eliminates every use of `Transaction::sender()` in the core modules by using a functional discipline: thread an explicit `&Sender` parameter everywhere that needs to read the sender. This is similar to `ViewerContext` (and related design patterns) in a codebase that is probably familiar to folks here.
- Similarly, adds a call to `Sender::move_to(&Sender::T)` (a newly introduced no-op function) before every use of `move_to_sender`. This doesn't actually do anything for now, but gives an idea of how the code would look if we replaced the `move_to_sender<R>(R)` bytecode with `move_to<R>(R, &Sender)`. 

Now, the obvious next question is: how do I get a `Sender::T` resource given that the 	`Sender` module exposes no API for creating one? There are a few possible answers:

1. Add a `sender: Option<Sender::T>` field to the `LibraAccount::T` struct that will be instantiated with `Sender { addr }` upon a call to `LibraAccount::create(addr)`. Then, expose `extract` and `fill` APIs for the `Option` that allow the account owner to take their `Sender` resource out/put it back. This does not require any changes to the language or the Libra/Move adapter.
2. Have the Libra/Move adapter create a `Sender { addr }` resource (where `addr` is the transaction sender) in Rust, then pass it in as a parameter of the transaction script (e.g., `main(sender: &Sender::T)` or `main(sender: Sender::T): Sender::T`). This requires a small change to the Libra/Move adapter and the bytecode verifier for transaction script signatures (for the `sender` param).

## Ways forward

I am not suggesting that we commit this change as-is; it was more of an experiment to understand whether this sort of programming discipline would be reasonable. Having completed it, I feel that the result is reasonable to write, easier to read, and has some significant benefits (more on that in the next section). There are several paths we could consider from here:

I. Decide we don't like this and leave everything as-is.   
II. Decide we like this as a design pattern, but want to keep both `Transaction::sender()` and `move_to_sender`.  
III. Decide we want to get rid of `Transaction::sender()`, but keep `move_to_sender`. This is still a fairly small change: delete the `GetTxnSender` bytecode + either (1) or (2) above.  
IV. Decide we want to get rid of `Transaction::sender()` and convert `move_to_sender<T>(T)` into `move_to<T>(T, &Sender::T)`. This is more work because we will probably need to figure out how to make `Sender::T` a native type, and change the interpreter/verifier/compiler/prover to handle to the new `move_to` bytecode. If we go this route, I think (2) above will be easier/better.
V. We could also keep `Transaction::sender()` and ditch `move_to_sender`, but I don't think option makes a lot of sense.

## Why?

This is the longest section, so I have left it for last. I think there are several unrelated, yet compelling reasons for considering some flavor of the change above.

### Explicit representation of sender authority

Something that has bothered me for awhile is that fact that everything is explicit in Move *except* for the  authority of the sender. If a procedure wants a coin from me, it can ask for it explicitly via (e.g.) `give_me(c: Libra<LBR::T>)`.  But, unfortunately, it can also just take it:

```rust
fun take() {
  LibraAccount::pay_from_sender<LBR::T>(0xb0b, 1000)
}
```
In general, if you call a function like `M::take()` without looking  at the body, you know it can't change your locals or stack. But it can change any piece of global state owned by `M` or its (transitive) dependencies, including resources published under the sender's address. If you want to be sure about `M::take`'s effects, your options are:

- **Look at `M::take()` and its callees carefully before you call it** This is simultaneously obvious best practice and unrealistic advice (think of "look carefully at code you call for memory safety" errors in a different setting!). Move's static call graph and the small size of modules makes this somewhat reasonable for now, but better answers are possible.
- **Use the Move prover** If the Move prover required programmers to specify all effects of a function, you could determine whether a function might steal your money by looking at the postcondition. This is a better answer than trusting a human to look carefully, but still not ideal.

Getting rid of `Transaction::sender()` and (to a lesser extent) `move_to_sender` provides a much better answer than the two above. If `take()` doesn't ask for a  `&Sender::T`, it can't know the sender's address and thus can't[1] modify the sender's state. In addition, if we get rid of `move_to_sender`, we also know that `take` doesn't publish a  resource under  the sender's account. 

If `take` does ask for a `&Sender::T`, the situation is less nice, but no worse than today: the caller must read the code carefully and/or use the prover.

### Simplifying the `save_account` native function

If we get rid of `move_to_sender`, we could replace `save_account` with `create_sender(addr): Sender::T`, then implement `save_account` in  pure Move: 

```
save_account(
  account_resource: T, 
  balance_resoure: Balance, 
) {
  let sender = create_sender(addr); // create_sender would be a private native that packs/returns a Sender resource
  move_to(&sender, account_resource);
  move_to(&sender, balance_resource);
  //  whatever other resources we want to put in a default account
  destroy_sender(sender); // this would also be a private native
}
```

Of course, variants are possible: let `create_sender` be `public native`.  This is the "malloc" design we have discussed before; it is very powerful, but correspondingly scary. Other designs could also work. This feels more general than `move_to_sender` + `save_account`.

### Finally answering the question: are `move_to_sender`, `GetTxnSender`, and `save_account` fundamental to Move, or Libra-specific?

I have wondered about this for a long time and feel like the answer is "not fundamental" to all (although some variant of `move_to` is fundamental). The combination of `Sender::T` and `move_to<T>(T, &Sender::T)` can implement the current Libra scheme for publishing resources , the new scheme described in this issue,  and many  other schemes  as  well (such as the "malloc" scheme above).

### Multi-sender transactions aka "atomic scripts"

This is a bigger project for future work, but worth mentioning. Credit due to @kchalkias for inspiring this with his idea of multi-sender transactions for currency swaps!

Getting rid of both `move_to_sender` and `Transaction::sender` opens the door to an easy representation of a transaction with multiple senders (e.g. `main(sender1:&Sender::T, sender2: &Sender::T)`). Multi-sender transactions are useful for intra-Libra atomic exchanges or (more generally) "atomic scripts"; any sequence of actions that requires >1 authority, but should only happen if they all happen together. I believe that a lot of the work on meta-transactions in Eth could be captured by multi-sender atomic scripts.
 TODO: lots more to say here about how this would work + the use-cases.

[1] This isn't strictly true; for example, the code might modify resources under a hardcoded address that  happens to be the same as the sender. But the caller can be sure that code with a safe API like `withdraw_from_sender(...,&Sender)` cannot be called

**Comment by tnowacki** [comment]
> Now, the obvious next question is: how do I get a Sender::T resource given that the Sender module exposes no API for creating one? 

Another option, you could set it and unset it in the prologue/epilogue. And block out calls to it with capabilities defined in the Account module

**Comment by tnowacki** [comment]
I'll write up some longer thoughts later but initial brain dump
- I would like this a lot more with aliasing, so you can do `&Sender` instead of `&Sender::T`. So you could have something like `module Transaction { native resource struct Sender;  native public fun address(s: &Sender) -> address; }` and then with aliasing just use `Sender`
- Alternatively. I think it makes a lot of sense to have some native bytecode setup for `move_to`. So you could make `sender` a new native primitive resource. With a native function/op code for getting the address. 
  - So `Sender` is a primitive type
  - `address(&Sender) -> address` could be a native op code
  - `move_to<T: nominal resource defined in the current module>(&Sender, address)` is nice
  - `create_sender` in libra account is fancy
- I think the example with multiple senders is really sexy 
- I have always really liked passing through the transaction info. And now that its just the sender, thats very neat and clean. 
- I don't think we can do this in the next few months. But it is a good long term goal

**Comment by sblackshear** [comment]
+1 to the native type and those two bytecodes. I think that is the nicest approach.

**Comment by dariorussi** [comment]
There are some very nice things about this, if we can ever pul it off and obviously not a chance for V1.
We want to avoid all stack walks in the runtime because they are disturbing. A stack model wants you to explicitly pass your state. It has the benefit that you see and understand what the side effects can be. `get_sender` always had a bad taste in that. An explicit _sender_ concept would make much easier to understand possible side effects. So that is nice!
The multiple sender is a really compelling example. Really compelling!!!

How all of that translates to user code I am still not cleat about and I need more thoughts.
Also the whole account creation (as you talk about) is a bit of a mystery still for me.

**Comment by dariorussi** [comment]
> 1. Add a sender: Option<Sender::T> field to the LibraAccount::T struct that will be instantiated with Sender { addr } upon a call to LibraAccount::create(addr). Then, expose extract and fill APIs for the Option that allow the account owner to take their Sender resource out/put it back. This does not require any changes to the language or the Libra/Move adapter.

I am not sure I understood usage of this, if can be overwritten and general expected usage

**Comment by sblackshear** [comment]
Other random ideas on bring in the `Sender` resource via transaction script: `main(&mut Sender)` + `move_to<T>(T, &mut Sender)`
- APIs that want to publish a new resource will need to ask for a `&mut Sender`; other APIs  only need `&Sender`
- You could imagine a stronger convention (though needs to be enforceable by the prover, too hard to do in the verifier) where you ask for a `&mut Sender` if you want to do a `borrow_global_mut`, `move_from`, or `move_to` and ask for a `&Sender` if you only want to do a `borrow_global` or `exists`

**Comment by bob-wilson** [comment]
Is this ready to close now?

**Comment by sblackshear** [comment]
We could either close it now or once we've deprecated `Transaction::sender()` and `move_to_sender`... Perhaps we should close and open a separate task for deprecation?

**Comment by bob-wilson** [comment]
I don't think we need a separate task, and you just answered my implied question about what is left to do. Let's leave this open until we have deprecated (and hopefully removed) those 2 things.

**Comment by bob-wilson** [comment]
This is done now
