### ISSUE TITLE
[network] collect latency metrics from pings

### ISSUE THREAD

**Issue by phlip9** [libra/libra#3681]
+ record successful ping latency
+ add prometheus metric

**Comment by davidiw** [comment]
Probably good idea to make this on a per RPC type basis, the time between request and response! The health check (ping / pong) providing the closet to internode latency.

**Comment by davidiw** [comment]
More concretely, here's Rpc: https://github.com/libra/libra/blob/master/network/src/protocols/rpc/mod.rs

Here's where we send requests and wait for responses: https://github.com/libra/libra/blob/master/network/src/protocols/rpc/mod.rs#L427

Part 1) Add a tracing log to print out how long this took along with the type
Part 2) Add a counter for this

**Comment by phlip9** [comment]
That does sound more useful. Maybe we can add this as a more general metric to `NetworkSender::send_rpc`.

**Comment by Rustinante** [comment]
By type do you mean the `NetworkMessage` types? or the `ProtocolId`?

**Comment by Rustinante** [comment]
I've added the counter for the different protocols here. Please let me know if this isn't something that we had in mind. Thanks

**Comment by phlip9** [comment]
closed by #3709
