### ISSUE TITLE
[network] memsocket should only appear in debug builds

### ISSUE THREAD

**Issue by phlip9** [libra/libra#3682]
+ network and netcore should only pull in network/memsocket as a dev-dependency
+ feature gate all memsocket related transport code

**Comment by ahmedelgohary** [comment]
I can give this a shot. Could you provide some more information on the feature gating?

**Comment by davidiw** [comment]
feature gating via crates / cargo.

**Comment by benallamar** [comment]
@davidiw is this issue still relevant ?

**Comment by davidiw** [comment]
I would challenge someone to see if it is actually practical or not. I haven't explored the code in a while. If it is reasonably doable, I don't see why not :).

**Comment by benallamar** [comment]
thank you! I'd like to work on the project, so if you see any good issue for newbie, I'd like to tackle them :)

**Comment by phlip9** [comment]
hi @benallamar, this issue is still relevant and practical : )

we're trying to feature gate the network/memsocket crate so it doesn't appear in production builds. this section of the coding_guidelines is relevant: https://github.com/libra/libra/blob/master/documentation/coding_guidelines.md#conditional-compilation-of-tests

1. the network and netcore production crates should only pull in memsocket as a test-only dependency.

2. netcore: the MemoryTransport module should be marked test-only

3. network: in network/src/peer_manager/builder.rs, the `[Memory(_)]` match arm should be marked test-only (https://github.com/libra/libra/blob/master/network/src/peer_manager/builder.rs#L320)

this list might not be exhaustive, but it should cover almost everything

**Comment by benallamar** [comment]
Hi @phlip9! thank you for your inputs, I'll read them and get back in case I need more informations. 
Just to my knowledge, is there any kind of 'chat' channel where I can asks if I've more questions about the project ? I mean in interactive way ?

**Comment by phlip9** [comment]
Closed by #5324
