### ISSUE TITLE
[move-prover] Align move-lang and spec-lang command line options

### ISSUE THREAD

**Issue by wrwg** [libra/libra#3706]
Prover team recently added command line options and logic to use a search path for finding sources for module dependencies. 

> if you specify --search_path <path> (short form -s <path>), the prover will try to find dependencies at the given path. It will only look at the direct directory provided, not recursively scan the directory. The flag can be repeated.

According to Bob, the same happened also recently for move-lang compiler:

> We recently changed the Move compiler so that the -d option can specify either a file or a directory for dependencies, and if it is a directory, then it recursively searches there for all ".move" files. 

For better user experience, those things should be aligned, probably based on the move-lang support.

@tnowacki @bob-wilson

**Comment by tnowacki** [comment]
No strong opinions here. I found the move-lang one being easier to use, as it just finds them all for you without an extra arg. 

But I understand it could be a bit of a weird experience if it catches something by accident

**Comment by bob-wilson** [comment]
Are there strong opinions from the Prover team? If not, I propose to change the Prover to use the same behavior for the -d option as the compiler. I can implement that if there are no objections.

**Comment by bmwill** [comment]
Its probably also worth noting that project wide we're trying to use dashes `-` instead of underscores `_` for binary names, and arg and option names.

**Comment by wrwg** [comment]
> Are there strong opinions from the Prover team? If not, I propose to change the Prover to use the same behavior for the -d option as the compiler. I can implement that if there are no objections.

No concerns from my side. I was mostly concerned making this recursive because this needs to do more than just look for files. It needs to scan each .move file to construct a ModuleName -> FileName mapping. If you feel this is OK, we can adopt this also for the prover.

Technically, there is a bunch of code in `move-prover/src/lib.rs` to handle this. I guess this would be removed and instead we use APIs from move-lang? Also note we currently have both `-d` for providing the name of a dependency, and -s for search path; those two options would need to be merged. I'm fine with having just -d like the compiler.

**Comment by bob-wilson** [comment]
There is another discrepancy between these tools that I think we should fix. The compiler takes its input files via a --source-files option. The prover has the inputs as (non-optional) arguments, i.e., at the end of the command line without an option specifier. The prover's style matches what I've seen from various other compilers, so I would prefer to adopt that in the Move compiler as well.
