### ISSUE TITLE
[Consensus] Voting for NIL and secondary proposals

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#371]
There are a couple of immediate enhancements for improving system performance in cases, in which some proposers are non-responsive.

1. Enhance the timeout message s.t. it would include the vote that has been sent in the round that just happened to time out. This way the broadcast of a timeout would also deliver the votes and thus a QC could be formed even if the designated aggregator is not responsive.
2. Enhance the timeout message s.t. if no votes have been made in a round, a special NIL block would be voted for (piggybacked to the `TimeoutMsg` as described above). NIL block would not contain any transactions and would have a special NIL author. The NIL blocks help with not breaking the contiguity of the QC chains during timeout rounds and thus improve the e2e latency of the commits.
3. In addition to the *primary* proposer per round, we want to introduce up to `k` *secondary* proposers per round (strictly ordered). The voter would not be willing to vote for any of the non-primary proposals during the round duration. Upon timeout it would vote for the best secondary proposal (or NIL as described above).

**Comment by huitseeker** [comment]
> In addition to the primary proposer per round, we want to introduce up to k secondary proposers per round (strictly ordered). The voter would not be willing to vote for any of the non-primary proposals during the round duration. Upon timeout it would vote for the best secondary proposal (or NIL as described above).

Note this will make the network go if *any* of the series of secondary proposers is responsive, whereas in the past we needed *all* of the proposers to be alive to continue.

This sounds like an improvement of the reliability story, and its very much is, but it simplifies attack that was difficult to deploy before, namely:

DDoS the proposer until you end up on one that is among the set of attacker-controlled nodes

So we need at least to deploy DDoS detection simultaneously to figure out if we are facing this attack when we fallback. Do we have plans for this?

**Comment by dmitri-perelman** [comment]
Interesting. We don't have any special DDoS work currently related to this issue. If I understand your concern correctly, you're talking about a scenario, in which a secondary proposer of a round has incentives to DDoS a primary proposer of that round. Note that in different rounds different pairs of primary / secondary nodes are going to be chosen. How is it fundamentally different from a single-proposer system, in which a node might have an incentive to DDoS a previous round proposer.

**Comment by huitseeker** [comment]
> If I understand your concern correctly, you're talking about a scenario, in which a secondary proposer of a round has incentives to DDoS a primary proposer of that round. 

Not necessarily the second (third, ...) proposer, but a party colluding with a proposer somewhere in the list of alternate proposers.

> Note that in different rounds different pairs of primary / secondary nodes are going to be chosen. 

I don't understand how/if this is relevant.

> How is it fundamentally different from a single-proposer system, in which a node might have an incentive to DDoS a previous round proposer.

The observable of the frequent round change under this attack is not present any more.

**Comment by dmitri-perelman** [comment]
Round timeouts would still be observable if a primary proposer of a round is down.
