### ISSUE TITLE
[Bug] Not able to connect to validator RpcFailure: DeadlineExceeded

### ISSUE THREAD

**Issue by dwjorgeb** [libra/libra#38]
# 🐛 Bug

When running the start_cli_testnet.sh I get this error

Building and running client in debug mode.
    Finished dev [unoptimized + debuginfo] target(s) in 1.75s
     Running `target/debug/client --host ac.testnet.libra.org --port 80 -s ./scripts/cli/trusted_peers.config.toml`
Not able to connect to validator at ac.testnet.libra.org:80, error RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") })

To report a security issue, please email security@libra.org.  -->

## To reproduce

`` ./scripts/cli/start_cli_testnet.sh `` 

## Expected Behavior

success

## System information

Ubuntu 18.04

**Comment by kphfb** [comment]
Can you check your network connection and try again?

**Comment by dwjorgeb** [comment]
@kphfb it has, apt update and upgrade work fine, can ping and open websites.

**Comment by kphfb** [comment]
@dwjorgeb can you please try editing:
libra/client/src/grpc_client.rs
and within the get_default_grpc_call_option() function, change the timeout to a larger value (perhaps 15000) and let me know if that resolves the issue or not.

**Comment by lingani** [comment]
Hi, I still have the error after chaging timeout to 15000 or larger.

**Comment by nootfly** [comment]
Hi, I still have the error after changing timeout to 15000 or larger.

**Comment by blockchain1977** [comment]
I have same issue:
    Finished dev [unoptimized + debuginfo] target(s) in 3m 37s
     Running `target/debug/client --host ac.testnet.libra.org --port 80 -s ./scripts/cli/trusted_peers.config.toml`
Not able to connect to validator at ac.testnet.libra.org:80, error RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") })

My environment:
Linux 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Comment by blockchain1977** [comment]
cool, got it work. Just by simply running again.

**Comment by lingani** [comment]
I changed internet provider, I run again and it works. Thank you all.

**Comment by mohamedahmed01** [comment]
same issue here :
 ./scripts/cli/start_cli_testnet.sh
Building and running client in debug mode.
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target/debug/client --host ac.testnet.libra.org --port 80 -s ./scripts/cli/trusted_peers.config.toml`
Not able to connect to validator at ac.testnet.libra.org:80, error RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") })
on ubuntu 18.04 
i tried using vpn and changing the connection but still the same.

**Comment by dwjorgeb** [comment]
> 
> 
> @dwjorgeb can you please try editing:
> libra/client/src/grpc_client.rs
> and within the get_default_grpc_call_option() function, change the timeout to a larger value (perhaps 15000) and let me know if that resolves the issue or not.

@kphfb I changed it to 30000 and it works now

**Comment by mohamedahmed01** [comment]
@dwjorgeb 
changed it to different values 15000,30000 still nothing ?

**Comment by KaviarasuSakthivadivel** [comment]
Not able to connect to validator at ac.testnet.libra.org:80, error RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") })

**Comment by icarter09** [comment]
@KaviarasuSakthivadivel what OS are you using?

**Comment by KaviarasuSakthivadivel** [comment]
@icarter09 MacOS, actually problem solved when I tried in my Home wifi, previously i tried in Office Wifi, and it seems a firewall block.

**Comment by icarter09** [comment]
@KaviarasuSakthivadivel glad to hear you found a solution. 

@dwjorgeb can you close this issue? Thanks.

**Comment by Johnny-lou** [comment]
happened again when running ./scripts/cli/start_cli_testnet.sh 
Not able to connect to validator at ac.testnet.libra.org:8001, error RpcFailure(RpcStatus { status: RpcStatusCode(4), details: Some("Deadline Exceeded") })

**Comment by Johnny-lou** [comment]
> happened again when running ./scripts/cli/start_cli_testnet.sh
> Not able to connect to validator at ac.testnet.libra.org:8001, error RpcFailure(RpcStatus { status: RpcStatusCode(4), details: Some("Deadline Exceeded") })
@davidiw 
![image](https://user-images.githubusercontent.com/5352713/70589382-8bdd2c80-1c0a-11ea-8999-7303cb364183.png)

**Comment by davidiw** [comment]
Could you try updating to the latest branch and try again?

**Comment by Johnny-lou** [comment]
> Could you try updating to the latest branch and try again?

yes,  I tryed serveral times, but not work

**Comment by davidiw** [comment]
> > Could you try updating to the latest branch and try again?
> 
> yes, I tryed serveral times, but not work

As you made this post, we were literally in the midst of redeploying our testnet. I suspect you were unlucky. I can confirm that the latest head of testnet is able to connect and mint.

**Comment by Johnny-lou** [comment]
> > > Could you try updating to the latest branch and try again?
> > 
> > 
> > yes, I tryed serveral times, but not work
> 
> As you made this post, we were literally in the midst of redeploying our testnet. I suspect you were unlucky. I can confirm that the latest head of testnet is able to connect and mint.

work now, thanks
