### ISSUE TITLE
[Bug] Duplicate accounts get created when running local validator and accessing using client cli in 2 different terminals

### ISSUE THREAD

**Issue by hvram1** [libra/libra#387]
# 🐛 Bug

## To reproduce

** I run the validator in local mode  **
<code>
cargo run -p libra_swarm -- -n 2
</code>
I get the message 
<code>
cargo run --bin client -- -a localhost -p 33781 -s "/tmp/.tmpFuX6Wr/trusted_peers.config.toml" -m "/tmp/keypair.ObwmZyKKdS3G/temp_faucet_keys"
</code>

I find the 2nd port using the following
<code>
cd /tmp/.tmpFuX6Wr/logs
grep admission_control_service_port *
</code>

and I get the following ports
<code>
admission_control_service_port: 42429
admission_control_service_port: 33781
</code>

I open two terminals and in each of them I connect as follows
<code>
cargo run --bin client -- -a localhost -p 42429 -s "/tmp/.tmpFuX6Wr/trusted_peers.config.toml" -m "/tmp/keypair.ObwmZyKKdS3G/temp_faucet_keys"

cargo run --bin client -- -a localhost -p 33781 -s "/tmp/.tmpFuX6Wr/trusted_peers.config.toml" -m "/tmp/keypair.ObwmZyKKdS3G/temp_faucet_keys"

</code>
I get 2 terminals with libra% prompt 

In terminal 1 I type account create 3 times and list the accounts 
<code>
account create
account create
account create
account list 
User account index: 0, address: 95ec055bfa9437a5d334540ce980b835ce4dadf9c8ee5315e01fedb849045f58, sequence number: 0, status: Persisted
User account index: 1, address: 6097797b7f5a448edb2e2172cb41bda8d3494d53203a63229c9bd15df0654a49, sequence number: 0, status: Local
User account index: 2, address: 37434e846cdc9bed98e97505019d64aba7594e25cba684812e36d80b46cd147a, sequence number: 0, status: Local
Faucet account address: 0000000000000000000000000000000000000000000000000000000000000000, sequence_number: 0, status: Persisted

</code>

In terminal 2 I type account create 4 times and list the accounts
<code>
libra% account list
User account index: 0, address: 95ec055bfa9437a5d334540ce980b835ce4dadf9c8ee5315e01fedb849045f58, sequence number: 0, status: Persisted
User account index: 1, address: 6097797b7f5a448edb2e2172cb41bda8d3494d53203a63229c9bd15df0654a49, sequence number: 0, status: Local
User account index: 2, address: 37434e846cdc9bed98e97505019d64aba7594e25cba684812e36d80b46cd147a, sequence number: 0, status: Local
User account index: 3, address: 2d2465c9559d338b662a3b9aa6e73f4ceb4a32ca7b9cec02a91ddade00bde838, sequence number: 0, status: Local
Faucet account address: 0000000000000000000000000000000000000000000000000000000000000000, sequence_number: 1, status: Persisted

</code>

As you can see the account addresses are the same . So when I type account 0 mint 100 in Terminal 1 it reflects on the other Terminal . 

## Expected Behavior

Can you make the account id ( random numbers I guess separate ) so that it is easy to play with accounts across terminals . The idea is that I wanted to create some test cases to demonstrate 
## System information

**Please complete the following information:**
- 
- 
-

**Comment by fbandersnatch** [comment]
When you run the client, a `client.mnemonic` file is generate and it is used to derive the accounts. If the file already exists, the client will pick it up -- and the accounts will be the same.
You can specify the mnemonic file (or point to an empty file) when you start the client by using the `-n` flag, with a different file for each client app.

**Comment by hvram1** [comment]
I use the -n as @fbandersnatch suggested . It allows me to to create accounts in an independent fashion but I am not able to mint . It says Method not allowed

This is how I ran
<code>
cargo run --bin client -- -a localhost -p 42429 -s "/tmp/.tmpFuX6Wr/trusted_peers.config.toml" -n "/tmp/keypair.ObwmZyKKdS3G/temp_faucet_keys2"
</code>

the file pointed to after "-n" flag does not exists  When I try to do 

<code>
account create
account mint 0 100
</code>
I get an error

<code>
libra% account create
>> Creating/retrieving next account from wallet
Created/retrieved account #0 address 973ed553a15d3015936b14b301512801e31b5385a5024bc9be2bb591bb299021
libra% account list
User account index: 0, address: 973ed553a15d3015936b14b301512801e31b5385a5024bc9be2bb591bb299021, sequence number: 0, status: Local
libra% account mint 0 100
>> Minting coins
[ERROR] Error minting coins: Failed to query remote faucet server[status=405 Method Not Allowed]: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"

</code>

As far I can see there is no Faucet account address if the -n flag is used

**Comment by fbandersnatch** [comment]
You cannot mint because you did not specify a mint key. Do not confuse the `-m` option for mint key with the `-n` option for client mnemonic file, that specifies the sequence of accounts that are going to be generated

**Comment by hvram1** [comment]
thanks . It works . The confusion existed because the help did not document the -n flag .
