### ISSUE TITLE
[state-sync] Make StateSynchronizer the source of truth for reconfiguration

### ISSUE THREAD

**Issue by davidiw** [libra/libra#3925]
StateSync provides a subscription service for sending off on chain config updates. Registration occurs [here](https://github.com/libra/libra/blob/master/libra-node/src/main_node.rs#L262) and delivery [here](https://github.com/libra/libra/blob/master/state-synchronizer/src/executor_proxy.rs#L218).

Network still depends on consensus to [update eligible peers](https://github.com/libra/libra/blob/master/consensus/src/epoch_manager.rs#L380), we need to eliminate this dependency. Also it is important to note that this API is incomplete as this only updates the networking keys and not the networking addresses.

To eliminate this, we need to funnel reconfiguration events into networking by adding a subscription service for networking that calls the appropriate APIs on connectivity manager: [UpdateEligibleAddresses and UpdateEligibleNodes](https://github.com/libra/libra/blob/master/network/src/connectivity_manager/mod.rs#L100-L102) or consider making a composite API -- but not recommended for MVP.

So we need a new service that has access to these endpoints, we'll call it simple_onchain_discovery and place it under libra/network/simple-onchain-discovery. The requirements are that it can either identify as a fullnode or a validator role. In the validator role, it acquires the changes for the validator nodes and pushes those to connectivity manager. In the fullnode case, it passes the fullnode updates. To instantiate this, we need a connection manager sender, which can be found [here](https://github.com/libra/libra/blob/master/network/src/validator_network/network_builder.rs#L106). We should export this via a new public interface on NetworkBuilder `pub fn connection_request_sender(&self) -> libra_channel::Sender<PeerId, ConnectionRequest>`. Or we can just use the existing [add_protocol_handler](https://github.com/libra/libra/blob/master/network/src/validator_network/network_builder.rs#L309) with empty fields.

Then we need to figure out when to pass updates, we can follow consensus [model](https://github.com/libra/libra/blob/master/consensus/src/epoch_manager.rs#L499) with the caveat that we can just set this up in an infinite loops on the await without needing a select because this has no other utility.

Note: This is a precursor to a larger interaction with Onchain discovery found in network/onchain-discovery. It is not intended to replace it, but to be an incremental improvement that we will integrate at a later time. My recommendation is to not investigate that code for the time being.

Second note: This must not be enabled by default, instead let's steal the existing onchain-discovery config [enable flag](https://github.com/libra/libra/blob/master/libra-node/src/main_node.rs#L200), remove it from being started and start this instead.

**Comment by agclement** [comment]
I think the context and mechanics of the proposed solution are clear;  provided the following is correct:

- **[context]** the _onchain\_discovery_ work places the configuration information into _LibraDB_ which is normally synced between nodes through _StateSync_
-  **[proposed solution]** add a service that a node can use to update networking with the configuration information from the DB as it changes.

There are two possible problems that this feature request can solve, one significantly more complicated than the other:

- **[problem 1:  local reconfiguration]** node _n_ is up-to-date with the system and a reconfiguration event is observed; that information should simply be pushed into networking
- **[problem 2: distributed reconfiguration]** on startup of a new node / catch up of a slow node _n_, _n_ may not have the current set of node keys and addresses; that information must be brought over and installed into networking

In either case, what are the conditions for removing the "old" information;  i.e., are keys/addresses overwritten with the update or should the previous set remain until explicitly removed at some future time?

In the case of problem 2, what configuration information is necessary at the network in order for state sync to work enough to have the requisite configuration information present locally?

**Comment by davidiw** [comment]
Ahh, you're a couple steps ahead in your thinking :)

If a node is behind, it cannot reasonably participate. If it can connect to at least one node, StateSynch will make progress. If it cannot connect to any, we need to leverage an up to date seed peers from NodeConfig::NetworkConfig for the respective network.

In terms of deciding when to update information, I would take a look at the current code for the UpdateEligibleAddresses and UpdateEligibleNodes. I think there may be a potential issue, were the seed peer configuration might be newer than some arbitrary state on the blockchain, so we may need to have multiple versions or use some sort of clocking / versioning scheme as part of the address.

**Comment by phlip9** [comment]
closed by #4034
