### ISSUE TITLE
[Bug] Readme doesnt have link to testnet explorer

### ISSUE THREAD

**Issue by TrevorJTClarke** [libra/libra#40]
# 🐛 Bug

## To reproduce

** Code snippet to reproduce **
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

** Stack trace/error message **
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by kphfb** [comment]
Hi TrevorJTClarke, we have not yet published the blockchain explorer.  Stay tuned!

**Comment by joanesespanol** [comment]
how does one connect to the testnet?

**Comment by lightmark** [comment]
> How does one connect to the testnet?

Please read https://developers.libra.org/docs/my-first-transaction
