### ISSUE TITLE
[network] add `ChainId` to prevent accidental network collision

### ISSUE THREAD

**Issue by davidiw** [libra/libra#4011]
Let's add a chain id to networking to prevent two blockchains from talking to each other:
* Add to [BaseConfig](https://github.com/libra/libra/blob/master/config/src/config/mod.rs#L93) a chain id as a string type
* Add this to [NetworkBuilder](https://github.com/libra/libra/blob/master/network/src/validator_network/network_builder.rs#L148)
* Update the [Handshake protocol](https://github.com/libra/libra/blob/master/network/src/protocols/wire/handshake/v1/mod.rs#L107) to have a new chain id
* Funnel this in via the [various builders](https://github.com/libra/libra/blob/master/network/src/transport.rs)
* Add some tests to ensure two networks cannot talk to each other

Now let's incorporate this into config-builder:
* Add a new flag to [config-builder](https://github.com/libra/libra/blob/master/config/config-builder/src/main.rs) --chain-id -- note this is valid for both validator and fullnodes (optionally figure out how to merge fields from validator and fullnode configs) -- have there be a default, so that this still works
* Update Libra [validator](https://github.com/libra/libra/blob/master/docker/validator-dynamic/docker-run-dynamic.sh) and [fullnode](https://github.com/libra/libra/blob/master/docker/validator-dynamic/docker-run-dynamic-fullnode.sh) docker container to allow this to be pulled in during deployment
* You can test this via the [running docker locally](https://github.com/libra/libra/blob/master/docker/README.md)

Once we get here, we should talk to @mgorven and @sherry-x so they can make sure we have distinct chain ids moving forward.

**Comment by phlip9** [comment]
closed by #4457
