### ISSUE TITLE
[network] disambiguate networks with `NetworkId` to fix network metrics/logs.

### ISSUE THREAD

**Issue by phlip9** [libra/libra#4012]
Replaces prev. issue #2397

Relevant issue #3341

### Problem

It's painful to view prometheus metrics or node logs for network when multiple network instances are running, e.g., a validator is connected to the validator swarm via one instance and their fullnode swarm via another instance. The issue is that network metrics don't have an extra label/dimension for the network type to ensure that the values aren't accidentally combining. Similarly, most log entries in network are difficult to disambiguate across multiple network instances. For example, the Rpc "cancelled requests" metric doesn't have a label for the network type, so it accidentally counts the total number of cancelled requests across all network instances without any way to refine the query to a specific network instance.

A separate (but somewhat orthogonal) problem is that application protocols like state sync or mempool have trouble disambiguating between network messages from different network instances. To unblock those protocols, we recently added some quick changes to state sync/mempool to deal with ambiguous network messages (#3568). However, we should probably find a long-term solution to this issue in network itself.

### Solution

Since different network instances are currently ambiguous, we can add a `NetworkId` to uniquely identify each one. This type will probably look something like `RoleType`. Unfortunately, we can't use `RoleType` to disambiguate networks as the existing `enum RoleType { Validator, FullNode }` describes a specific node's role inside a network instance, rather than the network instance itself.

Instead we can probably get by with exhaustively enumerating the network instance types in `NetworkId`:

```rust
// should probably look something like RoleType:
// https://github.com/libra/libra/blob/master/config/src/config/mod.rs#L110

#[repr(u8)]
enum NetworkType {
    Validator = 0,
    Public,
    Private,
}
struct NetworkId {
    network_type: NetworkType,
    network_name: String
    // ..
}
```

+ Each `NetworkConfig` should have a `network_id`. (https://github.com/libra/libra/blob/master/config/src/config/network_config.rs#L26)

+ `config-builder` should emit the right `network_id` for the `NetworkConfig`s it generates.
(https://github.com/libra/libra/blob/master/config/config-builder/src/validator_config.rs, https://github.com/libra/libra/blob/master/config/config-builder/src/full_node_config.rs, https://github.com/libra/libra/blob/master/config/src/generator.rs)

+ Will need some sanity checks in `NodeConfig` to check we don't have multiple `NetworkConfig`s with the same `NetworkId`.

+ `NetworkBuilder::new(..)` should probably take a `network_id`. (https://github.com/libra/libra/blob/master/network/src/validator_network/network_builder.rs#L148)

+ All network counters/metrics should include a new `network_id` label. We probably need to push down `NetworkId` into all network actors (peer_manager, peer, rpc, direct_send, connectivity_manager, ..)

+ All logs in network should include appropriate context (`network_id`, `role_type`, `peer_id`).

+ Later, we could also use this `NetworkId` to solve state sync/mempool issues with ambiguous network events. For example, we could tag `Event<TMessage>` (https://github.com/libra/libra/blob/master/network/src/protocols/network/mod.rs) with `NetworkId`. (cc @christinacelee would this actually be helpful?).

+ Add `NetworkId` (and `ChainId` #4011) to handshake message (https://github.com/libra/libra/blob/master/network/src/protocols/wire/handshake/v1/mod.rs#L107). Should help prevent accidental network discovery collisions.

**Comment by davidiw** [comment]
Should we add this as part of the handshake, like we plan to with chain id: https://github.com/libra/libra/issues/4011

**Comment by phlip9** [comment]
> Should we add this as part of the handshake, like we plan to with chain id: #4011

Good idea!

**Comment by gregnazario** [comment]
Okay key parts of this are as follows:

- [x] Add a `NetworkId` to the `NetworkConfig`, this should be an enum with the three network types.  (I've added a dummy type to ensure one of the networks are set purposefully)
- [x] Add `NetworkId` to the `HandshakeMsg`, this should check that Handshakes don't cross network boundaries.  (test included to check that this works)
- [x] Sanity check to ensure that a `NetworkId` isn't repeated in a `NodeConfig`.  It's not clear if this is across `full_node_networks`, `validator_network`, or combined.  I'm assuming combined.
- [x] NetworkConfig builder needs to include `NetworkId`
- [ ] Config builders for node types need to generate the right `NetworkId`
- [ ] Add to logging tuple of context`(network_id, role_type, peer_id)`
- [ ] Add to counters / metrics `network_id`

**Comment by davidiw** [comment]
Let's use an enum of the following format:

```
Enum NetworkType {
  Validator,
  Private { name: String} ,
  Public,
}
```
That way we can use the enum as a comparison point too and not just for string purposes.

**Comment by phlip9** [comment]
We still have to fix the metrics so they include the `NetworkId` in the labels

**Comment by gregnazario** [comment]
Logs have been completed https://github.com/libra/libra/pull/4382
Metrics were relatively a larger scope issue with how they are handled in general.  I've decided to put that off for now
