### ISSUE TITLE
user level coin, libra.move CurrencyRegistrationCapability

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#4037]
I'd like to create my own coin and register it.
When I read the code libra.move, it seems I need CurrencyRegistrationCapability.
That means I have to pay for a user level coin.
What's the guideline for user level coin?
Thanks.

George Wu

**Comment by sblackshear** [comment]
We do not support custom coins in Libra testnet or mainnet, but you can experiment with this in your own local network: https://developers.libra.org/docs/run-local-network and https://developers.libra.org/docs/run-move-locally.

**Comment by jolestar** [comment]
@sblackshear Does libra have plans to support user-defined token standards in the future? I think it's an important feature, such as a user-defined bond, asset, etc.

**Comment by aihuawu** [comment]
My understanding is libra software support custom coins and scripts, just for legal reason,
it will not be alive on mainnet and testnet.  That's just ridiculous.

So you guys build a good product just for people to watch?

george wu

**Comment by sblackshear** [comment]
Here is what the Libra whitepaper says on [this](https://libra.org/en-US/white-paper/#whats-next):

> The Association will work to foster the development and deployment of the Move language, allowing developers to use the safeguards inherent to the Move language to develop innovative financial applications. This will entail collaboration with regulators on defining appropriate safeguards for third-party publishing of smart contracts as well as an exploration of other financial programming contexts that would benefit from the innovations in Move.

There are testnets that allow custom modules and scripts; I believe [MoveOnLibra](https://devnet.explorer.moveonlibra.com/) is one.

**Comment by aihuawu** [comment]
Thank you very much.
That's the testnet I want.
