### ISSUE TITLE
[Bug] Race condition on SpeculationCache::add_block

### ISSUE THREAD

**Issue by gterzian** [libra/libra#4042]
# 🐛 Bug

A critical section is entered on `block_map` at https://github.com/libra/libra/blob/3c7c4fe6cecbddea30ce200230f2fef57fe65ced/execution/executor/src/speculation_cache/mod.rs#L200

and in the critical section, there is a check on whether the map already contains a block for the given id. 

Then the critical section is exited(on the same line calling `contains_key`). 

Then, in the "there is not block in the map" case, the critical section is re-entered at https://github.com/libra/libra/blob/3c7c4fe6cecbddea30ce200230f2fef57fe65ced/execution/executor/src/speculation_cache/mod.rs#L211

and the block is inserted. 

So it seems the code assumes that an invariant checked inside the first critical section holds even after having exited it. 

## To reproduce

Write a test like [`test_add_duplicate_block`](https://github.com/libra/libra/blob/3c7c4fe6cecbddea30ce200230f2fef57fe65ced/execution/executor/src/speculation_cache/test.rs#L97), that would actually assert no block can be inserted for a given key if one is already present,  and make it concurrent. 

## Expected Behavior

Concurrent use of `add_block` should not result in inserting duplicate blocks, or it should not be possible to call `add_block` concurrently. 

## Additional context

it's somewhat unclear how `SpeculationCache` is supposed to be used. Since not all members appear theadsafe I can only assume it's used with a lock around it(if used by multiple threads at all), so then the additional internal locking of `block_map` seems out of place. 

For example when a client calls `reset`, I assume both `block_map` and `heads` are assumed to be reset to new values as a kind of atomic "transaction", whereas now since one has a lock around it and the other does not, it would appear possible for `heads` to be reset, while another client is holding the lock on `block_map`, and then that other client could end-up using the "reset" heads together with the "old" `block_map`. 

So I'd say there should either not be any internal locking for `SpeculationCache`(not including the arcs stored in the various data structures), making it clear that methods cannot be called concurrently(there can be only one client at a time, either because a single thread owns it, or because it is used with a single lock around the struct), or if concurrent use is the goal then bugs like this should be addressed.

**Comment by gterzian** [comment]
And the solution is to put both operations in the same critical section, and to scope it since in some case below you want to re-acquire the lock at https://github.com/libra/libra/blob/3c7c4fe6cecbddea30ce200230f2fef57fe65ced/execution/executor/src/speculation_cache/mod.rs#L220

So something like:

```rust
{
    // Start critical section on  `block_map`.
    let map = self.block_map.lock().unwrap();
    if map.contains_key(&block_id) {
           return Ok(());
    }
     let block = //
     map.insert(block_id, Arc::downgrade(&block));
     // End critical section on  `block_map`.
}
if parent_block_id == self.committed_block_id() {
```

**Comment by gterzian** [comment]
Ah ok so looking at the various comments it now appears that it's not so much the `SpeculationCache` that can have multiple concurrent client, it's rather that the `block_map` is shared with each `SpeculationBlock`, only to remove itself from the map when it drops. 

So for example the race condition described above would appear "impossible" in practice, if `add_block` is actually never called concurrently, it's only a block that could remove itself from the map concurrently. 

However, I think it would be much clearer if just looking at the struct members you could understand how it's supposed to work. Right now you have to actually read all the logic to then finally "get it", I think it's brittle and bound to lead to bugs eventually as various people change the code. 

Also, I still don't fully understand how `get_block` is used in practice, or when/where a `SpeculationBlock` typically drops, whether calling `add_child` on it could influence some other client of a block(one that doesn't hold a lock consistently during an algorithm that assumes no children can be added for it's duration, for example). 

So in other words the "business logic" is externalised, and you'd have to actually read every place where a `SpeculationBlock` is used to get it. 

So this goes beyond this issue, however I think you could add a read-only `SpeculationBlockView` returned by `get_block`, which internally would have a shared `Arc<AtomicUsize>`, and decrement it on drop. 

Then you remove the lock around `block_map` and make the `SpeculationCache` the sole owner of it, containing non-shared `SpeculationBlock` which are just a piece of local data on which the cache runs it's logic. They would own the shared atomic counter. 

`heads` could just be a `Vec<HashValue>`.

each `SpeculationBlock` could also own a `Vec<HashValue>` representing it's children. When a `SpeculationBlock` is removed from the map, you then also remove all children of it. 

Then inside `add_block`, to determine whether a block is "present":

1. Check the map, if empty => negative.
2. Check the value, if the shared counter is zero and the hash it not in `heads` => negative and remove the entry from the map(as well as all the children). (no need to check if it still has a parent, since if it's in the map it should have one). 
3. Otherwise, positive, return Ok. 


That way, all business logic and data is private to the cache, with the exception of the shared counter, but that one tells you exactly what it is when you see it in a struct, whereas now the shared map implies all sorts of possible concurrent of it, leaving the door rather open for bugs down the road.

**Comment by zekun000** [comment]
If we want to avoid confusion of concurrent code vs just mutability, probably can replace Arc<Mutex<_>> with Rc<RefCell<_>>

**Comment by gterzian** [comment]
> If we want to avoid confusion of concurrent code vs just mutability, probably can replace Arc<Mutex<_>> with Rc<RefCell<_>>

Could be a solution, although in the current structure the mutex may be required.

Trying to understand all places where a speculation cache is used, it does seem to be a "local" concept, actually it appears like multiple components have their own local executor and cache?

Some places I found:

https://github.com/libra/libra/blob/d4ac3235d5bb4060bd0581006b0921236fbdecc4/consensus/src/state_computer.rs#L25

acquired at 

https://github.com/libra/libra/blob/191b40dc7108b1213150fa3d999aedc2f70394fe/consensus/src/consensus_provider.rs#L46

and then the state synchronizer also owns one at https://github.com/libra/libra/blob/d4ac3235d5bb4060bd0581006b0921236fbdecc4/consensus/src/state_computer.rs#L25

acquired via https://github.com/libra/libra/blob/c72c5e79c8d506d24e6877a828356a13c1bc78f4/libra-node/src/main_node.rs#L58

So the executor of the state synchronizer appears actually separate from the one from consensus? Consensus seems to be owning an actual client to the execution correctness component, whereas state synchronizer owns it's own local executor?

So anyway, in terms of removing the mutex, it looks like inherently the cache doesn't have to be made `Sync`, although in the consensus execution proxy there is a `Sync` bound around `BlockExecutor`, so I assume consensus shares it internally among tasks/threads? 

On the other hand, the coordinator in state synchronizer does not seem to require `ChunkExecutor` to be `Sync`. 

Then if you look inside the execution correctness manager itself, then it appears that with the exception of the local client, it's always a single thread owning the executor, for example https://github.com/libra/libra/blob/3c7c4fe6cecbddea30ce200230f2fef57fe65ced/execution/execution-correctness/src/serializer.rs#L21

So just trying to map a bit where the executor(and the cache is owned) is used and how, and it would appear like it's usually in a single thread or task, and that in the few execptions one could simply put a mutex around the thing as a whole, and remove the internal locking, and perhaps replace it with `Rc<RefCell<_>>`. 

(Unless the `Arc<Mutex<>>` returned by the cache in `get_block` really needs to itself be `Sync`)

**Comment by wqfish** [comment]
I took a quick look at the code. Note that the public APIs that mutates internal state all seem to have `&mut self` in the signature, so this indicates that we don't need to worry about concurrency at all: rust compiler will enforce that only one mutable reference is allowed. Whether it internally uses `Mutex` or `RefCell` and whether the struct is `Sync` don't actually matter.

On the other hand, the fact that concurrent mutation is not possible indicates that using mutexes isn't really necessary. So I do agree that having these mutexes could be confusing (and `RefCell` isn't much better), and ideally we remove them from the code. I believe the original problem here was basically that the code wants to mutate something through an `Arc` pointer, which is not possible unless you wrap the thing in a mutex, even if you know there's no concurrent access.

Personally I'm really not a fan of all these locks, so I'd be happy if we re-implement this in a different way 😄

**Comment by zekun000** [comment]
I took a quick look, it doesn't seem feasible to replace it with Rc since we're using async and spawn requires Send

**Comment by gterzian** [comment]
>  it doesn't seem feasible to replace it with Rc since we're using async and spawn requires Send

Ok, how about the alternative design I sketched above, where you'd separate the `SpeculationBlock` from a `SpeculationBlockView`, where the latter would be returned by `get_block`, and provide a read-only "view" into the block? (all methods of `SpeculationBlock` appear to be about reading data, with the expection of `add_child`, and I would say that could be removed by having the `SpeculationBlock` own a `Vec<HashValue>` representing the children. 

So `SpeculationBlockView` would simply be read-only, and `Send` by default(I'm hoping `id`, `transactions` and `output` are `Send`). 

Then the cache could simply own a `HashMap<HashValue, SpeculationBlock>`, and `get_block` would return a `Result<SpeculationBlockView>, Error>`.

Then for the refcount you could share a `Arc<AtomiUsize>` between the `SpeculationBlock` and the `SpeculationBlockView`. (or even a `Arc<Mutex<usize>>`), which I think would be better than actually sharing the `Arc<Mutex<HashMap<HashValue, Weak<Mutex<SpeculationBlock>>>>>` because it would clearer(since it could only represent a refcount, not some broader concurrent use of the map). 

Then also `heads: Vec<Arc<Mutex<SpeculationBlock>>>` could become `heads: Vec<HashValue>`.

Then to prune the cache, or determine the presence of a block, you'd just have to:

1. Check the map,
2. If it's in the map, check the refcount,
3. If the refcount is zero, check `heads`. 

So if a block is not in the map, or it's refcount is zero and it's not found in heads, then it's gone. 

The main advantage is that this logic is basically just local and not concurrent, with the exception of the refcount, but that should be very clear and remove opportunities for errors. 

The only question remaining would be "when to prune the cache from blocks with zero refs?". 

I'd say you could do it on each call to `get_block`, or otherwise add some dedicated periodic call that would have to be scheduled from the event-loop where the cache is being used from. 

Also it appeared to me the cache is quite often reset/pruned already by the user, it appears to be mostly for short-term storage, so if that is correct there should be plenty of opportunity to regularly run the refcount logic and prune it.

**Comment by zekun000** [comment]
I don't think it's worth the effort to change given it can be easily explained in the comment this is not multi threaded, closing.
