### ISSUE TITLE
is it possible for the move compiler to generate an abi file?

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#4044]
is it possible for the move compiler to generate an abi file? 
In ethereum, it can generate both bin and abi files.
the abi files define the message signature and is used in json-rpc.

Thanks.

George Wu

**Comment by tnowacki** [comment]
We currently generate serialized binary format for Move bytecode (`.mv` files), which is really the only data representation available for the bytecode currently. 

If I understand your request, you would like the compiler to also generate files that could then generate signed transactions? which could then be submitted directly on chain? (If I did not understand that correctly, let me know)
It's something we definitely could do. Currently a lot of that sort of developer facing support hasn't been planned out (outside of the existing client). It's something we definitely plan on sorting out more in detail in the future. That being said, it might not end up being exactly the Move compiler that generates these transactions, but rest assured, there will be some tool that does so :)

**Comment by aihuawu** [comment]
I have script:
void main<coin>(from:address, to: amount, amount:u64) {
...
}
I want to call it in javascript through json-rpc.
The generated .mv file is not enough for me to send the transaction since it has
arguments. I understand I need to build a lcs serialization for the transaction.

Since I am in javascript, my arguments are dynamic, I need to generate the serialization
on the fly, without the abi, I am unable to build the serialization.

In ethereum, the compiler generate abi file, and they provide web3.js library to build the
json-rpc. And I know how to sign and send a transaction, the writing a dapp is quite easy.

But in libra, I can't figure out how to write a simple hello world 
javascript application for the script above.
The hard part is serialization for arbitrary arguments. Computing hash and signing and sending
transaction is quite trivial.

george  wu

**Comment by dariorussi** [comment]
we seem to have more and more requests about this and we are actively and currently looking into it. Please bear with us a little longer as we come up with a story. This is nearly a problem for clients right now.
If you have any recommendation on what you'd like that API/ABi to be and you think we should look into please let us know

**Comment by aihuawu** [comment]
If you can also generate abi for the module and also we can call directly the module methods in json-rpc, it will be very nice.  That's the ethereum way to make a transaction.

**Comment by jolestar** [comment]
I think we need a tool to generate another language's code by Move resource/struct and main function, or generate an ABI description file, and another language generates code by the file.

**Comment by sblackshear** [comment]
CC @matbd

**Comment by matbd** [comment]
Good question!

We now have some notion of [a LCS schema](https://raw.githubusercontent.com/libra/libra/master/testsuite/generate-format/tests/staged/libra.yaml) and have used it successfully to generate python helpers for Libra transactions (the LCS bytes inside the JSON-RPC calls).

@sblackshear has been asking me about a similar idea for Move contracts for a while. (Specifically, the question is how to populate the TransactionArgument-s within the LCS bytes.) Hopefully, we'll come up with good answers very soon.

**Comment by matbd** [comment]
Here is a first PR in this direction: https://github.com/libra/libra/pull/4367

**Comment by matbd** [comment]
And now, in this PR, we are creating ABI files and making code generation first-class in the codebase: https://github.com/libra/libra/pull/4600

**Comment by matbd** [comment]
After https://github.com/libra/libra/pull/4703, we now have support for code generation of transaction types and transaction builders in two languages (python and C++) as well as the corresponding LCS runtimes. A quick example can be found in the summary of the PR.

**Comment by aihuawu** [comment]
@matbd 

Thanks for the code generation.
Actually I am working in a web environment, we are using javascript,  so are you going to support javascript?
Thanks.

george wu
