### ISSUE TITLE
[Bug] Client doesn't support HTTP proxies anymore

### ISSUE THREAD

**Issue by mgorven** [libra/libra#4082]
# 🐛 Bug

The client used to support connecting via an HTTP proxy, this is now broken (probably since JSON-RPC).

## To reproduce

```
$ scripts/cli/start_cli_testnet.sh
     Running `target/debug/cli --url 'https://client.testnet.libra.org' --waypoint_url 'https://developers.libra.org/testnet_waypoint.txt'`
ERROR 2020-05-27 20:46:18 common/crash-handler/src/lib.rs:38 details = '''panicked at 'Failure to retrieve a waypoint from https://developers.libra.org/testnet_waypoint.txt: URL https://developers.libra.org/testnet_waypoint.txt returned HTTP/1.1 500 Connection Failed', testsuite/cli/src/main.rs:89:21'''
$ curl https://developers.libra.org/testnet_waypoint.txt
0:64c09fc187261bf84d971f1b42711c26d2791647ca9e06222b52810e024106c7
$ env | grep http
http_proxy=http://fwdproxy:8080
https_proxy=http://fwdproxy:8080
```

## Expected Behavior

Client works with an HTTP proxy set.

**Comment by thefallentree** [comment]
not an issue.

**Comment by mgorven** [comment]
Please don't close issues without an explanation. Are you saying the client does support proxies? Or that it doesn't need to?

**Comment by thefallentree** [comment]
We need to switch frome ureq to reqwest here 
https://github.com/libra/libra/blob/5666bdc34859277ca705d75a0dbfb813e7756016/testsuite/cli/src/main.rs#L203

**Comment by thefallentree** [comment]
@dmitri-perelman  @mimoo  @davidiw

**Comment by mgorven** [comment]
Working with #4090, thanks @thefallentree.
