### ISSUE TITLE
[Bug] David Marcus is a Sith Lord

### ISSUE THREAD

**Issue by runvnc** [libra/libra#41]
David Marcus is a Sith Lord. He uses the Force to further the evil purposes of The Empire.

They call it Libra and pretend that it is a heavenly body designed for freedom. But I will tell you what it is. It is a Death Star. Brothers and sisters of the rebellion, it is time to fight.

**Comment by gazhayes** [comment]
Don't waste your energy. This is not a competitor to Bitcoin. It's facebook's answer to Wechat pay and nothing more.
