### ISSUE TITLE
[Client] Rust Client Feature requests

### ISSUE THREAD

**Issue by thefallentree** [libra/libra#4200]
Basic features

from @mimoo 

[ ] - verfication by default

from @thefallentree 

[ ] - use fault injection to test beahvior in stale response, timeout etc. 

from @dmitri-perelman 

send a txn and check its status
retrieve latest blockchain metadata
retrieve account state of a given address
retrieve mint, preburn, burn, payment events for a given address
[advanced?]: retrieve the content of the given address with all the resources: the AccountState type in Rust. AOS might want to retrieve the specific resource out of it (e.g., Preburn)

**Comment by ssinghaldev** [comment]
@thefallentree , should this issue be closed or reassigned?
