### ISSUE TITLE
[consensus] simplify PendingVote

### ISSUE THREAD

**Issue by zekun000** [libra/libra#4206]
PendingVote was designed to support votes in any round, and as we move to the RoundState world, PendingVote is per round instance.

We could simplify how it works by assuming all the votes/timeout inside is for the same round now.

**Comment by mimoo** [comment]
this would mean moving PendingVotes to the internal state of a RoundState right? Right now it is in block store

**Comment by zekun000** [comment]
@mimoo what revision are you looking at? it's part of the RoundState since long time ago

**Comment by mimoo** [comment]
Ah indeed! I got tricked seeing that the file is in `block_storage/`! There's a number of things that can be simplified here then :)

**Comment by mimoo** [comment]
So here's what I propose:

- [ ] make the logic work with the new assumption that we are at a specific/fixed round https://github.com/libra/libra/pull/4927
- [ ] simplify the logic to make it easy to match it to a spec (by inlining functions inside of `insert_vote()` https://github.com/libra/libra/pull/4927
- [ ] pass epoch+round as arguments to insert_vote()
- [ ] move out of `block_storage/`
