### ISSUE TITLE
[network] Consider another persistence format other than TOML

### ISSUE THREAD

**Issue by gregnazario** [libra/libra#4210]
After spending a lot of time reworking the NetworkConfig, I found that TOML will fail serialization, and the only way I fixed it was moving a field in a struct from the first field to the last field.  This means that the TOML implementation is fragile, and can be problematic in the future as it is extended.

We should look into using a different format (JSON/YAML/...) as the TOML formatter has some rough edges associated with [Enums with extra info](https://stackoverflow.com/questions/57560593/why-do-i-get-an-unsupportedtype-error-when-serializing-to-toml-with-a-manually-i), as well as the [ordering issue](https://github.com/alexcrichton/toml-rs/issues/142) I had, which wasn't solved by adding annotations, or custom building serializers.

**Comment by phlip9** [comment]
Closed by #4465
