### ISSUE TITLE
gRPC use in Libra Core

### ISSUE THREAD

**Issue by fbandersnatch** [libra/libra#422]
gRPC is used extensively in Libra Core. This is the main RPC mechanism we use in addition to Libra Core network layer.

Things to consider:
1. **[Protobuf]** The protobuf library use: The generated structs are not Rusty structs, and we end up wrapping them. The gRPC library we use supports Prost in addition to rust-protobuf, so migration is possible
2. **[GRPC]** The gRPC library we use (pingcap/grpc-rs) is a wrapper around the C implementation. The C implementation is stable and reliable but makes a more complicated build process, server executors are harder to manage, etc. Alternatives: tower-rs/tower-grpc is no longer in "Do not use in production" state.
3. **[Usage]** gRPC is used as the communication mechanism for clients to Validators and also between the different components in a validator node.
Some components are going to be deployed separately (e.g., AdmissionControl), in which case, keeping gRPC is reasonable, other components will always stay on the same machine/process -- in this case gRPC might not be the best option.

Related #221

**Comment by bmwill** [comment]
We've just completed migrating to tonic!
