### ISSUE TITLE
Stdlib cleanup: Finalize the accepted types in transaction scripts to support LCS (e.g., vector<vector<u8>>) [P1]

### ISSUE THREAD

**Issue by bob-wilson** [libra/libra#4264]

**Comment by matbd** [comment]
@bob-wilson Do we know the subset of Move types that are eligible here?

**Comment by dariorussi** [comment]
do we need to allow `vector<vector<>>`?
we are changing that in the VM but I would verify what we want for V1 in terms of transaction arguments and be happy to keep them even more limited.
Thoughts?

**Comment by jolestar** [comment]
Can we support Struct in transaction script args?

**Comment by dariorussi** [comment]
> Can we support Struct in transaction script args?

not sure if we will enable it in V1. However it depends on how the Move VM evolves in the next few weeks (the V1 timeline).
It's possible that the Move VM will accept that but not the Move Adapter (the layer that embeds the VM).
I am not sure what you are after and where you are thinking to allow Struct

**Comment by jolestar** [comment]
> > Can we support Struct in transaction script args?
> 
> not sure if we will enable it in V1. However it depends on how the Move VM evolves in the next few weeks (the V1 timeline).
> It's possible that the Move VM will accept that but not the Move Adapter (the layer that embeds the VM).
> I am not sure what you are after and where you are thinking to allow Struct

If arg support struct, it will simplify the passing of script args and make the transaction argument types more consistent with the types supported by the VM.

**Comment by bob-wilson** [comment]
@vgao1996 You're doing this now, right?

**Comment by sblackshear** [comment]
Just to clarify, as tx script arguments, is the idea that we are allowing:
```
ground_type ::= bool | u8 | u64 | u128 | address
composite_type ::= ground_type | vector<composite_type>
signer_type ::= signer
tx_arg_type ::= composite_type | &signer_type
```
?

~= everything but resources, structs, `signer`s, and refs to all types but `signer`?

**Comment by bob-wilson** [comment]
See https://github.com/libra/libra/pull/5138. From what I can tell, that matches Sam's summary above (and I was mistaken: it looks like @dariorussi is doing this work).

**Comment by dariorussi** [comment]
correct, it's what was decided by the team and what @sblackshear put there; to be more accurate, it is the definition of constants, something that can go in the constant pool.
We are going out with that for now and for "who knows how long". The point here is that it feels safe to pass in a constant (a literal so to speak) as it is uncommon to attach much semantics to them. So for now constants is going to be.

**Comment by bob-wilson** [comment]
#5138 landed now, so I believe this is done
