### ISSUE TITLE
Stdlib cleanup: Audit events to ensure that we have all the events we need + do not have superfluous events [P2]

### ISSUE THREAD

**Issue by bob-wilson** [libra/libra#4274]

**Comment by tzakian** [comment]
@sblackshear has this been completed with your events refactor from last week?

**Comment by bob-wilson** [comment]
@sblackshear ping?

**Comment by sblackshear** [comment]
We have at least https://github.com/libra/libra/issues/5351 to deal with here. I think we should also consider an event for rotating account authentication keys.

**Comment by bob-wilson** [comment]
#5351 is done now.
We're in the process of adding a new CreateAccountEvent in #6156 
@sblackshear Are you still considering an event for key rotation?

**Comment by sblackshear** [comment]
@bob-wilson: I think not. It seems like too big of a breaking change at this point, and there have not been a lot of requests. I think we can (hopefully!) close this when #6516 lands.

**Comment by bob-wilson** [comment]
OK, closing then.
