### ISSUE TITLE
Stdlib cleanup: Audit stdlib for dead code [P3]

### ISSUE THREAD

**Issue by bob-wilson** [libra/libra#4275]

**Comment by bob-wilson** [comment]
@tzakian or @wrwg: I saw some progress on this over the last few weeks. Is there more to do or can we consider this completed?

**Comment by tzakian** [comment]
I would consider this completed as far as the code freeze is concerned. Any code that is "dead" right now is tested and is there for future extension/functionality, so I'm not planning on making any code changes before the code freeze.

**Comment by wrwg** [comment]
Agree with Tim, we can close this (for this release).

**Comment by bob-wilson** [comment]
OK, thanks
