### ISSUE TITLE
Stdlib feature: Implement individual rotation of multisig keys to support LibraRoot role [P2]

### ISSUE THREAD

**Issue by bob-wilson** [libra/libra#4281]

**Comment by bob-wilson** [comment]
@tzakian is going to ask the AOS team if this is needed for v1

**Comment by tzakian** [comment]
This depends on decisions that remain TBD for dual-governance. Depending on the outcome of those decisions this will need to be implemented (or not) for V1.

**Comment by bob-wilson** [comment]
OK, I'm going to move it to the v1 priority column until we find out otherwise.

**Comment by bob-wilson** [comment]
Any update on this?

**Comment by davidiw** [comment]
single keys only
