### ISSUE TITLE
[Feature Request] testnet nodes list 

### ISSUE THREAD

**Issue by crysptos** [libra/libra#43]
# 🚀 Feature Request
**testnet nodes list** for CLI testing

## Motivation

**Is your feature request related to a problem? Please describe.**
Due to the crazy amount of traffic / throttling 

## Pitch

**Describe the solution you'd like**
alternative instances to test

**Describe alternatives you've considered**
Run separate nodes

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))

## Additional context
handicap the ability of some CLI to not connect due to : 

`
Not able to connect to validator at ac.testnet.libra.org:80, error RpcFailure(RpcStatus { status: Unavailable, details: Some("Socket closed") })
`

**Comment by ericnakagawa** [comment]
One more complex workaround is to run your own node and test on your local network. If we add additional networks, we'll make an announcement. Keep an eye on https://developers.libra.org/blog/.
