### ISSUE TITLE
subtype polymorphism and generics in move-lang

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#4329]
I noticed there is generics in move lang, but there is no subtype polymorphism.
I can see generics is done at compile time while polymorphism is done at run time.
So generics is safer.

do we also support subtype polymorphism?
thanks.

george wu

**Comment by jolestar** [comment]
As I understand it, Move doesn't support polymorphism or any dynamic dispatch。 I have a conversation with @tnowacki about this topic at #1567 .

**Comment by sblackshear** [comment]
Move does not support subtype polymorphism. See the discussion in https://community.libra.org/t/traits-or-type-specific-implementation-in-move/2790 for lots more detail on the rationale for this!

**Comment by bob-wilson** [comment]
I'm going to go ahead and close this. We can reopen if there is more to discuss, but as I understand it, we have no plans to add subtype polymorphism.

**Comment by aihuawu** [comment]
Without subtype, I want to do a sort in generics. Can I pass a function to sort?

dog_compare(x:dog, y:dog) {...}
cat_compare(x:cat, y:cat) {...}

sort(ls:vec<animal_type>, compare:function){
.....
if(compare(x,y)){
swap<animal_type>(ls,x,y);
}
.....
}

**Comment by sblackshear** [comment]
Move does not support custom comparators, but you can use the `Compare` module to implement a generic sort.

**Comment by aihuawu** [comment]
If move does not support custom comparators, the generics feature is too weak for a lot of usecases.
If I use the compare module, every type will have the same compare function, the sorting reusability
is not very useful.  In ethereum, it has inheritance, it can do dynamic binding. Although  it is not so safe, it is very powerful.  Since a lot of us come from an OOP background, move does not allow subtype, and it does not allow custom function argument, we will feel it is very weak as a programming language. Of course, I agree the resource move idiom is quite powerful.  Just I also want it to be a powerful programming language.
