### ISSUE TITLE
[Bug] [move-prover] Type-checking and using len(v) in the specification language.

### ISSUE THREAD

**Issue by kkmc** [libra/libra#4355]
# 🐛 Bug

In verifying the vector reverse function of the Vector module, we encountered issues in using len(v) inside of the specification expressions.

Referring to len(v) outside of a quantifier range (e.g. first argument to all and any) raises an error.

Also, a local argument whose name is len may conflict with len(v) inside the Boogie models. Refer to https://github.com/libra/libra/pull/4319/commits/3fcb7b44b54924214cb1bb50ad4701515e6fe70f#diff-d85da9b8b2c51c1651760f69f1eff8b4R151.

## To reproduce

Removing the comment for line 135 in tests/sources/functional/verify_vector.move (https://github.com/libra/libra/pull/4319/commits/3fcb7b44b54924214cb1bb50ad4701515e6fe70f#diff-d85da9b8b2c51c1651760f69f1eff8b4R135
) and keep the comments for every other line in the spec block to reveal the error below.

Now comment out line 135 and remove the comment for line 138  (https://github.com/libra/libra/pull/4319/commits/3fcb7b44b54924214cb1bb50ad4701515e6fe70f#diff-d85da9b8b2c51c1651760f69f1eff8b4R138), the type checker will no longer raise this error (which is not consistent with the previous error).

**Stack trace/error message**
```
error: expected `|vector<#0>|?1` but found `u64` in expression

     ┌── tests/sources/functional/verify_vector.move:123:32 ───
     │
 123 │                 assert (len == len(v));
     │                                ^^^^^^
     │
```

## Expected Behavior

Expected no errors when using a local variable `len` (issue with variable renaming?) and using len(v) anywhere inside of specification expressions (not just the quantifier range).

**Comment by wrwg** [comment]
This is by design. To access a shadowed global name, one can use `::len(x)`
