### ISSUE TITLE
Stdlib cleanup: remove all uses of Transaction::sender and get_txn_sender from functional tests

### ISSUE THREAD

**Issue by sblackshear** [libra/libra#4359]

**Comment by bob-wilson** [comment]
I did the Transaction::sender changes in https://github.com/libra/libra/pull/4447

**Comment by bob-wilson** [comment]
Most uses of get_txn_sender were removed in #4515 
There are still some in the Prover tests, but I believe those tests can be removed.

**Comment by bob-wilson** [comment]
I posted a PR to remove those Prover tests (#4590). I'm proceeding to start removing the compiler support for the old sender features.

**Comment by bob-wilson** [comment]
Here's a PR to update the prover's stackless-bytecode-generator tests: https://github.com/libra/libra/pull/4694

**Comment by bob-wilson** [comment]
I think the intent of this issue was to specifically track changes in functional_tests. That is done now, so I'm closing this.
