### ISSUE TITLE
start_cli_testnet.sh  Compiling prometheus v0.4.2 error[E0308]: mismatched types

### ISSUE THREAD

**Issue by danieljosediaz** [libra/libra#437]
# 🐛 Bug

I'm trying to run start_cli_testnet.sh, and have this err msg, when it try to compile Prometheus v0.4.2. Any help would be apreciate.

~/libra$ ./scripts/cli/start_cli_testnet.sh
Building and running client in debug mode.
   Compiling prometheus v0.4.2
error[E0308]: mismatched types
   --> /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.4.2/src/histogram.rs:272:43
    |
272 |                 let now_ms = now.tv_sec * MILLIS_PER_SEC + now.tv_nsec / NANOS_PER_MILLI;
    |                                           ^^^^^^^^^^^^^^ expected i32, found i64

error[E0277]: cannot multiply `i64` to `i32`
   --> /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.4.2/src/histogram.rs:272:41
    |
272 |                 let now_ms = now.tv_sec * MILLIS_PER_SEC + now.tv_nsec / NANOS_PER_MILLI;
    |                                         ^ no implementation for `i32 * i64`
    |
    = help: the trait `std::ops::Mul<i64>` is not implemented for `i32`

error[E0308]: mismatched types
   --> /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.4.2/src/histogram.rs:272:74
    |
272 |                 let now_ms = now.tv_sec * MILLIS_PER_SEC + now.tv_nsec / NANOS_PER_MILLI;
    |                                                                          ^^^^^^^^^^^^^^^ expected i32, found i64

error[E0277]: cannot divide `i32` by `i64`
   --> /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.4.2/src/histogram.rs:272:72
    |
272 |                 let now_ms = now.tv_sec * MILLIS_PER_SEC + now.tv_nsec / NANOS_PER_MILLI;
    |                                                                        ^ no implementation for `i32 / i64`
    |
    = help: the trait `std::ops::Div<i64>` is not implemented for `i32`

error[E0308]: mismatched types
   --> /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.4.2/src/histogram.rs:273:39
    |
273 |                 let t_ms = t.tv_sec * MILLIS_PER_SEC + t.tv_nsec / NANOS_PER_MILLI;
    |                                       ^^^^^^^^^^^^^^ expected i32, found i64

error[E0277]: cannot multiply `i64` to `i32`
   --> /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.4.2/src/histogram.rs:273:37
    |
273 |                 let t_ms = t.tv_sec * MILLIS_PER_SEC + t.tv_nsec / NANOS_PER_MILLI;
    |                                     ^ no implementation for `i32 * i64`
    |
    = help: the trait `std::ops::Mul<i64>` is not implemented for `i32`

error[E0308]: mismatched types
   --> /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.4.2/src/histogram.rs:273:68
    |
273 |                 let t_ms = t.tv_sec * MILLIS_PER_SEC + t.tv_nsec / NANOS_PER_MILLI;
    |                                                                    ^^^^^^^^^^^^^^^ expected i32, found i64

error[E0277]: cannot divide `i32` by `i64`
   --> /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.4.2/src/histogram.rs:273:66
    |
273 |                 let t_ms = t.tv_sec * MILLIS_PER_SEC + t.tv_nsec / NANOS_PER_MILLI;
    |                                                                  ^ no implementation for `i32 / i64`
    |
    = help: the trait `std::ops::Div<i64>` is not implemented for `i32`

error: aborting due to 8 previous errors

Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `prometheus`.

**Comment by huitseeker** [comment]
This should be made obsolete by https://github.com/libra/libra/pull/796
