### ISSUE TITLE
[Bug] Safety-rules refusing to sign round after crash

### ISSUE THREAD

**Issue by mgorven** [libra/libra#4390]
# 🐛 Bug

My validator crashed for other reasons, but after restarting safety-rules refuses to sign rounds. This is a 3 validator network.

```
DEBUG 2020-06-10 05:07:10 consensus/src/round_manager.rs:425 Planning to vote for a NIL block [id: 65dba7c3 (NIL), epoch: 1, round: 29445, parent_id: d62b2854]
DEBUG 2020-06-10 05:07:10 consensus/src/round_manager.rs:512 Success with NoWaitRequired { current_duration_since_epoch: 1591765630.644293691s, early_duration: 682.068273691s } for being able to vote
ERROR 2020-06-10 05:07:10 consensus/src/epoch_manager.rs:508 [RoundManager] SafetyRules [38;5;1mRejected[39m [id: 65dba7c3 (NIL), epoch: 1, round: 29445, parent_id: d62b2854]

Caused by:
    Proposal at round 29445 is not newer than the last vote round 29445
```

https://fburl.com/everpaste/tb57yu74
https://fburl.com/everpaste/fem98d5m

**Comment by huitseeker** [comment]
This seems to be a normal feature of the algorithm: the validator issued a vote for round 29445, sees the same proposal again on restart, and refuses to sign it (validators sign in strictly increasing rounds). The network should be able to advance on >= 2 signatures (2 or 3 depending on whether the leader has received the fallen validator's initial vote) and move on to the next round.

**Comment by zekun000** [comment]
see https://github.com/libra/libra/issues/4807, this refers to `Consensus losing a vote and re-requesting for the same round`

**Comment by zekun000** [comment]
https://github.com/libra/libra/pull/4843
