### ISSUE TITLE
[Feature Request]Provide a mechanism to detect Struct information, such as Module address, Module name, Struct name.

### ISSUE THREAD

**Issue by jolestar** [libra/libra#4468]
# 🚀 Feature Request

Provide a mechanism to detect Struct information, such as module address, module name, Struct name, like Reflection.

## Motivation
1.  Avoid hard code some address for some privilege check.
2. Get more info from source code to avoid hard code some string. 

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

This is a draft implement of this  #4469

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by tnowacki** [comment]
This is intentionally something we will not add. 
This sort of information becomes very difficult to reason about and very difficult to prove safety once its in the runtime. 

> Avoid hard code some address for some privilege check.
If you are avoiding hard coding some privilege check with an address. You should parametrize your module's functions with the address that is the "owner" of the current item. 

We agree that this is bad practice. The design patterns we advocate instead are:
- Define an explicit capability resource and have the privileged function accept the capability (or a reference to it) as input (e.g. https://github.com/libra/libra/blob/master/language/stdlib/modules/Libra.move#L257)
- Define an explicit capability resource, publish it under the privileged address, and then use exists in the privileged function (e.g. https://github.com/libra/libra/blob/master/language/stdlib/modules/Association.move#L69)
- One last trick... Make the privileged function generic and check its type at runtime. (e.g. https://github.com/libra/libra/blob/master/language/stdlib/modules/TransactionFee.move#L83). That is, if you had `fun foo<T>() { ... }` You can case on the instantiated type of T at runtime. This pattern is the least appealing of the three, but it is sometimes the best option. (Note: This isn't a huge safety concern as you cannot add new cases as time goes on. The set of cases is fixed at the declaration of the function).

> Get more info from source code to avoid hard code some string.

This is intentionally a design choice that we will not add. Code meta data should not affect runtime behavior. It becomes very difficult to reason about safety once this is true 

Again, constants might help for some of these situations.

--- 

For both of these questions, it would really help if you added some specific code examples. Let us know if you have any, and we can try to address specific issues you have having 

--- 

I'm going to close the issue, but please respond and comment if you have further questions/examples

**Comment by jolestar** [comment]
I got it. I try to use the TransactionFee approach. 

But I want to know the proven safety problem. Type's Module address, Module name, Struct name is not dynamic, it is also static variable like constants. if I want to pass a generic type argument by transaction script, I use Module address + Module name + Struct name to construct the argument, then I just deconstruct the type by a native function, Why it causes the safety problem?

**Comment by jolestar** [comment]
@tnowacki  Another question, How can I ensure a module only can init by the owner once without hard code the owner address in Move? if I use a capability, I must ensure the module deploys and init script execute in one transaction, but It's impossible to do this, except in genesis. like this https://github.com/libra/libra/pull/4469/files#diff-a2f3d3ccca0755f0f4caceca109205dd

**Comment by tnowacki** [comment]
> Type's Module address, Module name, Struct name is not dynamic ... Why it causes the safety problem?

The content is not dynamic, but the way you would be accessing them is. 
The "safety" we are talking about here isn't any sort of runtime safety issue, but one of privacy and provability. 
- For privacy, the Module should have complete control over what dynamic information its giving out. Such a native for reflection breaks that. It might seem harmless, but it causes a ton of issues with having to continue to support that behavior. For example it complicates: VM loader, VM runtime representation of constants, Module upgrades (which we still haven't figured out), etc (there might be others, but I can't think of any right now)
- For provability, this concept of reflection is another thing that the move prover has to consider. If you then gate behavior underneath reflection data, it can (in certain circumstances) be very difficult to prove anything about the safety of that system. We are intentionally building a constrained language that makes it easy to prove safety constraints you want to see in blockchain code. If there is a feature that would make that more difficult, we have to seriously consider if we *need* that feature. In the case of reflection, there are easy work arounds, so you don't really need the feature. 

> Another question, How can I ensure a module only can init by the owner once without hard code the owner address in Move? 

There is perhaps some confusion in what is going on there? The address of the module always has to be fixed. Currently, there is some limited language support to allow for the address to be set by a CLI flag. But the address is still *fixed*! As such, reflection is not the right way to solve such a problem. You would instead want some sort of macro to substitute in the CLI flagsender. 

I've been thinking of killing of the CLI flag feature for some time since its pretty half-baked. And I think this is a good example of limitations.

**Comment by jolestar** [comment]
> There is perhaps some confusion in what is going on there? The address of the module always has to be fixed. Currently, there is some limited language support to allow for the address to be set by a CLI flag. But the address is still fixed! As such, reflection is not the right way to solve such a problem. You would instead want some sort of macro to substitute in the CLI flagsender.

> I've been thinking of killing of the CLI flag feature for some time since its pretty half-baked. And I think this is a good example of limitations.

Thanks, @tnowacki . I try to use a CLI flag to replace a {{sender}} place holder in Move source before compile. But it is a workaround method. Hopefully, the Move compiler providing a macro to do this!

**Comment by jolestar** [comment]
Another question.

Move's script support Generic, user pass generic type argument by Address + Module Name + Struct Name. So the Module name and Struct Name may be a convention which defined between Module developer and user.

Such as the code in types/src/account_config/constants/libra.rs
```
// TODO: This imposes a few implied restrictions:
//   1) The currency module must be published under the core code address.
//   2) The module name must be the same as the gas specifier.
//   3) The struct name must be the same as the module name
// We need to consider whether we want to switch to a more or fully qualified name.
pub fn type_tag_for_currency_code(currency_code: Identifier) -> TypeTag {
    TypeTag::Struct(StructTag {
        address: CORE_CODE_ADDRESS,
        module: currency_code.clone(),
        name: currency_code,
        type_params: vec![],
    })
}
```
If we define some convention and check it in Move, such as currency Module Name must same as Struct Name and same as currency_code. It might make the system a little easier to use.

Hopefully, reconsider this feature.

**Comment by sblackshear** [comment]
>  How can I ensure a module only can init by the owner once without hard code the owner address in Move? 

Hardcoding is the correct/only way to do this. This would be unfortunate if singleton resources were common, but we have found that (1) singletons limit the reusability of modules and (2) well-designed Move code rarely requires them an. It is natural to reach for singletons if you are coming from the Eth world (where everything is a singleton!), but it is worth asking (we often do) "do I really need this to be a singleton, or could I design it differently?".  Curious to hear about your use-cases, though! 

> If we define some convention and check it in Move, such as currency Module Name must same as Struct Name and same as currency_code. It might make the system a little easier to use.

That is indeed the naming discipline we are going for, but I am not sure that I understand the proposal. Not all modules are currency modules or have currency codes, so it seems tricky to have the compiler enforce this without restricting the naming of other modules.

I do think that it would be reasonable to have a compiler warning for something like "Missing self resource name: module `M` has >= 1 resource, but no resource named `M`."

**Comment by jolestar** [comment]
> Hardcoding is the correct/only way to do this. This would be unfortunate if singleton resources were common, but we have found that (1) singletons limit the reusability of modules and (2) well-designed Move code rarely requires them an. It is natural to reach for singletons if you are coming from the Eth world (where everything is a singleton!), but it is worth asking (we often do) "do I really need this to be a singleton, or could I design it differently?". Curious to hear about your use-cases, though!

I got your point. Singletons limit the reusability of modules, But some times singleton real need. Such as the Libra/Coin/Token Module must not be a singleton, other developers can use the Module to define new Coin/Token, but the LBR is must be a singleton.

> That is indeed the naming discipline we are going for, but I am not sure that I understand the proposal. Not all modules are currency modules or have currency codes, so it seems tricky to have the compiler enforce this without restricting the naming of other modules.
> I do think that it would be reasonable to have a compiler warning for something like "Missing self resource name: module M has >= 1 resource, but no resource named M."

I mean if we support reflection in Move, the Module developer can do this restricting in Move. Such as check the Module name, Struct name, and currency code in Libra::register_currency function, avoid registering a Token that does not conform to the convention.

**Comment by sblackshear** [comment]
> I got your point. Singletons limit the reusability of modules, But some times singleton real need. Such as the Libra/Coin/Token Module must not be a singleton, other developers can use the Module to define new Coin/Token, but the LBR is must be a singleton.

Totally agree; singletons aren't common, but they have their place. Your mention of LBR got me thinking--that one is actually an interesting case. We currently enforce that it is a singleton with the ` assert(Signer::address_of(association) == 0xA550C18, 0);`, but we don't actually need to do that. The `Reserve` requires a `MintCapability` and a `BurnCapability` that are guaranteed to be globally unique, so we could safely omit that check. 

> I mean if we support reflection in Move, the Module developer can do this restricting in Move. Such as check the Module name, Struct name, and currency code in Libra::register_currency function, avoid registering a Token that does not conform to the convention.

You are right that this would work. However, I don't think adding an invasive feature like reflection to enforce an off-chain convention is a good trade for us at this time (particularly because we may want the flexibility to adjust the convention as we add new currencies).

**Comment by jolestar** [comment]
> Totally agree; singletons aren't common, but they have their place. Your mention of LBR got me thinking--that one is actually an interesting case. We currently enforce that it is a singleton with the assert(Signer::address_of(association) == 0xA550C18, 0);, but we don't actually need to do that. The Reserve requires a MintCapability and a BurnCapability that are guaranteed to be globally unique, so we could safely omit that check.

If we omit the check, we need to do another check at the time of grant MintCapability & BurnCapability to the association address. Genesis can do this because genesis deploy module and execute some init scripts as atomic. But other developers can only deploy the Module first and then execute the init script in another transaction, that can not be atomic.

In the early libra code, there was a type of transaction with a Program payload that contained both a module and a script. It can ensure that Module and Script are executed atomically, but it was later deprecated, and I want to know why.

I just want a way to init Module safety and no hard code address in Module code, not necessarily the 'Reflection' invasive feature.
