### ISSUE TITLE
which is safer? transfer? withdraw+deposit?

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#4498]
I noticed the difference between libra and ethereum.
In ethereum, It has an atomic transfer only the sender can execute.
In libra, it separate transfer to two operations which any user level program can execute.
I can see libra is more flexible. But I am worrying some buggy contract will steal money.

**Comment by sblackshear** [comment]
I'm not sure I fully understand the question, but let me say a few things that might be helpful:

- In Libra, `withdraw`/`deposit` (and all other functions) are static calls, so there's no risk of a buggy or malicious contract stealing money via re-entrancy
- Resource types prevent you (or a buggy contract) from accidentally losing a coin produced by `withdraw`
- `LibraAccount::withdraw` is the only way to debit an account balance, and it requires a `&WithdrawCapability`. If you don't hand unknown code (1) your `&WithdrawCapability` or (2) your `&signer`, it is not possible for the code to debit your account balance.
