### ISSUE TITLE
Possibly simplify structured logging

### ISSUE THREAD

**Issue by gregnazario** [libra/libra#4516]
As discussed here: https://github.com/libra/libra/pull/4484

We could have some possible improvements:
1. Environment variable that allows local log testing rather than adding a static function call
2. A structured logging guide with guidelines of what to put in structured logging and paradigms.
3. Possibly simplify from creating an object to pass to the macro, into just using the macro for it.

**Comment by andll** [comment]
Reference to previous discussion thread on (3): https://github.com/libra/libra/pull/4484#discussion_r439777991

**Comment by davidiw** [comment]
Great initiative here!
