### ISSUE TITLE
[ERROR] Failed to get balances: missing field `num_children`

### ISSUE THREAD

**Issue by joeyxp** [libra/libra#4602]
Clone master branch. Following the instructions of "start first transaction", I get error when 

run "account c":
`libra% account create
>> Creating/retrieving next account from wallet
ERROR 2020-06-18 13:18:53 testsuite/cli/src/client_proxy.rs:1320 Failed to get account state from validator, error: missing field `num_children`
Created/retrieved account #0 address 614afc63272338f3d74a9b7cb168cb95
libra% account c
>> Creating/retrieving next account from wallet
ERROR 2020-06-18 13:18:59 testsuite/cli/src/client_proxy.rs:1320 Failed to get account state from validator, error: missing field `num_children`
Created/retrieved account #1 address 8d2cdcee438945aa3b19f43f919f4473
libra% account c
>> Creating/retrieving next account from wallet
INFO 2020-06-18 13:19:03 testsuite/cli/src/libra_client.rs:255 Verified epoch changed to EpochState [epoch: 1, validator: ValidatorSet: [2d4c9ad5: 1, 45009200: 1, 65fe97db: 1, 7bbc44bb: 1, 987e34ea: 1, b1aaf856: 1, ]]
Created/retrieved account #2 address dcb1d28af9383aa71cc698c0bd32940a
libra%`

run "query" command:

`libra% account mint 0 100 LBR
>> Minting coins
Mint request submitted
libra% q b 0
[ERROR] Failed to get balances: missing field `num_children`
libra% q s 0
>> Getting current sequence number
[ERROR] Error getting sequence number: missing field `num_children``

**Comment by thefallentree** [comment]
pls make sure you reset libra client to testnet branch and re-run scripts/start_testnet_cli.sh
