### ISSUE TITLE
[Bug] Cannot remove validator / add validator on Pre-mainnet

### ISSUE THREAD

**Issue by sherry-x** [libra/libra#4617]
# 🐛 Bug

Need tooling support to remove / add validator on Pre-mainnet

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by gregnazario** [comment]
We have the tool for this now @sherry-x is it still a problem?

**Comment by sherry-x** [comment]
this is resolved!
