### ISSUE TITLE
[network] Consider removing diminishing backoff behavior for peer dials

### ISSUE THREAD

**Issue by gregnazario** [libra/libra#4651]
Having changing backoff behavior may cause some confusion later during an operational event.  Let's consider removing this logic and just sticking to a simple backoff mechanism with no modification based on the number of connected peers.

https://github.com/libra/libra/pull/4634#discussion_r443320866

https://github.com/libra/libra/blob/master/network/src/connectivity_manager/mod.rs#L341-L352

**Comment by benallamar** [comment]
Hi @gregnazario, is it possible to jump up on this issue ? I'd like to work on it :)

**Comment by benallamar** [comment]
Hi @gregnazario, is it possible to jump up on this issue ? I'd like to work on it :)

**Comment by gregnazario** [comment]
Turns out I already removed it :)
