### ISSUE TITLE
[Bug] Typo in the repo description

### ISSUE THREAD

**Issue by kinghrothgar** [libra/libra#47]
# 🐛 Bug
I think there's a typo in the repo description?

> Libra’s mission is to enable a simple global currency and financial infrastructure that empowers ~~billions of~~ people with billions.

**Comment by beeforbacon** [comment]
Hi. I can confirm and reproduce this bug. I recommend fix by destroying the entire system and starting over.

**Comment by bmaurer** [comment]
We're here to empower billions of people :)
