### ISSUE TITLE
[Feature Request] Use Move declared constants in Move Prover specs

### ISSUE THREAD

**Issue by DavidLDill** [libra/libra#4730]
# 🚀 Feature Request

The Move language recently added declared constants.  We should be able to refer to them in specs.

## Motivation

If we could refer to these in specifications, we could save writing a lot of helper functions to return various constants.

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by sblackshear** [comment]
+1
