### ISSUE TITLE
Sign/verify all consensus messages

### ISSUE THREAD

**Issue by aching** [libra/libra#479]
# 🚀 Feature Request

ProposalInfo and TimeoutMsg should sign the entire message and not just individual fields.

ProposalInfo should sign the entire struct in addition to having a signature on the block.  Verification should check both signatures.

VoteMsg seems fine as all fields are signed.

TimeoutMsg only signs the pacemaker timeout but not the sync info.  It's important that the sync_info is also signed those 2f+1 sync_infos on timeout will ensure honest blocks can be proposed.

**Comment by huitseeker** [comment]
https://github.com/libra/libra/pull/522 should help this significantly

**Comment by Doglin3** [comment]
Yeah

**Comment by zekun000** [comment]
not sure I understand why, there's consistency check for all fields
