### ISSUE TITLE
[tcb / consensus] Hardening

### ISSUE THREAD

**Issue by davidiw** [libra/libra#4807]
This issue covers the remainder of tasks necessary for completion of SafetyRules

- [x] LEC issues should not cause consensus to panic
- [x] Logging of all events, both positive and negative
- [x] Moving consensus_state logging into safety rules
- [x] Network errors do not affect consensus
- [ ] Consensus handling a key is missing
- [ ] Consensus handling not being involved in an epoch
- [x] Consensus handling a request to perform an outdated action (construct_and_sign_vote, sign_timeout, sign_proposal)
- [x] Consensus handling an unconfigured SafetyRules in the middle of an epoch / Consensus safely restarts an epoch if SafetyRules goes offline
- [x] Consensus losing a vote and re-requesting for the same round
- [x] The waypoint is more than 100 epochs behind the current state (currently the framework only retrieves 100
- [x] SafetyRules idempotent behavior to initialize with the same value without restart
- [x] Metrics for all public persistent store data and failures
- [x] Logging error where appropriate
- [x] Implement a write-through cache for persistent storage
- [ ] Remove explicit dependency on anyhow from interfaces
- [x] SafetyRules config
- [x] SafetyRules supports dns

## Discussion

**Issue**) Consensus handling a key is missing
**David**) Ideally, SafetyRules would keep checking and logging errors so the admin would respond. Consensus would fail operations but could still participate in storing and committing blocks.

**Issue**) Consensus handling not being involved in an epoch
**David**) Should consensus disable itself and rely on state sync? Should it exhibit the same behavior as if the key is missing? Does it even bother calling into SafetyRules? I'd say if we want to enter consensus the behavior should be the same, but SafetyRules only logs debugging info but still errors.

**Issue**) Consensus handling a request to perform an outdated action (construct_and_sign_vote, sign_timeout, sign_proposal)
**David**) Simply log and wait for the next event.

**Issue**) Consensus losing a vote and re-requesting for the same round
 **David**) Opinion, this is an optimization to increase liveness and avoid cases where consensus is stuck because only `2f + 1` nodes remain and `1` has a failure of this nature. This does not seem like a V1 critical area and can be added without breaking changes.

**Issue**) The waypoint is more than 100 epochs behind the current state (currently the framework only retrieves 100,
**David**) This should be optional, the waypoint should probably be updated in the case it is this far behind.

**Comment by davidiw** [comment]
Hey folks, I think this summarizes all of the outstanding concerns we have around SafetyRules / Consensus engagement.

**Comment by zekun000** [comment]
Thanks for putting this together!
- agree with missing key and different epoch, consensus can continue operating without the ability to vote. (still able to add block/sync)
- I think we should handle ` Consensus losing a vote and re-requesting for the same round`, since this requires a code change to fix.
- Manually update `waypoint` seems fine.
- looks to me consensus can safely ignore all the errors from LSR?

**Comment by davidiw** [comment]
* Actually my preference was kind of to do nothing and have consensus not participate, but since we need to handle errors anyway, this is probably more uniform.
* Why? This is something that we could update our code without impacting anything in the future. I personally see this as a nice to have. And we should also evaluate the performance overhead.
* Closing out the waypoint issue
* Yup!

**Comment by davidiw** [comment]
Consensus handling a request to perform an outdated action (construct_and_sign_vote, sign_timeout, sign_proposal) is already handled by these events being logged by consensus -- @zekun000 do you feel we should have explicit tests for these?

**Comment by davidiw** [comment]
@lightmark, I suspect there was some interesting condition wherein LEC wasn't capturing network errors in remote_service client -- likely wrapping them as anyhow::Error. At any rate, I hope that is the only LEC issue, so I'm going to close check that off too.

**Comment by lightmark** [comment]
@davidiw what interesting condition are you referring to?
