### ISSUE TITLE
[Bug] TC Account shouldn't be able to freeze itself

### ISSUE THREAD

**Issue by ankushagarwal** [libra/libra#4862]
## To reproduce

Freeze TC Account by sending a freeze transaction from TC Account. 
TC Account is frozen.
TC Account cannot do anything else.

cc @dmitri-perelman @sblackshear @tzakian

**Comment by ankushagarwal** [comment]
LibraRoot also shouldn't be able to freeze itself (I haven't tested this though)

**Comment by tzakian** [comment]
That could indeed cause an interesting situation....

I believe a more general issue is tracked here already #4811. Once those changes get in this shouldn't be possible any more. Let me know if that makes sense to you.

**Comment by ankushagarwal** [comment]
Makes perfect sense. Thank you!
