### ISSUE TITLE
[Bug] Spiky consensus round

### ISSUE THREAD

**Issue by sherry-x** [libra/libra#4894]
# 🐛 Bug

Premainnet has 22 nodes in ValidatorSet, and when we have 16 nodes online (1 might be not working properly), we see spiky consensus rounds. Create this issue to see if there's any followup needed. 

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by zekun000** [comment]
there're 4 nodes who can't connect to each others because the addresses on chain became invalid, so every time they become proposers they can only broadcast to 11 node instead of 15 which results in a timeout.

it's resolved after the addresses issue fixed.
