### ISSUE TITLE
[Bug] failed to spawn "protoc" during installation on Ubuntu 16.04/18.04

### ISSUE THREAD

**Issue by cballou** [libra/libra#49]
OS: Fresh install of Ubuntu 18.04
Steps to reproduce: 

1. Follow instructions from https://developers.libra.org/
2. On `./scripts/cli/start_cli_testnet.sh`, the following occurred:

```
Building and running client in debug mode.
   Compiling network v0.1.0 (/opt/libra/network)
   Compiling string_cache v0.7.3
error: failed to run custom build command for `network v0.1.0 (/opt/libra/network)`

Caused by:
  process didn't exit successfully: `/opt/libra/target/debug/build/network-3bce66de4ba49a2b/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/network.proto
cargo:rerun-if-changed=src/proto/mempool.proto
cargo:rerun-if-changed=src/proto/consensus.proto

--- stderr
thread 'main' panicked at 'protoc: Custom { kind: NotFound, error: StringError("failed to spawn `\"protoc\" \"--version\"`: No such file or directory (os error 2)") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
libra@dev:/opt/libra# protoc --version

Command 'protoc' not found, but can be installed with:

apt install protobuf-compiler
```

By default, Ubuntu 16.04 and 18.04 LTS only support protobuf 3.0. The pre-requisite of Libra is 3.6. You'll have to manually install protobuf for now unless you're willing to use Ubuntu 19.04:

https://gist.github.com/ryujaehun/991f5f1e8c1485dea72646877707f497

**Comment by c-edw** [comment]
Likewise on Fedora 29 over here. It installs the package `protobuf`, but this doesn't appear to contain the `protoc` compiler. Scroll down to `Files` [here](https://fedora.pkgs.org/29/fedora-x86_64/protobuf-3.5.0-8.fc29.x86_64.rpm.html) - it just provides some libraries.

Instead, the `protobuf-compiler` package can be installed which *does* provide the compiler.

**Comment by Sm1le291** [comment]
Fucking Zuckerberg! Can you make something normally? I spent a few hours to decide this problem? Idiot! I tried Ubuntu, Fuckingbuntu, Debian.
And! Where is bin for Windows?

**Comment by Sm1le291** [comment]
@c-edw Big thanks man!!!

**Comment by c-edw** [comment]
Not sure if the PR resolves your problem, but if it does, glad to help.

**Comment by Sm1le291** [comment]
@c-edw I am experiencing the same problem under 19.04

**Comment by trustfarm-dev** [comment]
in setup scripts, you can add following links or protobuf release tab links are better to beginner.
```
https://github.com/protocolbuffers/protobuf/blob/master/src/README.md
```

**Comment by diennguyenduy** [comment]
I'm using ubuntu 18.04 and i met this ptotoc's version error when i tried to run `./scripts/cli/start_cli_testnet.sh` and i did run:

1, Make sure you grab the latest version
`curl -OL https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip`

2, Unzip
`unzip protoc-3.6.1-linux-x86_64.zip -d protoc3`

3, Move protoc to /usr/local/bin/
`sudo mv protoc3/bin/* /usr/local/bin/`

4, Move protoc3/include to /usr/local/include/
`sudo mv protoc3/include/* /usr/local/include/`

 5, Optional: change owner
`sudo chown $USER /usr/local/bin/protoc`
`sudo chown -R $USER /usr/local/include/google`

Hope that it could solve your problem!

**Comment by dotrungkien** [comment]
For MAC users: install latest version of protobuf will solve that problem
- Download the latest version
```sh
curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.8.0/protobuf-all-3.8.0.zip
```
- Unzip the folder
- Enter the folder and run 
```sh
./autogen.sh
./configure
make
make check
sudo make install
which protoc
protoc --version
```
- then run script again 
```sh
./scripts/cli/start_cli_testnet.sh   
```

**Comment by ericnakagawa** [comment]
Thanks for chiming in here. We pushed some fixes and hope they resolve the issue. If not tag me with steps for repro and I'll follow up.
