### ISSUE TITLE
[Bug] Release/CI builds don't have LTO

### ISSUE THREAD

**Issue by metajack** [libra/libra#4987]
# 🐛 Bug

#4829 disabled LTO by default. We need to keep this default for developer ergonomics but ensure that release builds and CI builds include LTO. This can be done with Cargo's profile dependencies (https://github.com/rust-lang/rfcs/blob/master/text/2282-profile-dependencies.md) which is now stabilized and shipping as of Rust 1.43.

**Comment by metajack** [comment]
cc @andll

**Comment by thefallentree** [comment]
thx, fixed.
