### ISSUE TITLE
[Feature Request] A big vector to support name service

### ISSUE THREAD

**Issue by guangyuz** [libra/libra#5022]
In the previous discussion about [large vector support](https://github.com/libra/libra/issues/4377), @sblackshear gave some design patterns suitable for Move programming language. I implemented DNS and another NFT example based on the sorted linked list[ [1]](https://github.com/libra/libra/blob/master/language/ir-testsuite/tests/sorted_linked_list/sorted-linked-list.mvir). My sample code is pushed [here](https://github.com/libra/libra/pull/5021
). This design pattern is really interesting, but I still encounter two problems, and did not find a good solution.

1. Each account address can only contain at most one list node. For DNS, this will result in at most one domain name for an account.
2. In order to reduce the overhead of adding nodes, users are required to find the "previous address" and pass it as a parameter to the add_node() function. Finding the "previous address" can be done off-chain, but it requires the VM to provide an additional interface to search the global state.

For these two problems, I still have not found a good solution, but I still believe that this is the right direction. Do you have any suggestion?

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by sblackshear** [comment]
Hi Guangyu,

Thanks for the post!

> Each account address can only contain at most one list node. For DNS, this will result in at most one domain name for an account.

Good point; single name/account seems like an unfortunate limitation. One solution that came to mind is something like:

```
/// an identifier for a Node<T>
resource struct NodeHandle {
  /// address where the Node is stored
  addr: address,
  /// An index into the NodeVector stored under addr
  index: u64
}

resource struct Node<T> {
  /// pointer to previous and next Node's in the sorted linked list
  prev: EntryHandle, next: EntryHandle,
  data: T,
}

/// A vector of Node's stored under a single account
resource struct NodeVector<T> {
  nodes: vector<Node<T>>
}
```

If each account stores a vector of `NodeVector` instead of a single node, it can (e.g.) register as many domains as it wishes.

> In order to reduce the overhead of adding nodes, users are required to find the "previous address" and pass it as a parameter to the add_node() function. Finding the "previous address" can be done off-chain, but it requires the VM to provide an additional interface to search the global state.

Ah, I was assuming that for DNS-like use-cases, someone would want to mirror the data offline and build a variety of indexes for it. For example: if tweak the insertion code to emit a `InsertedAt { data, prev, next }` event (or similar), you can:
- Watch for `InsertedAt` events
- Update an offline copy of the data structure each time you see an event. The offline copy of the data structure can be a map, a big vector, a DB table, or anything else that can efficiently provide the "get predecessor address" API

Also, a simpler workaround to get started quickly/test: you can expose both the "insert with previous address" API and the linear "find position and insert API". The linear API won't be realistic to call once the list gets big, but it will let you experiment without needing to implement the offline copy of the data structure.

**Comment by guangyuz** [comment]
Hi Sam,

The solution to store NodeVector for each account is pretty good. Nodes are linked with EntryHandle. Users can register as many names as needed. I'll re-write the demo with NodeVector.

Watching the "InsertedAt" event and building an offline map is also a good solution. But in Ethereum, people sometimes use "read-only" calls to view the status. Is it also an alternative solution to "find position" before insert? What do you think? 

Thanks!

**Comment by sblackshear** [comment]
> also noticed that in Ethereum, people sometimes use "read-only" calls to view the status. Is it an alternative solution to "find position" before insertion? What do you think?

Good question. There's no conceptual blocker for implementing an equivalent feature to read-only calls in Libra; it's just not something we've done yet. A tool that 
- uses[`state_synchronizer`](https://github.com/libra/libra/tree/master/state-synchronizer) to grab the latest state
- spins up a local version of the VM and exposes an API for executing a script or function

shouldn't be too difficult for someone to implement. I anticipate that we'll have this eventually, but it's not currently on our roadmap.

**Comment by jolestar** [comment]
> spins up a local version of the VM and exposes an API for executing a script or function

This feature like my feature request at #4803. Spin up a local version of the VM for executing a script is easy, but MoveVM and  Scripts do not support return and obtain results in rust currently.

MoveVm's execute_script or execute_function: 

```rust
pub fn execute_script(
        &mut self,
        script: Vec<u8>,
        ty_args: Vec<TypeTag>,
        args: Vec<Value>,
        sender: AccountAddress,
        cost_strategy: &mut CostStrategy,
    ) -> VMResult<()> ;
```
It should be:

```rust
pub fn execute_script<T>(
        &mut self,
        script: Vec<u8>,
        ty_args: Vec<TypeTag>,
        args: Vec<Value>,
        sender: AccountAddress,
        cost_strategy: &mut CostStrategy,
    ) -> VMResult<T> ;
```

**Comment by guangyuz** [comment]
Hello Sam

I rewrote the sorted linked list to store a NodeVector for each account (instead of a single node). Accounts can now register as many names as needed. Currently, the "find_position_and_insert()" API is used as a workaround. I will do more investigations on "read-only calls". The demo code is placed [here](https://github.com/libra/libra/pull/5021) in case someone refers to it.

Thanks again for your help! If there is no further discussion, I'll close this issue.

**Comment by sblackshear** [comment]
> > spins up a local version of the VM and exposes an API for executing a script or function
> 
> This feature like my feature request at #4803. Spin up a local version of the VM for executing a script is easy, but MoveVM and Scripts do not support return and obtain results in rust currently.
> 
> MoveVm's execute_script or execute_function:
> 
> ```rust
> pub fn execute_script(
>         &mut self,
>         script: Vec<u8>,
>         ty_args: Vec<TypeTag>,
>         args: Vec<Value>,
>         sender: AccountAddress,
>         cost_strategy: &mut CostStrategy,
>     ) -> VMResult<()> ;
> ```
> 
> It should be:
> 
> ```rust
> pub fn execute_script<T>(
>         &mut self,
>         script: Vec<u8>,
>         ty_args: Vec<TypeTag>,
>         args: Vec<Value>,
>         sender: AccountAddress,
>         cost_strategy: &mut CostStrategy,
>     ) -> VMResult<T> ;
> ```

Good point! I don't think we would want `execute_script` to return a result because scripts cannot have return values,  but exposing `execute_function` for this purpose makes sense.
