### ISSUE TITLE
[Bug] precondition failure for module invariant

### ISSUE THREAD

**Issue by junkil-park** [libra/libra#5091]
# 🐛 Bug

Encountered the precondition failure of a module invariant when a private function did nothing to violate the invariant, but just called a public function.

## To reproduce
Add the following module spec to `LibraAccount.move`.

```
spec module {
        invariant Roles::spec_has_libra_root_role_addr(CoreAddresses::SPEC_LIBRA_ROOT_ADDRESS()) ==>
            !exists<Balance<Coin1>>(CoreAddresses::SPEC_LIBRA_ROOT_ADDRESS());
}
```

**Stack trace/error message**
Although, it produces multiple errors for precondition failure and timeout, please focus on the following error message:
```
     ┌── LibraAccount.move:869:9 ───
     │
 869 │ ╭         invariant Roles::spec_has_libra_root_role_addr(CoreAddresses::SPEC_LIBRA_ROOT_ADDRESS()) ==>
 870 │ │             !exists<Balance<Coin1>>(CoreAddresses::SPEC_LIBRA_ROOT_ADDRESS());
     │ ╰──────────────────────────────────────────────────────────────────────────────^
     ·
 630 │     public fun add_currency<Token>(account: &signer) {
     │                ------------ called function
     │
     =     at LibraAccount.move:440:5: add_currencies_for_account
     =         new_account = 0x11,
     =         add_all_currencies = false,
     =         new_account_addr = 0x11
     =     at LibraAccount.move:444:40: add_currencies_for_account
     =     at LibraAccount.move:630:5: add_currency (entry)
```

What is going is:

Note that `add_currencies_for_account` is a private function. Boogie starts from 
`$LibraAccount_add_currencies_for_account_$verify` which calls 
`$LibraAccount_add_currencies_for_account_$def_verify` which calls 
`$LibraAccount_add_currency_$direct_intra` which comes from the public function `add_currency`, and requires the invariant as a precondition as follows:
```
requires b#$Boolean($Boolean(b#$Boolean($Roles_spec_has_libra_root_role_addr($m, $txn, $CoreAddresses_SPEC_LIBRA_ROOT_ADDRESS())) ==> b#$Boolean($Boolean(!b#$Boolean($ResourceExists($m, $LibraAccount_Balance_type_value($Coin1_Coin1_type_value()), $CoreAddresses_SPEC_LIBRA_ROOT_ADDRESS()))))));
```
And (I think) this precondition fails because it wasn't assumed at the beginning of the private function `add_currencies_for_account`.

## Expected Behavior

No such precondition failure errors

**Comment by wrwg** [comment]
This is by design because `spec module { invariant ...` is only applied to public functions. In order to work around, use schema and apply.
