### ISSUE TITLE
[Bug] No local validation when trying to transfer higher balance than local wallet holds

### ISSUE THREAD

**Issue by cballou** [libra/libra#51]
There does not appear to be local application-side validation when attempting to transfer from one wallet to another. For example, I issued `transfer 0 1 5001` where `5001` is greater than the total minted coins for wallet index `0`. This likely should have failed within the CLI without submitting the transaction to the validator.

```
libra% query balance 0
Balance is: 5000
libra% query balance 1
Balance is: 2500
libra% transfer 0 1 5001
>> Transferring
Transaction submitted to validator
To query for transaction status, run: query txn_acc_seq 0 0 <fetch_events=true|false>
libra% query balance 0
Balance is: 5000
libra% query sequence 0
>> Getting current sequence number
Sequence number is: 1
```

**Comment by kphfb** [comment]
Thank you for the report cballou!  We don't currently do client-side validation because it allows you to test what happens if you were to submit a transaction that ran out of funds to pay for both gas and the transfer.  As an example, submit a transfer such as "t 0 1 6000 100 10000" and then query the balance and notice that it has decreased (very slightly) because gas was charged but the transaction itself was unable to complete.

**Comment by icarter09** [comment]
@kphfb should this issue be closed and a ticket for client-side validation with a label of 'Enhancement' be created?

**Comment by hvram1** [comment]
I had the same issue and was following the documentation about the life of a [transaction](https://developers.libra.org/docs/life-of-a-transaction#virtual-machine-b) .  The sequence etc. gets updated on the client side . Is there a way to see that the transaction is rejected at all ( The diagram in the documentation says there is validation done before submitting the transaction )

**Comment by kphfb** [comment]
@hvram1 when you submit a transaction, you should get an error if there is an issue with basic validation which is done by admission control / mempool.  If it makes it past there, you can query the transaction on chain.  If there are sent and received events, then you should be able to see that it was successful.  We are working on making a more intuitive way to tell the success/failure and hope to have that soon

**Comment by hvram1** [comment]
Nope . I am not getting an error . I am running a local validator node and when I submit the transaction I do not see any error from the cli side . The transaction obviously did not go through but I see the sequence number changing .

**Comment by bmwill** [comment]
This is a fairly old report and sufficient changes should have been made to the client to address this (I believe). If you still see the problem please reopen the issue.
