### ISSUE TITLE
[client tooling] Tool to sync local state to Libra state at a certain height, execute a transaction, view the state

### ISSUE THREAD

**Issue by sblackshear** [libra/libra#5134]

**Comment by sblackshear** [comment]
This would be useful for local testing by clients and Libra administrators. It is also related to https://github.com/libra/libra/issues/4803: supporting read-only Move calls.

**Comment by zekun000** [comment]
cc: @msmouse this sounds like backup&restore (sync to a certain height) + db bootstrapper (execute a txn and view the state)

**Comment by msmouse** [comment]
The tools already exists if we are talking about a DB that's behind the target version -- you just recover additional transactions in replay mode on top of the existing db, and use the db-bootstrapper. 

There's no tooling to go back in history though.

**Comment by bob-wilson** [comment]
@runtian-zhou and I discussed this today and he is going to follow up to figure out how we can make it easier to put these tools together

**Comment by bob-wilson** [comment]
CC @runtian-zhou 
The transaction-replay tool is what we needed here. This is done now.
