### ISSUE TITLE
how to run full node on the Libra network 

### ISSUE THREAD

**Issue by liangqi1983** [libra/libra#5163]
How to run full node on the Libra network . that can connect to testnet network.
I can see in "https://libra.org/en-US/blog/full-node-basics/" say "In a future post in this series, we'll talk about running full nodes on the Libra network". but i can't find the next content.  
so how to run full node  which connect to testnet.

**Comment by gregnazario** [comment]
I've gone ahead and made another issue specifically for this  https://github.com/libra/libra/issues/5485

I'm going to go ahead and close this one, but hopefully we'll come along and address it
