### ISSUE TITLE
i want the HTTPS schema for the site of “fauset.testnet.libra.org” .

### ISSUE THREAD

**Issue by toshirot** [libra/libra#517]
# 🚀 Feature Request

i want the HTTPS schema for the site of  “fauset.testnet.libra.org” .

## Motivation

i am making the site on the web, that is minting from “fauset.testnet.libra.org”

but the “fauset.testnet.libra.org” can not use https.

as a result, i made http page.

but, It is not secure without HTTPS.

## Pitch

**Describe the solution you'd like**

i want to this. 
https://fauset.testnet.libra.org

## Additional context

it can mint 6. ok  (on HTTP)
http://kabuda.net/test/libra/libra-core/http-mint-fetch-nocors.html

it can not mint 7.  (on HTTPS)
https://kabuda.net/test/libra/libra-core/https-mint-fetch-nocors.html

see Libra-Vista
https://www.libravista.com/address/9291e14f5e7c1ce211ce9477154faddb0c308af2f6a10324f893e2e59a13ff80

## console Error

Mixed Content: The page at 'https://kabuda.net/test/libra/libra-core/https-mint-fetch-nocors.html' was loaded over HTTPS, but requested an insecure resource 'http://faucet.testnet.libra.org/?amount=7&address=9291e14f5e7c1ce211ce9477154faddb0c308af2f6a10324f893e2e59a13ff80'. This request has been blocked; the content must be served over HTTPS.

**Comment by toshirot** [comment]
Write again

With HTTP page (non ssl/tls)

        let url='http://faucet.testnet.libra.org/?amount=20000000&address=9291e14f5e7c1ce211ce9477154faddb0c308af2f6a10324f893e2e59a13ff80'
        fetch(url, {
            method: 'post',
            mode: 'no-cors'
        }).then(data  => 
            console.log(data)
        ).catch(error => console.error(error))
        
is work!

but With HTTPS page (ssl/tls)  

        let url='http://faucet.... 
        
is  not work. because it is Mixed Content.

And https://faucet....  doesn't work

Because of that, I can't write mint code on the https page

**Comment by davidiw** [comment]
c
