### ISSUE TITLE
Putting Cargo.lock into git?

### ISSUE THREAD

**Issue by est31** [libra/libra#52]
I've seen that libra doesn't have Cargo.lock commited to git. In the gitignore, you write:

```
# Cargo.lock is needed for deterministic testing and repeatable builds.
#
# Having it in the repo slows down development cycle.
#
# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
```

Putting Cargo.lock into the git repo would be a very good idea as this repository is an application and application repositories should generally include a Cargo.lock.

Without Cargo.lock, you are at risk of a left-pad incident as there is no `--ignore-yanked` option or anything similar in `cargo`.

**Comment by c-edw** [comment]
I hate to leave a +1 comment, but this is really important. When finances are involved, we must be especially careful about how we manage code from other sources. Not only does this need to be looked into, but also a process for safely updating dependencies.

**Comment by sunshowers** [comment]
Thanks for the report! Yes, we're aware of the need to check in `Cargo.lock` files. Unfortunately there are some tooling issues that need to be resolved, particularly having a merge tool that can automatically merge changes to such files.

**Comment by est31** [comment]
@sunshowers curious what didn't work in the case of a merge conflict? Since https://github.com/rust-lang/cargo/pull/5831 , cargo should be able to fix lockfiles corrupted by a git merge. There are many projects that use Cargo and most of them are fine with having a Cargo.lock file.

**Comment by sunshowers** [comment]
> curious what didn't work in the case of a merge conflict?

Unfortunately, the fact that the merge conflict happens at all and is visible to devs is the problem. (Note that I'm not talking about merges that can be done automatically -- I'm talking about merges that fail and prompt for user intervention.)

We have some experience with it -- we had the file checked in for a while and it introduced too much friction in developers' workflows.

> Since rust-lang/cargo#5831 , cargo should be able to fix lockfiles corrupted by a git merge.

Thanks for the link! I didn't know about this. But even so, this would only work for some kinds of issues. It wouldn't work if there are conflict markers in the file, for example.

> There are many projects that use Cargo and most of them are fine with having a Cargo.lock file.

Hmm, well, I'd presume that most projects that use Cargo are libraries so won't have a `Cargo.lock` file :)

I believe that the appropriate solution here is to write a merge tool for `Cargo.lock` files that automatically merges more types of conflicts.

**Comment by sunshowers** [comment]
So I think I maybe wasn't clear here — we absolutely will have a Cargo.lock file checked in at some point before Libra is released. We just need to get some stuff sorted before then.

**Comment by est31** [comment]
> most projects that use Cargo are libraries so won't have a Cargo.lock file

I've meant binary projects. Definitely, in general libraries don't have a Cargo.lock file. The distinction is definitely important, thanks for pointing that out.

> we absolutely will have a Cargo.lock file checked in at some point before Libra is released

That's amazing!

**Comment by bstrie** [comment]
Does this imply that the merge conflicts were due to developers indepently running and committing `cargo update` as part of arbitrary feature branches? Because I would generally expect the act of updating dependencies to be an isolated feature on its own, and assigned to only one individual at a time. Can you elaborate more on the specific circumstances and projected solutions? I ask because I'm curious whether this is the sort of use case that people expect to be handled by Cargo out of the box--if so it would be good to make sure the Cargo team is aware of it. Does Facebook encounter this same problem in other languages with lockfiles, such as Node or Ruby?

**Comment by sunshowers** [comment]
> Does this imply that the merge conflicts were due to developers indepently running and committing cargo update as part of arbitrary feature branches?

Usually it involves multiple people simultaneously adding dependencies that would trigger updates to the Cargo.lock file. Those updates would often end up conflicting with each other.

Most projects at Facebook are in one of our single-versioned monorepos and don't rely on lockfiles. Libra is in a unique situation in Facebook terms.

**Comment by sunshowers** [comment]
BTW, the merge tool would look something like this: https://www.npmjs.com/package/npm-merge-driver

**Comment by sunshowers** [comment]
Ah, looks like this is requested at https://github.com/rust-lang/cargo/issues/1818

**Comment by sunshowers** [comment]
This has been done: https://github.com/libra/libra/pull/814

We've decided to lean towards adding friction while handling external dependencies.

**Comment by bmwill** [comment]
We still need to work on improving the reviewing experience when updating a the lock file but yes, we decided it was best to start adding some friction now.

**Comment by bstrie** [comment]
@sunshowers @bmwill You may be interested in the Cargo commit at https://github.com/rust-lang/cargo/commit/767ecea0b407431a3472fa351944ebf2438d1e24 , which not yet enabled by default but has by now has quietly percolated its way into stable, beta, and nightly.

**Comment by bmwill** [comment]
@bstrie Thanks for pointing that out, we'll have to take a look at using that new format.
