### ISSUE TITLE
Add Validator and ValidatorOperator role checks to LibraSystem

### ISSUE THREAD

**Issue by tzakian** [libra/libra#5327]

**Comment by valerini** [comment]
@tzakian, can you give a little bit more context? What exactly needs to be done?

**Comment by tzakian** [comment]
Currently validator and validator operator accounts don't have their role definitions published under them (but a PR adding these will be going up today). Once that is in, we'll need to add checks when an account is added as a validator/validator operator to make sure that the account has the correct role (e.g., so that treasury compliance can't be added as a validator).
