### ISSUE TITLE
[Feature Request] If the user should be in control of their money, then you need to have virtual banks that any user can create

### ISSUE THREAD

**Issue by SoniEx2** [libra/libra#54]
# 🚀 Feature Request

The right to move is a fundamental right for anyone who wants control over their own life, their own money, etc. The right to move simply means that, while the person is allowed to place their trust on whatever or whoever they want, as long as they allow it, that person is also guaranteed the freedom to take that trust elsewhere to any other party that allows it.

As such, anyone should be able to spawn up a virtual subcurrency/"bank", which can provide warranties not provided by the wider blockchain-based network. Such a subcurrency/"bank" may automatically attach fees to all your transactions, block third-parties, have their own currency which they freely control (including the ability to mint those subcurrencies). This means they have full control over your money if you trust them with your money.

Humans are social beings, and trust is an important part of human social interactions. To satisfy their needs, humans need to be able to trust eachother. This is where all other cryptocurrencies fail, and where you can do differently.

(Besides, whether you embed them into the blockchain or not, we're gonna have those bank-like things *anyway*. By embedding them into the blockchain you just solve some known issues like scalability and availability, and help prevent mess-ups.)

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))

**Comment by SourceCode3679** [comment]
I think the whole idea of digital currency is decentralization to eliminate fees from banks and credit cards. Whether you should choose to give your money to and investor based on whatever terms the investor has is up to you, but the ledger and blockchain is supposed to be secure and unhackable so there is no need for a bank in my opinion.

**Comment by SoniEx2** [comment]
Maybe there's no *strict* need for it, but I think it would quite benefit from it anyway. These "banks" are like... well "bank" is the wrong term for it, they're really just "managed subcurrencies". They can allow for/help with things like chargebacks and refunds tho.

**Comment by TechniumUnlimited** [comment]
@SourceCode3679 The bank is yourself. Decentralization is not to simply eliminate fees, it's so that you are in total command of your money, and no transaction you send from your node can be censored. Not only that, but also so that governments cannot influence or directly/indirectly control the payment network

The US Govt as well as French and EU governments are calling for banning the development of this project already, the same day the project has been announced. This is why Bitcoin is decentralized, so that governments cant shut it down or turn it into a slave to them.

**Comment by SoniEx2** [comment]
they think this project is dangerous? lol.

it's a major failure, that's what it is.

without trust, there's no money. IRL setting up a bank is extremely expensive, not only legally but also in terms of physical resources. if anyone can make a "bank" that would be a much bigger threat to governments.
