### ISSUE TITLE
[Bug] storage::command_adapter::tests::test_save_list_metadata_files is flaky

### ISSUE THREAD

**Issue by metajack** [libra/libra#5435]
# 🐛 Bug

I have seen a few PRs fail with no code changes in `storage::command_adapter::tests::test_save_list_metadata_files`. Two runs are:
- https://circleci.com/gh/libra/libra/167227
- https://circleci.com/gh/libra/libra/166268

**Comment by msmouse** [comment]
#5394 didn't fix it for CI

```
On Linux, sync is only guaranteed to schedule the dirty blocks for writing; it can actually take a short time before all the blocks are finally written. The reboot(8) and halt(8) commands take this into account by sleeping for a few seconds after calling sync(2).
```

looks like we still need to sleep ..

**Comment by metajack** [comment]
Another example: https://circleci.com/gh/libra/libra/169058?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by msmouse** [comment]
https://app.circleci.com/pipelines/github/libra/libra/27023/workflows/688e2465-9a59-4465-a0f7-f93bfb367427/jobs/176420

**Comment by msmouse** [comment]
https://github.com/libra/libra/pull/5838 should fix it..
