### ISSUE TITLE
[logging] Remove autonamed structured logging conversions

### ISSUE THREAD

**Issue by gregnazario** [libra/libra#5442]
### Overview
Structured logging conversions cause confusion and pain points around naming of variables.

If we want to continue using text -> structured log conversion, we should push for using named variables to ensure that they are mapped properly, and ignore all other usages.

Let's remove these for example:
```
let bad_name = 1;
info!("Test me: {}", bad_name) -> {"data":{"bad_name":"1"}}
info!("Test me: {}", bad_name.to_string()) -> {"data":{"_0":"1"}}
```

Currently, a much nicer alternative that can be used are named format variables.  This allows exact control over what the variable will be named.
```
let bad_name = 1;
info!("Test me: {peer_id}", peer_id=bad_name) -> {"data":{"peer_id":"1"}}
```

### Related Issues
Parent issue: https://github.com/libra/libra/issues/5441

**Comment by bmwill** [comment]
Closed by https://github.com/libra/libra/pull/5875
