### ISSUE TITLE
Add allowed sender to script publishing option.

### ISSUE THREAD

**Issue by tzakian** [libra/libra#5480]
Right now we only allow either `CustomScripts` or an allowlisted set of scripts. We want to keep this, but also allow (non writeset) custom scripts to be sent from Libra Root

**Comment by tzakian** [comment]
Is this done by #5503?

**Comment by bob-wilson** [comment]
@runtian-zhou , did you see the question here?

**Comment by runtian-zhou** [comment]
Yes this should be done!
