### ISSUE TITLE
[Bug] MacOS ./scripts/cli/start_cli_testnet.sh could not compile

### ISSUE THREAD

**Issue by sangmeshcp** [libra/libra#55]
# 🐛 MacOS ./scripts/cli/start_cli_testnet.sh could not compile

## To reproduce
** git clone https://github.com/libra/libra.git **
** cd libra && ./scripts/dev_setup.sh **
** ./scripts/cli/start_cli_testnet.sh ** 
```rust


** Stack trace/error message **
```
Building and running client in debug mode.
   Compiling prost-derive v0.5.0
   Compiling which v2.0.1
   Compiling protoc-grpcio v0.3.1
   Compiling failure_ext v0.1.0 (/Users/admin/libra/common/failure_ext)
   Compiling ed25519-dalek v1.0.0-pre.1
   Compiling threshold_crypto v0.3.1
   Compiling codespan v0.1.3
   Compiling snow v0.5.2
   Compiling network v0.1.0 (/Users/admin/libra/network)
   Compiling compiler v0.1.0 (/Users/admin/libra/language/compiler)
   Compiling canonical_serialization v0.1.0 (/Users/admin/libra/common/canonical_serialization)
   Compiling logger v0.1.0 (/Users/admin/libra/common/logger)
   Compiling prost-build v0.5.0
   Compiling codespan-reporting v0.1.4
   Compiling prost v0.5.0
   Compiling metrics v0.1.0 (/Users/admin/libra/common/metrics)
   Compiling crash_handler v0.1.0 (/Users/admin/libra/common/crash_handler)
   Compiling prost-types v0.5.0
   Compiling channel v0.1.0 (/Users/admin/libra/common/channel)
   Compiling grpc_helpers v0.1.0 (/Users/admin/libra/common/grpc_helpers)
   Compiling grpcio-compiler v0.5.0-alpha
   Compiling protoc-grpcio v1.0.2
   Compiling grpcio-client v0.1.0 (/Users/admin/libra/common/grpcio-client)
   Compiling build_helpers v0.1.0 (/Users/admin/libra/common/build_helpers)
   Compiling proto_conv v0.1.0 (/Users/admin/libra/common/proto_conv)
   Compiling types v0.1.0 (/Users/admin/libra/types)
   Compiling storage_proto v0.1.0 (/Users/admin/libra/storage/storage_proto)
   Compiling mempool v0.1.0 (/Users/admin/libra/mempool)
   Compiling admission_control_proto v0.1.0 (/Users/admin/libra/admission_control/admission_control_proto)
   Compiling crypto v0.1.0 (/Users/admin/libra/crypto/legacy_crypto)
   Compiling nextgen_crypto v0.1.0 (/Users/admin/libra/crypto/nextgen_crypto)
   Compiling noise v0.1.0 (/Users/admin/libra/network/noise)
   Compiling vm v0.1.0 (/Users/admin/libra/language/vm)
   Compiling scratchpad v0.1.0 (/Users/admin/libra/storage/scratchpad)
   Compiling state_view v0.1.0 (/Users/admin/libra/storage/state_view)
   Compiling config v0.1.0 (/Users/admin/libra/config)
   Compiling move_ir_natives v0.1.0 (/Users/admin/libra/language/stdlib/natives)
   Compiling libra_wallet v0.1.0 (/Users/admin/libra/client/libra_wallet)
   Compiling storage_client v0.1.0 (/Users/admin/libra/storage/storage_client)
   Compiling bytecode_verifier v0.1.0 (/Users/admin/libra/language/bytecode_verifier)
   Compiling vm_runtime v0.1.0 (/Users/admin/libra/language/vm/vm_runtime)
   Compiling vm_validator v0.1.0 (/Users/admin/libra/vm_validator)
   Compiling stdlib v0.1.0 (/Users/admin/libra/language/stdlib)
   Compiling vm_genesis v0.1.0 (/Users/admin/libra/language/vm/vm_genesis)
   Compiling client v0.1.0 (/Users/admin/libra/client)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 49s
     Running `target/debug/client --host ac.testnet.libra.org --port 80 -s ./scripts/cli/trusted_peers.config.toml`
I0618 12:12:30.379731 4603311552 common/crash_handler/src/lib.rs:28] Skip panic handler setup because RUST_BACKTRACE is set
Not able to connect to validator at ac.testnet.libra.org:80, error RpcFailure(RpcStatus { status: Unavailable, details: Some("Socket closed") })

stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized::h631f8b682c7bf9e8 (0x10382db3a)
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.30/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace::hce483a6931786ab2 (0x10382dac3)
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.30/src/backtrace/mod.rs:53
   2: backtrace::capture::Backtrace::create::h41a1ad863b6bd04c (0x10381f687)
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.30/src/capture.rs:163
   3: backtrace::capture::Backtrace::new_unresolved::hf676b835fb5332f0 (0x10381f608)
   4: failure::backtrace::internal::InternalBacktrace::new::h617a3d26385ca2fa (0x10381df70)
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
   5: failure::backtrace::Backtrace::new::ha1cbeceb28a7ae44 (0x10381dcff)
   6: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h8fd6f22cdedd00a6 (0x10252016d)
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19
   7: <failure::error::Error as core::convert::From<F>>::from::h98e094f261e4852c (0x1024ffea1)
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36
   8: client::grpc_client::GRPCClient::get_with_proof_async::{{closure}}::had362ec454321c8b (0x10251833c)
             at /Users/admin/libra/client/src/grpc_client.rs:143
   9: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll::{{closure}}::h49d167f320c2227a (0x1024d447a)
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/then.rs:33
  10: futures::future::chain::Chain<A,B,C>::poll::h7924489620473b09 (0x1024feffd)
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/chain.rs:39
  11: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll::h1ae06853db5346a1 (0x1024d429c)
  12: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::h8f37a9c5c163148a (0x1024fa56c)
  13: futures::task_impl::Spawn<T>::enter::{{closure}}::hf76f3e32daaa1427 (0x1024fabc7)
  14: futures::task_impl::std::set::hff63f3b7547e25e7 (0x1024d4ca3)
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/std/mod.rs:83
  15: futures::task_impl::Spawn<T>::enter::h27735a2e342c5b11 (0x1024fa6e0)
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:399
  16: futures::task_impl::Spawn<T>::poll_fn_notify::ha75a41dd402b87f5 (0x1024fa2ea)
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:291
  17: futures::task_impl::Spawn<T>::poll_future_notify::hfbec6354e65d4d4b (0x1024fa50c)
  18: futures::task_impl::std::<impl futures::task_impl::Spawn<F>>::wait_future::{{closure}}::h0c881ad8dcc97da7 (0x1024d4e23)
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/std/mod.rs:236
  19: futures::task_impl::std::ThreadNotify::with_current::{{closure}}::h11acb1957036dbc7 (0x1024d47fc)
  20: std::thread::local::LocalKey<T>::try_with::h8db036d9511d7275 (0x10251bf1c)
             at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libstd/thread/local.rs:299
  21: std::thread::local::LocalKey<T>::with::h0704e5a004a65f4a (0x10251b157)
  22: futures::task_impl::std::ThreadNotify::with_current::h9e93032fb8584f15 (0x1024d46fe)
  23: futures::task_impl::std::<impl futures::task_impl::Spawn<F>>::wait_future::h4020f730adc60702 (0x1024fac04)
  24: futures::future::Future::wait::h6e6d886fade3aa9c (0x1024d415d)
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/mod.rs:299
  25: client::grpc_client::GRPCClient::get_with_proof_sync::h3da2ca8ecd5e79d3 (0x1024e3553)
             at /Users/admin/libra/client/src/grpc_client.rs:175
  26: client::client_proxy::ClientProxy::test_validator_connection::h35b33e4be9a728c8 (0x10250f711)
             at /Users/admin/libra/client/src/client_proxy.rs:619
  27: client::main::h0c47a860a779f421 (0x10227cb90)
             at /Users/admin/libra/client/src/main.rs:69
  28: std::rt::lang_start::{{closure}}::h39541c9fb63d4814 (0x1022a2b91)
             at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libstd/rt.rs:64
  29: std::panicking::try::do_call::ha1be4cd83bcefe34 (0x10386efd8)
             at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libstd/panicking.rs:293
  30: ___rust_maybe_catch_panic (0x1038726ef)
             at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libpanic_unwind/lib.rs:93
  31: std::rt::lang_start_internal::he61fed75c07ba5f9 (0x10386f9fe)
             at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libstd/rt.rs:48
  32: std::rt::lang_start::h906298eb84e97768 (0x1022a2b62)
             at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libstd/rt.rs:64
  33: _main (0x10227e0c2)

```


## System information

**Please complete the following information:**
- rust 1.18.3 
-  Mac Os Mojave 10.14.5

**Comment by kphfb** [comment]
Hi sangmeshcp!  Can you please provide additional information?  What error message are you seeing?

**Comment by xfyfb** [comment]
From this error: 'Not able to connect to validator at ac.testnet.libra.org:80, error RpcFailure(RpcStatus { status: Unavailable, details: Some("Socket closed") })'
The client was not able to connect to testnet. Could you retry, it should be transient?

**Comment by crysptos** [comment]
same from a few clients that we're tested with > macs and ubuntu 16/17

**Comment by sangmeshcp** [comment]
its consistent for last 4 hours. hence, raised issue with traces

**Comment by mgorven** [comment]
Can you edit `scripts/cli/start_cli_testnet.sh`, change "--port 80" to "--port 8000" and then try again?

**Comment by sangmeshcp** [comment]
that works .. thank you

**Comment by mgorven** [comment]
Thanks for confirming! We'll update the script in the repo with this change.

**Comment by tiendq** [comment]
@mgorven it works well for me with current script which using port 80 so I don't think script is the issue.

**Comment by icarter09** [comment]
@sangmeshcp sounds like your issue was fixed. Can you close this ticket? If not, please ignore this. Thanks.
