### ISSUE TITLE
[Bug] Panic when entering return

### ISSUE THREAD

**Issue by ccastromar** [libra/libra#550]
# 🐛 Bug

## To reproduce
Just open the libra cli and press return.

** Stack trace/error message **
```
// Paste the output here
```
C0813 19:01:26.224069 140006918532352 common/crash_handler/src/lib.rs:36] details = '''panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/6e310f2abae97323ca1d5469657b83aa1a9407e0/src/libcore/slice/mod.rs:2681:10'''
backtrace = '''
stack backtrace:
   0: backtrace::backtrace::libunwind::trace::h64102c2725c2684e (0x55fa236baf0d)
             at /home/carlos/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.33/src/backtrace/libunwind.rs:88
      backtrace::backtrace::trace_unsynchronized::h15bf47854f7a50cd
             at /home/carlos/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.33/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace::hac39973fa021b0d7 (0x55fa236bae8e)
             at /home/carlos/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.33/src/backtrace/mod.rs:53
   2: backtrace::capture::Backtrace::create::h8e30d8f7094c513c (0x55fa236acd8d)
             at /home/carlos/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.33/src/capture.rs:165
   3: backtrace::capture::Backtrace::new::ha937e1364c6fe42e (0x55fa236acc84)
             at /home/carlos/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.33/src/capture.rs:128
   4: crash_handler::handle_panic::h3262a9582e019df6 (0x55fa21e5df0d)
             at common/crash_handler/src/lib.rs:33
   5: crash_handler::setup_panic_handler::{{closure}}::h50c2ed9822eb30a5 (0x55fa21e5ed18)
             at common/crash_handler/src/lib.rs:25
   6: std::panicking::rust_panic_with_hook::h4e9b0b66399f41c3 (0x55fa237109c9)
             at src/libstd/panicking.rs:481
   7: std::panicking::continue_panic_fmt::hc70357f1b69b61f2 (0x55fa23710462)
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind (0x55fa23710346)
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt::h58293202aee40982 (0x55fa23730a9d)
             at src/libcore/panicking.rs:85
  10: core::panicking::panic_bounds_check::he6afe0956f8ad338 (0x55fa23730a55)
             at src/libcore/panicking.rs:61
  11: <usize as core::slice::SliceIndex<[T]>>::index::ha0b48172c0eeaba8 (0x55fa21e6c44e)
             at /rustc/6e310f2abae97323ca1d5469657b83aa1a9407e0/src/libcore/slice/mod.rs:2681
  12: core::slice::<impl core::ops::index::Index<I> for [T]>::index::h641a965358f29b7a (0x55fa21e6b498)
             at /rustc/6e310f2abae97323ca1d5469657b83aa1a9407e0/src/libcore/slice/mod.rs:2538
  13: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index::h10be5444e197e79d (0x55fa21f1260b)
             at /rustc/6e310f2abae97323ca1d5469657b83aa1a9407e0/src/liballoc/vec.rs:1790
  14: client::main::hfe944a1d2efc2b79 (0x55fa21e5a736)
             at client/src/main.rs:97
  15: std::rt::lang_start::{{closure}}::haa9bbdd5cafa7911 (0x55fa21e31fc2)
             at /rustc/6e310f2abae97323ca1d5469657b83aa1a9407e0/src/libstd/rt.rs:64
  16: std::rt::lang_start_internal::{{closure}}::h97d75582852bd45b (0x55fa237102e3)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::hd358001485aeb1cd
             at src/libstd/panicking.rs:296
  17: __rust_maybe_catch_panic (0x55fa2371811a)
             at src/libpanic_unwind/lib.rs:82
  18: std::panicking::try::h2d5ccee2ed3f74fa (0x55fa23710ded)
             at src/libstd/panicking.rs:275
      std::panic::catch_unwind::h9c102f4007b228cb
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal::h449549f8f867a3ee
             at src/libstd/rt.rs:48
  19: std::rt::lang_start::h137a61e11a268370 (0x55fa21e31f89)
             at /rustc/6e310f2abae97323ca1d5469657b83aa1a9407e0/src/libstd/rt.rs:64
  20: main (0x55fa21e5c8ca)
  21: __libc_start_main (0x7f55e5c66830)
  22: _start (0x55fa21e2afe9)
  23: <unknown> (0x0)'''

## Expected Behavior
The program should not panic and crash when a return is entered in the cli.

## System information
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Please complete the following information:**
- 
- 
- 
Just cloned the git testnet branch.
Last Commit
05c40c977badf052b9efcc4e0180e3628bee2847 (HEAD -> testnet, origin/testnet, origin/pretestnet) [mempool] Check only gas price is updated when we allow increase in gas price to speed up a transaction

**Comment by fbandersnatch** [comment]
It got fixed in 32c5974 which missed our `testnet` branch by a couple of commits, but is going to get into the next release.

**Comment by fbandersnatch** [comment]
Closing:
Fixed on master for a while and on recent testnet
