### ISSUE TITLE
Round up of remaining hardening opportunities

### ISSUE THREAD

**Issue by davidiw** [libra/libra#5572]
* [x] Validator-Observer subsumed by https://github.com/libra/libra/issues/5866
* [ ] Fullnode bootstrap without genesis (nice to have)
* [ ] Fuzzing
    * [x] LSR -> Consensus Types -> Transactions
    * [x] KeyManager -> Lightweight JSON RPC
    * [x] Storage -> Vault storage
    * [x] LEC -> Executor -> Transactions
    * [ ] Network
    * [ ] Consensus
    * [ ] Check the coverage reports for each component to make sure no obvious/big gaps are untested
    * Out of scope: non-vault storage
* [ ] LSR / Consensus
    * [ ] Handle signaling of no keys / not in validator set more cleanly
    * [ ] Separate out Network config into an enum for either full node or validator network
    * [x] Improve the way we test LSR binary
* [ ] Configs
    * [x] Remove chain id (legacy code, shouldn't be part of the config)
    * [ ] Validate / extend config (new version of config builder)
    * [ ] Unify cluster test / smoke test configs
    * [ ] Data limitations on consensus, transactions, state sync, mempool etc
* [ ] Storage
    * [x] Update for vault tokens
    * [ ] Provide a shared filesystem storage via a RWLock and clean up the copy / pasting of that storage all over the place
    * [x] Enable Vault in land blocking tests
    * [ ] Update storage specification for new method that was exposed for fault recovery (i.e., get previous_public_key)
    * [x] Improve performance of vault using better configurations/deployment-specific settings
    * [x] Refactor storage to be type-specific/generic rather than enum based
* [ ] Network https://github.com/libra/libra/issues/3985
    * [ ] Remove requirement to listen — maybe requires the ability to dynamically load dialers or have an explicit list (entry) for a dialer
    * [x] Remove heartbeat packet types and specify the heartbeat service
    * [ ] Explore a means to properly load balance across nodes in a network. We could start first with each peer gets 1 / k * estimated bandwidth and then explore means to measure available bandwidth and to support dynamic distribution
    * [ ] Start exploring a framework for shared validator network encryption key rotation
    * [ ] Explore bottlenecks related to bad DNS, concurrent dials
    * [x] Ensure that Network wire errors can at least be handled even if we don't implement them (and potentially implement them)
    * [x] Complete validator network address encryption 
  * [x] NetworkContext is constructed before confirming peer_id is correctly formed in peer_manager/builder
* [x] Operational subsumed by https://github.com/libra/libra/issues/5865
* [ ] Testing
    * [ ] Fix flaky smoke tests
    * [ ] E2E Test (compliance / treasury) implementation
        * [ ] Designated dealer
        * [ ] VASP
        * [ ] Reserve
    * [ ] See if there are any big/obvious gaps in code coverage
* [x] Performance (LSR)
    * [x] Explore time spent in LSR
    * [x] Replace sending of the VoteProposal’s payload with an intermediate hash
    * [x] Combine last_vote last_voted_round
* [ ] Health monitors
    * [ ] LSR
    * [ ] KeyManager
    * [ ] LibraNode
    * [ ] FullNode
* [x] Figure out LSR metrics story
    * [x] labels https://github.com/libra/libra/issues/3694
    * [x] labels again? https://github.com/libra/libra/issues/5322
* [ ] Cleanup of TODOs (feel free to breakdown into sub categories)
* [ ] Review specification / implementation
  * [ ] Network
  * [ ] State sync -> move to libra
  * [ ] Mempool -> move to libra
  * [ ] Consensus
  * [ ] Safety Rules -> move to libra
  * [ ] Secure storage -> move to libra
  * [ ] LEC -> move to libra
  * [ ] Executor
  * [ ] Storage
* [x] Publish specifications to libra/libra
* [ ] Logging https://github.com/libra/libra/issues/5441
* [x] CLI
  * [x] Require waypoint
* [x] Genesis: Explore name hashing for Operators/Owners
* [x] Key Manager: Deploy in cluster test (or somewhere)
* [ ] Secure JSON RPC: Implement proof verification so we don't need to trust the endpoint
* [x] READMEs:
    * [x] Update Secure Storage README
    * [x] Update Key Manager README
    * [x] Update Secure JSON RPC README
    * [ ] Update LSR README
    * [x] Update LEC README

**Comment by gregnazario** [comment]
Maybe we should add a "cleanup TODOs"
