### ISSUE TITLE
[Bug] You can't trust this consortium or Facebook, how to fix?

### ISSUE THREAD

**Issue by TechniumUnlimited** [libra/libra#56]
# 🐛 Bug

You can't trust this consortium or Facebook, how to fix?
## To reproduce
Use Libra

## Expected Behavior
Spy, steal, sell your data, censor, and turn you into pig at the slaughter

## System information
Any

All Libra Versions

## Additional context

Proposed Fix: Buy Bitcoin Instead

**Comment by gazhayes** [comment]
I fixed this in #83
