### ISSUE TITLE
[Bug] Premainnet validator node has one extra connected peer

### ISSUE THREAD

**Issue by sherry-x** [libra/libra#5624]
On Premainnet v0.19, every validator nodes are currently having one more connected peer than they should.
http://prometheus.premainnet.testnet.libra.org:9091/d/validator

Premainnet v0.19 has 23 nodes in ValidatorSet, currently there's 22 nodes online but they all have 22 connected peers.

**Comment by gregnazario** [comment]
This node has connected out to 21 hosts, but connected twice to 1.
https://search-premainnet-logging-aiee5pnmt2aav4272fuf4ilwze.us-west-2.es.amazonaws.com/_plugin/kibana/goto/ea8ae77125bd52f19cf824cf7a1a7244

We connected twice, but the address looks like it changed in the middle
https://search-premainnet-logging-aiee5pnmt2aav4272fuf4ilwze.us-west-2.es.amazonaws.com/_plugin/kibana/goto/8ec4e1908276a4d6ebb9f54fc72179d0

There are 21 out and 1 in, so we need to check which one is connected in and out

http://prometheus.premainnet.testnet.libra.org:9091/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22libra_connections%7Bnetwork_id%3D%5C%22Validator%5C%22,%20partner%3D%5C%22Lyft%5C%22%7D%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

**Comment by gregnazario** [comment]
So looking at 2 different nodes, they both have 22 connections.  There is never a disconnect, so we're connected to another peer inbound and outbound
https://search-premainnet-logging-aiee5pnmt2aav4272fuf4ilwze.us-west-2.es.amazonaws.com/_plugin/kibana/goto/02574525db3c9c249420192d744629a4

**Comment by sherry-x** [comment]
@gregnazario Thanks for looking into this! Turn out we now have 23 nodes online, so the 22 connected peer is correct. Just our dashboard didn't updated with the new node
