### ISSUE TITLE
[Bug] mac Python 3.8 error message

### ISSUE THREAD

**Issue by fredzannarbor** [libra/libra#5652]
on first use I encounter the message below. unclear whether it is informational and I can safely ignore.

from libra import client
objc[20457]: Class QMacAutoReleasePoolTracker is implemented in both /usr/local/lib/python3.8/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x10d24a200) and /usr/local/lib/python3.8/site-packages/cv2/.dylibs/QtCore (0x1655610f8). One of the two will be used. Which one is undefined.
objc[20457]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /usr/local/lib/python3.8/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x10d24a278) and /usr/local/lib/python3.8/site-packages/cv2/.dylibs/QtCore (0x165561170). One of the two will be used. Which one is undefined.
objc[20457]: Class KeyValueObserver is implemented in both /usr/local/lib/python3.8/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x10d24a2a0) and /usr/local/lib/python3.8/site-packages/cv2/.dylibs/QtCore (0x165561198). One of the two will be used. Which one is undefined.
objc[20457]: Class RunLoopModeTracker is implemented in both /usr/local/lib/python3.8/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x10d24a2f0) and /usr/local/lib/python3.8/site-packages/cv2/.dylibs/QtCore (0x1655611e8). One of the two will be used. Which one is undefined.

**Comment by davidiw** [comment]
This issue doesn't seem related to this project.
