### ISSUE TITLE
[Bug] ValidatorConfig::set_config does not validate args.

### ISSUE THREAD

**Issue by moeziniaf** [libra/libra#5662]
# 🐛 Bug

ValidatorConfig::set_config() does not validate parameters. When a new epoch is issued, a new validator in the set with invalid parameters will bring down block execution.

**Stack trace/error message**
```
json-rpc waits on get_account_txn_and_sequence_number forever.
```

## Expected Behavior

able to get txn information after a change in validatorset.

## Additional context

https://toroeng.slack.com/archives/C010A1C8K6D/p1597762893198800

**Comment by davidiw** [comment]
Resolved by eliminating typing on network addresses and removing network identity keys.
