### ISSUE TITLE
[Bug] Censorship resistance

### ISSUE THREAD

**Issue by h4v0kr** [libra/libra#57]
Your white paper seems to discard Bitcoin in favour of federated IOUs backed by centralized IOUs and administrators. Bitcoin is censorship resistant. It scales through software, not bureaucrats, law enforcement, regulation and or governments. 

https://bitcoin.org/bitcoin.pdf

**Comment by mrbianchi** [comment]
But it could be the trojan horse

**Comment by TechniumUnlimited** [comment]
Thats because they want censorship and total control over payments and users duh

**Comment by uira** [comment]
I agree that is a bug...

But they made as a Feature...!

**Comment by Kixunil** [comment]
Fixed by https://github.com/libra/libra/pull/83

**Comment by bmaurer** [comment]
Unfortuantely, bitcoin's approach doesn't meet the requirement of low-volatility of this project. We think that the fiat-backed approach is a strong approach for many use cases. Given this decision we've structured the reserve to be as strong as possible:

https://libra.org/en-US/about-currency-reserve/

>  The reserve will be held by a geographically distributed network of custodians with investment-grade credit rating to limit counterparty risk. Safeguarding the reserve’s assets, providing high auditability and transparency, avoiding the risks of a centralized reserve, and achieving operational efficiency are the key parameters in custody selection and design.
