### ISSUE TITLE
[logging] Convert to Structured Logs

### ISSUE THREAD

**Issue by gregnazario** [libra/libra#5744]
### Overview
Currently, there are two logging systems, one for Structured Logs, and the other for Text logs.  In order to decrease the disparity between the two logs, we should move all the logs to the Structured logs as one place.

### Guidelines
1. All logs must have a `log` context line.  This is normally the text log line that will be printed out, and give context for the reader.
2. Index fields if querying by them adds value.
3. Field names should be unique to the type.  `result` is likely not a unique type, but `query_result` is unique.
4. Snake case field names.  Just to be consistent across all naming, we should snake case the field names

### How to convert Example

```
// Text Log
info!("[{}] Peer disconnected from {} due to {}", network_context, remote_peer, error);
```
into
```
// Structured Log
// StructuredLogEntry::new_named(category, name)
// .data(name, object) // Serialized into JSON.  Useful for fields that have more than one thing to query
// .data_display(name, object) // Serialized into String using `std::fmt::Display`

sl_info!(StructuredLogEntry::new_named("network", "disconnect_event")
  .data("network_context", network) // Serialized into JSON, as there are 3 fields within it to query
  .data("remote_peer", remote_peer)
  .data_display("error", error)
);
```

### Followup Items
* Central repository so names don't conflict.
* Central repository of `LoggingField`
* Print all structured logs to `stdout` to ensure that logs can be tailed live on the host (unless we use file logging)

**Comment by bmwill** [comment]
Maybe we can also take a look at improving the construction of a structured log. Right now its very verbose compared to the text log.

**Comment by gregnazario** [comment]
Closing in favor of google doc
