### ISSUE TITLE
[genesis-tool] Use genesis tool for setting the keys for compliance and libra root

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#5748]
The Association Operations Service (AOS) is going to generate the public keys for two accounts that it is going to control: 1) LibraRoot and 2) TreasuryCompliance.

We'd like to use the `libra-genesis-tool` for setting up these two keys: pass the parameters in a form of hex-encoded LCS-serialization of the public keys. Note that the AOS doesn't have its own Secure Storage.

**Comment by snakech** [comment]
> The Association Operations Service (AOS) is going to generate the public keys for two accounts that it is going to control: 1) LibraRoot and 2) TreasuryCompliance.
> 
> We'd like to use the `libra-genesis-tool` for setting up these two keys: pass the parameters in a form of hex-encoded LCS-serialization of the public keys. Note that the AOS doesn't have its own Secure Storage.

hmmmm, how did you know we just have discussed tool this morning ahaha

**Comment by dmitri-perelman** [comment]
Haha, yea, we discussed it with @davidiw and @ankushagarwal as well. Please tell us if you're planning to work on it and whether there is any missing context required for this task. Thanks!

**Comment by dmitri-perelman** [comment]
JFYI, we're planning to use this tool for the first time on Sep 8.

**Comment by ankushagarwal** [comment]
These are the two keys we need for AOS to control the premainnet network

```
LPN/TC Public Key = 1f68b944e6ce1387c729af5df4c587bc86230b464a41ad55cc6576acff9ae960
LibraRoot Public Key = 599a87bed2079654a8758ed774f1a7f9f8e5e9039c912ee77042082aa54e319a
```

**Comment by davidiw** [comment]
congrats guys!
