### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by saranshkataria** [libra/libra#58]
# 🚀 Feature Request

The documentation states only Linux and Mac are supported, Windows support would be a great addition to be looked upon.

**Comment by codemaveric** [comment]
Hi, saranshkataria

You can connect to Libra Core from Windows using WSL. Use the following article to get started with it on a Windows System.
https://medium.com/@ibraheemkolawolebello/connecting-to-libra-testnet-on-windows-with-wsl-45bdfd23150a

Cheers

**Comment by jquesnelle** [comment]
Couple of notes regarding getting this to build on Windows (at least my progress so far).

First, you'll need to install all of the dependencies in `scripts/dev_setup.sh` yourself and add them to `PATH`. These are Rust (obviously), CMake, Go, and protobuf. For protobuf, both the `bin` and the `include` directory will need to be in `PATH`.

As for getting it to build (in whatever way possible), my progress so far:

1. `libra_node` depends on [signal-hook](https://docs.rs/signal-hook/0.1.9/signal_hook/) which does not work on Windows at all. 

Remove `signal_hook` dependency and comment out use of `signal_hook` and definiton/call to `register_signals` in https://github.com/libra/libra/blob/master/libra_node/src/main.rs

2. [clap](https://docs.rs/clap/2.33.0/clap/) has a default feature that is not supported on Windows. 

Change all `clap = 2.32.0` dependencies to `clap = { version = "2.32.0", default-features = false }`

3. [jemallocator](https://github.com/gnzlbg/jemallocator) doesn't build on x86_64-pc-windows-msvc.

Comment out `dump_jemalloc_heap_profile` function in `node_debug_service.rs`, and the associated call and import in `debug_interface/src/lib.rs` 

Currently, I'm wrestling with `rocksdb`. Release 0.12.2 builds correctly on Windows, but the Rust interface has changed. Libra is pinned to a specific commit (`4f8c6b3a48c7acb0c81f9bb91e7d8493b1c5a73e`), which errors with `Cannot open include file: 'snappy.h'`. This should be solvable, though. I'll update once I have it figured out.

**Comment by Kixunil** [comment]
Fixed by #83

**Comment by bmwill** [comment]
The dependencies needed to build Libra have been simplified so this should make it easier to build on windows (I believe building rocksdb maybe be the only hurdle now), though it sounds like using WSL is also an option.
