### ISSUE TITLE
[Bug] Faucet giving 500 error during the mint command

### ISSUE THREAD

**Issue by prashantpawar** [libra/libra#5825]
# 🐛 Bug

Trying to follow the 'My First Transaction' tutorial and its failing to provide me with coins from the faucet as its giving me a 500 Internal server error.

## To reproduce

**Code snippet to reproduce**
```
git clone https://github.com/libra/libra.git && cd libra
git checkout testnet
./scripts/dev_setup.sh
./scripts/cli/start_cli_testnet.sh
libra% account create
libra% account create
libra% account mint 0 110 LBR
```

**Stack trace/error message**
```
libra% account mint 0 110 LBR
>> Sending coins from faucet
[ERROR] Error transferring coins from faucet: Failed to query remote faucet server[status=500]: 
"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>500 Internal Server Error</title>\n
<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to 
complete your request. Either the server is overloaded or there is an error in the application.</p>\n"
```

## Expected Behavior

It should successfully mint me some LBR tokens from the faucet.

## System information

**Please complete the following information:**
- testnet branch. Commit: 4d1a383caaa03ae0e80596000e0444a161d81941
- Rust version: Unknown
- Mac OS X High Sierra 10.13.6

**Comment by prashantpawar** [comment]
So it worked when I tried it again but only once now I'm back with the 500 error. Is the faucet being DoSed?

**Comment by davidiw** [comment]
if it persists, feel free to re-open.
