### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by fredzannarbor** [libra/libra#5832]
# 🐛 Bug

NER documentation is inaccurate.

## To reproduce

https://libradocs.github.io/html/nlp.html says

```
newClient = client('path_to_txt’)
newClient.get_named_entities('detect from text')

```
However this produces error.

```
newClient.get_named_entities('detect from text')
Traceback (most recent call last):

  File "<ipython-input-8-ae853ca01d72>", line 1, in <module>
    newClient.get_named_entities('detect from text')

AttributeError: 'client' object has no attribute 'get_named_entities'
```
 
```
dir(client):

dir(client)
Out[9]: 
...
 'named_entity_query',
...
```

Spyder4/Python 3.8.5

**Comment by bob-wilson** [comment]
This is about https://github.com/Palashio/libra, not https://github.com/libra/libra. They're different projects. You'll need to re-file this in the right place.
