### ISSUE TITLE
Remove ConfigBuilder and Gossip

### ISSUE THREAD

**Issue by davidiw** [libra/libra#5846]
## Problem

[ConfigBuilder](https://github.com/libra/libra/tree/master/config/config-builder) is deprecated and only used for a couple of cases:
* Integration testing
* The [dynamic validator](https://github.com/libra/libra/tree/master/docker/validator-dynamic)

[Gossip networking](https://github.com/libra/libra/tree/master/network/src/protocols/gossip_discovery) also is a deprecated dependency that only exists for config-builder.

## Goal

Remove ConfigBuilder and Gossip from networking.

## Approach

* Minimize the code necessary for ConfigBuilder to support Integration tests or explore how to make the [Genesis based config builder](https://github.com/libra/libra/blob/master/config/management/genesis/src/config_builder.rs) work for integration test cases
* Add a --test feature to libra-node that takes in a random seed used for producing a deterministic genesis
* Eliminate validator-dynamic containers and give instructions on how to leverage --test from within the [primary docker container](https://github.com/libra/libra/tree/master/docker/validator)
* Update docker information to show that we no longer directly support running a set of validators in docker
* Remove [gossip]( from networking

**Comment by gregnazario** [comment]
@davidiw I think we did it!

**Comment by davidiw** [comment]
WOW, we accomplished so much!
