### ISSUE TITLE
Operational Tooling

### ISSUE THREAD

**Issue by davidiw** [libra/libra#5865]
## Problem

We lack reference implementation for operational tools across both node operators and libra root. While the former is required for production use of the blockchain, the lack of the latter makes for janky (smoke) tests.

## Goal

Create a reference set of tools to accomplish these tasks and have tests that take advantage of them.

### Operational
* [x] Create validator
* [x] Create validator-operator
* [x] Set-operator
* [ ] Auto-validate commands
* [x] Print validator-owner and operator name in validator-set and validator-config commands
* [x] Eliminate excessive printout of commands and just print success / failure (with a reason)

### Genesis
* [x] Support optional owner keys
* [x] Supports insertion of LR and TR keys from files
* [x] Supports generating genesis with two root keys for different accounts (LR, TR)
* [x] Supports only a single entity for LR / TR in the layout
* [x] Eliminate excessive printout of commands and just print success / failure (with a reason)

**Comment by ankushagarwal** [comment]
These are the two keys we need for AOS to control the premainnet network

```
LPN/TC Public Key = 1f68b944e6ce1387c729af5df4c587bc86230b464a41ad55cc6576acff9ae960
LibraRoot Public Key = 599a87bed2079654a8758ed774f1a7f9f8e5e9039c912ee77042082aa54e319a
```

**Comment by davidiw** [comment]
Seems that there's also work in making smoke test work with names :/
