### ISSUE TITLE
[Bug] genesis-tools exits 0 on errors

### ISSUE THREAD

**Issue by mgorven** [libra/libra#5916]
# 🐛 Bug

## To reproduce

    $ target/debug/libra-genesis-tool owner-key --validator-backend 'backend=vault;server=https://localhost:8201;ca_certificate=/home/mgorven/libra-partners/validator/gcp/default-vault.ca;token=vault.gcp;namespace=libra' --shared-backend 'backend=disk;path=/tmp/tmp.vVm7yMg31J;namespace=gcp'; echo $?
    Operation unsuccessful: Failed to read 'owner' from validator storage: Permission denied
    0

## Expected Behavior

Tool should exit with non-zero exit code on errors.

## System information

- 0102f6f89

**Comment by gregnazario** [comment]
I think that's fair, all the exit codes are the same right now

**Comment by davidiw** [comment]
wow, we addressed this quickly... genesis has a pr landing to address this...
