### ISSUE TITLE
Malleability check perf improvement

### ISSUE THREAD

**Issue by 0-o-0** [libra/libra#601]
# 🚀 Feature Request

During our performance testing, we identified that the signature deserialization with nextgen_crypto becomes the bottleneck that drives CPU utilization to 100% on c5d.xlarge machines. If the perf of the signature deserialization can be improved, the overall latency and throughput will be improved directly. For record, the current peak throughput with 100 c5d.xlarge nodes is ~300 TPS.

![image](https://user-images.githubusercontent.com/2981981/63189709-71f35a80-c019-11e9-85e6-164d04c47aba.png)

**Comment by huitseeker** [comment]
For reference, this is the place where I suspect our CPU time goes:
https://github.com/libra/libra/blob/c18d58b558fdd8124ca8ed92e173cc1e3f6ba018/crypto/nextgen_crypto/src/ed25519.rs#L114-L149

/cc @kchalkias

**Comment by kchalkias** [comment]
@0-o-0 could we rerun these tests when #907 gets merged? I'm very curious to see if there is any improvement after removing `R` and optimizing `S` validation logic.

**Comment by kchalkias** [comment]
Closing as we resolved it in #907
