### ISSUE TITLE
[Bug] warnings swallowed when compiling in root of workspace

### ISSUE THREAD

**Issue by metajack** [libra/libra#621]
# 🐛 Bug

Warnings appear to be swallowed when compiling in the root of a workspace. This is the intended behavior for non-path dependencies, but we'd like to see warnings for the local crates.

This also appears to prevent treating warnings as errors. See #618 where this was attempted unsuccessfully.

## To reproduce

1. checkout d8ecd67c which contains a warning in the `types` crate.
2. cargo build
3. cargo clean -p types
4. cd types
5. cargo build

Step 2 succeeds with no output, but Step 5 shows the warning.

## Expected Behavior

Step 2 above should also show the same warning as Step 5.

## Additional context

This appears related to rust-lang/cargo#5998.

**Comment by huitseeker** [comment]
I jotted down :
https://github.com/rust-lang/cargo/issues/6915
https://github.com/rust-lang/cargo/issues/1796

**Comment by metajack** [comment]
Thanks @huitseeker. The root cause of this is that the testing feature is getting flipped for crates, and the hidden warnings are because those warnings don't exist when compiled with the testing feature.

This is a low priority, since the only warnings we miss will be ones that aren't warnings under testing.

**Comment by davidiw** [comment]
feel free to re-open this issue if the issue persists.
