### ISSUE TITLE
[Bug] Recovering Wallet queries validator for no reason raising 429 errors

### ISSUE THREAD

**Issue by kf106** [libra/libra#65]
# 🐛 Bug
I created a mnemonic key file:

`silver silver silver silver silver silver silver silver silver silver silver silver;500`

and then using the Libra CLI ran `a r 0`

After a few seconds I started to get a lot of 429 error messages:

`E0619 00:48:08.655316 140305093594048 client/src/client_proxy.rs:640] Failed to get account state from validator, error: RpcFailure(RpcStatus { status: Cancelled, details: Some("Received http2 header with status: 429") })`

Presumably, this is due to too many queries to the validator.

Why is regenerating the key/address pairs making repeated queries to the validator? If queries to the validator are necessary, then the account recover command should space the requests out so that errors are not raised.

## To reproduce

See above

** Stack trace/error message **
`E0619 00:48:08.655316 140305093594048 client/src/client_proxy.rs:640] Failed to get account state from validator, error: RpcFailure(RpcStatus { status: Cancelled, details: Some("Received http2 header with status: 429") })`

## Expected Behavior

Loading a mnemonic key file should not require external calls to the validator. Hence there should be no error and the addresses should simply be generated.

## System information
Libra Version: ./scripts/cli/start_cli_testnet.sh has no version command and shows no version on running...
Rust Version: rustc 1.36.0-nightly (50a0defd5 2019-05-21)
Computer OS: Ubuntu 18.04

**Comment by xfyfb** [comment]
During wallet recovery, client will try to sync with validator for the latest sequence number. As the client/wallet generates address deterministically, if the same mnemonic file is used, the account might already exists on chain. In this case, cli/wallet will need the latest sequence number to submit transaction. 429 is from rate limit and is supposed to be transient, and it should work with retry.

**Comment by xfyfb** [comment]
Oh, I saw you set the child number to 500. It will recover 500 accounts and issue 500 rpc calls to validator, which is over the limit. Please try with a small number first and we will fix it with a more flexible solution.

**Comment by kf106** [comment]
Glad you noticed that. A suggestion: the sequence number sync should only occur when a transaction that relies on a valid sequence number is issued. So on generating e.g. 500 addresses, they could all start with sequence number -1, and then when an address is queried for balance or a transaction is issued, first submit a sync rpc.

**Comment by icarter09** [comment]
@kf106 can you relabel this issue from `bug` to `Enhancement`?

**Comment by xfyfb** [comment]
@kf106, the changes already merged. Can you run again and verify?

**Comment by kf106** [comment]
On it now.

**Comment by kf106** [comment]
Verified as improved.
