### ISSUE TITLE
[Feature Request] Eliminate encode_raw_bytes from canonical serialization

### ISSUE THREAD

**Issue by davidiw** [libra/libra#655]
Right now there are two means to encode byte arrays in canonical serialization. This requires authors to specify their byte encoding format and can lead to confusion. To address that, let's simplify the specification and eliminate the optional encoding of the length and make it required.

**Comment by davidiw** [comment]
We prepend 4 bytes. I completely agree that it improves readability but it also makes the canonical definition have non-trivial ambiguity. When reading a struct, when as a byte array require a prefix or not. To mitigate that, it was decided to accept the 4 byte prefix. The code was merged in https://github.com/libra/libra/commit/59d29647f8aac104c6552dff7dd292f6a3953f10

**Comment by kchalkias** [comment]
True, bincode serialization prepends 8 bytes, but ours 4, meaning the max payload is 2^32 bytes and incompatible with bincode, which I guess is ok.

We need to crosscheck this feature more carefully.
