### ISSUE TITLE
Just to say hi and good luck!

### ISSUE THREAD

**Issue by Chococoin** [libra/libra#66]
Nice to be here and be a witness to a big change breaking event in the modern world. I was preparing this kind of disruption with my chococoin and its proof-of-tree algorithm, but I have to give space to the team of Libra to do the job, you have the resources. I wish you all the luck and success of the world. I know you will do a better job than the current bank system. 

My best regards.

**Comment by FlorianWendelborn** [comment]
Because a global currency controlled by Facebook is *exactly* what the world needs...

Yes, they will do a better job than the current banking system, in spying, manipulating and abusing privacy — as is facebook's entire business model.

**Comment by Chococoin** [comment]
> Because a global currency controlled by Facebook is _exactly_ what the world needs...
> 
> Yes, they will do a better job than the current banking system, in spying, manipulating and abusing privacy — as is facebook's entire business model.

It won't be controlled by Facebook as I may read [https://libra.org/en-US/association-council-principles/#goals_and_principles](here)

But in any case, consensus is vote. 

Nobody is obligated to use Facebook nor LibraCoin, but you will see coming some governments that will ban their citizens to use LibraCoin. According to what I know, evil is always on the side where people have not choices.
