### ISSUE TITLE
[Bug] Memory usage increases with chain size

### ISSUE THREAD

**Issue by mgorven** [libra/libra#6644]
# 🐛 Bug

The RSS memory usage of validators and fullnodes increases as the size of the chain increases. This chart shows RSS of the Novi pre-mainnet validator along with the committed version:

![firefox-20201102-153016](https://user-images.githubusercontent.com/183923/98019426-95d5c400-1db6-11eb-9e5d-136e928aaef3.png)

After a process restart memory usage is back at the previous baseline within 1-2h, so this this isn't related to process uptime. It also happens on fullnodes.

## To reproduce

Run a public fullnode against pre-mainnet, mainnet. Or run a k8s testnet with cluster-test to generate a large chain state.

## Expected Behavior

Memory usage should not continually increase.

## System information

release-1.0_41e23b4aff

**Comment by davidiw** [comment]
@lightmark / @msmouse, does this make sense? I would imagine that as our merkle trees become larger, they will take more RSS. Also if we use the premise that RSS increases with the chain size, then it most likely is storage related. Do we have any info about how storage uses RSS over time? Is there max?

**Comment by mgorven** [comment]
Managed to get `jeprof` working by installing inside the running container.
[jeprof.pdf](https://github.com/libra/libra/files/5490512/jeprof.pdf)

**Comment by lightmark** [comment]
I guess it about default option keeps all the tables open. Let's try to limit it.
