### ISSUE TITLE
Compilation of script & how to run the main function of .mvir file

### ISSUE THREAD

**Issue by Noah-Vincenz** [libra/libra#67]
# 🐛 Bug

Running the following command in the /.../move_getting_started_examples directory with the script flag enabled produces an error:

<img width="776" alt="Screenshot 2019-06-18 at 23 35 18" src="https://user-images.githubusercontent.com/16804823/59724455-d2386c80-9221-11e9-872c-f5a3dcf92994.png">

Why is this happening? I have also tried using --script instead of -s.
Also, how can one run the main function of a .mvir file?

## Expected Behavior

Compilation and verification of transaction script.

## System information

- rust --version: rustc 1.36.0-nightly (50a0defd5 2019-05-21)
- MacOS Mojave Version 10.14.4

**Comment by bmwill** [comment]
If you're using cargo to run one of the binaries in the project you'll need to delineated command line options that you want passed to the binary and not to cargo with `--`.  For example, try the following:
```
cargo run -p compiler -- create_account_script.mvir
```
