### ISSUE TITLE
create dapp like eos chain???

### ISSUE THREAD

**Issue by plimerence** [libra/libra#7]
# 🐛 Bug

can I  create a dapp with libra chain??

**Comment by acodercc** [comment]
libra不是一个dapp platform

**Comment by acodercc** [comment]
libra is not a dapp platform

**Comment by theBigChups** [comment]
@plimerence You can use Snax, if you need something social with dapps
https://github.com/SnaxFoundation/snax

**Comment by TechniumUnlimited** [comment]
@acodercc If it has smart contracts then how is it not capable of making a dapp

**Comment by tangyongzheng** [comment]
It can completely replace EOS. The white paper mentions smart contracts.

**Comment by LewisFreitas** [comment]
Probably with the [Move language](https://developers.libra.org/docs/assets/papers/libra-move-a-language-with-programmable-resources.pdf).

**Comment by ericnakagawa** [comment]
Our smart contract language, Move, is still under development. I suggest starting [here](https://developers.libra.org/docs/move-overview.html).
