### ISSUE TITLE
[Bug] Duplicitous and subversive nature of the project

### ISSUE THREAD

**Issue by runvnc** [libra/libra#71]
This project is backed by Visa, Mastercard, and Paypal -- sworn enemies of cryptocurrency, since it competes with their primary business model which is to profit from the digital exchange of money.

Yet, Libra purports to bring all of the benefits of cryptocurrency to the masses.  This is ludicrous.

The primary benefit of cryptocurrency is control over your own digital money.   You control your wallet, and you control who and when you transfer it to.  There is no need for a bank to hold your money and profit from it, and no need for an intermediary to charge you for the privilege of transferring money, or monitor or prevent you from doing so.

Libra aims to take advantage of the goodwill and hype around cryptocurrency, but deliver none of the primary benefits I have just mentioned.  They will control and profit from your money, and they will charge you fees for transmitting it to other parties.

But again, this is marketed as a cryptocurrency, supposedly just like other cryptocurrencies.  And yet nothing could be further from the truth.

The payment processors recognized that cryptocurrency presented a challenge to their business model, and they came up with a clever way to subvert it.

I urge developers and citizens across the world to support real cryptocurrencies.  Do not fall for this scam.

**Comment by timolson** [comment]
There is no blockchain as far as I can tell, only a centralized database with a checksum passed around.  Clearly false advertising.

**Comment by sbourdeauducq** [comment]
Y'all, please shut up and take your $400k/year salary from Facebook or another similar Silicon Valley company.

**Comment by pigd0g** [comment]
This is a critical bug and possibly requires a full re-write. Upvote.

**Comment by ericnakagawa** [comment]
Hi @runvnc, thanks for taking the time submitting this. Unfortunately, we're using GitHub for technical issues. If you'd like to have a further discussion about our approach to building Libra check out our Discourse. https://community.libra.org

**Comment by runvnc** [comment]
It is a technical issue because it concerns the developer community that visits this repo and looks in the issue section.  Developers are going to hear the false marketing for Libra and be attracted to the project for altruistic reasons.  

They need to know that due to technical reasons of the structure of the project such as the limited number of closed validators and the reliance on fiat, the project is insecure and untrustworthy and cannot provide the benefits of real cryptocurrencies.  Developers need to know that supporting this project undermines real cryptocurrency efforts such as Bitcoin and Ethereum that _can_ provide those benefits.

It's true that everyone has to make money.  Especially if they live somewhere expensive like the Bay Area.  But I just hope that everyone involved here or contemplating getting involved with or promoting this project realizes that what they have traded their integrity in to work for the enemy.  Visa, MasterCard, and PayPal cannot possibly ever support the core principles of cryptocurrency.  Their sole concern is to make money and avoid having their business model superceded.
