### ISSUE TITLE
[Bug]Can't create mint request

### ISSUE THREAD

**Issue by morsamatias** [libra/libra#710]
# 🐛 Bug

I'm following [this guide](https://developers.libra.org/docs/my-first-transaction#create-alice-s-and-bob-s-account) , I have created the 2 accounts, with index of 0 and 1, but when I try to mint Libra to any account I get an error.

Computer: MacBook Pro 2018
System: MacOS Mojave 10.14.6
Libra version:  How can I know the Libra version?

** Code snippet to reproduce **
```
%libra account create
%libra account mint 0 110 
```

** Stack trace/error message **
```
Minting coins
[ERROR] Error minting coins: Failed to query remote faucet server[status=405 Method Not Allowed]: "<html><body><h1>405 Method Not Allowed</h1>\nA request was made of a resource using a request method not supported by that resource\n</body></html>\n"
```

**Comment by fbandersnatch** [comment]
> Libra version: How can I know the Libra version?

When you checkout `testnet` run `git rev-parse HEAD`

When did you checkout the code? This error could happen if you're using a very old version of testnet code.

**Comment by morsamatias** [comment]
The code was from a month ago. I try with the latest version and everything worked fine.
