### ISSUE TITLE
[proposal] Transactions with Private Subaddressing

### ISSUE THREAD

**Issue by kphfb** [libra/libra#714]
# Transactions with Private Subaddressing v3

* * *

## Motivation

* * *
Merchants and wallet holders may rely on third parties to maintain custody of their wallet and may optionally want to receive additional, yet private data in transactions. Those transferring money to a merchant or other wallet holders may wish to do so without publicly revealing the identity of the recipient. Libra leverages subaddressing with encryption to provide transaction privacy.

As an example, assume a recipient account provides custodial wallets. One of those wallets is owned by a merchant that sells various merchandise. A customer purchases something from the merchant and would like to tell the merchant where to ship the item. To do this within Libra:

* The recipient crafts a QR code containing a URI that references the account hosting the custodial wallet, or the host, and a reference to their wallet. In addition, the URI contains the specific item to be purchased.
* The consumer scans the QR code, constructs a transaction and includes within it the encrypted subaddress contained therein, the item to be purchased as specified by the QR code, and their personal address.
* Once the transaction has been submitted and committed to the blockchain, the host notifies the recipient of the transaction and shares with it the decrypted contents.

This document describes an approach supporting transactions like this by defining a standard that supports:

* Subaddressing to support multiplexing a single account address into multiple wallets enabling custodial wallets to maintain a single address rather than maintain numerous.
* Unlinkability by using encryption that makes it impossible to link different uses of the same subaddress.
* Inclusion of (optionally private) data within a transaction.

* * *

## URI Format for Transaction Recipient

* * *
When a user wishes to inform another party how to send them a transaction, they will share a “target”. A common example of a target would be embedded in a QR code. To follow typical QR code formats for blockchains, we use a URI format as follows:

`libra:{base_58_encode(to_address|to_subaddress)}?memo={url encoded memo}&amount={amount}`

Note, the ‘|’ is not a logical/bitwise OR but is instead simply the ‘|’ character intended to act as a separator. The subaddress, which will be discussed shortly, is optional. In the event where a subaddress is not needed, the format is as follows (simply omitting the to_subaddress field):

`libra:{base_58_encode(to_address)}?memo={url encoded memo}&amount={amount}`

Note, the address/to_subaddress combination is base58 encoded and the memo is url encoded.  The amount is base10 with a max size of u64 max and specified in microlibra.

Fields:
`**to_address** - (Required) The public address to which the funds should be sent`
`**to_subaddress** - (Optional) The subaddress to which the funds should be sent. This is the private address under the public address. As an example, a custodial wallet could identify their users by email address. In this case, the to_subaddress may be “[_kph@example.com_](mailto:kph@example.com)”.`
`**memo** - (Optional) Additional information to include with the transaction. An example would be an invoice ID from a merchant`
`**amount** - (Optional) The amount of the transaction requested by this target (in micro-libra).`

### Target Sample Generation

```
// Create the param string.  Note that all fields are optional
// and can be excluded as desired
param_string = "memo=" + url_encode(memo) + "&amount=" + amount;
to_address = to_address + "|" + sub_address;
to_address_encoded = base_58_encode(to_address);
uri = "libra:" + to_address_encoded + "?" + param_string;
```

This generates a URI with a “libra:” prefix.
* * *

## The Lifetime of a Transaction Containing Metadata

* * *
The first step to submitting a transaction is producing the metadata. The sender first obtains the URI as specified above and produces a matching **Libra Canonically Serialized (LCS)** metadata_wrapper consisting of an optionally encrypted LCS-serialized Metadata object:

```
struct MetadataWrapper {
    // Tuple of (key_type, key_version)
    Option<(u32, u32)> key,

    // If key is present, this will be an encrypted instance
    // of the LCS-serialized Metadata object.
    // If key is absent, this is an LCS-serialized Metadata object
    Vec<u8> payload,
}

struct Metadata {
    // Subaddress to which the funds are being sent
    Option<Vec<u8>> to_subaddress,
    // Memo to include with the transaction
    Option<string> memo,
    // Subaddress from which the funds are being sent
    Option<Vec<u8>> from_subaddress,
}
```

The metadata wrapper is then prefixed with a single byte representing the format.  The format proposed in this document is specified as format 0x1.  Other formats could later be added using a different format specifier.

Using the initial example described in the motivation, the merchant whose wallet, 0x5678, is hosted by 0x1234  may post a URI for shoes that cost 20 Libra:

```
libra:{base_58_encode(0x1234|0x5678)}?memo={shoes}&amount={20}
```

The purchaser would then submit a transaction containing the following metadata:

```
01 [01, {7, 0}, encrypt([01, 0x5678, 01, "shoes", 00], key({7, 0})]
/* format_specifier, [key_is_present, key_tuple, 
    encrypted_payload(
      [to_subaddress_present, to_subaddress,  
      memo_present, memo, from_subaddress_not_present], 
      instance_of_encryption_key)] */
```

Where {7, 0} refers to a specific key, and key({7, 0}) is the instance of that key (used by encryption method).

### Key Storage and encryption

Each account may have one or more encryption keys associated with it stored at '“/address/encryption_keys”. This storage supports one key per type (e.g., RSA, Curve25519), the version or iteration of the current key, and the encryption key itself. For example, account 0x1234 has two keys:

```
`/``0x1234``/``encryption_keys `=>
{
    // `key_type ``=> key_version, key_value``   `
`    ``7``           ``=>`` ``0``,``           ``0xabc57697`
`    ``3``           ``=>`` ``2,``           ``0xddd57697`
`}`
```

By leveraging a key type and encryption standard that supports unlinkability, a transaction with the same metadata will always produce distinct bytes providing unlinkability for transactions targeting the same sub-address.

Senders should retrieve and use encryption keys immediately prior to sending. The framework supports updating encryption_keys, but recipients are expected to retain the decryption key for some time period thereafter. We recommend at least a week to mitigate the loss of information due to delayed transactions.

### Submitting a transaction

With the metadata in hand, the sender can now submit a transaction to the Libra block chain via a deposit call in Move:

```
deposit(prefixed_metadata_wrapper, recipient, amount);
```

### Processing the transaction

Much like any other funds transfer request, validators only verify that the sender has the sufficient libra to support the transaction and that the transaction is properly formed and valid, they do not inspect or verify the correctness of the metadata.
* * *

## Transaction Examples

* * *
The following examples demonstrate how subaddressing and metadata are used in the transaction flow.  **Note that the terminology “NC” will mean non-custodial account and “C” will mean a custodial account.**

### NC to NC transaction Flow

User A (address 0x1234) on a NC wallet wishes to send 100 microlibra to merchant B (address 0x8997) who is also on a NC wallet.  User A scans the QR code of merchant B which contains the following:

```
libra:<base_58_encode(0x8997)>?memo="invoice_123"&amount=100
```

User A’s client now queries the account state of 0x8997 and finds that there is no value at /0x8997/encryption_keys which means that no encryption key is present, so the memo field will remain in plaintext.

User A's client now composes a raw transaction with the following relevant fields:

```
metadata = Metadata {
  memo: "invoice_123",
};

metadata_wrapper = MetadataWrapper {
  payload: lcs(metadata),
};


program = get_send_program_with_args(
    prefix_with_format_byte(0x1, lcs(metadata_wrapper)),
    0x8997 /*recipient*/,
    100 /*amount*/,
);

RawTransaction {
    sender_account: 0x1234,
    program: program, 
}
```

This transaction is sent to a validator and executed.  B monitors their events and sees a received transaction.  B can now see the metadata to determine the memo.

### NC to C Transaction Flow

User A (address 0x1234) on a NC wallet wishes to send 100 microlibra to merchant B who is on a private custodial wallet (Where the custodial wallet has a public address of 0x7777 and the merchant has a sub-account of “kevin”) .  User A scans the QR code of merchant B which will contain the following:

```
libra:{base_58_encode("0x7777|kevin")}?memo="invoice1"&amount=100
```

User A’s client queries the account state of 0x7777 and finds:

```
`/``0x7777``/``encrypt_keys `=> {
    // `key_type``       =>  key_version,  key_value``   `
`    7`` ``=>``                   ``0``,``         ``   ``0x0987654321`
`    3`` ``=>``                   ``2``,``       ``     ``0xddd57697`
`}`
```

User A’s client can support both key_types of 7 and 3, so chooses to use whichever it desires.  In this case, the client uses key_type of 7.  User A's client now composes a raw transaction with the following relevant fields:

```
metadata = Metadata {
  to_subaddress: "kevin",
  memo: "invoice_1",
};

metadata_wrapper = MetadataWrapper {
  payload: encrypt(lcs(metadata), key(7, 0)),
};

program = get_send_program_with_args(
    prefix_with_format_byte(0x1,lcs(metadata_wrapper)),
    0x7777 /*recipient*/,
    100 /*amount*/,
);

RawTransaction {
    sender_account: 0x1234,
    program: program, 
}
```

### C to NC transaction flow

User A who is on a custodial wallet (Where the C wallet has a public address of 0x7777 and user A has a sub-account of “kevin”) wishes to send 100 microlibra to merchant B who is on a NC wallet (with an address of 0x1234) .  User A scans the QR code of merchant B which will contain the following:

```
libra:{base_58_encode(0x1234)}?memo="invoice1"&amount=100
```

User A queries the state information for account 0x1234 and finds that there are no encryption keys listed.  User A's wallet then composes a transaction via:

```
metadata = Metadata {
  memo: "invoice_1",
  from_subaddress: "kevin",
};

metadata_wrapper = MetadataWrapper {
  payload: lcs(metadata),
};

program = get_send_program_with_args(
    prefix_with_format_byte(0x1,lcs(metadata_wrapper)),
    0x1234 /*recipient*/,
    100 /*amount*/,
);

RawTransaction {
    sender_account: 0x7777,
    program: program, 
}
```

### Refunds

Merchant B now wishes to refund user A. But user A was sending from a custodial account so merchant B must send the funds back to the custodial account and include subaddress information so that the funds are directed back to user A.  So to refund user A, merchant B now must query the account state of the custodial account of user A to determine encryption keys.  Merchant B’s client queries the account state of 0x7777 and finds: 

```
`/``0x7777``/``encryption_keys `=> {
    // `key_type``       =>  key_version,  key_value``   `
`    7`` ``=>``                   ``0``,``         ``   ``0x0987654321`
`    3`` ``=>``                   ``2``,``       ``     ``0xddd57697`
`}`
```

Merchant B’s client can support both key_types of 7 and 3, so chooses to use whichever it desires.  In this case, the client uses key_type of 7.  Merchant B’s client now constructs a transaction via the following:

```
metadata = Metadata {
  to_subaddress: "kevin",
  memo: "invoice_1",
};

metadata_wrapper = MetadataWrapper {
  payload: encrypt(lcs(metadata), key(7, 0)),
};

program = get_send_program_with_args(
    prefix_with_format_byte(0x1,metadata_wrapper),
    0x7777 /*recipient*/,
    100 /*amount*/,
);

RawTransaction {
    sender_account: 0x1234,
    program: program, 
}
```

### C to C transaction flow

User A who is on a custodial wallet (where the custodial wallet has a public address of 0x7777 and user A has a sub-account of “kevin”) wishes to send 100 microlibra to merchant B who is on another custodial wallet (where the custodial wallet has a public address of 0x8888 and merchant B has a sub-account of “ben”). User A scans the QR code of merchant B which will contain the following:

```
libra:<base_58_encode("0x8888|ben")>?memo="invoice1"&amount=100
```

User A’s client queries the account state of 0x8888 and finds:

```
`/``0x8888``/``encrypt_keys `=> {
    // `key_type``       =>  key_version,  key_value``   `
`    7`` ``=>``                   ``0``,``         ``   ``0x0987654321`
`    3`` ``=>``                   ``2``,``       ``     ``0xddd57697`
`}`
```

User A’s client can support both key_types of 7 and 3, so chooses to use whichever it desires. In this case, the client uses key_type of 7.  User A's client now composes a raw transaction with the following relevant fields:

```
metadata = Metadata {
  to_subaddress: "ben",
  memo: "invoice_1",
  from_subaddress: "kevin",
};

metadata_wrapper = MetadataWrapper {
  payload: prefix_with_format_byte(0x1,encrypt(lcs(metadata), key(7, 0))),
};

program = get_send_program_with_args(
    metadata_wrapper,
    0x8888 /*recipient*/,
    100 /*amount*/,
);

RawTransaction {
    sender_account: 0x7777,
    program: program, 
}
```

* * *

## Potential concerns of URI scheme

The max URI size needs to be considered, but in both Android and iOS, it appears that there is effectively no limit on max size for the URIs (at least not one that will be reached by us): 

* iOS: Mentions a de facto 2000 characters, but a test later confirms that 1MB is fine: https://stackoverflow.com/questions/11546582/custom-url-scheme-maximum-url-length
* Android: https://stackoverflow.com/questions/28729955/max-size-of-string-data-that-can-be-passed-in-intents?lq=1

**Comment by bmaurer** [comment]
It took me a few reads through this to figure out how to use MetadataType.

* It seems a bit confusing to have the encryption key & the encrypted message be in different instances of the enum. As a parser of this data you now need to buffer an encryption key. Some implementations might (despite the way the spec is written) rely on the elements of the vector being adjacent. Why not simply use a tuple for encrypted_data that has the key attached? this seems far easier to parse.

* is it legal to have multiple instances of, say from_subaddress? For example `[from_subaddress(abc), from_subaddress(efg)]`. How should somebody interpret that, is the from_subaddress abc or efg? Or both? What if there's a from_subaddress and then later there's an encrypted message with a different from_subaddress? As an attacker one thing I'd look for is if different software treated this case differently (i.e. one person thinks it's from abc the other person efg). If different software treats the same message differently it could be a way to have one system think you made a payment but another system not.

* Allowing multiple encrypted messages seems to suffer from the same system. If you expect a payment to contain two different encrypted messages, what if an attacker sends two different messages?

When we wrote this recursive spec, we didn't have the LCS format defined. I wonder if, given that format, it might make sense to consider something like this:

```
struct MaybeEncryptedMetadata {
  Option<(int, int)> key;
  // if key is present, an encrypted instance of Metadata
  // if no key, an LCS serialized Metadata
  string maybe_encrypted_data;
}

struct Metadata {
  // from_address, memo, etc
}
```

This approach is easier to parse, as there's less ambiguity around double specifying a field. That said, it's also less expressive. I.e. the current spec supports a plain text memo then an encrypted to address.

**Comment by kchalkias** [comment]
Reading @bmaurer's comment I realized there is also a racing issue between key lookup and submitting a transaction, because in the meantime the key (and version) might change.

**Comment by bmaurer** [comment]
> Reading @bmaurer's comment helped me realize there is also a racing issue between key lookup and submitting a transaction, because in the meantime the key (and version) might change. So, we should expect to see ordering incompatibilities in the chain, meaning that users should cache their key map history.
> I'm wondering if we should also consider attaching the decryption public key itself in the transaction, not just the mapping.

I think we could say that if you fetch a key at time T that, by convention, the key should be at least valid until T+n. i.e. if you set the TTL on your transaction so that it will never get committed after T+n you can be sure it will be readable.

**Comment by kchalkias** [comment]
I mainly consider what we see on the blockchain.
T0: key = 0
T1: lookup key = 0
T2: update to key = 1
T3: tx encrypted under key = 0

If at T2 I updated my key because I lost the previous one, then I won't be able to decrypt. My questions is if we should enforce key_index checking when processing a transaction (and discard mismatches) rather than having a the T+n rule.

**Comment by bmaurer** [comment]
Having the processing done at validation time means that validators now need to parse the subaddress.

In the case above you'll always lose some transactions i.e. the ones between the key loss and T2. I think we can keep n small here -- say 1 hour.

That said, this does suggest an interesting use case of reversing a transaction that you can't decrypt. I wonder if we should make it so that you can always reverse a transaction by sending a transaction that references the metadata of the transaction to be reversed.

**Comment by kchalkias** [comment]
> Having the processing done at validation time means that validators now need to parse the subaddress.

Hm.. I thought subaddresses are checked at the VASP side (receiver's database requires it to update the corresponding user-account internally). Thus, do validators need to parse metadata? Then, we'll need a flag to distinguish between regular and sub-address related transactions.

**Comment by kphfb** [comment]
Proposal has been updated to reflect comments

**Comment by kphfb** [comment]
> > Having the processing done at validation time means that validators now need to parse the subaddress.
> 
> Hm.. I thought subaddresses are checked at the VASP side (receiver's database requires it to update the corresponding user-account internally). Thus, do validators need to parse metadata? Then, we'll need a flag to distinguish between regular and sub-address related transactions.

Validators do not need to parse metadata.  The recipient is the one who needs to parse it (and validators cannot parse it in the case of encrypted data)

**Comment by talbeerysec** [comment]
> Also check this 1 pager around QRishing, QR revocation and refresh issues. https://docs.google.com/document/d/11PH-X_63zaxpn6-uYJXo-iS8YQLblJCxrd-bz4T0LqU/edit#

Google doc requires permission

**Comment by jaypalma** [comment]
😉

**Comment by jaypalma** [comment]
usage: <command> <args>

Use the following commands:

account | a
  Account operations
query | q
  Query operations
transfer | transferb | t | tb
  <sender_account_address>|<sender_account_ref_id> <receiver_account_address>|<receiver_account_ref_id> <number_of_coins> [gas_unit_price (default=0)] [max_gas_amount (default 10000)] Suffix 'b' is for blocking.
  Transfer coins from account to another.
help | h
  Prints this help
quit | q!
  Exit this client


Please, input commands:

libra%

**Comment by sblackshear** [comment]
> is it legal to have multiple instances of, say from_subaddress? For example [from_subaddress(abc), from_subaddress(efg)]

Following up on this question, since it has implications for batching. If each metadata struct has ab most one `(to, from)` subaddressing pair, we can implement batching by creating a transaction script with multiple recipient addresses/amounts/metadata structs and calling `pay_from_sender` once for each. E.g.,

```
main(recipient1: address, amount1: u64, metadata1: bytearray,
     recipient2: address, amount2: u64, metadata2: bytearray) {

  LibraAccount.pay_from_sender(recipient1, amount1, metadata1);
  LibraAccount.pay_from_sender(recipient2, amount2, metadata2);
}
```

This form of batching is simple and intuitive. We could also support a different, more concise form of batching (was discussing with @kchalkias today) by allowing the metadata format to contain multiple `(to, from, amount, memo)` tuples. For the variant of the above where `recipient1 = recipient2`, that would let us do something like

```
main(recipient: address, amount: u64, metadata: bytearray) {
  // Now amount = amount1 + amount2 and the split is specified in metadata
  LibraAccount.pay_from_sender(recipient, amount, metadata);
}
```

This form of batching has some upsides:
- It will hide the amount received by private wallet users. In the previous form of batching, an observer will know that there are two distinct payments to private wallet users and how large each one is. In this form, the observer wouldn't know either of these things
- This costs less gas and emits fewer events than the previous approach (but the metadata will be bigger/more complex)

Wondering if we want to support this form of batching too. It will make the metadata bigger/trickier to interpret, but might be worth it for the privacy and savings.

**Comment by sblackshear** [comment]
^ This doesn't matter much from the Move perspective, FWIW; the only change is that the representation of metadata should probably be a larger type if we want to support the more aggressive batching.

**Comment by kchalkias** [comment]
I personally see two extra issues that we probably haven't extensively addressed before:
a) privacy: should we reveal if this was a batch payment? Why should externals know if it was 1, 10 or 20 payments?
b) travel rule: is this aligned with the travel rule design considerations?

**Comment by davidiw** [comment]
Seems this issue has moved on to greater places.
