### ISSUE TITLE
error: failed to run custom build command for `grpcio-sys v0.4.4` when running start_cli_testnet.sh

### ISSUE THREAD

**Issue by tiendq** [libra/libra#72]
Errors when running `./scripts/cli/start_cli_testnet.sh`

error: failed to run custom build command for `grpcio-sys v0.4.4`

And I see this at the end of building output.

```sh
CMake Error at CMakeLists.txt:5405 (add_library):
  Cannot find source file:

    src/csharp/ext/grpc_csharp_ext.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:5405 (add_library):
  No SOURCES given to target: grpc_csharp_ext
```

I'm using macOS 10.12.6

**Comment by jingtying** [comment]
I'm having the same error too. I'm using Amazon EC2 Linux

**Comment by jingtying** [comment]
I solved the problem. Uninstall CMake and reinstall again & I also install C++ compiler as it showed in my error message

**Comment by tiendq** [comment]
I had used GCC before, removed it and also reinstalled CMake, and libra works now :)

But don't know what was issue with CMake (previously installed version was 3.12).
