### ISSUE TITLE
[Question] About mapping/multiIndex in Libra Move language

### ISSUE THREAD

**Issue by johnteee** [libra/libra#77]
## ❓ Questions and Help

&#x200B;

&#x200B;

&#x200B;

The concepts of Libra & Move language are awesome;

however there's no primary type such like mapping(Solidity) or multiIndex(EOS).

Is there any method to achieve mapping functionalities in current Move language prototype?

&#x200B;

&#x200B;

&#x200B;

Primitive Types:

* In the white paper: [https://developers.libra.org/docs/assets/papers/libra-move-a-language-with-programmable-resources.pdf](https://developers.libra.org/docs/assets/papers/libra-move-a-language-with-programmable-resources.pdf)
* Parser: [https://github.com/libra/libra/blob/master/language/compiler/src/parser/mod.rs](https://github.com/libra/libra/blob/master/language/compiler/src/parser/mod.rs)

There's no HashMap-like type

&#x200B;

&#x200B;

&#x200B;

Currently it seems "Account-Based" resource accessing...no `Mapping/MultiIndex`

For Example:

[Link](https://github.com/libra/libra/blob/master/language/stdlib/modules/libra_account.mvir)

&#x200B;

That might restrict DApp developments somehow...

**Comment by sblackshear** [comment]
Hi John,
  Good question! The initial release of Move does not have collections such as maps, but they are a top priority (along with generics, which are related) for our next release. The technical [roadmap](https://developers.libra.org/blog/2019/06/18/the-path-forward#move-language) for Libra describes our plans in more detail:

> We will add container types, such as vectors and maps. Containers will greatly increase the expressivity of Move and are required to implement some core system modules (e.g., the validator-set module manages a collection of validators).

In addition, many use-cases of maps in other platforms involve building a map from account addresses to something (e.g.) ints. You can often replicate a map from addresses to some type `T` in the current version of Move by:

- Creating a module that declares `T`
- Define a procedure like `public get_a_t() { t = ...; move_to_sender<T>(t) }` that allows the caller to publish a `T` under their account + other procedures for accessing the state of `T` in accordance with the policies its module wants to encode.

Happy to discuss strategies for implementing something specific in more detail on our [discourse](https://community.libra.org/) if you have questions.

**Comment by davidiw** [comment]
Closing out stale issue.

**Comment by luatnd** [comment]
Can you tell us is there any update?
