### ISSUE TITLE
error: linking with 'cc' failed: exit code: 1

### ISSUE THREAD

**Issue by jingtying** [libra/libra#78]
What is the problem for this error message? 

Stucked at the last part compiling client

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" 
"/home/ec2-user/.rustup/toolchains/nightly-2019-05-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" 
"/home/ec2-user/libra/target/debug/deps/client-660f4b58bcda33f2.11p9ib01weplspni.rcgu.o" "/home/ec2-user/libra/target/debug/deps/client-660f4b58bcda3                      3f2.17eh1i05h96j5hsm.rcgu.o" 

-
-
( I deleted the remaining, just showed the error message)
-

error: aborting due to previous error

error: Could not compile `client`.

To learn more, run the command again with --verbose.

**Comment by wqfish** [comment]
Hi @jingtying it might have been that you ran out of disk space. Can you check that?

**Comment by wongchiuchun** [comment]
I had the same issue running Ubuntu on my VM. Looks like it was an issue with memory and CPU - I have reallocate more resources to it and it worked.

**Comment by jingtying** [comment]
Thank you @wqfish and @wongchiuchun .. Yes I tried in my own Ubuntu, it’s solved. I didn’t expect testnet need so much memory and CPU power.
