### ISSUE TITLE
[Bug]./scripts/dev_setup.sh ERROR MAC,python3.6

### ISSUE THREAD

**Issue by weisong82** [libra/libra#80]
`(py3-6) ➜  libra git:(master) ./scripts/dev_setup.sh

Welcome to Libra!

This script will download and install the necessary dependencies needed to
build Libra Core. This includes:
	* Rust (and the necessary components, e.g. rust-fmt, clippy)
	* CMake, protobuf, go (for building protobuf)

If you'd prefer to install these dependencies yourself, please exit this script
now with Ctrl-C.

Proceed with installing necessary dependencies? (y) > y
Installing Rust......
info: downloading installer

info: updating existing rustup installation

Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
environment variable. Next time you log in this will be done automatically.

To configure your current shell run source $HOME/.cargo/env
info: syncing channel updates for 'stable-x86_64-apple-darwin'

info: checking for self-updates

  stable-x86_64-apple-darwin unchanged - rustc 1.35.0 (3c235d560 2019-05-20)

info: component 'rustfmt' for target 'x86_64-apple-darwin' is up to date
info: component 'clippy' for target 'x86_64-apple-darwin' is up to date
Installing CMake......

==> Installing dependencies for cmake: sphinx-doc
==> Installing cmake dependency: sphinx-doc
==> Downloading https://files.pythonhosted.org/packages/7a/1e/415e6071c7bbceb5ce5e92b06297a5192544bcd5c0d50fd73e1f61da55f5/Sphinx-1.6.6.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc-1.6.6.tar.gz
==> Downloading https://files.pythonhosted.org/packages/41/5f/6da80400340fd48ba4ae1c673be4dc3821ac06cd9821ea60f9c7d32a009f/setuptools-38.4.0.zip
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--setuptools-38.4.0.zip
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/d0/a5/e3a9ad3ee86aceeff71908ae562580643b955ea1b1d4f08ed6f7e8396bd7/alabaster-0.7.10.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--alabaster-0.7.10.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/5a/22/63f1dbb8514bb7e0d0c8a85cc9b14506599a075e231985f98afd70430e1f/Babel-2.5.1.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--Babel-2.5.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/23/3f/8be01c50ed24a4bd6b8da799839066ce0288f66f5e11f0367323467f0cbc/certifi-2017.11.5.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--certifi-2017.11.5.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--chardet-3.0.4.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/84/f4/5771e41fdf52aabebbadecc9381d11dea0fa34e4759b4071244fa094804c/docutils-0.14.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--docutils-0.14.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/f4/bd/0467d62790828c23c47fc1dfa1b1f052b24efdf5290f071c7a91d0d82fd3/idna-2.6.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--idna-2.6.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/53/72/6c6f1e787d9cab2cc733cf042f125abec07209a58308831c9f292504e826/imagesize-0.7.1.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--imagesize-0.7.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/56/e6/332789f295cf22308386cf5bbd1f4e00ed11484299c5d7383378cf48ba47/Jinja2-2.10.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--Jinja2-2.10.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--MarkupSafe-1.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/21/94/0e087bd669bb69da3b0996acfee97cee9f7d91c825991ad76eb863dc020d/numpydoc-0.7.0.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--numpydoc-0.7.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/71/2a/2e4e77803a8bd6408a2903340ac498cb0a2181811af7c9ec92cb70b0308a/Pygments-2.2.0.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--Pygments-2.2.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/60/88/d3152c234da4b2a1f7a989f89609ea488225eaea015bc16fbde2b3fdfefa/pytz-2017.3.zip
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--pytz-2017.3.zip
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/b0/e1/eab4fc3752e3d240468a8c0b284607899d2fbfb236a56b7377a329aa8d09/requests-2.18.4.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--requests-2.18.4.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--six-1.11.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/20/6b/d2a7cb176d4d664d94a6debf52cd8dbae1f7203c8e42426daa077051d59c/snowballstemmer-1.2.1.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--snowballstemmer-1.2.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/c5/6b/f0630436b931ad4f8331a9399ca18a7d447f0fcc0c7178fb56b1aee68d01/sphinxcontrib-websupport-1.0.1.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--sphinxcontrib-websupport-1.0.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/ca/38/16ba8d542e609997fdcd0214628421c971f8c395084085354b11ff4ac9c3/typing-3.6.2.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--typing-3.6.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> Downloading https://files.pythonhosted.org/packages/ee/11/7c59620aceedcc1ef65e156cc5ce5a24ef87be4107c2b74458464e437a5d/urllib3-1.22.tar.gz
Already downloaded: /Users/wei/Library/Caches/Homebrew/sphinx-doc--urllib3-1.22.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec/vendor --single-version-externally-managed --record
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.6.6/libexec --single-version-externally-managed --record=instal
Error: parent directory is world writable but not sticky
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:708:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:322:in `install'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:562:in `install_dependency'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:524:in `block in install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:524:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:524:in `install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:262:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:313:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:246:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:244:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:244:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'`

**Comment by PJUllrich** [comment]
I haven't received this issue myself, but "according to the internet"™, it might help to set the 'sticky' permission on your `/private/tmp` folder. To do that, simply run this:
```
sudo chmod +t /private/tmp/
```

**Comment by Kixunil** [comment]
#83 compiles on my machine, it should fix this as well.

**Comment by icarter09** [comment]
@weisong82 did either of the posted comments from @PJUllrich or @Kixunil help out with the issue?

**Comment by weisong82** [comment]
@icarter09  both comments don't help out this issue.

**Comment by bmwill** [comment]
The external dependencies needed to build Libra have been simplified and should only require Rust now so this shouldn't be an issue anymore on master. If it is, please let us know.
