### ISSUE TITLE
[benchmark] Evolve load generator

### ISSUE THREAD

**Issue by littlepretty** [libra/libra#807]
# 🚀 Feature Request
Evolve [load generator](https://github.com/libra/libra/blob/master/benchmark/src/load_generator.rs) to work flexibly with Benchmarker for playing real world transactions.

## Motivation
For playing transaction history, say, from Bitcoin or Ethereum, in Libra.

## Pitch
As mentioned benchmark/doc/load_generator in pull request #586 , may this can be divided into two tasks 
1. Introduce `round` into the `load_generator` interface
2. Implement a `load_generator` that is able to parse transaction dependencies from transaction history

**Comment by bmwill** [comment]
The benchmark crate has been removed and the new way to generate load is the cluster-test infrastructure. I'd take a look there for more info.
