### ISSUE TITLE
failed to run custom build command for `mempool v0.1.0 

### ISSUE THREAD

**Issue by heipacker** [libra/libra#808]
cargo build
   Compiling channel v0.1.0 (/home/heipacker/RubyProjects/libra/common/channel)
   Compiling grpc_helpers v0.1.0 (/home/heipacker/RubyProjects/libra/common/grpc_helpers)
   Compiling schemadb v0.1.0 (/home/heipacker/RubyProjects/libra/storage/schemadb)
   Compiling mempool v0.1.0 (/home/heipacker/RubyProjects/libra/mempool)
error: failed to run custom build command for `mempool v0.1.0 (/home/heipacker/RubyProjects/libra/mempool)`

Caused by:
  process didn't exit successfully: `/home/heipacker/RubyProjects/libra/target/debug/build/mempool-f67b88cb0a33a2b8/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=../types/src/proto/proof.proto
cargo:rerun-if-changed=../types/src/proto/language_storage.proto
cargo:rerun-if-changed=../types/src/proto/events.proto
cargo:rerun-if-changed=../types/src/proto/account_state_blob.proto
cargo:rerun-if-changed=../types/src/proto/validator_change.proto
cargo:rerun-if-changed=../types/src/proto/transaction_info.proto
cargo:rerun-if-changed=../types/src/proto/access_path.proto
cargo:rerun-if-changed=../types/src/proto/get_with_proof.proto
cargo:rerun-if-changed=../types/src/proto/transaction.proto
cargo:rerun-if-changed=../types/src/proto/vm_errors.proto
cargo:rerun-if-changed=../types/src/proto/validator_set.proto
cargo:rerun-if-changed=../types/src/proto/ledger_info.proto
cargo:rerun-if-changed=../types/src/proto/validator_public_keys.proto
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=src/proto/shared/mempool_status.proto

--- stderr
events.proto: warning: Import access_path.proto but not used.
transaction.proto: warning: Import access_path.proto but not used.
mempool_status.proto: No such file or directory
thread 'main' panicked at 'failed to write descriptor set: Custom { kind: Other, error: "protoc (\"protoc\" \"-I../types/src/proto\" \"-Isrc/proto/shared\" \"-Isrc/proto/shared\" \"--descriptor_set_out=/tmp/f1bec225f1c84915977a08e149f0b941\" \"--include_imports\" \"mempool_status.proto\") exited with non-zero exit code" }', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by bmwill** [comment]
The external dependencies needed to build Libra have been simplified and should only require Rust now so this shouldn't be an issue anymore on master. If it is, please let us know.
