### ISSUE TITLE
[question] `nextgen_crypto::ed25519::Ed25519PrivateKey: std::clone::Clone` is not satisfied

### ISSUE THREAD

**Issue by dofork** [libra/libra#811]
when I  building vm_genesis of branch [testnet] there is a error: 

error[E0277]:
 the trait bound `nextgen_crypto::ed25519::Ed25519PrivateKey: std::clone::Clone` is not satisfied
 
 ----- /libra/language/vm/vm_genesis/src/lib.rs:61:5

----------------------------------------------------------------------------------------------------------
in "language/vm/vm_genesis/src/lib.rs"

```
_#[derive(Debug, Clone)]
pub struct Account {
    pub addr: AccountAddress,
    pub privkey: Ed25519PrivateKey,
    pub pubkey: Ed25519PublicKey,
}_
```

See "/crypto/nextgen_crypto/src/ed25519.rs"

```
/// An Ed25519 public key
#[derive(Clone, Debug)]
pub struct Ed25519PublicKey(ed25519_dalek::PublicKey);
```
but Ed25519PrivateKey is not derived clone, however, Ed25519PublicKey is derived clone.

**Comment by huitseeker** [comment]
I can't reproduce this on the latest testnet at 171a766095954ff6eecf7147a4847b3c3590cdae or 
master at afbfd77bf380175ef6739e166b7e70608fc56a19, what's the commit you are working on?

**Comment by huitseeker** [comment]
Closed for lack of activity, feel free to reopen with more data @dofork
