### ISSUE TITLE
libra_fuzzer environment should use the same Cargo.lock versions as the main workspace

### ISSUE THREAD

**Issue by sunshowers** [libra/libra#816]
At the moment, the environment within `testsuite/libra_fuzzer/fuzz` is totally separated from the main workspace. This means that it gets its own lock file which has no correspondence to the main lock file, which means that a different set of versions could be active. Figure out a way to mirror the main lock file into the fuzzing environment.

**Comment by bmwill** [comment]
This was recently fixed
