### ISSUE TITLE
Figure-3 in LibraBFT whitepaper seems wrong

### ISSUE THREAD

**Issue by ardpx** [libra/libra#82]
# 🐛 Bug

According to HotStuff, the validators shall send the votes to Leader of next round, instead of current round. Otherwise, the leader of next round is not able to send out the QC referencing previous blocks...

However, figure-3 in https://cdn.crowdfundinsider.com/wp-content/uploads/2019/06/LibraBlockchainConsensus.pdf looks like the normal protocol with block syned and committed in current round.

**Comment by aching** [comment]
The original HotStuff protocol does indeed send votes to the leader of the next round in order for the next leader to generate a quorum certificate to be able to generate a valid proposal.  Note that the main objective is that the next leader has a valid quorum certificate that a new block can be added to.  This process can be implemented in another way into 2 steps:
e.g. 

1) a leader collecting votes for its own proposal
2) the leader then broadcasting quorum certificates to all replicas (prioritizing the next leader first) 

There are pros/cons of these approaches.  The later approach allows a leader to have more control over its ability to get its proposal certified, but it also introduces an extra network message to the next leader.  Our current white paper uses the later approach but it's an area that we want to continue to explore.
