### ISSUE TITLE
[Bug]`target/debug/client --host ac.testnet.libra.org --port 8000 -s ./scripts/cli/trusted_peers.config.toml` Not able to connect to validator at ac.testnet.libra.org:8000, error InvalidSignature

### ISSUE THREAD

**Issue by hexiaosheng** [libra/libra#824]
run ./scripts/cli/start_cli_testnet.sh get below output
Building and running client in debug mode.
    Finished dev [unoptimized + debuginfo] target(s) in 14.57s
     Running `target/debug/client --host ac.testnet.libra.org --port 8000 -s ./scripts/cli/trusted_peers.config.toml`
Not able to connect to validator at ac.testnet.libra.org:8000, error InvalidSignature

**Comment by gatmac** [comment]
Did you checkout testnet after cloning? 

> git checkout testnet

I was getting that error, but now I am getting a different one: 

   Compiling vm_runtime v0.1.0 (/home/ubuntu/github/libra/language/vm/vm_runtime)
   Compiling stdlib v0.1.0 (/home/ubuntu/github/libra/language/stdlib)
   Compiling vm_validator v0.1.0 (/home/ubuntu/github/libra/vm_validator)
   Compiling vm_genesis v0.1.0 (/home/ubuntu/github/libra/language/vm/vm_genesis)
   Compiling client v0.1.0 (/home/ubuntu/github/libra/client)
    Finished dev [unoptimized + debuginfo] target(s) in 8m 31s
     Running `target/debug/client --host ac.testnet.libra.org --port 8000 -s ./scripts/cli/trusted_peers.config.toml`
Not able to connect to validator at ac.testnet.libra.org:8000, error RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") })

**Comment by gatmac** [comment]
Sorry, just tried it again, and invalidSignature error just came back.

**Comment by dofork** [comment]
> run ./scripts/cli/start_cli_testnet.sh get below output
> Building and running client in debug mode.
> Finished dev [unoptimized + debuginfo] target(s) in 14.57s
> Running `target/debug/client --host ac.testnet.libra.org --port 8000 -s ./scripts/cli/trusted_peers.config.toml`
> Not able to connect to validator at ac.testnet.libra.org:8000, error InvalidSignature

just pull again

**Comment by ssyuan** [comment]
me, too.
====
  Running `target/debug/client --host ac.testnet.libra.org --port 8000 -s ./scripts/cli/trusted_peers.config.toml`
Not able to connect to validator at ac.testnet.libra.org:8000, error InvalidSignature

**Comment by fMercury** [comment]
mmm 
Looks like something was updated. 
because this error started a few hours ago. 
It is necessary to rebuild everything again

**Comment by bothra90** [comment]
The current testnet is deployed at the git-sha `05364e6da23a58948c1243c09023df4c9be74783`. The announcement was shared on Discourse: https://community.libra.org/t/testnet-update-september-4th/1630.  If you checkout your local git branch at this sha, the client should connect to testnet as expected.

**Comment by nshCore** [comment]
> 05364e6da23a58948c1243c09023df4c9be74783

checking out this commit throws error during build process

```
error[E0425]: cannot find function `verify_batch` in module `ed25519_dalek`
   --> crypto/crypto/src/ed25519.rs:353:24
    |
353 |         ed25519_dalek::verify_batch(&messages[..], &dalek_signatures[..], &dalek_public_keys[..])?;
    |                        ^^^^^^^^^^^^ not found in `ed25519_dalek`

error: aborting due to previous error

```
