### ISSUE TITLE
[Bug] Critical security vulnerability

### ISSUE THREAD

**Issue by gazhayes** [libra/libra#84]
Critical security vuln discovered and patched in #83

**Comment by crawfordleeds** [comment]
This is hilarious but I think I'm still going to give Libra a shot.

**Comment by suprnurd** [comment]
> This is hilarious but I think I'm still going to give Libra a shot.

You probably own Ripple too.

**Comment by bioharz** [comment]
Please keep at least the GitHub issues an objective place. Every software has security vulnerabilities.

**Comment by crawfordleeds** [comment]
> > This is hilarious but I think I'm still going to give Libra a shot.
> 
> You probably own Ripple too.

I should have been more clear - I'm going to try building something with Move; I'm not interested in owning anything with built-in KYC enforcement.

**Comment by alexindigo** [comment]
> > > This is hilarious but I think I'm still going to give Libra a shot.
> > You probably own Ripple too.
> I should have been more clear - I'm going to try building something with Move; I'm not interested in owning anything with built-in KYC enforcement.

@crawfordleeds My understanding enforced KYC is property of the calibra wallet, not the protocol. Correct me if I'm wrong.

**Comment by crawfordleeds** [comment]
> > > > This is hilarious but I think I'm still going to give Libra a shot.
> > > > You probably own Ripple too.
> > > > I should have been more clear - I'm going to try building something with Move; I'm not interested in owning anything with built-in KYC enforcement.
> 
> @crawfordleeds My understanding enforced KYC is property of the calibra wallet, not the protocol. Correct me if I'm wrong.

@alexindigo I don't know for sure, there's a good chance you are correct and I am wrong. That was something I heard second hand, and that seemed to vibe with the terminology of the whitepaper. There is a mention something along the lines of "people should be entitled to the fruits of their legal labor". Maybe it's imprecise language (I would be surprised) but that seems to mandate KYC if Libra is going to ensure legality. For example, to know which country's laws to apply, they would need to know some information about the customer, at the very least location.

I'll have to dig some more. If it's just the wallet, and other wallets are going to be available in the future, that would be a nice relief.

**Comment by alexindigo** [comment]
I mean, it’s only enforceable on wallet level, for protocol itself it’s just public keys.
The question is how much they’d be controlling other wallets on the network, but I don’t see that any KYC data transfer baked into the protocol. So if it’d be done, only through audit. And most likely will be enforced through local laws rather than network itself.

**Comment by bmaurer** [comment]
Closing as discussed on the pull request and subsequent bug.
