### ISSUE TITLE
Why not check expired_time of tx in VM::ValidateTransaction()?

### ISSUE THREAD

**Issue by lightning-li** [libra/libra#85]
# 🐛 Bug

If expired_time of tx validation rule is not checked in VM::ValidateTransaction() or Execution::ExecuteBlock(), this means that  expired_time validation rule is not part of consensus rule. And if leader/proposer propose a block which includes expired txs, this block may be committed at all validators

**Comment by kphfb** [comment]
Hi @lightning-li, excellent question! This is a known limitation and indeed something that we are planning to add very soon.  We have not yet finished the design for exposing the consensus time to the smart contract layer, so we are unable to validate the expiration time yet.  It is one of our top priorities, so you can expect it to be coming soon.

**Comment by anthony19114** [comment]
I am uncertain of block times but expiryheight could be implemented instead. Using a block height as its maximum height to notify that the transaction is expiring. I see there are also sequence numbers pegged to each account which the smart contract will verify against to invalidate replay, duplicate transactions. The same exact code set could be replicated and applied to block height and invalidate after a certain future height.

**Comment by lightning-li** [comment]
@anthony19114  I think you can get both like bitcoin nLockTime and OP_CHECKLOCKTIMEVERIFY logic

**Comment by bob-wilson** [comment]
We added checking for transaction expiration time in #2275
