### ISSUE TITLE
[Bug]There are two errors when run 'cargo test' 

### ISSUE THREAD

**Issue by rainysiu** [libra/libra#859]
# 🐛 Bug
running 2 tests
test tests::test_benchmarker_read_requests ... test tests::test_benchmarker_read_requests has been running for over 60 seconds
test tests::test_benchmarker_counters ... test tests::test_benchmarker_counters has been running for over 60 seconds
test tests::test_benchmarker_read_requests ... FAILED
test tests::test_benchmarker_counters ... FAILED

failures:

---- tests::test_benchmarker_read_requests stdout ----
Base directory containing logs and configs: Temporary(TempDir { path: "/var/folders/dc/bm051tv904l3l5n48t08rhtr0000gn/T/.tmpFHLAGn" })
Base directory containing logs and configs: Temporary(TempDir { path: "/var/folders/dc/bm051tv904l3l5n48t08rhtr0000gn/T/.tmpnWpmXf" })
Base directory containing logs and configs: Temporary(TempDir { path: "/var/folders/dc/bm051tv904l3l5n48t08rhtr0000gn/T/.tmpwINIM3" })
Base directory containing logs and configs: Temporary(TempDir { path: "/var/folders/dc/bm051tv904l3l5n48t08rhtr0000gn/T/.tmpeezMBk" })
Base directory containing logs and configs: Temporary(TempDir { path: "/var/folders/dc/bm051tv904l3l5n48t08rhtr0000gn/T/.tmpao20lv" })
thread 'tests::test_benchmarker_read_requests' panicked at 'Max out 5 attempts to launch swarm', libra_swarm/src/swarm.rs:247:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- tests::test_benchmarker_counters stdout ----
thread 'tests::test_benchmarker_counters' panicked at 'child exited unsuccessfully with exit code: 70', /Users/rainysiu/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty-fork-0.2.2/src/fork_test.rs:135:9

running 1 test
Base directory containing logs and configs: Temporary(TempDir { path: "/var/folders/dc/bm051tv904l3l5n48t08rhtr0000gn/T/.tmp8PAbR9" })
Base directory containing logs and configs: Temporary(TempDir { path: "/var/folders/dc/bm051tv904l3l5n48t08rhtr0000gn/T/.tmpTmogMd" })
Base directory containing logs and configs: Temporary(TempDir { path: "/var/folders/dc/bm051tv904l3l5n48t08rhtr0000gn/T/.tmpSEkP6d" })
Base directory containing logs and configs: Temporary(TempDir { path: "/var/folders/dc/bm051tv904l3l5n48t08rhtr0000gn/T/.tmp0Blu9B" })
Base directory containing logs and configs: Temporary(TempDir { path: "/var/folders/dc/bm051tv904l3l5n48t08rhtr0000gn/T/.tmpEW8eVz" })
thread 'main' panicked at 'Max out 5 attempts to launch swarm', libra_swarm/src/swarm.rs:247:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

failures:
    tests::test_benchmarker_counters
    tests::test_benchmarker_read_requests

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p benchmark --bin ruben'

have run 'cargo test -p benchmark --bin ruben' 
still failed

**Comment by hello2mao** [comment]
+1

**Comment by bmwill** [comment]
The benchmark crate has been removed so this should be fixed now.
