### ISSUE TITLE
Oxymorons in the white paper, "Decentralized Governance" [Bug]

### ISSUE THREAD

**Issue by beeforbacon** [libra/libra#86]
The phrase "decentralized governance" is used many times in the white paper. This is an oxymoron as governance is centralized by nature and by definition. A decentralized system does not have governance, that is what makes it decentralized. Can someone with an IQ higher than 60 please rewrite the white paper without these errors? Thanks.

**Comment by anon17** [comment]
Are you retarded? Lack of centralization is what makes a decentralized system decentralized, not lack of governance.

**Comment by crawfordleeds** [comment]
The definition of governance is "the action or manner of governing" and centralization is not a pre-requisite. A preference for greater decentralization does not seem to be sufficient to change the meaning of words.

**Comment by beeforbacon** [comment]
Centralization is not a spectrum in distributed systems, crowford. You're either one or the other.

**Comment by karozagorus** [comment]
BUY BITCOIN.

**Comment by ericnakagawa** [comment]
If you would like to discuss our whitepaper please head to our [Discourse](https://community.libra.org).
