### ISSUE TITLE
[Bug] while shutdown testnet and start testnet, the account information is missing

### ISSUE THREAD

**Issue by rainysiu** [libra/libra#860]
# 🐛 Bug
while shutdown testnet and start testnet, the account information is missing
but when you input 'account create', the balance is retrieved

libra% account list
No user accounts
libra% account create
>> Creating/retrieving next account from wallet
Created/retrieved account #0 address 463cbe95a428c717d4ac1cb6ecd7b3db9d92d72f538bf7be85c1325143259a7d
libra% account create
>> Creating/retrieving next account from wallet
Created/retrieved account #1 address 9d2e961954cbc7bdc24a07acc39920943c2fce283b3e6ddd0cea9c94b02e4a3d
libra% query balance 1
Balance is: 152.000000
libra% account list
User account index: 0, address: 463cbe95a428c717d4ac1cb6ecd7b3db9d92d72f538bf7be85c1325143259a7d, sequence number: 0, status: Persisted
User account index: 1, address: 9d2e961954cbc7bdc24a07acc39920943c2fce283b3e6ddd0cea9c94b02e4a3d, sequence number: 0, status: Persisted
libra% query balance 0
Balance is: 210.000000
libra%

## To reproduce

** Code snippet to reproduce **
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

** Stack trace/error message **
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by bmwill** [comment]
This is working as intended. You need to use the 'account write client.mnemonic' command in order to save the updated client.mnemonic file with the number of accounts you've created.
