### ISSUE TITLE
[Feature Request] Many old move functional_tests scripts are not working. I fixed 58 out of date scripts. 

### ISSUE THREAD

**Issue by LingTian** [libra/libra#885]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**

Many old move functional_tests scripts are not working after update.
I go through all scripts in functional_tests and fixed 58 out of date move scripts in the functional_tests. 

## Pitch

**Describe the solution you'd like**
I fix all the out of date move scripts and update them already.
https://github.com/libra/libra/pull/884
I test all of them in the latest compiler in LibraIDE (libraide.com)

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes. 
https://github.com/libra/libra/pull/884

**Comment by bmwill** [comment]
Closing due to https://github.com/libra/libra/pull/884#pullrequestreview-285665899
