### ISSUE TITLE
[Bug]  query transaction sequence command syntax needs love

### ISSUE THREAD

**Issue by richbodo** [libra/libra#89]
# 🐛 Bug

## To reproduce

After a transfer, the cli suggests a query transaction sequence as follows:

"To query for transaction status, run: query txn_acc_seq 0 2 <fetch_events=true|false>"

and in the help text for the cli, the following syntax is suggested:

txn_acc_seq | ts <account_ref_id>|<account_address> <sequence_number> <fetch_events=true|false>                               Get the committed transaction by account and sequence number.  Optionally also fetch events emitted by this transaction.  

This results in attempts to make transaction queries that explicitly include the string "fetch_events", like so:

`
libra% q b 1
Balance is: 153
libra% q b 0
Balance is: 109
libra% t 0 1 10
>> Transferring
Transaction submitted to validator
To query for transaction status, run: query txn_acc_seq 0 2 <fetch_events=true|false>
libra% q ts 0 2 fetch_events=true
>> Getting committed transaction by account and sequence number
[ERROR] Error getting committed transaction by account and sequence number: Unable to parse input for fetch_events - please enter an Bool.  Input was: fetch_events=true, error: ParseBoolError { _priv: () }
libra% q ts 0 2 fetch_events=1
>> Getting committed transaction by account and sequence number
[ERROR] Error getting committed transaction by account and sequence number: Unable to parse input for fetch_events - please enter an Bool.  Input was: fetch_events=1, error: ParseBoolError { _priv: () }
libra% q ts 0 2 
>> Getting committed transaction by account and sequence number
[ERROR] Error getting committed transaction by account and sequence number: Invalid number of arguments to get transaction by account and sequence number
libra%
libra% q ts 0 2 fetch_events=TRUE
>> Getting committed transaction by account and sequence number
[ERROR] Error getting committed transaction by account and sequence number: Unable to parse input for fetch_events - please enter an Bool.  Input was: fetch_events=TRUE, error: ParseBoolError { _priv: () }
`

## Expected Behavior

It is expected that 
## System information

**Please complete the following information:**
- 
Shoot, can't find it.  Sorry.  Libra released earlier today, installed on deb9 as per the instructions. Pretty sure this was the last commit: 004d472284ce7d3a0ce2f577ecd05de56026dbd4
- 
- 
Debian GNU/Linux

**Comment by wqfish** [comment]
Just use ‘q ts 0 2 true’.

**Comment by richbodo** [comment]
> Just use ‘q ts 0 2 true’.

That did it.  Thanks, @wqfish.  I'll update the title of this bug to suggest better language on the command syntax.

**Comment by icarter09** [comment]
@richbodo is this still a "bug" or an "Enhancement" ?

**Comment by richbodo** [comment]
@icarter09 I filed this as a bug as the cli docs indicate an lvalue/rvalue instead of true or false for the last parameter, which will trip a lot of people up.

Now that you made me actually think about it...If we want to follow IEEE or GNU standard argument format for the CLI, I personally think that would be a great enhancement ticket - I could write up suggested mods to the CLI to meet those standards, throw the docs in here, and change this to an enhancement ticket.  Let me know if that's at all helpful.

**Comment by icarter09** [comment]
@richbodo Very helpful and I also think that would be a great enhancement ticket. Once you create that enhancement ticket, please close this one out if you feel that it is no longer a bug/issue. Thanks again for following up on this.

**Comment by davidiw** [comment]
feel free to reopen if the api is still needs love.
