### ISSUE TITLE
[Consensus] Minimize datatype dependencies of TCB

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#935]
This issue tracks the effort of cleaning up the datatype dependencies of safety rules to the bare minimum. It could then help the efforts of building formal proofs for the safety properties.
For example, the protocol does not really depend on all the fields in the Block structure, and some fields of QuorumCert are not used as well.
The plan is to define the internal TCB structure for SafetyRules, which would receive the masked types that carry only the information required for the protocol.

**Comment by davidiw** [comment]
I think we're good here :)
