### ISSUE TITLE
dev compile error : Unrecognized token 'R'

### ISSUE THREAD

**Issue by okcrinum** [libra/libra#943]
## ❓ dev compile error : Unrecognized token 'R', how to fix its?
![lan2](https://user-images.githubusercontent.com/37081892/64916493-32e72f00-d7a8-11e9-92f6-cdafbb7e3b54.png)

**Comment by Vid201** [comment]
Kind annotations were removed. Remove `R#` (`V#`) and try to compile again.

**Comment by okcrinum** [comment]
Thank you,  for your suggestions.

ในวันที่ อา. 15 ก.ย. 2019 17:28 Vid Kersic <notifications@github.com>
เขียนว่า:

**Comment by bmwill** [comment]
Sounds like @Vid201 was able to answer your question. If this wasn't solved feel free to reopen this issue.
