### ISSUE TITLE
Decentralize Libra Protocol (http://dlibra.one/)

### ISSUE THREAD

**Issue by dlibra-one** [libra/libra#96]
According to the white paper, Libra enforces a very strict bar on being a validator for the sake of performance and security. However, it limits the level of decentralized trust such a platform can provide. It is strongly recommended that a more decentralized protocol needs to be investigated.

**Comment by zsabbasi** [comment]
Having a more decentralized platform comes at a cost of speed and finality problems that many other Blockchain implementations have. Delegating this to a more restricted number of nodes allows for a balance of diverse enough pool of stakeholders and at the same time allowing for more speedy transactions. There is little double that the pool can be made a bit more diverse as at the moment many of the organisations will be a bit of an exclusive club (even after including the top charities and the top universities). I think the community will benefit from better criteria and protocol implementations but this is not an easy problem to solve and given that there are enough calls for it then this protocol will likely evolve to cater for the demand.

**Comment by bmaurer** [comment]
As mentioned in the whitepaper, this is a conscious choice. Over time the set of validators will grow and become more decentralized. I'm closing as this is already an item that is directionally on our roadmap.
