### ISSUE TITLE
[network] Logging improvements for readability

### ISSUE THREAD

**Issue by opsguy** [libra/libra#961]
Two main issues:

Currently when running a validator, if any peer is offline the following log message spams:
140527787833088 network/src/protocols/direct_send/mod.rs:315] DirectSend to peer 1337d6d0 failed: Peer disconnected

I think we should:
1) Change the language here to be a bit more meaningful
2) Possibly move this to debug

And ideally:
3) Add some log message that periodically logs the list of connected peers as a basic status message.

**Comment by davidiw** [comment]
cc: @gregnazario hahaha
