### ISSUE TITLE
[cargo-dep-bot] remove old comment when its no longer relevant

### ISSUE THREAD

**Issue by bmwill** [libra/libra#976]
cargo-dep-bot currently will look at the diff between the merge-base and the tip of a PR to construct a "lockfile diff" to post in a comment. If a PR is updated and there are still changes to the lockfile, the old comment is removed and a new one is posted with the up-to-date diff. The one area where this breaks down is if a PR (like in #968) is updated to no longer make any meaningful changes to the lockfile. When this happens the old comment is left up and and instead should be deleted.

**Comment by davidiw** [comment]
huh?
