### ISSUE TITLE
Is the ecdsa algorithm related operation one of the bottle neck of the performance?

### ISSUE THREAD

**Issue by GingerMoon** [libra/libra#98]
Hi team, 

I am from a hardware company [(accelor.io)](accelor.io) and one of our focus is accelerating blockchain via various means, including using FPGA doing ecdsa sign/verify for the blockchain.

I would appreciate if  anyone could share a profiling result to illustrate the percentage of ecdsa related computation in the whole performance profiling result.

By the way, providing a TEE(trusted execution environment, which is expected to be more secure than [Intel SGX](https://software.intel.com/en-us/sgx)) for blockchain is also one of our focus.

Best Regards,
Xiang
[accelor.io](accelor.io)

**Comment by barrystyle** [comment]
I did some benchmarking of ECDSA (as implemented here https://github.com/bitcoin-core/secp256k1) a few years back and was able to achieve around 2 million keys per core per minute. I wouldn't think its a bottleneck.

However i've just had a (quick) look through the codebase and it doesnt appear to be used here?

**Comment by mimoo** [comment]
hey, closing as this hasn't received much response.
