### ISSUE TITLE
[consensus] Refine block size and grpc limits

### ISSUE THREAD

**Issue by andll** [libra/libra#990]
We need better understand relation between grpc limit and maximum block size, and have ability to adjust both in safe manner.

Currently we arbitrary picked 100 transactions per block. This is bad for two reasons.

(1) **It is not safe.** While it works for small transactions that we use in bench, it does not work for arbitrary transaction.
Transaction limit is 4096 bytes, and most likely 100 transactions of 4k size aren't going to meet grpc limits. This is pretty bad, because it means that client can cripple our network by submitting relatively small number of large transactions - if block generated by consensus does not fit grpc, we are simply going to be stuck.
(2) **It is not optimal** We get better TPS numbers with hight block size (~300 and possibly more), so we need to be able to increase block size higher, without risking safety even more.

Since its an important liveness issue, we also need a smoke test that would try to submit maximum size block of maximum size transactions and verifies that such block can be executed and committed

**Comment by aching** [comment]
I think it would be helpful for us to think about block limits in terms of bytes or gas rather than transactions.

**Comment by andll** [comment]
@aching  Yes, thats also valid approach (although at this point this is not 'good first issue' for sure)

**Comment by andll** [comment]
We got rid of grpc so I think this problem of block size and grpc limits alignment does not exist anymore
